### ISSUE TITLE
USB Interface Issue

### ISSUE THREAD

**Issue by meerd** [knxd/knxd#100]
Hello,

I have an ABB USB/S1.1 interface. When I try use it with the latest release, it simply doesn't work. 

Here is my command line to initialize knxd: 
knxd --trace=5 --listen-local=/tmp/eibd  usb:3:9:1:0:0

Yet another command line to be able to write to the KNX bus: 
knxtool groupswrite local:/tmp/eibd2 0/1/9 0

The interface worked fine with BCUSDK v0.0.5 that has cEMI patch. Later on, I wanted to dig the issue a bit and found that something is broken after commit 46d2f8ba.  I have been able to use knxd up to the commit 237dcea3.

Do you have any idea about this? Has anyone experienced it before?

Thanks.
Erdem

**Comment by smurfix** [comment]
Hi,

There is no functional change between these commits. Something else must
be going on.
Did you run "make clean; make; make install" after every "git bisect"
command? The Makefile didn't (doesn't, actually) contain all
dependencies and the installed version might interfere with the local copy.

What does it actually do when it "simply doesn't work"? Crash? Sit there
and do nothing?

Please run knxd with full tracing (-t1023 -f9) and tell me what it says
on startup / when you issue a "knxtool groupswrite".

-- 
-- Matthias Urlichs

**Comment by meerd** [comment]
Hello Mathias,

The deamon keeps running but does nothing. I haven't observed a crash. I made a clean chekout from the master and ran the deamon according to your suggestion. Here is the output: 

Layer 3(01692120,562686E8) Open
Layer 8(016A2880,562686E8) OpenLocalSocket /tmp/eibd
Layer 8(016A2880,562686E8) LocalSocket opened
Layer 1(016B2F40,562686E8) Detect
Layer 1(016B2F40,562686E8) Using 3:9:1:0:0 (2:129)
Layer 1(016B2F40,562686E8) Open
Layer 1(016B2F40,562686E8) Claimed
Layer 1(016B2F40,562686E8) Opened
Layer 1(016B2F40,562686E8) Send(064): 01 13 09 00 08 00 01 0F 01 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 3(01692120,562686E8) L3 started
Layer 0(016B2F40,562686E8) StartRecv
Layer 0(016B2F40,562686E8) Send(064): 01 13 09 00 08 00 01 0F 01 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(016B2F40,562686E8) StartSend
Layer 0(016B2F40,562686E8) SendComplete 64
Layer 0(016B2F40,562686E8) RecvComplete 64
Layer 0(016B2F40,562686E8) RecvUSB(064): 01 13 0B 00 08 00 03 0F 02 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(016B2F40,562686E8) StartRecv
Layer 1(016B2F40,562686E8) Recv(064): 01 13 0B 00 08 00 03 0F 02 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 1(016B2F40,562686E8) Send(064): 01 13 0A 00 08 00 02 0F 03 00 00 05 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(016B2F40,562686E8) Send(064): 01 13 0A 00 08 00 02 0F 03 00 00 05 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(016B2F40,562686E8) StartSend
Layer 1(016B36E0,562686E8) EMI1
Layer 2(016D9030,562686E8) Open
Layer 2(016D9030,562686E8) Opened
Layer 3(01692120,562686E8) registerLayer2 016B49E0
Layer 2(016D9030,562686E8) OpenL2
Layer 0(016B36E0,562686E8) Send-EMI(005): 46 01 00 60 12
Layer 1(016B2F40,562686E8) Send(064): 01 13 0D 00 08 00 05 01 01 00 00 46 01 00 60 12 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(016B2F40,562686E8) SendComplete 64
Layer 0(016B2F40,562686E8) Send(064): 01 13 0D 00 08 00 05 01 01 00 00 46 01 00 60 12 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(016B2F40,562686E8) StartSend
Layer 0(016B2F40,562686E8) SendComplete 64
Layer 3(01692120,562686E8) registerLayer2 016B49E0 = 1
W00000020: EIBD should not run as root
Layer 8(016A2880,562686ED) New Connection
Layer 8(016B4580,562686ED) ClientConnection Init
Layer 8(016B4580,562686ED) RecvMessage(005): 00 22 01 09 FF
Layer 7(016F9D00,562686ED) OpenGroup
Layer 4(01691C20,562686ED) OpenGroup 0/1/9 WO
Layer 3(01692120,562686ED) registerLayer2 01691C20
Layer 3(01692120,562686ED) registerLayer2 01691C20 = 1
Layer 7(016F9D00,562686ED) OpenGroup complete
Layer 8(016B4580,562686ED) SendMessage(002): 00 22
Layer 8(016B4580,562686ED) RecvMessage(004): 00 25 00 80
Layer 7(016F9D00,562686ED) Send(002): 00 80
Layer 4(01691C20,562686ED) Send Group T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
Layer 3(01692120,562686ED) Enqueue L_Data low from 0.0.0 to 0/1/9 hops: 07 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
Layer 7(016F9D00,562686ED) CloseGroup
Layer 4(01691C20,562686ED) CloseGroup
Layer 3(01692120,562686ED) deregisterLayer2 01691C20 = 1
Layer 8(016B4580,562686ED) ClientConnection closed
Layer 3(01692120,562686ED) RecvData L_Data low from 0.0.0 to 0/1/9 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
Layer 2(016D9030,562686ED) Send L_Data low from 0.0.1 to 0/1/9 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
Layer 8(016A2880,562686EF) New Connection
Layer 8(01691C20,562686EF) ClientConnection Init
Layer 8(01691C20,562686EF) RecvMessage(005): 00 22 01 09 FF
Layer 7(016F9D00,562686EF) OpenGroup
Layer 4(016B4580,562686EF) OpenGroup 0/1/9 WO
Layer 3(01692120,562686EF) registerLayer2 016B4580
Layer 3(01692120,562686EF) registerLayer2 016B4580 = 1
Layer 7(016F9D00,562686EF) OpenGroup complete
Layer 8(01691C20,562686EF) SendMessage(002): 00 22
Layer 8(01691C20,562686EF) RecvMessage(004): 00 25 00 81
Layer 7(016F9D00,562686EF) Send(002): 00 81
Layer 4(016B4580,562686EF) Send Group T_DATA_XXX_REQ A_GroupValue_Write (small) 01 
Layer 3(01692120,562686EF) Enqueue L_Data low from 0.0.0 to 0/1/9 hops: 07 T_DATA_XXX_REQ A_GroupValue_Write (small) 01 
Layer 7(016F9D00,562686EF) CloseGroup
Layer 4(016B4580,562686EF) CloseGroup
Layer 3(01692120,562686EF) deregisterLayer2 016B4580 = 1
Layer 8(01691C20,562686EF) ClientConnection closed
Layer 3(01692120,562686EF) RecvData L_Data low from 0.0.0 to 0/1/9 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01 
Layer 2(016D9030,562686EF) Send L_Data low from 0.0.1 to 0/1/9 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01

**Comment by meerd** [comment]
I also made a clean checkout for 237dcea390e114477ab0b464d1c8369e8ffab9c0. It is working as it worked before and here is the output. 

Layer 1(0097F4C0,56268804) Detect
Layer 1(0097F4C0,56268804) Using 3:9:1:0:0 (2:129)
Layer 1(0097F4C0,56268804) Open
Layer 1(0097F4C0,56268804) Claimed
Layer 1(0097F4C0,56268804) Opened
Layer 1(0097F4C0,56268804) Send(064): 01 13 09 00 08 00 01 0F 01 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(0097F4C0,56268804) StartRecv
Layer 0(0097F4C0,56268804) Send(064): 01 13 09 00 08 00 01 0F 01 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(0097F4C0,56268804) StartSend
Layer 0(0097F4C0,56268804) SendComplete 64
Layer 0(0097F4C0,56268804) RecvComplete 64
Layer 0(0097F4C0,56268804) RecvUSB(064): 01 13 0B 00 08 00 03 0F 02 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(0097F4C0,56268804) StartRecv
Layer 1(0097F4C0,56268804) Recv(064): 01 13 0B 00 08 00 03 0F 02 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 1(0097F4C0,56268804) Send(064): 01 13 0A 00 08 00 02 0F 03 00 00 05 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(0097F4C0,56268804) Send(064): 01 13 0A 00 08 00 02 0F 03 00 00 05 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(0097F4C0,56268804) StartSend
Layer 1(0097E390,56268804) EMI1
Layer 2(009A3300,56268804) Open
Layer 2(009A3300,56268804) Opened
Layer 3(009B39B0,56268804) Open
Layer 2(009A3300,56268804) OpenL2
Layer 0(0097E390,56268804) Send-EMI(005): 46 01 00 60 12
Layer 1(0097F4C0,56268804) Send(064): 01 13 0D 00 08 00 05 01 01 00 00 46 01 00 60 12 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(0097F4C0,56268804) SendComplete 64
Layer 0(0097F4C0,56268804) Send(064): 01 13 0D 00 08 00 05 01 01 00 00 46 01 00 60 12 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(0097F4C0,56268804) StartSend
Layer 0(0097F4C0,56268804) SendComplete 64
Layer 8(009B3AB0,56268804) OpenLocalSocket
Layer 8(009B3AB0,56268804) LocalSocket opened
Layer 4(009D47E0,56268804) GroupCacheInit
Layer 8(009B3AB0,56268809) New Connection
Layer 8(0097F160,56268809) ClientConnection Init
Layer 8(0097F160,56268809) RecvMessage(005): 00 22 01 09 FF
Layer 7(009E5730,56268809) OpenGroup
Layer 4(009E5890,56268809) OpenGroup 0/1/9 WO
Layer 8(0097F160,56268809) SendMessage(002): 00 22
Layer 8(0097F160,56268809) RecvMessage(004): 00 25 00 80
Layer 7(009E5730,56268809) Send(002): 00 80
Layer 4(009E5890,56268809) Send Group T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
Layer 3(009B39B0,56268809) Send L_Data low from 0.0.0 to 0/1/9 hops: 07 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
Layer 2(009A3300,56268809) Send L_Data low from 0.0.0 to 0/1/9 hops: 07 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
Layer 1(009A3300,56268809) Send L_Data low from 0.0.0 to 0/1/9 hops: 07 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
Layer 0(0097E390,56268809) Send-EMI(009): 11 0C 00 00 01 09 F1 00 80
Layer 1(0097F4C0,56268809) Send(064): 01 13 11 00 08 00 09 01 01 00 00 11 0C 00 00 01 09 F1 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 7(009E5730,56268809) CloseGroup
Layer 0(0097F4C0,56268809) Send(064): 01 13 11 00 08 00 09 01 01 00 00 11 0C 00 00 01 09 F1 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(0097F4C0,56268809) StartSend
Layer 4(009E5890,56268809) CloseGroup
Layer 3(009B39B0,56268809) deregisterGroupCallBack 009E5890 = 0
Layer 8(0097F160,56268809) ClientConnection closed
Layer 2(009A3300,56268809) Recv L_Data low from 0.0.0 to 0/1/9 hops: 07 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
Layer 3(009B39B0,56268809) Recv L_Data low from 0.0.0 to 0/1/9 hops: 07 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
Layer 0(0097F4C0,56268809) SendComplete 64
Layer 0(0097F4C0,56268809) RecvComplete 64
Layer 0(0097F4C0,56268809) RecvUSB(064): 01 13 11 00 08 00 09 01 01 00 00 4E BC 11 FD 01 09 F1 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(0097F4C0,56268809) StartRecv
Layer 1(0097F4C0,56268809) Recv(064): 01 13 11 00 08 00 09 01 01 00 00 4E BC 11 FD 01 09 F1 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(0097E390,56268809) RecvEMI(009): 4E BC 11 FD 01 09 F1 00 80
Layer 8(009B3AB0,5626880A) New Connection
Layer 8(0097F160,5626880A) ClientConnection Init
Layer 8(0097F160,5626880A) RecvMessage(005): 00 22 01 09 FF
Layer 7(009F5FA0,5626880A) OpenGroup
Layer 4(009F60B0,5626880A) OpenGroup 0/1/9 WO
Layer 8(0097F160,5626880A) SendMessage(002): 00 22
Layer 8(0097F160,5626880A) RecvMessage(004): 00 25 00 81
Layer 7(009F5FA0,5626880A) Send(002): 00 81
Layer 4(009F60B0,5626880A) Send Group T_DATA_XXX_REQ A_GroupValue_Write (small) 01 
Layer 3(009B39B0,5626880A) Send L_Data low from 0.0.0 to 0/1/9 hops: 07 T_DATA_XXX_REQ A_GroupValue_Write (small) 01 
Layer 2(009A3300,5626880A) Send L_Data low from 0.0.0 to 0/1/9 hops: 07 T_DATA_XXX_REQ A_GroupValue_Write (small) 01 
Layer 1(009A3300,5626880A) Send L_Data low from 0.0.0 to 0/1/9 hops: 07 T_DATA_XXX_REQ A_GroupValue_Write (small) 01 
Layer 0(0097E390,5626880A) Send-EMI(009): 11 0C 00 00 01 09 F1 00 81
Layer 1(0097F4C0,5626880A) Send(064): 01 13 11 00 08 00 09 01 01 00 00 11 0C 00 00 01 09 F1 00 81 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 7(009F5FA0,5626880A) CloseGroup
Layer 0(0097F4C0,5626880A) Send(064): 01 13 11 00 08 00 09 01 01 00 00 11 0C 00 00 01 09 F1 00 81 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(0097F4C0,5626880A) StartSend
Layer 4(009F60B0,5626880A) CloseGroup
Layer 3(009B39B0,5626880A) deregisterGroupCallBack 009F60B0 = 0
Layer 8(0097F160,5626880A) ClientConnection closed
Layer 2(009A3300,5626880A) Recv L_Data low from 0.0.0 to 0/1/9 hops: 07 T_DATA_XXX_REQ A_GroupValue_Write (small) 01 
Layer 3(009B39B0,5626880A) Recv L_Data low from 0.0.0 to 0/1/9 hops: 07 T_DATA_XXX_REQ A_GroupValue_Write (small) 01 
Layer 0(0097F4C0,5626880A) SendComplete 64
Layer 0(0097F4C0,5626880A) RecvComplete 64
Layer 0(0097F4C0,5626880A) RecvUSB(064): 01 13 11 00 08 00 09 01 01 00 00 4E BC 11 FD 01 09 F1 00 81 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(0097F4C0,5626880A) StartRecv
Layer 1(0097F4C0,5626880A) Recv(064): 01 13 11 00 08 00 09 01 01 00 00 4E BC 11 FD 01 09 F1 00 81 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0(0097E390,5626880A) RecvEMI(009): 4E BC 11 FD 01 09 F1 00 81

**Comment by meerd** [comment]
After waiting sometime, I get these messages in both:

Layer 0(022F5650,56268996) RecvError 2
Layer 0(022F5650,56268996) StartRecv
Layer 0(022F5650,562689B4) RecvError 2
Layer 0(022F5650,562689B4) StartRecv
Layer 0(022F5650,562689D2) RecvError 2
Layer 0(022F5650,562689D2) StartRecv

However,  even though I got those "RecvError 2" messages 237dcea390e114477ab0b464d1c8369e8ffab9c0 keeps working. I was able to send and receive data.

**Comment by smurfix** [comment]
The RecvError messages were caused by a timeout on the Receive URB. I have since removed that timeout because it's unnecessary.
