### ISSUE TITLE
Can't get knxd working: failure when starting /etc/init.d/knxd start

### ISSUE THREAD

**Issue by gjniewenhuijse** [knxd/knxd#101]
Goal: Get KNXD working on my PI (hardware Jung KNX ip gateway at 192.168.2.16)
My raspberry:
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie

systemctl status knxd.service gives:
â knxd.service - KNX Daemon
   Loaded: loaded (/lib/systemd/system/knxd.service; disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2015-11-05 09:32:17 UTC; 6s ago
  Process: 21931 ExecStart=/usr/bin/knxd $KNXD_OPTS (code=exited, status=1/FAILURE)
 Main PID: 21931 (code=exited, status=1/FAILURE)

Nov 05 09:32:17 homekit systemd[1]: Unit knxd.service entered failed state.

In /etc/init.d/knxd is changed the following lines:
DAEMON=/usr/bin/knxd
DAEMON_ARGS="-c -D -R -T -f9 -S ipt:127.0.0.1 -b ipt:192.168.2.16"
start-stop-daemon --start --quiet --pidfile $PIDFILE -c $DAEMONUSER --e$ || return 1
start-stop-daemon --start --quiet --pidfile $PIDFILE -c $DAEMONUSER --e$ -d -p $PIDFILE DAEMON_ARGS || return 2

How to get KNXD working on my PI, or has someone a working image with knxd that i can download?

**Comment by smurfix** [comment]
Hi,

You're using systemd, thus /etc/init.d/knxd is not used. You want to
edit /etc/knxd.conf. See the README file.

ipt: is used to tunnel to an external gateway. I do not know what your
two ipt: entries are supposed to accomplish, but they're definitely
nonsense; if you want to listen on a TCP port, use the -i flag, but
/lib/systemd/system/knxd.socket already contains port 6720, thus you
usually don't need that at all.

Please tell us more about your actual setup.

On 05.11.2015 10:38, Gert-Jan Niewenhuijse wrote:
>
> Goal: Get KNXD working on my PI (hardware Jung KNX ip gateway at
> 192.168.2.16)
> My raspberry:
> Distributor ID: Raspbian
> Description: Raspbian GNU/Linux 8.0 (jessie)
> Release: 8.0
> Codename: jessie
>
> systemctl status knxd.service gives:
> â knxd.service - KNX Daemon
> Loaded: loaded (/lib/systemd/system/knxd.service; disabled)
> Active: activating (auto-restart) (Result: exit-code) since Thu
> 2015-11-05 09:32:17 UTC; 6s ago
> Process: 21931 ExecStart=/usr/bin/knxd $KNXD_OPTS (code=exited,
> status=1/FAILURE)
> Main PID: 21931 (code=exited, status=1/FAILURE)
>
> Nov 05 09:32:17 homekit systemd[1]: Unit knxd.service entered failed
> state.
>
> In /etc/init.d/knxd is changed the following lines:
> DAEMON=/usr/bin/knxd
> DAEMON_ARGS="-c -D -R -T -f9 -S ipt:127.0.0.1 -b ipt:192.168.2.16"
> start-stop-daemon --start --quiet --pidfile $PIDFILE -c $DAEMONUSER
> --e$ || return 1
> start-stop-daemon --start --quiet --pidfile $PIDFILE -c $DAEMONUSER
> --e$ -d -p $PIDFILE DAEMON_ARGS || return 2
>
> How to get KNXD working on my PI, or has someone a working image with
> knxd that i can download?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/knxd/knxd/issues/101>.
>


-- 
-- Matthias Urlichs

**Comment by gjniewenhuijse** [comment]
My Linux knowledge is basic, so please explain simply :)

My actual setup / goal:
Raspberry Pi with Raspbian GNU/Linux 8.0 (jessie) and an installed Homebridge from Git
A Jung KNX Ip Interface at 192.168.2.16
I like to control my knx installation with Homebridge using KNXD

**Comment by gjniewenhuijse** [comment]
You say:  if you want to listen on a TCP port, use the -i flag, but
/lib/systemd/system/knxd.socket already contains port 6720, thus you
usually don't need that at all.

But i don't have knxd.socket
pi@homekit ~ $ ls -la /lib/systemd/system/knxd*
-rw-r--r-- 1 root root 250 Nov  6 12:36 /lib/systemd/system/knxd.service

How to solve this

**Comment by gjniewenhuijse** [comment]
problem solved. added a -i to the options to add a listener
