### ISSUE TITLE
SystemD: "Address already in use" on fresh RPI

### ISSUE THREAD

**Issue by pos-ei-don** [knxd/knxd#103]
Installef both branches of knxd on RPI with new debian lennie and systemd.

When running knxd like
# knxd -D -S -i --eibaddr=0.0.1 --daemon=/var/log/knxd.log --no-tunnel-client-queuing ipt:192.168.1.5

I always get 
# initialisation of the knxd inet protocol failed: Address already in use

Netstat reports
tcp        0      0 0.0.0.0:6720            0.0.0.0:\*               LISTEN      1/init
this is because of the file
/etc/systemd/system/sockets.target.wants/knxd.socket

Others reported the same error at:
http://knx-user-forum.de/forum/öffentlicher-bereich/knx-eib-forum/39972-eibd-war-bcusdk-fork-knxd?p=874426#post874426

Is there any workaround?

**Comment by smurfix** [comment]
On 13.11.2015 12:35, pos-ei-don wrote:
>
> Is there any workaround?
>
systemd passes the open socket to knxd. This is called "socket
activation" and a very good idea because you don't need strong boot
ordering dependencies any more.

Simply delete this option and everything works.

-- 
-- Matthias Urlichs

**Comment by pos-ei-don** [comment]
Thanks a lot. So is this an error of knxd because the "passing" of the activation doesn't work?
