### ISSUE TITLE
error during Installation on fresh Raspberry Pi 2 (Jessie)

### ISSUE THREAD

**Issue by misc2000** [knxd/knxd#106]
I did set up a Paspberry Pi 2 with a 8GB SSD with curent img (2015-09-24-raspbian-jessie.img)
After updating OS I did try to install knxd by following this description:
http://knx-user-forum.de/forum/öffentlicher-bereich/knx-eib-forum/25473-raspberry-image-eibd-linknx-mit-cometvisu?p=826244#post826244
During the knxd block of comands an error show up:

cd ..
mkdir knxd
cd knxd
git clone https://github.com/knxd/knxd.git
cd knxd
./bootstrap.sh
dpkg-buildpackage -b
cd ..
dpkg -i *.deb
After installing 2 missing things with apt-get (dh-systemd and libsystemd-daemon-dev) I was able the build the package.
But during the installation of it I got this errors:

root@raspberrypi:/usr/local/src/knxd# dpkg -i *.deb
Vormals nicht ausgew?hltes Paket knxd wird gew?hlt.
(Lese Datenbank ... 120023 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von knxd_0.10.9-3_armhf.deb ...
Entpacken von knxd (0.10.9-3) ...
Vormals nicht ausgew?hltes Paket knxd-dev wird gew?hlt.
Vorbereitung zum Entpacken von knxd-dev_0.10.9-3_all.deb ...
Entpacken von knxd-dev (0.10.9-3) ...
Vormals nicht ausgew?hltes Paket knxd-examples wird gew?hlt.
Vorbereitung zum Entpacken von knxd-examples_0.10.9-3_armhf.deb ...
Entpacken von knxd-examples (0.10.9-3) ...
Vormals nicht ausgew?hltes Paket knxd-tools wird gew?hlt.
Vorbereitung zum Entpacken von knxd-tools_0.10.9-3_armhf.deb ...
Entpacken von knxd-tools (0.10.9-3) ...
knxd (0.10.9-3) wird eingerichtet ...
Lege Gruppe ?knxd? (GID 115) an ...
Fertig.
Lege Systembenutzer ?knxd? (UID 110) an ...
Lege neuen Benutzer ?knxd? (UID 110) mit Gruppe ?knxd? an ...
Erstelle Home-Verzeichnis ?/var/lib/knxd? ...
**Job for knxd.service failed. See 'systemctl status knxd.service' and 'journalctl -xn' for details.**
**Job for knxd.service failed. See 'systemctl status knxd.service' and 'journalctl -xn' for details.**
**invoke-rc.d: initscript knxd, action "start" failed.**
**dpkg: Fehler beim Bearbeiten des Paketes knxd (--install):**
** Unterprozess installiertes post-installation-Skript gab den Fehlerwert 1 zur?ck**
knxd-dev (0.10.9-3) wird eingerichtet ...
knxd-examples (0.10.9-3) wird eingerichtet ...
knxd-tools (0.10.9-3) wird eingerichtet ...
Trigger f?r systemd (215-17+deb8u2) werden verarbeitet ...
Trigger f?r libc-bin (2.19-18+deb8u1) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 knxd
**"systemctl status knxd.service" shows:**
knxd.service - KNX Daemon
Loaded: loaded (/lib/systemd/system/knxd.service; enabled)
Active: activating (auto-restart) (Result: exit-code) since Di 2015-11-17 22:01:45 CET; 2s ago
Process: 29599 ExecStart=/usr/bin/knxd $KNXD_OPTS (code=exited, status=1/FAILURE)
Main PID: 29599 (code=exited, status=1/FAILURE)
Nov 17 22:01:45 raspberrypi systemd[1]: Failed to start KNX Daemon.
Nov 17 22:01:45 raspberrypi systemd[1]: Unit knxd.service entered failed state.

**and "journalctl -xn" shows:**
-- Logs begin at Di 2015-11-17 19:46:57 CET, end at Di 2015-11-17 22:03:48 CET. --
Nov 17 22:03:38 raspberrypi systemd[1]: knxd.service: main process exited, code=exited, status=1/FAILURE
Nov 17 22:03:38 raspberrypi systemd[1]: Failed to start KNX Daemon.
-- Subject: Unit knxd.service has failed
-- Defined-By: systemd
-- Unit knxd.service has failed.
-- The result is failed.
Nov 17 22:03:38 raspberrypi systemd[1]: Unit knxd.service entered failed state.
Nov 17 22:03:48 raspberrypi systemd[1]: knxd.service holdoff time over, scheduling restart.
Nov 17 22:03:48 raspberrypi systemd[1]: Stopping KNX Daemon...
-- Subject: Unit knxd.service has begun shutting down
-- Defined-By: systemd
-- Unit knxd.service has begun shutting down.
Nov 17 22:03:48 raspberrypi systemd[1]: Starting KNX Daemon...
-- Subject: Unit knxd.service has begun with start-up
-- Defined-By: systemd
-- Unit knxd.service has begun starting up.
Nov 17 22:03:48 raspberrypi knxd[29967]: not a valid url
Nov 17 22:03:48 raspberrypi systemd[1]: knxd.service: main process exited, code=exited, status=1/FAILURE
Nov 17 22:03:48 raspberrypi systemd[1]: Failed to start KNX Daemon.
-- Subject: Unit knxd.service has failed
-- Defined-By: systemd
-- Unit knxd.service has failed.
-- The result is failed.
Nov 17 22:03:48 raspberrypi systemd[1]: Unit knxd.service entered failed state.

Because I only have basic linux knowledge I do not know how to solve it.
Do you know this error and do you have any workaround for it?
Thanks
Michael

**Comment by misc2000** [comment]
I think found the problem by my own.
After some more tests today I found out that the port 6720 is blocked by OS and can not be used for knxd.
pi@knx-rpi ~ $ sudo netstat -tanp | grep 6720
tcp6       0      0 :::6720                 :::*                    LISTEN      1/init    

After change the knxd port with --listen-tcp=6721 to 6721 it works for me.

**Comment by smurfix** [comment]
It's not blocked by "OS", but by the knxd.socket file, i.e. it's opened by systemd and passed to knxd when it starts.
Simply skip that parameter. The current version will have some more explanation for this in the knxd.conf file.
