### ISSUE TITLE
Debian package format should be native not quilt

### ISSUE THREAD

**Issue by hari2** [knxd/knxd#107]
Is there a specific reason why the debian package format is set to '3.0 (quilt)' and not '3.0 (native)'?

**Comment by smurfix** [comment]
General laziness on my part.

Does that cause any problems? If so, feel free to submit a pull request.

**Comment by RichiH** [comment]
With my DD hat on: `3.0 (quilt)` with no patches is less pain in case things ever need to be fixed.

That being said, doing all work in the master branch and simply pulling in changes into packaging branches is the Best Thing To Do given responsive upstream (which is the case here).

Not that this is too relevant before we _finally_ have progress on https://github.com/knxd/knxd/issues/29

**Comment by hari2** [comment]
The problem I have with quilt is that you can't build e.g. with sbuild (it rants about the missing upstream tarball). As the debian dir is provided by the upstream knxd source, and no patches need to be applied, the version should be native afaict.

https://www.debian.org/doc/manuals/maint-guide/dother.en.html#sourcef

**Comment by RichiH** [comment]
The maint-guide is not always the most up to date resource.

Using `gbp`, we just have a (signed, ideally) release tag, merge that in, `dch; dch -r`, build, test, and sign/tag/upload.

**Comment by RichiH** [comment]
A slightly complex, but very much working, example can be found at https://github.com/RichiH/vcsh/network

**Comment by hari2** [comment]
RichiH, I'm far no debian package building expert but the current format being set to quilt prevents proper packages from being built with common tools like sbuild. You can also reproduce that by building a full package (not only binary) with dpkg-buildpackage. It will rant about the missing upstream tarball. With knxd, everything is contained in the tree. There is no need to take a source ball, add the debian dir, and apply whatever patches. So quilt is just not correct in this case, and it prevents me from building packages on multiple arches with sbuild. If you insist on having quilt format set, I'd be interested in your very specific reason.

**Comment by RichiH** [comment]
I am not insisting, I am just saying that modern build systems just build the orig tarball from the appropriate tag all by themselves so I don't see the concern, really.

**Comment by hari2** [comment]
commit 85701b4f7215c814438d183f301d488f9d280f66
