### ISSUE TITLE
Crashes with segmentation fault if option "-i" is given without port parameter

### ISSUE THREAD

**Issue by Sonderstorch** [knxd/knxd#111]
```
(gdb) run
Starting program: /usr/bin/knxd -e 1.1.15 -b tpuarts:/dev/ttyAMA0 -i
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000b964 in parse_opt (key=105, arg=<optimized out>, state=0xbefff504) at knxd.cpp:374
374             int port = atoi(OPT_ARG(arg,state,"6720"));
```

There's also a typo in knxd.cpp, line 234 ("a commonication stack").

I wanted to fix it, but seeing this crude mix between old-style C and CPP as "C with classes" approach I rather supress my urge to rewrite the whole thing... The command line parsing is just pathologic. Guys, use boost::program_options or at least getopt.

Ah, and what makes this an issue is, that the PORT parameter is described as optional (but rather isn't).

**Comment by Sonderstorch** [comment]
Update: Don't having the parameters "ip:port" at the -S option also crashes.

Omitting the defaults worked with eibd, so these are regressions.

**Comment by RichiH** [comment]
Would anyone actually object to Sonderstorch simply rewriting option
parsing in C++ with boost/getopts?

Richard

Sent by mobile; excuse my brevity.

**Comment by tru7** [comment]
not directly, but there has always existed the configure switch --without-libstdc. What do you do with it then?

**Comment by RichiH** [comment]
I really think we should cut out some old stuff and continue from there. A
raspberry pi is a reasonable minimum these days and cleaning up and
modernizing the codebase would help.

If anyone really needs to use the old WRT they have used for a decade,
fine. Let them use it along with an old version of knxd which receives only
critical fixes and nothing else.

Richard

Sent by mobile; excuse my brevity.

**Comment by Sonderstorch** [comment]
If you care for size, why event bother with C++ anyway? In that case, you should have gone the C-only route a long time ago, IMHO (maybe using glib).

We're approaching 2016 now and you're still wasting efforts re-inventing the wheel.

**Comment by smurfix** [comment]
I pushed a fix for this crash. Untested but obviously correct. ;-)

A re-write of argument handling should start with designing a reasonable configuration file format / data structure (I'm a fan of YAML, personally). Then add an argument parser which teaches the old arguments to simply modify that structure.

One big reason for this: larger KNX installations require multiple zones and filtering / translating group addresses. You can't handle this sort of situation with a zillion command line arguments.

I don't like people to spend time designing a better hammer when what we really need is a powered screwdriver.
