### ISSUE TITLE
invalid argument handling

### ISSUE THREAD

**Issue by tru7** [knxd/knxd#113]
I'm afraid argument handling is still invalid:
this works: knxd -d -DTS -i 6720 ipt:192.168.1.20
this fails: knxd -d -DTS -i ipt:192.168.1.20
initialisation of the knxd inet protocol failed: Interrupted system call
To me it looks like the last argument before URL must not be without value, which makes it impossible to use something like knxd -d -DTS ipt:192.168.1.20 which should be valid, right?

**Comment by smurfix** [comment]
On 05.01.2016 23:25, Othmar Truniger wrote:
>
> I'm afraid argument handling is still invalid:
> this works: knxd -d -DTS -i 6720 ipt:192168120
> this fails: knxd -d -DTS -i ipt:192168120
> initialisation of the knxd inet protocol failed: Interrupted system call
>
Add "-b" (or "--layer2=") in front of the "ipt:". Or move the "-i" in
front of "-DTS".
>
> To me it looks like the last argument before URL must not be without
> value, which makes it impossible to use something like knxd -d -DTS
> ipt:192168120 which should be valid, right?
>
Yes it's valid and it works. The problem is how to detect an optional
argument. The code that handles this situation doesn't know what that
argument is supposed to look like, so it just decides this by checking
whether it starts with a dash.

-- 
-- Matthias Urlichs

**Comment by tru7** [comment]
Not a big issue of course, it's just not exactly doing what may be expected, fifth priority.
knxd -d -DTS ipt:192.168.1.20
E00000011: Addr 'ipt' not resolvable
initialization of the EIBnet/IP server failed: Invalid argument

**Comment by Makki1** [comment]
Maybe I missed something..
But 192168120 is not even close to being a valid IPv4-Address?
Have you ommited the required dots only in all posts or also in the args?

Michael

**Comment by tru7** [comment]
@Makki1 the dots were stipped off by the portal software. They are still there in all my original posts. I can still see them.

**Comment by smurfix** [comment]
There is a new "-b" option which is the preferred way of specifying an interface.
