### ISSUE TITLE
KNXD don't work with USB interface

### ISSUE THREAD

**Issue by fabioz23** [knxd/knxd#114]
Hi,

KNXD don't work with Weinzierl 330 USB interface.

It starts but it doesn't read/write nothing on the knx bus.

**Launching eibd with the same arguments it works.**

What can I do?

**Comment by smurfix** [comment]
Hi,

please think while reporting an error. Specifically …
>
> /Launching eibd with the same arguments it works/
>
… what arguments are you actually using??

-- 
-- Matthias Urlichs

**Comment by fabioz23** [comment]
Yes, I'm sorry but for reporting more info I need to re-test at home. Tomorrow morning I'll send all the info useful for diagnose the problem.

**Comment by fabioz23** [comment]
in the meantime this is the command launched:

```bash
eibd -D -T -R -S -i -u --eibaddr=0.0.100 usb:2:3:1:0:0

OR

knxd --eibaddr=0.0.100  -i -u -D -T -R -S usb:2:3:1:0:0

```

**Comment by fabioz23** [comment]
after, launching some write with:
```bash
groupswrite localhost 0/0/1 1
```
works.

If I launch:
```bash
knxtool groupswrite localhost 0/0/1 1
```
don't works and on the console the knxd process don't print any rows on input message.

**Comment by tru7** [comment]
I think this is related to #113. Just take care that the last parameter before the URL is one without an optional argument or a parameter with argument value. Or just put -b in front of the URL. In your case -S befor usb: is problematic

**Comment by smurfix** [comment]
On 08.01.2016 13:38, fabioz23 wrote:
>
> after, launching some write with:
>
> groupswrite localhost 0/0/1 1
>
> works.
>
> If I launch:
>
> knxtool groupswrite localhost 0/0/1 1
>
> don't works
>
That's strange, as these tools really didn't change and should do the
exact same thing.

Is there an error message?

Can you compare the packets sent by these two programs? (strace -e
connect,read,write,close -s100 knxtool …, the interesting part is
between the _last_ connect and close calls)


-- 
-- Matthias Urlichs

**Comment by stargieg** [comment]
Hi
I have a similar Problem with Gira USB.
knxd run and works only in forground with --error=1

This works
```
knxd --error=1 --listen-local=/var/run/knxd --pid-file=/var/run/knxd.pid --layer2=usb:2:2:1:0:0
knxtool groupswrite local:/var/run/knxd 0/0/1 0
```
but not with bash & or with --daemon. The result is a zombie process or an segfault
```
[ 2418.930045] usb 2-2: usbfs: interface 0 claimed by usbfs while 'knxd' sets config #1
[57294.535943] knxd[14862]: segfault at 8 ip b76ce62e sp 0847af34 error 6 in libuClibc-0.9.33.2.so[b769a000+4f000]
```
I have compile knxd with -g0 and -O0 for openwrt x86 with gdbserver and valgrind.
What is the preferred way to figure out what is going wrong?

**Comment by smurfix** [comment]
No, that's not the same problem at all. Please open a separate issue for this.

**Comment by smurfix** [comment]
@fabioz23 Please try again with "-b" in front of the "usb:…" string.

**Comment by migabc** [comment]
Can someone please tell me which syntax I should use to interface the knxd or eibd with the Gira USB?

**Comment by smurfix** [comment]
@migabc "-b usb:" should be sufficient. You might need to add a UDEV rule which changes the USB interface's owner to knxd. The current version has a few more examples for that.

**Comment by migabc** [comment]
I'm using the eibd where the -b option is not supported:

$ /opt/knx/bin/eibd -i  -e 0.0.100 -b usb:
eibd: invalid option -- b
Try `eibd --help' or `eibd --usage' for more information.

How can I use the usb interface with the eibd?
How can I install the knxd on a Mac?

**Comment by smurfix** [comment]
Again: Questions should go to the mailing list.

**Comment by smurfix** [comment]
Closing because of lack of feedback. Please re-open if appropriate.
