### ISSUE TITLE
conn_sep doesn't compile on debian squeeze

### ISSUE THREAD

**Issue by gedia** [knxd/knxd#115]
Hello,

Compilation on debian-squeeze of branch conn_sep fails with the following error:

    g++ -DHAVE_CONFIG_H -I. -I../..  -I../../src/include -I../../src/common -I/usr/include   -g -O2 -std=c++0x -fno-exceptions -c -o layer2.o layer2.cpp
    In file included from layer2.cpp:21:
    layer3.h:119: error: ‘nullptr’ was not declared in this scope
    layer3.h:122: error: ‘nullptr’ was not declared in this scope
    make[4]: *** [layer2.o] Error 1
    make[4]: Leaving directory `/root/knxd/src/libserver'
    make[3]: *** [all-recursive] Error 1
    make[3]: Leaving directory `/root/knxd/src'
    make[2]: *** [all-recursive] Error 1
    make[2]: Leaving directory `/root/knxd'
    make[1]: *** [all] Error 2
    make[1]: Leaving directory `/root/knxd'
    dh_auto_build: make -j1 returned exit code 2
    make: *** [build] Error 2
    dpkg-buildpackage: error: debian/rules build gave error exit status 2

That is with gcc (Debian 4.4.5-8) 4.4.5 on debian i386

**Comment by gedia** [comment]
I assume this is because a C++11 compatible gcc is needed?

**Comment by smurfix** [comment]
On 08.01.2016 18:00, gedia wrote:
>
> I assume this is because a C++11 compatible gcc is needed?
>
Yes, that's the way it's written currently.

You might be able to fake most, if not all, of what knxd needs with boost.
I'll accept a patch if it's not too intrusive, but it's probably easier
to upgrade the Squeeze box to Lenny. :-P

-- 
-- Matthias Urlichs

**Comment by gedia** [comment]
I compiled it on a debian wheezy, and then installed the resulting debs on squeeze, and it seems to work so far.
