### ISSUE TITLE
groupsocketlisten buffers output

### ISSUE THREAD

**Issue by RichiH** [knxd/knxd#118]
- `groupsocketlisten ip:127.0.0.1` outputs immediately, as expected
- `groupsocketlisten ip:127.0.0.1 | cat` buffers until the buffer is full or until the program exits
- `unbuffer groupsocketlisten ip:127.0.0.1 | cat` outputs immediately, as expected

I tried making it flush properly on non-TTY STDOUT, but failed.

**Comment by smurfix** [comment]
I cannot understand why this should happen. `src/examples/groupsocketlisten.c` has had an appropriate `fflush(stdout)` call for years.

**Comment by InnoredFR** [comment]
It seems to be resolved, or am I mistaken ? 
I wanted to fix this, since it was marked as "help wanted" but either i did not understand the issue, or it is already fixed.
Can someone confirm ?

**Comment by smurfix** [comment]
Looked at it again, immediately saw the problem. Owch. Fix forthcoming.
