### ISSUE TITLE
Auto-reconnect USB

### ISSUE THREAD

**Issue by Makki1** [knxd/knxd#12]
Reconnect USB-Interfaces as well as USB TP-UART after a disconnection (or USB-hub reset)
If possible, this would be a good enhancement for stability.

**Comment by smurfix** [comment]
This actually applies to all interfaces. Might be tackled after the move to a config file.

**Comment by wbramw** [comment]
Any updates on this story? I have the same problem with LAN-interfaces. When I reconnect the LAN cable, sometimes the knxd will no longer function.

**Comment by smurfix** [comment]
Interface restart options exist by now. Check the documentation.

One problem with LAN restarts that this may not solve is if your DHCP server gives you another address after reconnecting. Best to give infrastructure fixed addresses.

**Comment by wbramw** [comment]
Where exactly is this documented?
