### ISSUE TITLE
Raspberry 2 knx don't work

### ISSUE THREAD

**Issue by niwa83** [knxd/knxd#125]
Hi,
while i'm tried to install knxd on my raspberry 2 jessie the following error is printed:

 sudo dpkg-buildpackage -b -uc
dpkg-buildpackage: source package knxd
dpkg-buildpackage: source version 0.9.0-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Timo knxd@timo-wingender.de
dpkg-buildpackage: host architecture armhf
 dpkg-source --before-build knxd
 debian/rules clean
dh clean
   dh_testdir
   dh_auto_clean
   dh_clean
        rm -f debian/knxd.substvars
        rm -f debian/knxd._.debhelper
        rm -rf debian/knxd/
        rm -f debian/knxd-tools.substvars
        rm -f debian/knxd-tools._.debhelper
        rm -rf debian/knxd-tools/
        rm -f debian/knxd-dev.substvars
        rm -f debian/knxd-dev._.debhelper
        rm -rf debian/knxd-dev/
        rm -f debian/knxd-examples.substvars
        rm -f debian/knxd-examples._.debhelper
        rm -rf debian/knxd-examples/
        rm -f debian/_.debhelper.log
        rm -f debian/files
        find .  ( ( \
                ( -path .\_/.git -o -path .*/.svn -o -path .*/.bzr -o -path .*/.hg -o -path .*/CVS ) -prune -o -type f -a \
                ( -name '#_#' -o -name '._~' -o -name '_~' -o -name DEADJOE \
                 -o -name '_.orig' -o -name '_.rej' -o -name '_.bak' \
                 -o -name '._.orig' -o -name ._.rej -o -name '.SUMS' \
                 -o -name TAGS -o ( -path '_/.deps/_' -a -name '_.P' ) \
                ) -exec rm -f {} + ) -o \
                ( -type d -a -name autom4te.cache -prune -exec rm -rf {} + ) )
        rm -f *-stamp
 debian/rules build
dh build
   dh_testdir
   debian/rules override_dh_auto_configure
make[1]: Entering directory '/home/pi/knxd'
dh_auto_configure -- --enable-usb --enable-eibnetip --enable-eibnetiptunnel --enable-eibnetipserver --enable-groupcache --enable-tpuart --enable-ft12
make[1]: Leaving directory '/home/pi/knxd'
   dh_auto_build
   dh_auto_test
 debian/rules binary
dh binary
   dh_testroot
   dh_prep
        rm -f debian/knxd.substvars
        rm -f debian/knxd._.debhelper
        rm -rf debian/knxd/
        rm -f debian/knxd-tools.substvars
        rm -f debian/knxd-tools._.debhelper
        rm -rf debian/knxd-tools/
        rm -f debian/knxd-dev.substvars
        rm -f debian/knxd-dev._.debhelper
        rm -rf debian/knxd-dev/
        rm -f debian/knxd-examples.substvars
        rm -f debian/knxd-examples._.debhelper
        rm -rf debian/knxd-examples/
   dh_auto_install
        install -d debian/knxd
        install -d debian/knxd-tools
        install -d debian/knxd-dev
        install -d debian/knxd-examples
   dh_install
        install -d debian/knxd///usr/bin
        cp -a debian/tmp//usr/bin/knxd debian/knxd///usr/bin/
cp: cannot stat ‘debian/tmp//usr/bin/knxd’: No such file or directory
dh_install: cp -a debian/tmp//usr/bin/knxd debian/knxd///usr/bin/ returned exit code 1
debian/rules:14: recipe for target 'binary' failed
make: *_\* [binary] Error 2
dpkg-buildpackage: error: debian/rules binary gave error exit status 2

What is the problem?

regards

**Comment by ProjektHTPC** [comment]
Had the same problem. Try this:

**1.**
sudo apt-get install debhelper cdbs automake libtool libusb-1.0-0-dev git-core build-essential

**2.**
sudo apt-get install libsystemd-daemon-dev dh-systemd

**after install change to directory pthsem-2.0.8**
cd pthsem-2.0.8

proceed like written in the manual

regards

**Comment by niwa83** [comment]
Now following error after sudo dpkg -i knxd_*.deb knxd-tools_*.deb

Selecting previously unselected package knxd.
(Reading database ... 127323 files and directories currently installed.)
Preparing to unpack knxd_0.10.12-1_armhf.deb ...
Unpacking knxd (0.10.12-1) ...
Selecting previously unselected package knxd-tools.
Preparing to unpack knxd-tools_0.10.12-1_armhf.deb ...
Unpacking knxd-tools (0.10.12-1) ...
Setting up knxd (0.10.12-1) ...
Adding group `knxd' (GID 115) ...
Done.
Adding system user `knxd' (UID 110) ...
Adding new user `knxd' (UID 110) with group `knxd' ...
Creating home directory `/var/lib/knxd' ...
Job for knxd.service failed. See 'systemctl status knxd.service' and 'journalctl -xn' for details.
invoke-rc.d: initscript knxd, action "start" failed.
dpkg: error processing package knxd (--install):
 subprocess installed post-installation script returned error exit status 1
Setting up knxd-tools (0.10.12-1) ...
Processing triggers for systemd (215-17+deb8u3) ...
Processing triggers for libc-bin (2.19-18+deb8u3) ...
Errors were encountered while processing:
 knxd

What to do?

**Comment by smurfix** [comment]
On 23.02.2016 17:15, niwa83 wrote:
> Job for knxd.service failed. See 'systemctl status knxd.service' and
> 'journalctl -xn' for details.
Do that. And add the configuration from /etc/knxd.conf.

-- 
-- Matthias Urlichs

**Comment by smurfix** [comment]
Closing due to missing feedback.
