### ISSUE TITLE
knxd only with read and write of groupaddresses

### ISSUE THREAD

**Issue by Hollywood64** [knxd/knxd#127]
I use currently knxd with a rapberry pi.
3 years ago i used openWrt with eibd of TU Wien and i had a ntpd installed. While the ntpd was unsafe, some guys have hacked the openWrt and they reprogrammed the instabus of my house.

My question is: 
Is it possible to configure the knxd without programming interface and i will use only read and write function of kny addresses locally inside of the raspberry pi ?

**Comment by smurfix** [comment]
On 05.03.2016 18:03, Hollywood64 wrote:
>
> I use currently knxd with a rapberry pi.
> 3 years ago i used openWrt with eibd of TU Wien and i had a ntpd
> installed. While the ntpd was unsafe, some guys have hacked the
> openWrt and they reprogrammed the instabus of my house.
>
> My question is:
> Is it possible to configure the knxd without programming interface and
> i will use only read and write function of kny addresses locally
> inside of the raspberry pi ?
>
>
If the bad guys can somehow access the KNX bus, they can do pretty much
everything.
Currently knxd doesn't support any filtering.

The solution is to partition and/or filter your network so that the
router doesn't even see the KNX packets.
You might be able to set up a fancy iptables rule which only passes
read+write.

-- 
-- Matthias Urlichs

**Comment by xvdessel** [comment]
Depends which level of attack you want to cope with.

There is nothing you can do against a root level attack. Even if you could build a knxd with limited support, all they need to do is copy over the full knxd (which is open source anyway) and run it.

If you want to protect against user level attacks, then there are some more options.

You could start knxd normally, but protect its IP input to only accept localhost connections. This can be easily done with iptables or any other firewall layer.
Then, you can shield off the knxtool program which calls knxd, and allow it only to be run by root.
Thirdly, you can use sudo to allow your functional userid to specifically allow a subset of the knxd calls, in your case the groupread and groupwrite. Either you encapsulate these in bash scripts that are allowed by sudo, or you define more elaborate sudo rules that only match if you specify the groupread or groupwrite options.
Under the above setup, the link with the KNX device (USB, serial) is locked by the running knxd instance so unless they can stop the knxd service, they can't reach the native bus interface.

**Comment by Hollywood64** [comment]
Thank you,

for the suggestion.

I will try to use a firewall first. Depending on the parameters of knxd i have to protect the multicast address too. I will try to start knxd with parameters, which start without multicast access.

To protect the knxtool and allowing only a subset of knxd calls is a good idea.

Thank you

**Comment by smurfix** [comment]
The "libev" version of knxd (work in progress, will probably be somewhat ready next week) will have support for disabling management commands. In fact they will not work at all initially because basic bus communication is kindof more important. ;-)
