### ISSUE TITLE
Doesn't build on Debian Jessie

### ISSUE THREAD

**Issue by samkrew** [knxd/knxd#128]
I build with `dpkg-buildpackage -b -uc`

Got an error:

dh build 
   dh_testdir
   debian/rules override_dh_auto_configure
make[1]: Entering directory '/root/knxd-0.10.1'
dh configure.in 
dh: Unknown sequence configure.in (choose from: binary binary-arch binary-indep build build-arch build-indep clean install install-arch install-indep)
debian/rules:14: recipe for target 'configure.in' failed
make[1]: *** [configure.in] Error 2
make[1]: Leaving directory '/root/knxd-0.10.1'
debian/rules:14: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by smurfix** [comment]
Hi,
>
> |
> make[1]: Entering directory '/root/knxd-0.10.1'
> |
>

|Why are you trying to use an old version?|

-- 
-- Matthias Urlichs

**Comment by samkrew** [comment]
Because of https://github.com/knxd/knxd/releases

**Comment by smurfix** [comment]
On 11.03.2016 15:27, samkrew wrote:
>
> Because of https://github.com/knxd/knxd/releases
>

Ah. Thank you for reminding me to build a new one.

Please get the latest master or conn_sep branch.

-- 
-- Matthias Urlichs

**Comment by snowdd1** [comment]
Good point. I made a fresh install following the readme yesterday and it says 
````
pi@knxd-raspberry:~ $ knxd --version
knxd 0.10.0
````
Did I get an old version or does it simply report an old version number as no one increased it?

Regards
Raoul

**Comment by smurfix** [comment]
On 12.03.2016 10:58, Raoul wrote:
>
> Good point. I made a fresh install following the readme yesterday and
> it says
>
> |pi@knxd-raspberry:~ $ knxd --version knxd 0.10.0 |
>
> Did I get an old version or does it simply report an old version
> number as no one increased it?
>
Yes, I completely forgot to increase that.
I (or somebody else, hint hint) will have to add something to do that
automatically.

-- 
-- Matthias Urlichs

**Comment by smurfix** [comment]
Version numbering is in #131, closing this bug.
