### ISSUE TITLE
Differences between /etc/knxd.conf and commandline?

### ISSUE THREAD

**Issue by snowdd1** [knxd/knxd#130]
On my fresh install on raspi 1b+ with raspbian minimal (JESSIE w/ systemd) I have strange differences between running knxd from commandline and the service, maybe I overlooked something.

Commandline works as expected, example: 
`sudo -u knxd knxd  --trace=1023 --Routing --Server --listen-tcp=4711 --layer2=tpuarts:/dev/ttyKNX1`
(even without `trace` :smile: )

In the knxd.conf I can use
````
# configuration for knxd.service
KNXD_OPTS="--eibaddr=0.0.2 --layer2=tpuarts:/dev/ttyKNX1"
````
but I **cannot** use `--Routing` and `--Server`, it will fail to start the service.

I found this also applies to 
`--Name`
`--Tunnelling --Server`

Any idea why, what have I missed?

**Comment by smurfix** [comment]
On 12.03.2016 12:03, Raoul wrote:
>
> On my fresh install on raspi 1b+ with raspbian minimal (JESSIE w/
> systemd) I have strange differences between running knxd from
> commandline and the service, maybe I overlooked something.
>
> Commandline works as expected, example:
> |sudo -u knxd knxd --trace=1023 --Routing --Server --listen-tcp=4711
> --layer2=tpuarts:/dev/ttyKNX1|
> (even without |trace| :smile: )
>
> In the knxd.conf I can use
>
> |# configuration for knxd.service KNXD_OPTS="--eibaddr=0.0.2
> --layer2=tpuarts:/dev/ttyKNX1" |
>
> but I *cannot* use |--Routing| and |--Server|, it will fail to start
> the service.
>
> I found this also applies to
> |--Name|
> |--Tunnelling --Server|
>
> Any idea why, what have I missed?
>
Not at the moment. Could you turn on logging and check what systemctl is
saying? Does it work with -RS instead?

-- 
-- Matthias Urlichs

**Comment by snowdd1** [comment]
> Could you turn on logging 

How do I do logging with a service? Sorry, new to `systemd`; I understand that `daemon=logfile` does not work with systemd services

**Comment by smurfix** [comment]
On 12.03.2016 16:22, Raoul wrote:
>
>     Could you turn on logging
>
> How do I do logging with a service? Sorry, new to |systemd|; I
> understand that |daemon=logfile| does not work with systemd services
>
You just let it write to stderr, same way you'd do it when manually
starting knxd.
systemctl / journalctl will show the output.

-- 
-- Matthias Urlichs

**Comment by snowdd1** [comment]
I am ashamed in multiple ways...
There was a *minor* but important difference between the two parameter sets in my first post: 
The existence of `--eibaddr=` which **must not** appear after `-S`
Plus I found the log in `var/log/daemon`

It would probably a good thing to have a list of parameters **_in order of appearance_** additionally to the alphabetical listing. I knew there were a lot of discussions about having the `-S` after `-R` and `-D` and `-T` but never heard of the `--Name` and `--eibaddr` parameters, though it makes perfectly sense as they apply to the `Server` as well.

**Comment by snowdd1** [comment]
As a means of reparation for your time consumed I can offer to write a section about how to get a busware pigator KNX to work with knxd, if that is of any interest - it's comparable to TUL, only the UDEV params are a little different.

**Comment by smurfix** [comment]
On 12.03.2016 16:41, Raoul wrote:
>
> As a means of reparation for your time consumed I can offer to write a
> section about how to get a busware pigator KNX to work with knxd, if
> that is of any interest - it's comparable to TUL, only the UDEV params
> are a little different.
>
No problem.
Please do.
Also, if you want to rearrange the list of options (sections:
server-as-a-whole / applies-to-next-driver / drivers (-b -i -u -S)) so
that you would have gotten it right without filing spurious bugs ;-) be
my guest, having the options alphabetical is much less interesting than
understanding what they do and affect.

NB: if you do this, please use the conn_sep branch.

In fact, these bugs are not spurious, they show that the documentation
is lacking and/or server configuration could be improved. Which is
certainly true; a .ini-style document or YAML would be much better, but
somebody gotta take a day or two off and code that; unfortunately that
person is not going to be me for the foreseeable future (~6months at least).

-- 
-- Matthias Urlichs

**Comment by snowdd1** [comment]
@smurfix : Matthias, I have put an update to the parameter readme in a gist for commenting: 
https://gist.github.com/snowdd1/0ecceb38e924ee125d36
