### ISSUE TITLE
Automate version numbering

### ISSUE THREAD

**Issue by smurfix** [knxd/knxd#131]
There's too many places with a version number. The build system should get it from a central place, probably the top of debian/changelog, and update all other occurrences accordingly.

**Comment by tru7** [comment]
There is a central place: it's the version argument in the AC_INIT macro in configure.ac and the manual says it must be static. But: it can be computed by M4. You could use m4_esyscmd_s to call a new script which extracts the version from debian/changelog.

**Comment by tru7** [comment]
done nicely ;-)
