### ISSUE TITLE
groupsocketlisten in conn_sep branch

### ISSUE THREAD

**Issue by snowdd1** [knxd/knxd#133]
I successfully updated my knxd to the **conn_sep** branch as of last weekend. Everything is nice and running now, except for a tool that requires a groupsocketlisten functionality (the node_eibd node module).

I had a knxd running before from July 2015 in which *that* was working perfectly fine.

It digged into it and found it sends a command of (uints) `0,38,0,0,0` (decimal) to the knxd to register.

BTW: `knxtool groupsocketlisten ip:localhost` didn't produce any output as well, whereas `knxtool vbusmonitor1time ip:localhost` prints in great detail.

So the issue might be already in that, and not in a changed API definition?

Confused...
Raoul

**Comment by snowdd1** [comment]
Ok, some more details.
I am running knxd (conn_sep) as a service on a Raspberry with physical interface.

On that Raspberry `groupsocketlisten` does not work, as decribed above.

On a second Raspberry I have now - for testing - installed a knxd (master branch). I have linked both with `knxd -b ip` (-i and -u implicit) as service on the second raspberry.

`knxtool vbusmonitor1time ip:localhost` does work on both raspberries, and simultaneously prints the bus traffic

`knxtool groupsocketlisten ip:localhost` only works on the *master branch* version. On the `conn_sep` version raspberry it stays silent.

The same using UNIX sockets, with `local:` instead of `ip:localhost`.
Anything I could have missed?

**Comment by smurfix** [comment]
On 17.03.2016 19:14, Raoul wrote:
>
> |knxtool vbusmonitor1time ip:localhost| does work on both raspberries,
> and simultaneously prints the bus traffic
>
> |knxtool groupsocketlisten ip:localhost| only works on the /master
> branch/ version. On the |conn_sep| version raspberry it stays silent.
>
>
That's obviously a bug. Feel free to have a closer look at the code; I
probably won't have time until next month.

Also, a testcase for this would be good to have.

-- 
-- Matthias Urlichs

**Comment by snowdd1** [comment]
>Feel free to have a closer look at the code

I tried, but as I never learned c++ it's a maze for me. I tried to follow the calls and definitions from knxtool but failed to find "EIBOpen_GroupSocket" except in eibclient.h#330, and there I lost it. Sorry, I am of no help with c++.

**Comment by smurfix** [comment]
On 18.03.2016 23:41, Raoul wrote:
>
>     Feel free to have a closer look at the code
>
> I tried, but as I never learned c++ it's a maze for me. I tried to
> follow the calls and definitions from knxtool but failed to find
> "EIBOpen_GroupSocket" except in eibclient.h#330, and there I lost it.
> Sorry, I am of no help with c++.
>
That's a client function. The problem, most likely, is in the server.

To explain what's going on: the client code is constructed by a bunch of
macros, the goal being to have just one magic formula that can be
applied to any programming language whatsoever by clever use of C
macros. (This basically guarantees that you're writing C code in Perl or
Python or Ruby, instead of using proper object-oriented abstraction, but
one can't have everything.) This cleverness causes the client C code to
be totally non-debuggable, and the best way to verify that it still
works correctly is to check that the transmitted packets didn't change
between master and conn_sep, using wireshark.

src/client/def/opengroupsocket.inc contains the macro that constructs a
message of type EIB_OPEN_GROUPCON
The server code which processes this message is in
src/libserver/client.cpp#139. It constructs an A_GroupSocket object
(whose code is in src/libserver/connection.cpp) which basically takes
over the connection. Its creator function (#125) sets up a GroupSocket,
which is the thing that actually connects to the layer3 objects and
monitors group broadcasts (unless created write-only):
GroupSocket::Send_L_Data() is called from Layer3 code, where the message
is put onto a queue. It then gets picked up by A_GroupSocket::Run and is
forwarded to the client.

(The original author of knxd was in love with threads reading from
queues. The only code which actually needs them is the transmitting part
of slow Layer-2 interfaces; the other 90% add useless complications and
could be replaced with a simple callback.)

-- 
-- Matthias Urlichs

**Comment by snowdd1** [comment]
I've to admit I did not grasp everything you tried to explain...
I focused on what I can directly see, and generated knxd trace outputs from my test-raspberry. First I installed master, ran it against my production knxd (which has the physical and the multicast server) and tried knxtool groupsocketlisten, then I installed conn_sep and did the same.

Here are the results

master | conn_sep
----------|--------------
Layer 8(0064C1E0,56ED197D) New Connection | Layer 8(008BE1F8,56ED1A2D) New Connection
Layer 8(0067ECA0,56ED197D) ClientConnection Init | Layer 8(008F0C68,56ED1A2D) ClientConnection Init
Layer 8(0067ECA0,56ED197D) RecvMessage(005): 00 26 E7 00 00 | Layer 8(008F0C68,56ED1A2D) RecvMessage(005): 00 26 **3D** 00 00
Layer 7(0068F104,56ED197D) OpenGroupSocket | Layer 7(0090114C,56ED1A2D) OpenGroupSocket
Layer 4(0067EAF8,56ED197D) OpenGroupSocket RW | Layer 4(008F0A38,56ED1A2D) OpenGroupSocket RW
Layer 3(0063BC60,56ED197D) registerLayer2 0067EAF8 | Layer 7(0090114C,56ED1A2D) **OpenGroupSocket init bad**
Layer 3(0063BC60,56ED197D) registerLayer2 0067EAF8 = 1 |
Layer 7(0068F104,56ED197D) OpenGroupSocket complete |
Layer 8(0067ECA0,56ED197D) SendMessage(002): 00 26 | Layer 8(008F0C68,56ED1A2D) SendMessage(002): 00 26
Layer 0(0065C758,56ED1980) Recv(017): 06 10 05 30 00 11 29 00 B8 D0 11 47 2B 02 01 00 00 | Layer 0(008CE780,56ED1A2E) Recv(017): 06 10 05 30 00 11 29 00 B8 D0 11 47 29 02 01 00 00
Layer 1(0065C758,56ED1980) Recv(011): 29 00 B8 D0 11 47 2B 02 01 00 00 | Layer 1(008CE780,56ED1A2E) Recv(011): 29 00 B8 D0 11 47 29 02 01 00 00
Layer 2(0065C6F0,56ED1980) Recv L_Data normal from 1.1.71 to 5/3/2 hops: 05 T_DATA_XXX_REQ A_GroupValue_Read | Layer 2(008CE710,56ED1A2E) Recv L_Data normal from 1.1.71 to 5/1/2 hops: 05 T_DATA_XXX_REQ A_GroupValue_Read
Layer 3(0063BC60,56ED1980) Enqueue L_Data normal from 1.1.71 to 5/3/2 hops: 05 T_DATA_XXX_REQ A_GroupValue_Read | Layer 3(008ADC70,56ED1A2E) Enqueue L_Data normal from 1.1.71 to 5/1/2 hops: 05 T_DATA_XXX_REQ A_GroupValue_Read
Layer 3(0063BC60,56ED1980) RecvData L_Data normal from 1.1.71 to 5/3/2 hops: 04 T_DATA_XXX_REQ A_GroupValue_Read | Layer 3(008ADC70,56ED1A2E) RecvData L_Data normal from 1.1.71 to 5/1/2 hops: 04 T_DATA_XXX_REQ A_GroupValue_Read
Layer 4(0067EAF8,56ED1980) Recv GroupSocket(002): 00 00 | 
Layer 7(0068F104,56ED1980) Recv(002): 00 00 | 
Layer 8(0067ECA0,56ED1980) SendMessage(008): 00 27 11 47 2B 02 00 00 |
Layer 0(0065C758,56ED1980) Recv(017): 06 10 05 30 00 11 29 00 BC C0 11 45 2B 02 01 00 41 | Layer 0(008CE780,56ED1A2E) Recv(017): 06 10 05 30 00 11 29 00 BC C0 11 42 29 02 01 00 41
Layer 1(0065C758,56ED1980) Recv(011): 29 00 BC C0 11 45 2B 02 01 00 41 | Layer 1(008CE780,56ED1A2E) Recv(011): 29 00 BC C0 11 42 29 02 01 00 41
Layer 2(0065C6F0,56ED1980) Recv L_Data low from 1.1.69 to 5/3/2 hops: 04 T_DATA_XXX_REQ A_GroupValue_Response (small) 01 | Layer 2(008CE710,56ED1A2E) Recv L_Data low from 1.1.66 to 5/1/2 hops: 04 T_DATA_XXX_REQ A_GroupValue_Response (small) 01
Layer 3(0063BC60,56ED1980) Enqueue L_Data low from 1.1.69 to 5/3/2 hops: 04 T_DATA_XXX_REQ A_GroupValue_Response (small) 01 | Layer 3(008ADC70,56ED1A2E) Enqueue L_Data low from 1.1.66 to 5/1/2 hops: 04 T_DATA_XXX_REQ A_GroupValue_Response (small) 01
Layer 3(0063BC60,56ED1980) RecvData L_Data low from 1.1.69 to 5/3/2 hops: 03 T_DATA_XXX_REQ A_GroupValue_Response (small) 01 | Layer 3(008ADC70,56ED1A2E) RecvData L_Data low from 1.1.66 to 5/1/2 hops: 03 T_DATA_XXX_REQ A_GroupValue_Response (small) 01
Layer 4(0067EAF8,56ED1980) Recv GroupSocket(002): 00 41 | 
Layer 7(0068F104,56ED1980) Recv(002): 00 41 | 
Layer 8(0067ECA0,56ED1980) SendMessage(008): 00 27 11 45 2B 02 00 41 | 
**here after I killed cut the knxd** | **here after I killed cut the knxd**

Of course, as I had to install the knxd Branche sequentially, these are not the same telegrams, but comparable. I marked the first differences in **bold**

The first I noted was the difference in the command message. 0x26 is decimal 38, so it is the same message type I mentioned in the first post. While my client (node_eibd) sent `00 0x26 00 00 00`, the knxtool groupsocketlisten seems to send to different sequences. Nevertheless, with conn_sep, both fail (`00 0x26 00 00 00` and `00 0x26 0x3D 00 00`).

**Comment by snowdd1** [comment]
Ok, following your explanation further:

master | conn_sep
----------|--------------
[connection#158](https://github.com/knxd/knxd/blob/master/src/libserver/connection.cpp#L158) |  [connection#135](https://github.com/knxd/knxd/blob/conn_sep/src/libserver/connection.cpp#L135)
`c = new GroupSocket (layer3, t, con->buf[4] != 0 ? 1 : 0); if (!c->init ())` | `c = GroupSocketPtr(new GroupSocket (con->l3, con->t, con->buf[4] != 0 ? 1 : 0)); if (!c->init ())`
this is ok | this fails!

Looks to me as if the GroupSocket got a new constructor - which I think after looking at the branches is not the case (layer4.cpp, master#602 vs conn_sep#606)

I do not understand enough of the code to grasp the wrapping in `GroupSocketPtr()` is meant to be, and eclipse just hints me `typedef std::shared_ptr<GroupSocket> GroupSocketPtr;` which doesn't mean anything to me.

**Comment by snowdd1** [comment]
>The first I noted was the difference in the command message. 0x26 is decimal 38, so it is the same message type I mentioned in the first post. While my client (node_eibd) sent  00 0x26 00 00 00 , the knxtool groupsocketlisten seems to send to different sequences. Nevertheless, with conn_sep, both fail ( 00 0x26 00 00 00  and  00 0x26 0x3D 00 00 ).


I made several attempts, and the 3rd number in the message changes with every call, so it does not seem important to the failure.

Also using the new -E parameter in knxd does not change anything. I thought that fail in [addGroupAddress(0)](https://github.com/knxd/knxd/blob/conn_sep/src/libserver/layer4.cpp#L613) might be caused by not giving client physical addresses but that is not the case. It seems to fail for another reason.

Following the definition chain, I stumbled across [layer2.cpp#56](https://github.com/knxd/knxd/blob/conn_sep/src/libserver/layer2.cpp#L56) which checks whether group address is not yet used - and to my humble conclusion it seams to be taken in conn_sep and free in master. *Who or what is using 0/0/0* ?

**Comment by smurfix** [comment]
I think I found it. I'll test and send a patch later today.
-- 
-- Matthias Urlichs

**Comment by snowdd1** [comment]
I hope I did not confuse you, I was thinking of layer2.cpp#L82 (Layer2::addGroupAddress) not 56 (Layer2::addAddress), the latter is supposed to fail at 0.

**Comment by snowdd1** [comment]
If you already found it, the better. I came to the conclusion that addGroupAddress(0) is called twice, once in GroupSocket::GroupSocket() (the constructor if I am right), and once in Layer4common::init()  via layer2_is_bus(), which basically does the same.

I am mighty proud to have found anything at all :smile:

**Comment by smurfix** [comment]
On 19.03.2016 15:52, Raoul wrote:
>
> I am mighty proud to have found anything at all 
>
Good for you. ;-)
Yes, that was the culprit. I removed that duplicate call
and pushed change 1fae3f6 to github.
Please test.

-- 
-- Matthias Urlichs

**Comment by snowdd1** [comment]
Good news: groupsocketlisten immediately worked again with conn_sep. 
Not-so-good news I have trouble writing values to the bus using the multicast server, please see #134; which is not connected to this issue and not limited to conn_sep - but my fault, I assume.

**Comment by snowdd1** [comment]
The issue reported is solved, I close this. 
Both `knxtool groupsocketlisten ip:` and `knxtool groupsocketlisten local:` are working in the `conn_sep` branch again.
