### ISSUE TITLE
Writing to knxd multicast server using knxtool or a second knxd

### ISSUE THREAD

**Issue by snowdd1** [knxd/knxd#134]
During my tests for #133 I had trouble to send telegrams from one knxd to another and from there to the bus wire.

My setup:
Hardware: 2 Raspberries (Raspbian Lite Feb 2016), 1 Pigator Single KNX

Production knxd server w/ pigator (i.e. hardware interface): 
- master branch (https://github.com/knxd/knxd/commit/c8a4bb3b042de1fd692a93cdb7a307546f2be359) 
- knxd.conf: **KNXD_OPTS="--trace=1023 --eibaddr=0.0.3 --Name=KNXD2 --Routing --Discovery --Server --layer2=tpuarts://dev/ttyKNX1"**
- A GIRA homeserver is also using this multicast server
- Clients using knxd ip: address can successfully write and listen to the bus
- trace=1023 was inserted for this test

Dev/Test knxd server
- knxd.conf: **KNXD_OPTS="-u /tmp/eib -b ip:"**

What I was doing (on dev server):
I was using `knxtool groupsocketlisten ip:localhost` to see telegrams from the bus via production knxd multicast to dev knxd. This was working (except the cases in #133 which seems to be solved).
But when I tried `knxtool groupswrite ip:localhost 1/3/5 1` nothing happened.

Next, I stopped the dev knxd `sudo systemctl stop knxd` to enable tracing, and restarted the local dev knxd with `sudo -u knxd knxd -t 1023 -f 9 -e 1.1.199 -i 4711 -b ip:`

Now I got a trace of what happened when I issued a `knxtool groupswrite ip:localhost:4711 1/3/5 1` in a second terminal:

```
Layer 8(009421E0,56ED7794) New Connection
Layer 8(00931BB0,56ED7794) ClientConnection Init
Layer 8(00931BB0,56ED7794) RecvMessage(005): 00 22 0B 05 FF
Layer 7(0098505C,56ED7794) OpenGroup
Layer 4(00931BF8,56ED7794) OpenGroup 1/3/5 WO
Layer 3(00931C60,56ED7794) registerLayer2 00931BF8
Layer 3(00931C60,56ED7794) registerLayer2 00931BF8 = 1
Layer 7(0098505C,56ED7794) OpenGroup complete
Layer 8(00931BB0,56ED7794) SendMessage(002): 00 22
Layer 8(00931BB0,56ED7794) RecvMessage(004): 00 25 00 81
Layer 7(0098505C,56ED7794) Send(002): 00 81
Layer 4(00931BF8,56ED7794) Send Group T_DATA_XXX_REQ A_GroupValue_Write (small) 01
Layer 3(00931C60,56ED7794) Enqueue L_Data low from 0.0.0 to 1/3/5 hops: 07 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
Layer 3(00931C60,56ED7794) RecvData L_Data low from 0.0.0 to 1/3/5 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
Layer 7(0098505C,56ED7794) CloseGroup
Layer 4(00931BF8,56ED7794) CloseGroup
Layer 3(00931C60,56ED7794) deregisterLayer2 00931BF8 = 1
Layer 8(00931BB0,56ED7794) ClientConnection closed
```

On the production server **nothing** of this telegram was seen in the log (/var/log/daemon.log), (though every other telegram was logged) and the actuator consequently didn't switch.

Puzzled, I tried writing directly to my multicast server: `knxtool groupswrite ip: 1/3/5 1` - again, nothing happened at the production server. I tried `conn_sep` branch on the dev server (happily noting #133 is solved!), but to no avail for the current issue: neither knxd nor knxtool actually can **write** to the multicast server, although listening works fine.

I tried to contact the local listener of my production knxd with `knxtool groupswrite ip:knxd2-raspberry 1/3/5 1` and the light came immediately on, and the log showing the incoming message.

How did I wreck it this time?
Regards
Raoul

**Comment by smurfix** [comment]
On 19.03.2016 17:31, Raoul wrote:
> How did I wreck it this time?
I don't know yet, but I'll run a few tests.

-- 
-- Matthias Urlichs

**Comment by snowdd1** [comment]
I used tcpdump and tshark to watch the dev raspberry's NIC, and it does not send to the multicast address when doing a `knxtool groupswrite ip: 1/3/5 1`

In the dump, I could see the gira HomeServer sending UDP packets to the prod knxd, I could see the production knxd raspberry answer to the multicast address, I could see all my SSH packets in and out, but no packets from dev raspberry to multicast address.

**Comment by snowdd1** [comment]
FYI: This issue seems to be reported by other folks, e.g. here: https://knx-user-forum.de/forum/öffentlicher-bereich/knx-eib-forum/36352-apple-homekit-schnittstelle-zur-heimautomation?p=919215#post919215

I knew I had seen it before.

**Comment by smurfix** [comment]
On 19.03.2016 21:35, Raoul wrote:
>
> FYI: This issue seems to be reported by other folks, e.g. here:
> https://knx-user-forum.de/forum/öffentlicher-bereich/knx-eib-forum/36352-apple-homekit-schnittstelle-zur-heimautomation?p=919215#post919215
> <https://knx-user-forum.de/forum/%C3%B6ffentlicher-bereich/knx-eib-forum/36352-apple-homekit-schnittstelle-zur-heimautomation?p=919215#post919215>
>
> I knew I had seen it before.
>
I think I know where that is coming from. Will fix tomorrow. (Hopefully.)

However, the problem that's described in the knx-user-forum.de thread
has a different cause.
(They don't use the conn_sep branch.)

-- 
-- Matthias Urlichs

**Comment by snowdd1** [comment]
I tried both branches with the same result.

**Comment by snowdd1** [comment]
Though the root cause might be different, of course.

**Comment by ds82** [comment]
Any update on this? I'm having the same issue .. 
Is there an older hash I could build until this is fixed?

**Comment by smurfix** [comment]
There have been some fixes WRT multicast group membership. Please test the current version.

**Comment by smurfix** [comment]
Closing due to lack of feedback. Please re-open when appropriate.

**Comment by snowdd1** [comment]
Was not able to test until now. Which versions should I take for testing - I need to update my productive system (to latest STABLE I guess) and the dev system (to latest MASTER)?
I hope I can do that on Sunday afternoon.

**Comment by snowdd1** [comment]
Can confirm that it works now if the second knxd (on hardware without physical knx interface) is version 0.12 (stable branch as of today), even if the multicast server (that one with the physical interface) is still on 0.10.x  
Consider that solved.
Thanks for all the work you do!
