### ISSUE TITLE
Similar issue like #102

### ISSUE THREAD

**Issue by stijnvdv86** [knxd/knxd#136]
Hello,

I was upgrading from eibd to knxd because my tunneling in ETS5 is not working properly. It seems like I have the same issue from post #102 

Groupmonitor and downloading applications in ETS5 works fine for me but when I try the busmonitor I get invalid frames.

This is only for the tunneling mode! The router mode works without any problem.
This problem is the same then when I was using eibd.

Is there something that I can try to fix this?
I'm using a USB backend device from Hager. And my config file looks like this:
KNXD_OPTS="-e 1.1.128 -t1023 -f9 -DTRS -b usb:1:4:1:0:0"

In ETS5 I can see the Tunnel and Router through discovery:

![capture](https://cloud.githubusercontent.com/assets/18006111/13952251/ae71492a-f035-11e5-9308-6a65fd1c1573.PNG)

When using the tunnel and the busmonitor I get this output 

![capture2](https://cloud.githubusercontent.com/assets/18006111/13952267/c40051d2-f035-11e5-91b2-af3407dd3deb.PNG)

Regards,
Stijn

**Comment by elupus** [comment]
Here is a patch that seem to fix it for me. The mentioned fix above did not fix the issue. It's incomplete since it changed the length of the "Additional Information" field without adjusting the total length of the field.

I'm not sure what type of data should be sent in that field. But keeping it empty seem to work fine for TP at least.

```
From 79c84b28fd0d5a12bca77004e94351e6295b6f8e Mon Sep 17 00:00:00 2001
From: Joakim Plate <joakim.plate@gmail.com>
Date: Sun, 27 Nov 2016 02:20:40 +0000
Subject: [PATCH] Drop additional information field which ETS5 doesn't accept

---
 src/libserver/emi.cpp | 10 +++-------
 1 file changed, 3 insertions(+), 7 deletions(-)

diff --git a/src/libserver/emi.cpp b/src/libserver/emi.cpp
index 9bb540d..e9da456 100644
--- a/src/libserver/emi.cpp
+++ b/src/libserver/emi.cpp
@@ -132,14 +132,10 @@ CArray
 Busmonitor_to_CEMI (uchar code, const L_Busmonitor_PDU & p, int no)
 {
   CArray pdu;
-  pdu.resize (p.pdu () + 6);
+  pdu.resize (p.pdu () + 2);
   pdu[0] = code;
-  pdu[1] = 4;
-  pdu[2] = 3;
-  pdu[3] = 1;
-  pdu[4] = 1;
-  pdu[5] = no & 0x7;
-  pdu.setpart (p.pdu, 6);
+  pdu[1] = 0;
+  pdu.setpart (p.pdu, 2);
   return pdu;
 }
 
-- 
2.7.4


```

**Comment by smurfix** [comment]
Pull request, please?
