### ISSUE TITLE
ETS3 - "Authentication failed."

### ISSUE THREAD

**Issue by chester4444** [knxd/knxd#138]
Hi

i am using a raspberry with a TPUART device for home automation.
i tried to switch from eibd to knxd. (just for fun, eibd is working well)

ETS3, knxd (version: knxd 0.10.0) results in an error
when programming a certain knx-device from Berker for shutters.

Programming all my other devices (switches) is working well with ETS3/knxd.  
Programming the Berker device with the "old" eibd is working without any problems.

i can post detailed logs from knxd, if needed (-t1023 or -t???)

Is it a problem of knx, ETS3, ...?

ETS3 is saying:
Ein interner Fehler ist aufgetreten (Details: Authentication failed.)

EDI: KNXnet/IP
Params: Name='RASP2KNXD';IpAddr='10.0.0.110';Port='3671';NAT='off'
Last messages (cEMI):
  09:27:44.656 S L_DATA.req (OPR/) 80 60 0000 1109 00 80
  09:27:44.656 R L_DATA.con (OPR/) B0 50 0000 1109 00 80
  09:27:44.656 S L_DATA.req (NDT-0/DeviceDescriptor_Read) 80 60 0000 1109 01 43 00
  09:27:44.671 R L_DATA.con (NDT-0/DeviceDescriptor_Read) B0 50 0000 1109 01 43 00
  09:27:44.734 R L_DATA.ind (ACK-0/) B0 50 1109 0000 00 C2
  09:27:44.781 R L_DATA.ind (NDT-0/DeviceDescriptor_Response) B0 50 1109 0000 03 43 40 00 21
  09:27:44.781 S L_DATA.req (ACK-0/) 80 60 0000 1109 00 C2
  09:27:44.781 R L_DATA.con (ACK-0/) B0 50 0000 1109 00 C2
  09:27:44.781 S L_DATA.req (NDT-1/Authorize_Request) 80 60 0000 1109 06 47 D1 00 FF FF FF FF
  09:27:44.781 R L_DATA.con (NDT-1/Authorize_Request) B0 50 0000 1109 06 47 D1 00 FF FF FF FF
  09:27:44.906 R L_DATA.ind (CLR/) B0 50 1109 0000 00 81
  09:27:44.937 R L_DATA.ind (CLR/) B0 50 1109 0000 00 81
  09:28:02.875 S L_DATA.req (OPR/) 80 60 0000 1109 00 80
  09:28:02.875 R L_DATA.con (OPR/) B0 50 0000 1109 00 80
  09:28:02.875 S L_DATA.req (NDT-0/DeviceDescriptor_Read) 80 60 0000 1109 01 43 00
  09:28:02.875 R L_DATA.con (NDT-0/DeviceDescriptor_Read) B0 50 0000 1109 01 43 00
  09:28:02.953 R L_DATA.ind (ACK-0/) B0 50 1109 0000 00 C2
  09:28:02.984 R L_DATA.ind (NDT-0/DeviceDescriptor_Response) B0 50 1109 0000 03 43 40 00 21
  09:28:02.984 S L_DATA.req (ACK-0/) 80 60 0000 1109 00 C2
  09:28:02.984 R L_DATA.con (ACK-0/) B0 50 0000 1109 00 C2
  09:28:02.984 S L_DATA.req (NDT-1/Authorize_Request) 80 60 0000 1109 06 47 D1 00 FF FF FF FF
  09:28:02.984 R L_DATA.con (NDT-1/Authorize_Request) B0 50 0000 1109 06 47 D1 00 FF FF FF FF
  09:28:03.109 R L_DATA.ind (CLR/) B0 50 1109 0000 00 81

**Comment by smurfix** [comment]
Looks like an ETS-3 problem. Did you try with ETS4 or ETS5?

**Comment by smurfix** [comment]
Closing due to lack of feedback. Please re-open when appropriate.
