### ISSUE TITLE
Repository for Ubuntu apt-get installation

### ISSUE THREAD

**Issue by Schaussi** [knxd/knxd#140]
Hi,
I found a [Launchpad Repository](https://launchpad.net/~timo-wingender/+archive/ubuntu/knxd-daily/?field.series_filter=trusty) and one [here](http://www.cometvisu.org/wiki/CometVisu/Installation/Backend/de), but both do not seem to be up to date.
Is there maybe any other source for aptitude, or is every user forced to compile it?

E.g. problem with the Launchpad version: apt-get searches for libusb-1.0, even if libusb-1.0.4 is installed.

Thank you

**Comment by smurfix** [comment]
This will have to wait for the libev branch to be production ready, at which time knxd can be added to Debian, which will resolve this problem.
