### ISSUE TITLE
knxd with Selfbus FT1.2 Raspi PCB?

### ISSUE THREAD

**Issue by sallos** [knxd/knxd#142]
Hi,

it is possible to use knxd with this adapter:
http://selfbus.myxwiki.org/xwiki/bin/view/Selfbus/FT12_Raspi

Lars

**Comment by smurfix** [comment]
On 04.06.2016 12:51, sallos wrote:
>
> Hi,
>
> it is possible to use knxd with this adapter:
> http://selfbus.myxwiki.org/xwiki/bin/view/Selfbus/FT12_Raspi
>
Of course. knxd is just an improved eibd. There are no known regressions.

-- 
-- Matthias Urlichs

**Comment by sallos** [comment]
Thanks.

there is a config example?


I have also a Startup Problem:
[....] Starting knxd (via systemctl): knxd.serviceJob for knxd.service failed. See 'systemctl status knxd.service' and 'journalctl -xn' for details.
 failed!

**Comment by thelsing** [comment]
KNXD_OPTS="-e 0.0.254 -c -D -T -S -b ft12:/dev/ttyAMA0" in /etc/knxd.conf works for me. Don't forget to remove the console from ttyAMA0 in /boot/cmdline.txt
