### ISSUE TITLE
knxd not working

### ISSUE THREAD

**Issue by mucheinz** [knxd/knxd#148]
Hello,
I've downloaded and installed knxd on my pi2, but it seems not to work, have an ABB IP interface.

This is the information I get:

pi@pi2:/ $ knxtool groupswrite ip:192.168.178.200 1/1/7 0
Open failed: Connection refused

lsof shows: 

COMMAND   PID USER   FD      TYPE DEVICE SIZE/OFF NODE NAME
knxd    24179 knxd  cwd   unknown                      /proc/24179/cwd (readlink: Permission denied)
knxd    24179 knxd  rtd   unknown                      /proc/24179/root (readlink: Permission denied)
knxd    24179 knxd  txt   unknown                      /proc/24179/exe (readlink: Permission denied)
knxd    24179 knxd NOFD                                /proc/24179/fd (opendir: Permission denied)

**Comment by bmxp** [comment]
You did not write which KNXD_OPTS you used ... Could it be that your issue is about the same problem that I already described in https://github.com/knxd/knxd/issues/147 ?

**Comment by mucheinz** [comment]
Hello, I tried all of the following:
KNXD_OPTS="-u /tmp/eib -t 2023 -c -b ipt:192.168.178.200"
KNXD_OPTS="-u /tmp/eib -b ipt:192.168.178.200"

**Comment by mucheinz** [comment]
Hello bmxp,
no it is something different.  modifying KNXD_OPTS with '-i' always results in start failures, see below:

Jul 21 16:51:45 pi2 knxd[25628]: Layer 4(0046A1E0,57910BB1) GroupCacheEnable
Jul 21 16:51:45 pi2 knxd[25628]: Layer 8(0046A450,57910BB1) OpenInetSocket 6720
Jul 21 16:51:45 pi2 knxd[25628]: Layer 0(0046A450,57910BB1) OpenInetSocket 6720: bind: Address already in use
Jul 21 16:51:45 pi2 knxd[25628]: initialisation of the knxd inet protocol failed: Address already in use
Jul 21 16:51:45 pi2 systemd[1]: knxd.service: main process exited, code=exited, status=1/FAILURE
Jul 21 16:51:45 pi2 systemd[1]: Failed to start KNX Daemon.
Jul 21 16:51:45 pi2 systemd[1]: Unit knxd.service entered failed state.

using the KNX_OPTS from #147 without -i 
KNXD_OPTS="-t 1023 -c  -b ipt:192.168.178.200"
still results in the same 
Open failed: Connection refused

Therefore #148 is different from #147

**Comment by smurfix** [comment]
Not a bug.
"knxd -i" opens an internet socket on the local host, using knxd's protocol. You use "knxtool ip:this_host" to talk to it.
"knxd -b ipt:that_host" opens a KNX link to a ("commercial") gateway, using the "official" KNX gateway protocol.

These are different protocols. You can't use "knxtool ip:that_host".

**Comment by smurfix** [comment]
Also, with systemd, knxd.socket does the same thing as the -i option (and passes that through to knxd). You can't open a port twice. Either lose the -i or disable knxd.socket.

**Comment by mucheinz** [comment]
Hello smurfix,
whilst I have now understood the difference  between  "knxtool ip:this_host" and "knxd -b ipt:that_host" I still have not seen an example configuration for the latter configuration (connecting to a commercial knx interface) using the tunneling protocol.
Can you point me to some documentation?

**Comment by Makki1** [comment]
knxd ipt:<ip-of-yourknxnetipinterface> should be enough documentation?
ip: is KNXnet/IP "Routing" (called multicastin IP-world), :ipt ist KNXnet/IP Tunneling (recommended, look how many parallel connections your "commercial interface" supports! knxd is just unlimitied on that)

**Comment by mucheinz** [comment]
Hello Makki1,
what I know:
- I need the tunneling protocol (ipt:)
- my commercial interface (192.168.178.200) supports 5 parallel connections

what I don't know:
I haven't seen a sample configuration for knxd using ipt: to connect via a (any) commercial gateway.
I assume it is a configuration thing, 
knxtool groupswrite ip:192.168.178.200 1/1/7 0
Open failed: **Connection refused**

**Comment by smurfix** [comment]
knxtool does not talk to your commercial interface. knxtool talks to knxd.
You need to use the address of the host knxd is running on.

You don't need a "sample configuration" for knxd. You simply use "-b ipt:192.168.178.200".

**Comment by mucheinz** [comment]
thx a lot for this clarification which I have not realized so far.
I'm now fine and can communicate via knxtool now. Hooray!
