### ISSUE TITLE
MacBook + KNXD

### ISSUE THREAD

**Issue by coliflower** [knxd/knxd#149]
Hi all,

does knxd working on a MacBookPro, please ?

Thanks a lot !

**Comment by bdgeyter** [comment]
I'm also trying to compile knxd on Mac. Any luck @coliflower? Tips?

I'm mainly having issues with `systemd`, which I think should be replaced by `launchd` somehow?

**Comment by RichiH** [comment]
You don't need systemd, you can start by hand.

Richard

Sent by mobile; excuse my brevity.

**Comment by bdgeyter** [comment]
@RichiH running `./configure --disable-systemd` is still giving me the following error. How can I bypass `systemd`

```
checking for GNU Pth... version 2.0.8, installed under /usr/local
checking systemd/sd-daemon.h usability... no
checking systemd/sd-daemon.h presence... no
checking for systemd/sd-daemon.h... no
./configure: line 17523: syntax error near unexpected token `SYSTEMD,'
./configure: line 17523: `	PKG_CHECK_MODULES(SYSTEMD, libsystemd-daemon)'
```

**Comment by smurfix** [comment]
On 18.10.2016 17:00, Bram De Geyter wrote:
> |./configure: line 17523: ` PKG_CHECK_MODULES(SYSTEMD, libsystemd-daemon)'|
If |PKG_CHECK_MODULES| appears in configure, then you have problems with
the autoconf tools. Most likely you did not run "aclocal" correctly: it
didn't find the pkg-config macros. Did you install them?

-- 
-- Matthias Urlichs

**Comment by bdgeyter** [comment]
@smurfix thanks! managed to install `pgk-config`, and got through `./configure`

I'm now running into some trouble during the actual build...

```
g++ -DHAVE_CONFIG_H -I. -I../..  -I../../src/include -I../../src/common -I/usr/local/include   -g -O2 -MT layer7.o -MD -MP -MF .deps/layer7.Tpo -c -o layer7.o layer7.cpp
layer7.cpp:40:10: error: no viable overloaded '='
      l4 = 0;
      ~~ ^ ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3950:17: note: 
      candidate function not viable: no known conversion from 'int' to 'const std::__1::shared_ptr<T_Broadcast>'
      for 1st argument
    shared_ptr& operator=(const shared_ptr& __r) _NOEXCEPT;
```

and a few similar errors... I have little experience with C++, so it's hard for me to debug. Any ideas?

**Comment by smurfix** [comment]
On 20.10.2016 20:39, Bram De Geyter wrote:
> I have little experience with C++, so it's hard for me to debug. Any
> ideas?

Umm … what? Zero is supposed to be a valid null pointer.

Try to replace that with "nullptr".

-- 
-- Matthias Urlichs

**Comment by smurfix** [comment]
any progress?

**Comment by bdgeyter** [comment]
hi @smurfix , thanks for following up! I've been busy lately and haven't found the time to tinker with it further. I'll let you know and update you when I get a chance!

**Comment by migabc** [comment]
Hi,

Can some one please provide a step by step procedure for installing the knxd on a Mac
P.S. I already installed homebridge and homebridge-knx.

Thanks!

**Comment by smurfix** [comment]
Closing due to lack of feedback. Please re-open when appropriate.
