### ISSUE TITLE
every command send twice

### ISSUE THREAD

**Issue by gjniewenhuijse** [knxd/knxd#150]
Every command is send with knxd is received double/twice on the bus.

My config: DAEMON_ARGS="-e 1.1.200 -u -i -b ipt:192.168.11.3"
Command:  sudo knxtool groupwrite ip:127.0.0.1 10/1/100 1

What is wrong with my settings/config that every command is send twice?

**Comment by smurfix** [comment]
Which version do you use? Please turn on tracing (-t 1023) and post the log here.

**Comment by smurfix** [comment]
Fixed in 0.12.
