### ISSUE TITLE
Wrong (old) output vor knxd -V ...

### ISSUE THREAD

**Issue by LichtiMC** [knxd/knxd#151]
I'm not sure if it's a problem with my pc only, but if I execute "knxd -V" I get: 
knxd 0.10.0

Shouldn't it print knxd 0.10.13-3?

Thank you btw. for the software! :+1:

**Comment by itarch** [comment]
You are not alone...
I just performed fresh installation from github (0.11.9-1) and end up with "/usr/bin/knxd -V":
knxd 0.10.0

***
Rasp Pi 3, Debian Jessie, TUL-TPUART ...

**Comment by tru7** [comment]
should be fixed with commit https://github.com/knxd/knxd/commit/61ff9070f640712e195c499c6693c32ab440a1bb
