### ISSUE TITLE
Mention this project in KNX Scientific Conference

### ISSUE THREAD

**Issue by jcbastosportela** [knxd/knxd#154]
Hi all,
first of all, sorry for opened this topic as an "issue", but I couldn't find a more effective way of reaching the main involved members of this project at once.

In 27th of October I'm going to be in KNX Scientific conference in Dortmund as one of the presenters (check [here).](http://scientificpartner2016.eventzilla.net/web/event?eventid=2138877435) I'm working on a paper that suggests improvements to the new KNX webServer/Gateway defined by KNX Association. I don't know if you are aware of it or not, but in short they use a RPi that hosts a webservice providing RESTfull API for the Internet side, for the KNX side they use Calimero that connects to an KNXnet/IP router.

The topic of my paper is how to improve this topology. My thesis is that RESTfull shall not be the only interface: there should be a full duplex protocol since KNX is doesn't fit well in a client started communication topology. The second part of my thesis is that KNXnet/IP is redundant and could be erased by using TPUART, Elmos or alike... It's in this second part this project came across.

In fact, in my company I'd developed a TPUART driver, and it was from this that I was suggesting this improvement. But recently I found this project that is much wider than what I've developed.

Now that you are aware of my background and intentions, my question is: can I reference your project in my paper and during the conference? If it is okay, is there a special way you would like me to refer you or something you would like me to highlight about this project?

Thank you so much. Again sorry about opening it in "issues".

**Comment by RichiH** [comment]
For this kind of discussion, https://groups.google.com/forum/#!forum/knxd is probably the best place, but it's not very active. I doubt anyone will mind if you point people to this project, ideally just point them to GitHub and the Google group.

As to your bi-directional communication issue, whatever should receive events could simply offer its own RESTful API endpoint.

**Comment by ekarak** [comment]
You should also take a look at https://bitbucket.org/ekarak/knx.js , a Javascript library for KNXnet/IP , which opens an exciting new interface to KNX, as it opens it up to the vast ecosystem of Node.js applications. IMHO, restful APIs are *not a good fit* for realtime control protocols as it gets stuff unnecessary complex (e.g. you need to webhooks to update the client asynchronously). Instead, just leverage existing tools like meteor.js to get seamless status updates between the RPi (which talks to KNX) and your client, or even better: Use http://electron.atom.io/ to have your HTML5 app talk KNX natively!

**Comment by smurfix** [comment]
On 08.10.2016 10:17, jcbastosportela wrote:
>
> In 27th of October I'm going to be in KNX Scientific conference in
> Dortmund. I'm working on a paper that suggests improvements to the new
> KNX webServer/Gateway defined by KNX Association. I don't know if you
> are aware of it or not, but in short they use a RPi that hosts a
> webservice providing RESTfull API for the Internet side, for the KNX
> side they use Calimero that connects to an KNXnet/IP router.
>
Owch.

When knx was conceived, the hype was all about the OSI model, so KNX has
those nice seven layers (some of them being empty). Now the hype is all
about client/server and REST. The problem is that web clients can't
reasonably be expected to talk anything else …

I suspect that the next thing they come up with is a Websocket-based API
for getting notifications from the bus. (Asterisk does the same thing
with telephony.)

Also: you can base your infrastructure on Java. No problem. You can also
base it on a RPi. No problem either.
But to base your infrastructure on Java running on RPi is foolish.

As an example, OpenHAB runs on RPi, but it limps along, eats a lot of
memory, and takes half an eternity to start up. You want your IoT
devices to restart in a couple of seconds, not minutes.

So, if this is intended as a frontend for visualization, well, why not.
But m2m communication has different requirements.

> The topic of my paper is how to improve this topology. My thesis is
> that RESTfull shall not be the only interface: there should be a full
> duplex protocol since KNX is doesn't fit well in a client started
> communication topology.
>
Like I said: add a websocket. :-P
>
> The second part of my thesis is that KNXnet/IP is redundant and could
> be erased by using TPUART, Elmos or alike... It's in this second part
> this project came across.
>
What, and tell the vendors that their nice IP gateways are no longer
needed? the horror …

NB: what do you mean, KNXnet/IP is redundant? Quite the opposite is
true: the basic idea is just to place the KNXnet/IP router on the same
computer as the web service.
>
> In fact, in my company I'd developed a TPUART driver, and it was from
> this that I was suggesting this improvement. But recently I found this
> project that is much wider than what I've developed.
>
Thanks (on behalf of all its authors).
>
> Now that you are aware of my background and intentions, my question
> is: can I reference your project in my paper and during the
> conference? If it is okay, is there a special way you would like me to
> refer you or something you would like me to highlight about this project?
>
Well, of course. What I'd like to highlight is the fact that the project
needs collaborators, there's a ton of things on the TODO list.

There's also a main architectural strength, which is that at the heart
of knxd there's a KNX router with multiple interfaces, physcial and
otherwise. In effect, knxd blurs the distinction between clients and
hardware buses, because at the end of the day both are things with a
physical address (dynamically assigned by the server, if necessary) that
send and receive datagrams.
>
> Thank you so much. Again sorry about opening it in "issues".
>
Not a problem. It _is_ an "issue" to be addressed, if only getting
people to notice that knxd even exists.


-- 
-- Matthias Urlichs

**Comment by RichiH** [comment]
> When knx was conceived, the hype was all about the OSI model, so KNX has
> those nice seven layers (some of them being empty).

Interesting; I didn't know that. I _did_ think that this was all a bit
cumbersome, but with more forethought than usual and KNX itself really
resilient.


> Now the hype is all
> about client/server and REST. The problem is that web clients can't
> reasonably be expected to talk anything else …

That would be Protobuf ;)

Considering who's pushing that and the level of usage it gets, that
one might actually stick around.

**Comment by smurfix** [comment]
On 08.10.2016 10:54, Richard Hartmann wrote:
>
> As to your bi-directional communication issue, whatever should receive
> events could simply offer its own RESTful API endpoint.
>
How would a client "offer an endpoint"? It's a client. Servers offer
endpoints. Clients are not servers.

In any case, KNX doesn't even have RESTish endpoints; it has group
addresses and messages. A REST server's job is to construct an internal
model of each device (or rather, each function group within that device)
which reflects its state reasonably correctly, and then present that to
its clients.

To facilitate that, the first order of business would probably be some
code that digests .knxproj files and emits something far more
readable/usable. :-/

-- 
-- Matthias Urlichs

**Comment by RichiH** [comment]
On Sat, Oct 8, 2016 at 1:48 PM, Matthias Urlichs <notifications@github.com>
wrote:

> How would a client "offer an endpoint"? It's a client. Servers offer
> endpoints. Clients are not servers.
>

That was the point; if it's RESTful, you basically need a server on either
side.

I am not saying it's useful in this case, it was more a technical point.


Richard

**Comment by jcbastosportela** [comment]
Hi!
First of all, sorry for late answer, but the country I currently live in decided to block github for a couple of days.

@smurfix 

> Also: you can base your infrastructure on Java. No problem. You can also base it on a RPi. No problem either. But to base your infrastructure on Java running on RPi is foolish.

It isn't my approach! It's KNX Ass. approach! I'll be suggesting improvements to it. In my implementations in embedded platforms I mostly always try to develop in C or C++, always trying to use "standard" libs in order to ease cross compiling. I've tried openhab, but they are doing other thing different from what is being done here. **This here** is the solution the KNX Ass. is trying to develop, just it's already developed. This just needs to take a web interface: in my company we agreed in a simple protocol over TCP, but WebSocket would have make more sense. I'm definitely take this one! :)

> 
What, and tell the vendors that their nice IP gateways are no longer needed? the horror ...

Hahah... I got it! I know they don't really want to erase the KNXnet/IP routers in the cases Gateway is available.

> NB: what do you mean, KNXnet/IP is redundant? Quite the opposite is true: the basic idea is just to place the KNXnet/IP router on the same computer as the web service.

I am talking about the need of an extra device when something like KNXD is available. In that case it makes all the sense to put TPUART/Elmos/... (personally using Elmos) in case it's Twisted Pair and access the bus directly. The gateway is always going to exist in the installation side, so does KNXnet/IP router, so the KNXnet/IP router is already made by KNXD :), and very well! I've been using it since I found it.

I'll definitely mention this project!

**Comment by smurfix** [comment]
On 10.10.2016 21:29, jcbastosportela wrote:
>
>     Also: you can base your infrastructure on Java. No problem. You
>     can also base it on a RPi. No problem either. But to base your
>     infrastructure on Java running on RPi is foolish.
>
> It isn't my approach! It's KNX Ass. approach!
>
I know. "You" was generic, not you specifically.
> I'll definitely mention this project! 
Thanks. I'd like to attend myself, but time is severely limited, we're
getting audited in November. :-/

-- 
-- Matthias Urlichs

**Comment by RichiH** [comment]
On Mon, Oct 10, 2016 at 9:29 PM, jcbastosportela <notifications@github.com>
wrote:

> First of all, sorry for late answer, but the country I currently live in
> decided to block github for a couple of days.
>
>
sshuttle could help there; (almost) no one blocks SSH, even if they
throttle it.

**Comment by jcbastosportela** [comment]
Hi all,

I'm still digging in the paper. I'm now about to give some details about this project. Is there anyone here that knows how was TPUART/Elmos and/or NCN5210 modules written? I mean, they are user level, and "TPUARTs" have some time strict conditions, for example the EOF detection (approx 2.5ms break). How were this situations worked around? I would dig into code, but I'm a little out of time and I couldn't find doc about that code. If some could give me some insight about it I would really appreciate, if not I'll have to spend some time understanding the code XD.

In my implementation I implemented a module I called ARTCOM (Almost Real Time COM):
- two threads: RxMonitor and TxMonitor;
- two callbacks that will behave as Interrupts: Rx_IRQ (byte received) and Tx_IRQ (byte transmitted = Tx Ready) that can be registered by client module;

I tested latency in Rpi2 and got way bellow 1ms (average 140us): time difference between Tx_IRQ and Rx_IRQ.

On the top of that, my tpuart module makes frame sniff: just to be in the safe side I get the length info and I count the received bytes.

NOTE: for the ones who didn't read my prev posts, I've written a (worst) TPUART/Elmos driver before knowing this project.

**Comment by ChristianMayer** [comment]
BTW, you can have a look at the CometVisu protocol (https://github.com/CometVisu/CometVisu/wiki/Protocol) that the eibd/knxd is already speaking through the eibread-cgi and eibwrite-cgi. That a highly efficient protocol for realtime access of the KNX that also can be easily used through JavaScript running in a browser.

**Comment by smurfix** [comment]
On 05.11.2016 20:18, Christian Mayer wrote:
>
> BTW, you can have a look at the CometVisu protocol
> (https://github.com/CometVisu/CometVisu/wiki/Protocol) that the
> eibd/knxd is already speaking through the eibread-cgi and
> eibwrite-cgi. That a highly efficient protocol for realtime access of
> the KNX that also can be easily used through JavaScript running in a
> browser.
>
Mmh. A visualisation should be concerned with, well, visualizing data.
It's the backend's job to know which data are available and what their
format is. CometVisu delegates that job entirely to the web browser.
IMHO that's not a good idea.

-- 
-- Matthias Urlichs

**Comment by ChristianMayer** [comment]
Am 06.11.2016 um 11:44 schrieb Matthias Urlichs:
> Mmh. A visualisation should be concerned with, well, visualizing data.
> It's the backend's job to know which data are available and what their
> format is. CometVisu delegates that job entirely to the web browser.
> IMHO that's not a good idea.

The CometVisu protocol doesn't require this. It is just a method to
transfer per-GA-data in such a way that states as well as events are
handled.

This per-GA-data can either be in the raw form (as the current
eibread-cgi/eibwrite-cgi are doing) or already in processed form (what
the OpenHAB backend is mostly doing).
