### ISSUE TITLE
knxd on virtualbox: request sent but no result

### ISSUE THREAD

**Issue by lecabel** [knxd/knxd#157]
Hi I have installed successfully knxd on virtualbox machine. Previously I had a working eibd.
I can start knxd with the following knxd --trace=1023 -DTRS --layer2=ip:192.168.0.100:3671
I can start monitor with the following: vbusmonitor1time ip:localhost
but we I send a comment for example: knxtool groupswrite ip:localhost 0/0/1 0
I don't have any result, light in the above example does not switch.
the virtual machine is connect through bridge same way I did for eibd.

thanks for any help!
Fabio

**Comment by smurfix** [comment]
That can't work.
The `ip:` driver is for multicast. You want `ipt:`.
