### ISSUE TITLE
latest master (0.11) and -c (GroupCache) parameter

### ISSUE THREAD

**Issue by itarch** [knxd/knxd#158]
Hi 

couple of weeks ago I pulled a knxd version (released with 0.10.13-3) and installed it on a Raspberry Pi 3 B with Debian Jessie. I run this version with the following configuration parameter in /etc/knxd.conf "KNXD_OPTS="-e 1.0.206 -c -DTRS -b tpuarts:/dev/ttyKNX1"" since I have a TUL - TPUART device installaed. Given that I was able to get a connection to the EIB BUS with Linknx (on the Raspi) and Gira HS.

Now after performed a clean Installation with the latest version (0.11...) I can't start the knxd with the -c parametr. Start procedure aborts. Starting this knxd without -c parameter works fine. 

However, I do not know exactly if it is necessary for my setup to had this parameter in the list. 
My aim is to run RASP, TUL, KNXD , LINKNX, CometVisu and Gira HS. You may introduce me

Anyway, If you need more details I'm ready to install 0.11 version again ... currently I switched back to the older version as mentioned before.

Regards, Itarch

**Comment by smurfix** [comment]
Verified. Will debug.

**Comment by smurfix** [comment]
Should work now. Please test.

**Comment by itarch** [comment]
puh, ok, I will do, but later

**Comment by itarch** [comment]
I test it. 
Knxd (0.11.9-1) starts without errors.
