### ISSUE TITLE
Question about examples/eibread-cgi.c

### ISSUE THREAD

**Issue by svsool** [knxd/knxd#160]
Hello, I'm use this script as backend for my UI, and have question

https://github.com/knxd/knxd/blob/master/src/examples/eibread-cgi.c#L303

```
if ((subscribedGA[i>>3]&(1<<(i&7))) || (subscribedGA[0] | 1)) //this is HEAVY g=all reads ALL this will take LONG!
```

looks like ```subscribedGA[0] | 1``` always true, right? I get full GA scan, even if I don't pass g=all as commented

**Comment by smurfix** [comment]
This is not an issue; please ask on the mailing list.

To answer anyway: you'll need to take apart the macros and figure out where to insert the address.
