### ISSUE TITLE
Compiling under debian sid

### ISSUE THREAD

**Issue by fma38** [knxd/knxd#161]
Hi!

I'm trying to compile knxd under debian sid. The libsystemd-daemon-dev package has been replaced by libsystemd-dev.

I corrected this in debian/control, but configure still fails, unable to find libsystemd-daemon.

Where do I change this?

**Comment by smurfix** [comment]
Works here.
Which branch / git version are you using?

**Comment by fma38** [comment]
I'm using the be1fcfe85cc1dfcc41f791cd9a45c57fe18da6a0 commit, which is the same as my OpenWRT router, where I want to run knxd. I'm having issues, so I want to test on a regular PC, to see if it is not an iptables or so problem on the router.

**Comment by smurfix** [comment]
Already fixed, in a0ea02a

**Comment by fma38** [comment]
Thanks!
