### ISSUE TITLE
Cannot compile knxd on Debian Jessie - exit 77

### ISSUE THREAD

**Issue by Dizlem** [knxd/knxd#162]
All I am unable to compile knxd on Debian Jessie at the moment.  I've followed the readme and compiled all pre-reqs including libpthsem.

Standard git clone and then compile with dpkg-buildpackage -b.  It fails the dh_auto_configure exit code 77.

Is this a known issue on Jessie or am I missing something?  knxd/config.log attached
[config.log.txt](https://github.com/knxd/knxd/files/583249/config.log.txt)

There are some warnings in the conf test (see below) around missing terminating character but that may be a red herring.

Thanks,

Dizlem

----------------

 conftest.c:4:25: warning: missing terminating " character
 #define PACKAGE_VERSION "0.11.9
                         ^
conftest.c:5:1: warning: missing terminating " character
 "
 ^
conftest.c:5:1: error: missing terminating " character

**Comment by Dizlem** [comment]
The characters were not a red herring I have now compiled it by altering the 'knxd/configure' file to fix the single quotations that had slipped on to the next lines:

Lines 591-594:

_PACKAGE_VERSION='0.11.9
'
PACKAGE_STRING='knxd 0.11.9
'_
and lines 3136-3137:

 _VERSION='0.11.9
'_

After I fixed this it compiled no problem.

Thanks,

Dizlem

**Comment by tru7** [comment]
It helps to modify the version.sh like this:
sed -ne '1s/.*(\(.*\)-.*).*/\1/p' debian/changelog | tr -d "[\n]"
Don't know if one can rely on sed and tr command on every plattform though. Maybe it needs some extra validation checks.

**Comment by smurfix** [comment]
fixed in 61ff907
using ` | tr -d "\n" `
as the brackets do not make sense.
Yes I can depend on these being present. Any system that has m4 will have sed and tr IMHO.
