### ISSUE TITLE
crosscompiling misses shared_ptr in libstc++

### ISSUE THREAD

**Issue by tru7** [knxd/knxd#164]
I get a problem crosscompiling for openwrt plattform. I suspect the libstc++ is missing the shared_ptr template. This is the error I get:
In file included from layer2.h:23:0,
                 from layer2.cpp:20:
layer2common.h:28:14: error: 'shared_ptr' in namespace 'std' does not name a template type
 typedef std::shared_ptr<Layer2> Layer2Ptr;
              ^
layer2common.h:45:19: error: ISO C++ forbids declaration of 'Layer2Ptr' with no type [-fpermissive]

Doing some quick research I read that shared_ptr is not part of the c++ standard. So I'm afraid that I cannot compile the code for openwrt anymore. Is there a workaround? What do I have to look for?

**Comment by smurfix** [comment]
On 12.11.2016 10:01, Othmar Truniger wrote:
> Doing some quick research I read that shared_ptr is not part of the
> c++ standard
Yes it is, as of c++11. Is openwrt's g++ too old?

-- 
-- Matthias Urlichs

**Comment by tru7** [comment]
Nevermind, I had to rework the settings for cross compilation a little more by explicitly setting -std=c++0x and -lstdc++. It didn't test on openwrt yet but compiling works now to the end.
The toolchain is on Ubuntu 16.04.01 LTS and uses gcc-5.3.0 and musl-1.1.14
