### ISSUE TITLE
Assertion: top() from empty out-queue triggered on ETS 5 group monitor connect

### ISSUE THREAD

**Issue by stmichaelis** [knxd/knxd#166]
When trying to use the latest master an assertion is triggered on first connection attempt from ETS 5 group monitor. 
I was able to finally pin it down to this line:
https://github.com/knxd/knxd/blob/e91e38acb68d65d344e26a5c2e38cec741ebfa2b/src/libserver/eibnetserver.cpp#L422

top() is called even as the queue `out` is empty. Last trace lines are
 (`EIBnet_ConfigRequest 1` is my log message, the 1 indicates out.isempty == true), full trace attached:
```
Layer 8(013AA720,5834BBB2) TunnelSend 2
Layer 8(013AA720,5834BBB2) EIBnet_ConfigRequest 0
Layer 1(013466E0,5834BBB2) Send(012): 04 02 00 00 FB 00 00 01 38 00 01 00
Layer 0(013466E0,5834BBB2) Send(018): 06 10 03 10 00 12 04 02 00 00 FB 00 00 01 38 00 01 00
Layer 0(01387B78,5834BBB2) RecvB(008): BC 11 AB 19 00 E3 00 80
Layer 0(01387B78,5834BBB2) SendAck 11
Layer 0(01387B78,5834BBB2) RecvB(003): 0C 2F A0
Layer 1(01387B78,5834BBB2) RecvLP(011): BC 11 AB 19 00 E3 00 80 0C 2F A0
Layer 3(013775E8,5834BBB2) Enqueue L_Data low from 1.1.171 to 3/1/0 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write 0C 2F
Layer 3(013775E8,5834BBB2) RecvData L_Data low from 1.1.171 to 3/1/0 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write 0C 2F
Layer 8(01335C70,5834BBB2) Send_Route L_Data low from 1.1.171 to 3/1/0 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write 0C 2F
Layer 1(01335D10,5834BBB2) Send(013): 29 00 BC D0 11 AB 19 00 03 00 80 0C 2F
Layer 0(01335D10,5834BBB2) Send(019): 06 10 05 30 00 13 29 00 BC D0 11 AB 19 00 03 00 80 0C 2F
Layer 0(013466E0,5834BBB2) Dropped(019): 06 10 05 30 00 13 29 00 BC D0 11 AB 19 00 03 00 80 0C 2F
Layer 8(01399758,5834BBB3) TunnelSend 1
Layer 1(013466E0,5834BBB3) Send(017): 04 01 00 00 29 00 BC D0 11 FE 10 01 03 00 80 00 F1
Layer 0(013466E0,5834BBB3) Send(023): 06 10 04 20 00 17 04 01 00 00 29 00 BC D0 11 FE 10 01 03 00 80 00 F1
Layer 8(013AA720,5834BBB3) TunnelSend 2
Layer 8(013AA720,5834BBB3) EIBnet_ConfigRequest 1
knxd: queue.h:110: const T& Queue<T>::top() const [with T = Array<unsigned char>]: Assertion `akt != 0' failed.
```

Used a Raspberry 2 and the TPUART Pigator module from busware. knxd command line is: `knxd --trace=1023 -e 1.1.255 -E 1.1.21:10 -D -T -R -S -b tpuarts:/dev/ttyAMA0`

Any ideas? Nobody else having this problem?
Please notice that this is the problem preventing me from testing the workaround in #121 on the master branch.

[trace.txt](https://github.com/knxd/knxd/files/610008/trace.txt)

**Comment by smurfix** [comment]
Hmm. One possible reason why something like this could happen comes to mind when reading the code. See branch p166.

If that fixes your problem, you need to investigate why confirmation packets are not processed (or get lost).

**Comment by rkiggen** [comment]
I have the same problem as @stmichaelis on a Rapberry Pi 2 with a pigator module from busware.

**Comment by smurfix** [comment]
But clause A can only be reached when state is increased, which can only happen (at least in branch p166 -- did you test that?) when the queue is not empty.

**Comment by rkiggen** [comment]
Sorry @smurfix I was looking in the master so I didn't see the . If you'd like me to, I'll test the p166 branch.

**Comment by smurfix** [comment]
Please do.

-- 
-- Matthias Urlichs

**Comment by elupus** [comment]
Seems to resolve the crash for me.

**Comment by rkiggen** [comment]
I've tested this branch and can confirm that it does solve the crash. On another note I'm using a Raspberry Pi2 in combination with a Pigator module from Busware. The device shows up in ETS5 but testing the interfaces takes a long time, while doing address checks or trying to program a device I get timeouts. In general all knx communication seems to be real slow. Is anyone else experiencing this? Do you have any idea what might be causing this?

**Comment by elupus** [comment]
@rkiggen the slowness is likely what i'm seeing in: https://github.com/knxd/knxd/issues/167. Try turning on NAT mode if you are tunneling.

**Comment by stmichaelis** [comment]
Thx for the super-fast patch. Using p166 the assertion is not triggered for me as well and ETS receives a connection event. Nevertheless, no further data or group messages show up in the monitor.

Seems that in the original code for `state > 10` the last packet in the queue is removed by `out.get()` and therefore the next `out.top()` fails.

@rkiggen with your hardware you could also look at #121 and the workaround in https://github.com/knxd/knxd/issues/121#issuecomment-252978001
With this version knxd was running solid as a rock.
