### ISSUE TITLE
knxd 0.11.9-1 looses packets when sending multiple commands at once

### ISSUE THREAD

**Issue by michael1** [knxd/knxd#171]
I'm using linknx to send multiple commands directly one after another.
When I'm sending 6 KNX messages at the same time, only the first 3 ones get sent and the other 3 are lost.
The issue happens with version 0.11.9-1
This was working with version 10.13.  I haven't tried any version in-between, so I can't say when this problem was introduced.
I downgraded back to the old version and it is working again without any other configuration change.

Configuration I use to start knxd:
`KNXD_OPTS="-e 15.0.99 -c --no-tunnel-client-queuing -DTS -b ipt:XXX.XXX.XXX.X"`
together with an EIB KNX IP SCHNITTSTELLE N401

**Comment by smurfix** [comment]
So why don't you simply remove the --no-tunnel-client-queuing argument?

**Comment by michael1** [comment]
Good question - and thank's for the fast follow-up.
I haven't tested with the latest version of knxd, but back with eibd I added that because without that option the IP interface N401 also lost the packages. So I assume that's still the case.
See here: https://knx-user-forum.de/forum/%C3%B6ffentlicher-bereich/knx-eib-forum/diy-do-it-yourself/27483-eibd-zu-schnell
I think that's why this option was added.

**Comment by smurfix** [comment]
This option may have gotten reversed while fixing the timeout code.

Please test without it.

**Comment by drehm** [comment]
Hi smurfix,

i have recently experienced the same issue. I was using an old installation of knxd where frequent bus reading and writing was working properly, but only when using  option --no-tunnel-client-queuing. If I was not using the option then I could see that knxd was logging that a read request for example was triggered, but using ETS i could not see the read requests on the bus. When i updated to a more recent version of knxd 0.11.9 i noticed that again the same issues appeared as I had with 0.10.0 when not using the option --no-tunnel-client-queuing. I did test version 0.11.9 with and without the option. It did not make any difference. What is not clear to me right now is: is the new version expected to be working without the option or is it expected to use the option but has a bug?

Many thanks to everyone working on knxd! You do an excellent job!!!

**Comment by wvhn** [comment]
The issue drehm is reporting has been documented quite well [here](https://knx-user-forum.de/forum/supportforen/smarthome-py/999500-eibd-anstatt-knxd?p=1017331#post1017331). There are several hints in the forum that switching back to V0.10.0 solves some problems which V0.11.9 has.

**Comment by smurfix** [comment]
Please test branch p171.
I implemented a configurable delay. Use `--send-delay` instead of `--no-tunnel-client-queuing`.
`--send-delay` defaults to 30 msec. You might want to start with `--send-delay=200` or so.
