### ISSUE TITLE
Trouble compling KNXD on Rasperry - Jessie

### ISSUE THREAD

**Issue by erw111n** [knxd/knxd#172]
Hi, i hav a new installed jessie on RPI- Mdl 3B: 
Linux CL-RPI-2 4.4.34-v7+ #930 SMP Wed Nov 23 15:20:41 GMT 2016 armv7l GNU/Linux
I've worked thru the install aids from github-wiki and FHEM wiki.

1 can compile pthsem w.o. error
however, when trying to compile KNXd i get the following:
`pi@CL-RPI-2:~/knxdinstall $ git clone https://github.com/knxd/knxd.git
Cloning into 'knxd'...
remote: Counting objects: 4497, done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 4497 (delta 42), reused 0 (delta 0), pack-reused 4426
Receiving objects: 100% (4497/4497), 1.50 MiB | 472.00 KiB/s, done.
Resolving deltas: 100% (3176/3176), done.
Checking connectivity... done.
pi@CL-RPI-2:~/knxdinstall $ cd knxd
pi@CL-RPI-2:~/knxdinstall/knxd $ sudo dpkg-buildpackage -b -uc
dpkg-buildpackage: source package knxd
dpkg-buildpackage: source version 0.11.10-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Matthias Urlichs <matthias@urlichs.de>
dpkg-buildpackage: host architecture armhf
 dpkg-source --before-build knxd
 debian/rules clean
dh clean
   dh_testdir
   dh_auto_clean
   debian/rules override_dh_clean
make[1]: Entering directory '/home/pi/knxdinstall/knxd'
dh_clean
        rm -f debian/knxd.substvars
        rm -f debian/knxd.*.debhelper
        rm -rf debian/knxd/
        rm -f debian/knxd-tools.substvars
        rm -f debian/knxd-tools.*.debhelper
        rm -rf debian/knxd-tools/
        rm -f debian/knxd-dev.substvars
        rm -f debian/knxd-dev.*.debhelper
        rm -rf debian/knxd-dev/
        rm -f debian/knxd-examples.substvars
        rm -f debian/knxd-examples.*.debhelper
        rm -rf debian/knxd-examples/
        rm -f debian/*.debhelper.log
        rm -f debian/files
        find .  \( \( \
                \( -path .\*/.git -o -path .\*/.svn -o -path .\*/.bzr -o -path .\*/.hg -o -path .\*/CVS \) -prune -o -type f -a \
                \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
                 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
                 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
                 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
                \) -exec rm -f {} + \) -o \
                \( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
        rm -f *-stamp
rm -f debian/knxd.install
make[1]: Leaving directory '/home/pi/knxdinstall/knxd'
 debian/rules build
dh build
   dh_testdir
   debian/rules override_dh_auto_configure
make[1]: Entering directory '/home/pi/knxdinstall/knxd'
sh bootstrap.sh
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./config.guess'
libtoolize: copying file `./config.sub'
libtoolize: copying file `./install-sh'
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
libtoolize: AC_PROG_RANLIB' is rendered obsolete by LT_INIT'
autom4te: need GNU m4 1.4 or later: /usr/bin/m4
aclocal: error: echo failed with exit status: 1
debian/rules:24: recipe for target 'configure' failed
make[1]: *** [configure] Error 1
make[1]: Leaving directory '/home/pi/knxdinstall/knxd'
debian/rules:14: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
pi@CL-RPI-2:~/knxdinstall/knxd $`

Any hint ?? - i tried both with and w.o sudo...
best regards & thanks 
erwin

**Comment by smurfix** [comment]
That's easy:

On 30.11.2016 16:54, erw111n wrote:
> autom4te: need GNU m4 1.4 or later: /usr/bin/m4
So please fix your m4 installation. Or demonstrate that yours works:

desk ~$ m4 --version
m4 (GNU M4) 1.4.17

NB: please turn off wrapping when pasting console output.

NB²: running "sudo dpkg-buildpackage" (or building as root) is not a
good idea. Don't even think of doing that.

-- 
-- Matthias Urlichs

**Comment by erw111n** [comment]
Thanks for the immediate resonse, looks like i a have a problem with m4:
`pi@CL-RPI-2:~/knxdinstall/knxd $ m4 --version`
`/usr/bin/m4: line 1: syntax error near unexpected token `)'`
`/usr/bin/m4: line 1: `Ó)        ÊûAä{¦æ)«'`
now I'v done: sudo apt-get install m4 --reinstall
and get: m4 (GNU M4) 1.4.17
now build and install works!
...whatever happen to m4 - it was a frehs install yesterday!!!
Thanks & best regards erwin

**Comment by smurfix** [comment]
On 30.11.2016 17:52, erw111n wrote:
> ...whatever happen to m4 - it was a frehs install yesterday!!!
I'd assume a bad memory card and/or a marginal power supply.

-- 
-- Matthias Urlichs
