### ISSUE TITLE
KNXD (EIBD) influences audio performance

### ISSUE THREAD

**Issue by mayrjohannes** [knxd/knxd#176]
I installed knxd (and also eibd) on my openmediavault and try to play audio on the same server (e.g. by mpd or speaker-test). In this case if the knxd is running and using a non IP device to interface the sound is broken. Stopping knxd gives perfect sound again. As non IP devices I could only test a NCN5120.
For the IP device test I was running a second knxd on my desktop pc and connected to that knxd from the servers knxd. 

I assume that it is somehow related to serial communication. Any suggestions where to look for that error?

For more error description please see also:
https://knx-user-forum.de/forum/öffentlicher-bereich/knx-eib-forum/39972-eibd-war-bcusdk-fork-knxd?p=987717#post987717
https://knx-user-forum.de/forum/öffentlicher-bereich/knx-eib-forum/39972-eibd-war-bcusdk-fork-knxd?p=1011529#post1011529
https://knx-user-forum.de/forum/öffentlicher-bereich/knx-eib-forum/39972-eibd-war-bcusdk-fork-knxd?p=1018606#post1018606

**Comment by smurfix** [comment]
That looks like a generic Raspberry Pi problem. Which Pi are you using?
Are you using a USB-based serial interface, or the built-in serial port on the extension header?
If the former: Did you try with an external powered hub?

**Comment by mayrjohannes** [comment]
I'm not using a RPi at all. My setup is:
- Asrock Q1900 ITX mit Intel® Quad-Core Processor J1900 und 7.1 CH HD Audio with Content Protection (Realtek ALC892 Audio Codec)
- 160GB SSD
- 8 GB RAM
- NCN5120 über USB-Seriel Konverter 

The serial converter is a FTDI
lsusb: Bus 003 Device 005: ID 0403:6001 Future Technology Devices International, Ltd FT232 USB-Serial (UART) IC

**Comment by smurfix** [comment]
Looks like a USB bandwidth problem. Is the audio also on USB? DId you try a different audio adapter?

**Comment by mayrjohannes** [comment]
The audio comes from the onboard audio chip (7.1 CH HD Audio with Content Protection (Realtek ALC892 Audio Codec))

If it is related to USB bandwith, shouldn't it also occour if I connect an external USB hardddisk? If so, that would be easy to test.

But is it realistic that serial communication can cause an USB bandwith problem (very low load?)? 

I also tested the same error on my netbook with Ubuntu months ago and it was the same audio problem. Maybe the netbook uses the same USB controller, but if its a different one maybe this is against your theory?

**Comment by Makki1** [comment]
Just guessing: the FTDI switches something on the USB (or something like that) and/or the soundcard is internally connected via USB (lsusb?)
Anyway, theres probably really nothing knxd can do about this as the usbserial driver is separate and kernel-mode.. and we really need the quick responsetimes to do acks in TP-UART for KNX (but very, very few bandwidth - though the bandwidth is blasted by the usb minimum packetsize of 64byte..)

I'd try another usb-serial (the ft232 is pretty ancient) or better: put knd on a separate (small) system, I learned it's not always the best to mix too many services on a single box..
Just my 2ct..

**Comment by mayrjohannes** [comment]
Makki you had been right. I switched from an FTDI to an Prolific PL2303 and now it works without noise. 
Only thing I'm facing now is that after a while the eibd / knxd stops receiving. I can still send packages, but do not get any response from the bus anymore. A restart of eibd / knxd gives full functionality again. But as this is a different topic I will write it in the knx-user-forum as well.

Thanks for your help! Issue can be closed.
