### ISSUE TITLE
knxd doesn't like the MDT SCN-USBR.01

### ISSUE THREAD

**Issue by HLeithner** [knxd/knxd#187]
I'm trying to get knxd to talk to a MDT SCN-USBR.01 usb interface on a raspberry pi.

At the moment I have knxd 0.11.14 running, but it seams that knxd doesn't receive no anwser from the usb port:

```
root@raspberrypi:~# knxd --error=1 -e 1.1.128 -D -T -t1023 -f9 -R usb:/dev/bus/usb/001/004
Layer 3 [3:layer3                   0.001] Open
Layer 1 [2:usb:/dev/bus/usb/001/004 0.054] Detect
Layer 1 [2:usb:/dev/bus/usb/001/004 0.070] Using 1:4:1:0:0 (1:130)
Layer 1 [2:usb:/dev/bus/usb/001/004 0.072] Open
Layer 1 [2:usb:/dev/bus/usb/001/004 0.139] Claimed
Layer 1 [2:usb:/dev/bus/usb/001/004 0.142] Opened
Layer 1 [2:usb:/dev/bus/usb/001/004 0.142] Send(064): 01 13 09 00 08 00 01 0F 01 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 3 [3:layer3                   0.147] L3 started
Layer 0 [2:usb:/dev/bus/usb/001/004 0.152] StartRecv
Layer 0 [2:usb:/dev/bus/usb/001/004 0.155] Send(064): 01 13 09 00 08 00 01 0F 01 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0 [2:usb:/dev/bus/usb/001/004 0.168] StartSend
Layer 0 [2:usb:/dev/bus/usb/001/004 0.169] SendComplete 64
Layer 0 [2:usb:/dev/bus/usb/001/004 30.152] RecvError 2
W00000033: RecvError 2
Layer 0 [2:usb:/dev/bus/usb/001/004 30.154] StartRecv

```

```knxtool vbusmonitor1 local:``` Doesn't show anything.

I'm not sure if its releated to this https://github.com/knxd/knxd/issues/124#issuecomment-217216361 by @Makki1 

On windows its possible to use the USB Interface with ETS5 to program devices.

**Comment by smurfix** [comment]
Unfortunately I don't have any USB devices to test with. (Hint, hint …)

You might want to try other USB endpoints, maybe the device has more than one.

**Comment by HLeithner** [comment]
Thx for your answer, I'm sorry to say that my MDT USB interface is on the way back to the Seller. But I contacted MDT for support.

**Comment by smurfix** [comment]
I now own an MDT interface. 0.12 works ACAICT. Please re-open this bug if yours does not.

**Comment by smurfix** [comment]
NB: knxd does not use `usb:/dev/usb/whatever`. It uses `usb:` or, if knxd finds multiple HID devices, `usb:1:2` (bus and device numbers).
