### ISSUE TITLE
How do you update knxd on a raspberry pi

### ISSUE THREAD

**Issue by petkoe** [knxd/knxd#188]
Hi,

I cannot update from Knud v 0.11.9 to the latest.

Thanks 

Peter

**Comment by smurfix** [comment]
*Sigh* do you also call up your car mechanic and say "my car doesn't work, tell me how to fix it"?

What did you do, and what happened?

**Comment by petkoe** [comment]
HI, 

I followed the instructions from https://www.boernyblog.de/raspberry-pi-3-als-knx-bridge-fuer-ios-homekit/
it installed the v 0.11.9. via git clone and dpkg-buildpackage -b -uc 

How do I get an update to the new version? I am not very good on the command line.
I tried another git clone .. git fetch apt-get-update .. Anything i know to do updates but nothing did an update to 0.11.14 (latest).

Sorry but I do not know how to be more specific. I am also not able to get any results with my google searches.

TIA 

Peter

**Comment by smurfix** [comment]
Following the instructions a second time will replace your knxd. This is not a bug.

**Comment by petkoe** [comment]
I deleted the Knxd folder and followed the instructions, but 

(Reading database ... 37591 files and directories currently installed.)
Preparing to unpack knxd_0.11.15-1_armhf.deb ...
Warning: Stopping knxd.service, but it can still be activated by:
  knxd.socket
Unpacking knxd (0.11.15-1) over (0.11.9-1) ...
dpkg: warning: downgrading knxd from 0.11.15-1 to 0.11.9-1
Preparing to unpack knxd_0.11.9-1_armhf.deb ...
Unpacking knxd (0.11.9-1) over (0.11.15-1) ...
Preparing to unpack knxd-tools_0.11.15-1_armhf.deb ...
Unpacking knxd-tools (0.11.15-1) over (0.11.9-1) ...
dpkg: warning: downgrading knxd-tools from 0.11.15-1 to 0.11.9-1
Preparing to unpack knxd-tools_0.11.9-1_armhf.deb ...
Unpacking knxd-tools (0.11.9-1) over (0.11.15-1) ...
More than one copy of package knxd has been unpacked
 in this run !  Only configuring it once.
More than one copy of package knxd-tools has been unpacked
 in this run !  Only configuring it once.
Setting up knxd (0.11.9-1) ...
addgroup: The group `knxd' already exists as a system group. Exiting.
Warning: The home dir /var/lib/knxd you specified already exists.
The system user `knxd' already exists. Exiting.
Setting up knxd-tools (0.11.9-1) ...
Processing triggers for systemd (215-17+deb8u5) ...
Processing triggers for libc-bin (2.19-18+deb8u6) ...

It seems that I get the latest version but it is then not used????

**Comment by petkoe** [comment]
I was able to get the latest version using 

sudo dpkg -i knxd_0.11.15-1_armhf.deb knxd-tools_0.11.15-1_armhf.deb

where 0.11.5 is the version.

**Comment by smurfix** [comment]
On 25.12.2016 09:02, Peter wrote:
> More than one copy of package knxd has been unpacked
> in this run ! Only configuring it once.
So delete the old .dpkg files before you try installing the new ones.

Isn't that reasonably obvious when you read the message?

-- 
-- Matthias Urlichs
