### ISSUE TITLE
branch libev: several compiling issues

### ISSUE THREAD

**Issue by tru7** [knxd/knxd#189]
For me branch libev never reached a state where it could be compiled out of the box. At current state I have found several issues:

Using configure with default settings fails for configure if package libev-dev is not installed. This is a new dependency. This is OK, just nowhere mentioned.

Using configure with default settings fails for make in src/libserver with:
g++ -DHAVE_CONFIG_H -I. -I../..  -I../../src/include -I../../src/common    -g -O2 -std=c++0x -MT common.o -MD -MP -MF .deps/common.Tpo -c -o common.o common.cpp
In file included from common.h:57:0,
                 from common.cpp:21:
threads.h:23:20: fatal error: pthsem.h: No such file or directory
--> configure didn't report dependency for pthsem but obviously there still is.

Using configure with --enable-usb fails for make in libev with:
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -DECB_NO_LIBM -fPIC -g -O2 -I/scratch/knxd/libev -DEV_USE_PTHSEM -MT ev.lo -MD -MP -MF .deps/ev.Tpo -c ev.c  -fPIC -DPIC -o .libs/ev.o
ev.c:224:21: fatal error: pthsem.h: No such file or directory
--> my pull request for smurfix/libev would help to resolve this issue

Next problem (with --enable-usb): make fails in src/tools/eibnet with:
libtool: link: g++ -g -O2 -std=c++0x -I/scratch/knxd/libev -o eibnetdescribe eibnetdescribe.o  ../../libserver/libeibstack.a ../../common/libcommon.a /scratch/knxd/libev/.libs/libev.a
/scratch/knxd/libev/.libs/libev.a(ev.o): In function `pthsem_poll':
/scratch/knxd/libev/ev_pthsem.c:88: undefined reference to `pth_event'
....
--> change in src/tools/eibnet/Makefile.am can resolve this:
"$(PTHSEM_LIB) $(EV_LIBS) -lpthsem" instead of "$(EV_LIBS)" for lines with LDADD
--> with this change makes runs fine

**Comment by smurfix** [comment]
Meh. I admit that I haven't even built without libpthsem installed (even if it didn't end up being included in the binary). The first problem should now be fixed.

I have pulled your libev patch which should take care of the second item.

As for the third, "$(EV_LIBS) $(PTHSEM_LIB)" works for me and has been pushed.

Note that I had to add another config item which disables bus monitor support, since that still requires a (quite unnecessary) pthsem thread, which I haven't yet gotten around to eliminating and which incidentally should be the main culprit for the test not working. Added to my TODO-soon list.

**Comment by tru7** [comment]
My pthsem is not installed in the default location - this helps to find incomplete definitions ;-)
Yes "$(EV_LIBS) $(PTHSEM_LIB)" works well because $(PTHSEM_LIB) contains -lpthsem and is at the right position this way.
Now make runs successfully with and without pthsem dependency. Well done.
Next I can test the new binaries.

**Comment by tru7** [comment]
libusb is not pthsem-free when usb.h loads threads.h from src/libserver because this still loads pthsem.h

**Comment by tru7** [comment]
with --enable-ft12 make fails with:
ft12.cpp:307:17: error: ‘EMIVer’ in ‘class LowLevelDriver’ does not name a type

**Comment by tru7** [comment]
usb and ft12 compile fine again with latest commits.
