### ISSUE TITLE
Memory leak on any client command

### ISSUE THREAD

**Issue by dallmair** [knxd/knxd#192]
A few days ago, [Stijn Van De Voorde reported a memory leak on Google Groups](https://groups.google.com/forum/#!topic/knxd/NtodHPoWRSI). Unfortunately this problem is not related to a specific backend, as I can easily reproduce it with TPUART.

**Comment by dallmair** [comment]
Of course there could be several independent memory leaks; PR #193 addresses the problem I noticed in my setup.

**Comment by smurfix** [comment]
Does the current release, which incorporates #193, fix your problem?

**Comment by dallmair** [comment]
Yes it does, I tested it successfully with TP-UART and USB devices -> closed.
