### ISSUE TITLE
knxd 0.11.17 - smartvisuNG spooky behavior

### ISSUE THREAD

**Issue by geertge** [knxd/knxd#194]
Hi, 

I installed the smarthomeNG pi image and I upgraded knxd to the latest version (0.11.17). If I connect with ETS 5 and I use the multicast mode I can send and receive telegrams (other methods don't work). Everything is working fine. If I use smartVISU I get as status 0 (not the real status), no telegram will be send on the knx bus. It seem's I have no connection between smarthome/smartvisu and knxd.  Booth are running on the same PI (IP 192.168.2.199). And now the spooky thing. I start a old PI with smarthome and knxd (IP 192.168.2.149-knxd 0.10.0) which connect to a NOT connected IP interface (192.168.1.102, not even in the same range), I change the IP address in the I/O connection on the new PI (192.168.2.199) to 192.168.2.149 (smarthome.py driver, IP address of the old PI, where knxd is connected to a not existing IP interface) and smartVISU WORKS. What can be the problem and/or solution?

Geert

**Comment by smurfix** [comment]
I assume that both computers are using knxd configurations with -R -S ?
What are you using to talk to the KNX wire?
You might want to give the libev branch a try if you'd like to be helpful. ;-)

Anyway, the CGI programs on 0.11 seem to be somewhat broken. I'll try to find the problem.

**Comment by smurfix** [comment]
0.11.18 should have a working CGI reader. This should solve your problem. Please test.

**Comment by smurfix** [comment]
Closing due to lack of feedback. Please re-open when appropriate.
