### ISSUE TITLE
Multicast server on multihomed host only listens to one interface

### ISSUE THREAD

**Issue by KaneTW** [knxd/knxd#198]
Multicast groups in knxd belong to INADDR_ANY. 
Unfortunately, this causes the group to only be bound to one interface. 
This means that if I have a host with
- eth0: 10.1.5.x/24
- eth1: 10.1.1.x/24
multicast packets are only received from the 10.1.5.x subnet.

A fix would be to specify the interfaces you want to join multicast groups on or to join on all multicast-enabled interfaces.

**Comment by smurfix** [comment]
Patch written and pushed. f162e1e (completely untested).

You might need to turn off reverse route protection.
`sysctl -w net.ipv4.conf.eth1.rp_filter 0`

**Comment by smurfix** [comment]
Did you have a chance to test this?

**Comment by smurfix** [comment]
Closing due to lack of feedback. Please re-open when appropriate.
