### ISSUE TITLE
ini-style config file instead of argument list

### ISSUE THREAD

**Issue by smurfix** [knxd/knxd#199]
This issue tracks the conversion of knxd from understanding a heap of arguments to parsing a config file.

**Comment by smurfix** [comment]
Working on it. To do this cleanly I'll need to re-structure the way drivers are set up.

This work will also allow us to reliably trace driver state, restart failing drivers, or hook up new ones without restarting.

**Comment by snowdd1** [comment]
I just want to express my admiration for all the work you do here. You are basically doing it alone. I feel ashamed I am even behind with testing of quite old issues. 


:thumbs up:

**Comment by smurfix** [comment]
Work in progress, on the master branch.

**Comment by dallmair** [comment]
@smurfix This is completed, right? Or is there anything left to do regarding an ini-style config file from your pov?

**Comment by smurfix** [comment]
Nope. Many thanks for your bug triaging!
