### ISSUE TITLE
knxd no longer routes from ipt to multicast using latest git

### ISSUE THREAD

**Issue by gedia** [knxd/knxd#201]
Hello,

It appears something has been broken with latest git code. First, a topology diagram:
```
KNX TP <--> ABB IP Interface (.254) <-ipt-> knxd (.250) <--> multicast client (.178)
```
The above addresses (only host part is included) are unicast. There is only one multicast server (that's knxd) listening to 224.0.23.12:3671. The multicast client is configured to use the same address. The issue is:
- A datagram originating from a multicast client is routed to KNX TP.
- A datagram originating on KNX TP is not forwarded to multicast clients.

I have verified this by installing a previous version. The arguments have only changed a bit because the -E option isn't supported by the older codebase:

1) Working setup: Built from commit bbc322380a9c14c4d482eb32a89857a8d595a76f. Args:
```
KNXD_OPTS="-e 1.1.254 -i -D -T -R -S -b ipt:172.17.178.254"
```
The multicast client can send and receive datagrams to/from KNX

2) Non-working setup: Built from commit 230eed4c46a03f29ec58d5d2a8a78bda54ab4db7
```
KNXD_OPTS="-e 1.1.254 -i -E 1.1.240:10 -D -T -R -S -b ipt:172.17.178.254"
```
The multicast client can send datagrams to KNX, but it can't receive datagrams originating from KNX TP.

Commit fed87f2d6bb9b1d66a91fa6f53cbd0b2310ad2e1 is affected as well. The offending code (assuming I'm not doing anything terribly wrong here) must have been committed between Dec 31 and Jan 9.

**Comment by smurfix** [comment]
Hmm. Will check.

**Comment by smurfix** [comment]
I have updated my test script to check for this (commit 4f34b75) but cannot reproduce the problem. Please send me a log file.

**Comment by gedia** [comment]
You mean by running knxd with -t 0xffc -f 9? Will the output be available to syslog/journald?

**Comment by smurfix** [comment]
On 21.01.2017 23:43, George Diamantopoulos wrote:
>
> You mean by running knxd with -t 0xffc -f 9? Will the output be
> available to syslog/journald?
>
0xfffe would be better. Yes.

-- 
-- Matthias Urlichs

**Comment by smurfix** [comment]
Please re-test with 0.12.6. You might require "-B single" in front of the "-b ipt:".

**Comment by gedia** [comment]
Works charmingly now! Thanks!

-B single doesn't seem to make a difference for the issue reported here.

Did you find out what might have caused it or did you just merge the libev branch and hoped it would go away?

**Comment by gedia** [comment]
Note: this test was performed with e927fef752fd6d5a2aaf6ca75e2144db896a7956

**Comment by smurfix** [comment]
I did find a possible cause (received packet was attributed to the wrong channel).

**Comment by fluppie** [comment]
Is there an example config for this setup? I also want to add support for Multicast so I can use Tasmota devices directly over KNX-IP.

I use an MDT IP Interface SCN-IP000.02:
KNX IP-Interface
Individual Address	1. 1. 9
Tunneling Addresses	15.15.241
15.15.242
15.15.243
15.15.244

TP Device
Individual Address	15.15.254

The HomeAssistant Hass.io config should be like this?
{
  "address": "1.1.10",
  "client_address": "1.1.10:10",
  "interface": "ipt",
  "device": "192.168.1.5",
  "custom_config": ""
}
