### ISSUE TITLE
Compile for nas ARMv7

### ISSUE THREAD

**Issue by mpl1337** [knxd/knxd#203]
Hey there, is it possible to compile and run knxd on a syology ds214+ (Marvell ARMADA XP ARMv7) with USB support?

**Comment by smurfix** [comment]
On 17.01.2017 21:29, mpl1337 wrote:
>
> Hey there, is it possible to compile and run knxd on a syology ds214+
> (Marvell ARMADA XP ARMv7) with USB support?
>
I have no idea. Which compiler is used for that system? knxd stable
(0.10) needs a reasonably recent GCC; the current master/libev branch
(0.12) requires support for the c++11 standard, i.e. at least gcc 4.8.1.

As this is not an issue per se, please use the mailing list for further
questions.

-- 
-- Matthias Urlichs
