### ISSUE TITLE
USB only as root working

### ISSUE THREAD

**Issue by mpl1337** [knxd/knxd#204]
Hello,

i have compiled knxd

pi@raspberrypi:~/knxd/src/usb $ knxd -V
knxd 0.12.1

my /etc/knxd.conf:
`KNXD_OPTS="-e 0.0.1 -E 0.0.2:8 -u /tmp/eib -u/var/run/knx -DTRS -B single -b usb:1:6:1:0:0"
`

when i try to start

> pi@raspberrypi:~/knxd/src/usb $ sudo service knxd start
> Job for knxd.service failed. See 'systemctl status knxd.service' and 'journalctl -xn' for details.
> pi@raspberrypi:~/knxd/src/usb $ sudo systemctl status knxd.service
> ● knxd.service - KNX Daemon
>    Loaded: loaded (/lib/systemd/system/knxd.service; enabled)
>    Active: activating (auto-restart) (Result: exit-code) since Mi 2017-01-18 19:17:44 UTC; 8s ago
>   Process: 3086 ExecStart=/usr/bin/knxd $KNXD_OPTS (code=exited, status=1/FAILURE)
>  Main PID: 3086 (code=exited, status=1/FAILURE)
> 
> Jan 18 19:17:44 raspberrypi systemd[1]: Unit knxd.service entered failed state.
> pi@raspberrypi:~/knxd/src/usb $ sudo journalctl -xn
> -- Logs begin at Mi 2017-01-18 18:12:18 UTC, end at Mi 2017-01-18 19:18:03 UTC. --
> Jan 18 19:17:53 raspberrypi sudo[3106]: pam_unix(sudo:session): session closed for user root
> Jan 18 19:17:55 raspberrypi systemd[1]: knxd.service holdoff time over, scheduling restart.
> Jan 18 19:17:55 raspberrypi systemd[1]: Stopping KNX Daemon...
> -- Subject: Unit knxd.service has begun shutting down
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> --
> -- Unit knxd.service has begun shutting down.
> Jan 18 19:17:55 raspberrypi systemd[1]: Starting KNX Daemon...
> -- Subject: Unit knxd.service has begun with start-up
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> --
> -- Unit knxd.service has begun starting up.
> Jan 18 19:17:55 raspberrypi knxd[3114]: initialisation of backend 'unix' failed: Permission denied
> Jan 18 19:17:55 raspberrypi systemd[1]: knxd.service: main process exited, code=exited, status=1/FAILURE
> Jan 18 19:17:55 raspberrypi systemd[1]: Failed to start KNX Daemon.
> -- Subject: Unit knxd.service has failed
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> --
> -- Unit knxd.service has failed.
> --
> -- The result is failed.
> Jan 18 19:17:55 raspberrypi systemd[1]: Unit knxd.service entered failed state.
> Jan 18 19:18:03 raspberrypi sudo[3117]: pi : TTY=pts/0 ; PWD=/home/pi/knxd/src/usb ; USER=root ; COMMAND=/bin/journalctl -xn
> Jan 18 19:18:03 raspberrypi sudo[3117]: pam_unix(sudo:session): session opened for user root by pi(uid=0)

thats the error.... but when i start knxd as root:

> pi@raspberrypi:~ $ sudo knxd -e 0.0.1 -E 0.0.2:8 -u /tmp/eib -u/var/run/knx -DTRS -B single -b usb:1:6:1:0:0
> pi@raspberrypi:~ $ sudo knxtool groupswrite local: 2/2/2 1
> Send request
> pi@raspberrypi:~ $ sudo knxtool groupswrite local: 2/2/2 0
> Send request

i can send telegrams and the light go on/off 
but i cant connect over ets4... i see KNXD in connections but on "test" error no connection

so whats my problem?

**Comment by smurfix** [comment]
You need an udev rule to set the USB device's owner to knxd.

Also, `-u/var/run/knx` may not work correctly because systemd's knxd.socket already opens /run/knx for you and that's the same directory (or at least it should be).

Start the options with `-f9 -t1020` to log more verbosely. Journald's `-x` option is useless here, but you should use `-u knxd.service` to only print entries about knxd.

**Comment by mpl1337** [comment]
Okay, have changed config to:

> KNXD_OPTS="-e 1.1.4 -E 1.1.5:10 -f9 -t1020 -u /tmp/eib -DTRS -b usb:"

knxd starts now and i can usw groupswrite and busmonitor1 but vbusmonitors not working.

on ETS4.2.0 is se "ok" on Connection to KNXD but the Busmonitor/groupmonitor connect but does not log, programming works

where can i found the -f9 -t1020 log?

**Comment by smurfix** [comment]
What do you mean, "vbusmonitors not working"? Which command do you use? It works here …

The log is in the journal. "journalctl -n500 -u knxd" should display it.

**Comment by mpl1337** [comment]
no output when i write a group on my bus...but on busmonitor iv got the outputs and ets4 monitor too no output

knxtool vbusmonitor1 local:

**Comment by smurfix** [comment]
So, nothing happens? that should not happen, vbusmonitor1 hooks into the datagram dispatcher so if anything works at all then you should see it.

**Comment by mpl1337** [comment]
> pi@raspberrypi:/ $ knxtool groupswrite local: 0/0/1 1
> Send request

Relay goes on

> pi@raspberrypi:/ $ knxtool groupswrite local: 0/0/1 0
> Send request

Relay goes off

> pi@raspberrypi:/ $ knxtool busmonitor1 local:
> LPDU: BC 11 01 00 01 E1 00 81 32 :L_Data low from 1.1.1 to 0/0/1 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
> LPDU: CC :ACK
> LPDU: BC 11 02 00 02 E1 00 81 32 :L_Data low from 1.1.2 to 0/0/2 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
> LPDU: CC :ACK
> LPDU: BC 11 01 00 01 E1 00 80 33 :L_Data low from 1.1.1 to 0/0/1 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 00
> LPDU: CC :ACK
> LPDU: BC 11 02 00 02 E1 00 80 33 :L_Data low from 1.1.2 to 0/0/2 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 00
> LPDU: CC :ACK
> ^C

Pressed on my Sensor ON and then Off

> pi@raspberrypi:/ $ knxtool vbusmonitor1 local:
^C

Pressed on my Sensor ON and then Off and nothing to see

> Jan 19 16:52:42 raspberrypi knxd[817]: knxd: Layer 8 [ 6:systemd         2368.633] New Connection
Jan 19 16:52:42 raspberrypi knxd[817]: knxd: Layer 8 [ 6:systemd         2368.633] ClientConnection Init
Jan 19 16:52:42 raspberrypi knxd[817]: knxd: Layer 3 [ 3:layer3          2368.633] Allocate 1.1.13
Jan 19 16:52:42 raspberrypi knxd[817]: knxd: Layer 7 [25:systemd:monitor 2368.642] Open A_Busmonitor
Jan 19 16:52:42 raspberrypi knxd[817]: knxd: Layer 3 [ 3:layer3          2368.643] registerVBusmonitor 00FDB9B8
Jan 19 16:52:42 raspberrypi knxd[817]: knxd: Layer 8 [24:systemd         2368.643] SendMessage(002): 00 13
Jan 19 16:52:47 raspberrypi knxd[817]: knxd: Layer 8 [24:systemd         2373.295] ClientConnection 1.1.13 closing
Jan 19 16:52:47 raspberrypi knxd[817]: knxd: Layer 3 [ 3:layer3          2373.295] Release 1.1.13
Jan 19 16:52:47 raspberrypi knxd[817]: knxd: Layer 7 [25:systemd:monitor 2373.295] Close A_Busmonitor
Jan 19 16:52:47 raspberrypi knxd[817]: knxd: Layer 3 [ 3:layer3          2373.295] deregisterVBusmonitor 00FDB9B8 = 1

**Comment by smurfix** [comment]
Did you configure your bus interface (with ETS) in some way? looks like it doesn't relay the packets if it's not in dedicated bus monitor mode.

What make+model of USB adapter are you using?

**Comment by mpl1337** [comment]
i try 2 adapters.

the first is BuschJaeger 6186 USB and second is ABB USB/S1.1 but i thing this are the same hardware/software only other labels.

there are no configurations for the bus interfaces on the ETS

**Comment by smurfix** [comment]
I'm afraid that it's difficult to help without having such an adapter.

You might try

KNXD_OPTS="-e 1.1.4 -E 1.1.5:10 -f9 -t1020 -u /tmp/eib -DTRS -B single -b usb:"

**Comment by mpl1337** [comment]
> knxd       789  0.3  0.7  14004  3348 ?        Ssl  18:12   0:00 /usr/bin/knxd -e 1.1.4 -E 1.1.5:10 -f9 -t1020 -u /tmp/eib -DTRS -B single -b usb:

still not working :/

**Comment by smurfix** [comment]
You were too fast … I updated my earlier comment.

As you have two of those, you could send me one. I'll get it working and mail it back.

**Comment by mpl1337** [comment]
http://pastebin.com/ha6mxf6E

**Comment by mpl1337** [comment]
okay can send you one

**Comment by smurfix** [comment]
Matthias Urlichs
Schleiermacherstraße 12
90491 Nürnberg
Germany

**Comment by mpl1337** [comment]
Ok geht Montag raus da der 2te in der Firma ist.

**Comment by Makki1** [comment]
I have also two lying around..
But really: forget about the old cEMI USB-Ifs, they never really
"worked" neither with eibd/knxd nor ETS/HS, ... at least not in a stable
manner for more than 2hrs or more than 8 tps..

But if you really want to test, i'll grab them an send(?)

Michael

Am 20.01.2017 um 19:18 schrieb Matthias Urlichs:

**Comment by smurfix** [comment]
On 21.01.2017 14:59, Makki1 wrote:
> I have also two lying around..
> But really: forget about the old cEMI USB-Ifs, they never really
> "worked" neither with eibd/knxd nor ETS/HS, ... at least not in a stable
> manner for more than 2hrs or more than 8 tps..
>
The problem is, people do have these interfaces – and would like knxd to
work with them.

The least I can do is try to add a workaround for these instabilities.

> But if you really want to test, i'll grab them an send(?)
>
Please do.

-- 
-- Matthias Urlichs

**Comment by mpl1337** [comment]
> But if you really want to test, i'll grab them an send(?)
which one do you send?

i send him a BuschJaeger 6186 USB(the same as a ABB USB/S1.1)

**Comment by xxfuma85xx** [comment]
Hi all,

I've same/similar problem with the same interface.

knxd is on a raspberry pi connected via USB to ABB USB/S1.1.
I created file /etc/udev/rules.d/70-knxd.rules with this line: ACTION=="add", ATTRS{idVendor}=="147b", ATTRS{idProduct}=="5120", SYMLINK+="usbKNX0", OWNER="knxd"

knxd is launched with "-f9 -t1023 -e1.1.1 -E1.1.128:100 -c -R -S -B single -b usb:/dev/usbKNX0"

I can connect to devices on the bus via ETS and program devices.
I can write group address from the raspberry directly via groupswrite, from openhab server in the LAN and from ETS.
But I cannot receive response when reading a group address.

If I open busmonitor in a shell and vbusmonitor in another shell I can see all the bus traffic (from all physical devices wired on the bus) only in the busmonitor but nothing in the vbusmonitor.

For example I push a light button to turn on a light: on busmonitor I see
LPDU: BC 11 27 00 01 E1 00 81 14 :L_Data low from 1.1.39 _(button device)_ to 0/0/1 _**(light command group address)**_ hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
LPDU: CC :ACK
LPDU: BC 11 02 08 01 E1 00 81 39 :L_Data low from 1.1.2 _(switch actuator)_ to 1/0/1 _**(light state group address)**_ hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
On vbusmonitor nothing happens.

When I turn on the same light from openhab: on vbusmonitor I see
LPDU: BC 1F 0A 00 01 E1 00 81 37 :L_Data low from 1.1.129 (openhab) to 0/0/1 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
And on busmonitor I see 
LPDU: BC 11 02 08 01 E1 00 81 39 :L_Data low from 1.1.2 (switch actuator) to 1/0/1 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
LPDU: CC :ACK

But if I read the state of 1/0/1 from ETS I see on vbusmonitor 
LPDU: 9C 11 80 08 01 E1 00 00 1A :L_Data low from 1.1.128 to 1/0/1 hops: 06 T_DATA_XXX_REQ A_GroupValue_Read
And on busmonitor I see
LPDU: BC 11 02 08 01 E1 00 40 F8 :L_Data low from 1.1.2 to 1/0/1 hops: 06 T_DATA_XXX_REQ A_GroupValue_Response (small) 00
LPDU: CC :ACK
But the value is not forwarded to ETS neither to openhab.

Maybe my configuration can help mpl1337.

**Comment by smurfix** [comment]
I created file /etc/udev/rules.d/70-knxd.rules with this line: ACTION=="add", ATTRS{idVendor}=="147b", ATTRS{idProduct}=="5120", SYMLINK+="usbKNX0", OWNER="knxd"

**Comment by smurfix** [comment]
>  I created file /etc/udev/rules.d/70-knxd.rules with this line: ACTION=="add", ATTRS{idVendor}=="147b", ATTRS{idProduct}=="5120", SYMLINK+="usbKNX0", OWNER="knxd"

You cannot do "usb:/dev/usbKNX0". Symlinks are only useable for serial devices. Remove the symlink and use "-b usb:".

You also cannot use busmonitor and expect the interface to still work. Busmonitor grabs the interface, it's then dead for the rest of knxd. Just don't ever use the thing. Use the log to figure out what happens on which interface.

This will be improved in v0.14.

Please only use vbusmonitor, create a complete log testing first a group write and then a group read, and put that into a pastebin.

**Comment by xxfuma85xx** [comment]
I made those changes and now knxd service doesn't start with error:
knxd[691]: initialisation of backend 'usb:' failed: Permission denied

Why can I switch on and off the light from ETS or openhab when I'm using busmonitor if busmonitor detach the interface from knxd?

**Comment by xxfuma85xx** [comment]
I updated knxd from 0.12.6 to 0.12.14.
The problem persist. But I made some test with my previous configuration.

This is without the udev rule and knxd executed by root:
http://pastebin.com/AHSRLxsF

This is with the udev rule and knxd service start by systemd with user knxd and the same options:
http://pastebin.com/hwj5Jaxq

Before the line 
"Feb 28 16:53:11 raspberrypi knxd[647]: knxd: Layer 8 [ 7:systemd              185.222] New Connection" 
commands are sent via ETS3 connected in ROUTER mode and as you can see there are read and write commands without response logged.
The new connection line is about another shell on the raspberry where i launched the command:
knxtool busmonitor1 local:
as root user.
After that line I repeat the commands sent via ETS3 and, as you can see, there are responses logged but ETS never receive these responses.

It seems that knxd route only from IP to BUS (because if I write from ETS the light turn on and off) but doesn't listen on the BUS if I don't open a busmonitor.

TUNNEL or ROUTER mode doesn't make any difference.

**Comment by xxfuma85xx** [comment]
I forget to write that address 1.1.1 is knxd, 1.1.128 is ETS and 1.1.2-47 are my physical devices.

**Comment by smurfix** [comment]
Please stop using usb:/dev/usbwhatever. USB does not use device files. Your command line is exactly equivalent to "usb:" (I really need to teach that parser to return errors).
Also, "-B single" in front of the USB device does not make sense. This is a dumb bus interface, not a tunnel gateway which "helpfully" filters messages it doesn't know about.

Then, please use more intense logging (-t 0xfff) and re-submit the two pastebins. I need to understand what knxd is doing here and that requires looking at the byte-level data.

**Comment by snowdd1** [comment]
That's normal for standard knx USB devices (if you google that, you'll find a lot of discussions about that being the worst interface definition possible, but that's not the point here)

**Comment by snowdd1** [comment]
Does the knxd log end after the hid entry?

**Comment by xxfuma85xx** [comment]
Ok there was something wrong with bluetooth or wifi modules or something else...
Now the service start and communicate with USB but there is something strange:
http://pastebin.com/MXQt7cUv
After knxd start I try to turn on a light by button on KNX device and I can see the telegram in knxd log but physical address are all wrong.
Same telegram that should be read from the button above emulated with command:
knxtool on local: 0/0/1 and knxtool off local: 0/0/1
http://pastebin.com/K3YwFgJS

**Comment by xxfuma85xx** [comment]
This is a read of group address 1/0/1 from ETS3 on the bus:
http://pastebin.com/UPHnEu0Y
the group address 1/0/1 become 11.12.17 in the response from the log and the source address change every time.
http://pastebin.com/ZL66my3i

**Comment by snowdd1** [comment]
For smurfix to analyze your case you should tell
- what are the addresses (group addresses and physical addresses) you have expected?
- at which lines do you see the addresses you got in the pastbin logs?

**Comment by xxfuma85xx** [comment]
If in another shell I open a busmonitor1, group address and device address are ok but response on group read from ets aren't received.

busmonitor opened and button pressed to turn on and off the light: http://pastebin.com/zVhpqZYg
1.1.39 is my button (ABB 2CSYK1003)
1.1.2 is my switch actuator (ABB SA/S12.10.2.1)
0/0/1 is group address of actuator command on channel A
1/0/1 is group address of actuator state on channel A

busmonitor opened and ets read request for 1/0/1: http://pastebin.com/zJWfjZTK

busmonitor opened and knxtool groupreadresponse for 1/0/1: http://pastebin.com/LZWA91eP
(the command end without read the value of the response)

**Comment by snowdd1** [comment]
How is the ETS talking to the bus? Using the knxd or do you have another interface?

**Comment by snowdd1** [comment]
..and **busmonitor***X* is a no-go, as @smurfix wrote several times. I wish he would just remove that command from knxtool, it makes more people unhappy than it helps.

use **vbusmonitor1** instead, it doesn't block the interface.

**Comment by xxfuma85xx** [comment]
ETS connects to the bus via knxd with connection configured as KNXnet/IP Routing to the address 224.0.23.12 on port 3671.

Commands in sequence:
busmonitor1 closed
vbusmonitor1 opened
knxtool groupreadresponse local: 1/0/1
knxtool on local: 0/0/1
knxtool off local: 0/0/1
log: http://pastebin.com/TAS9sak0

I'm sorry if I used busmonitor1 but it's the only that let me read the bus correctly.

**Comment by xxfuma85xx** [comment]
It's time to buy a new interface...

**Comment by smurfix** [comment]
Either because sending still works despite the monitoring setup, or because the busmonitor command grabs the wrong interface. I have no idea without detailed logs.

In v0.14 any device will either be a monitor – unavailable for regular use – or not, but there'll be no runtime switching via "knxtool busmonitor"ish commands. For 0.12 if somebody wants to implement an "enable bus monitoring for this interface" command line argument, feel free.

**Comment by xxfuma85xx** [comment]
The problem was the interface. I bought the ABB IPS/S 3.1.1 and all works fine now.
