### ISSUE TITLE
Merge remaining patch branches (was: Delete outdated/obsolete branches)

### ISSUE THREAD

**Issue by dallmair** [knxd/knxd#205]
Not a code issue, but related to the project and repository: From my point of view it's currently harder to navigate the project and get a first overview (as a newbie) than necessary, especially because there's a list of branches that didn't have any changes for quite some time. Please delete the outdated, obsolete, and merged branches.

From my point of view in this category are:
* cplus
* debian
* fix-tpuart-duplicates
* knxnetip-core
* p166
* p171
* test
* test_no_dups
* usbtest
* v0.9

Since issue #117 has been closed deliberately without merging the proposed change, it seems that branch fix/knxd.conf is obsolete as well and can be deleted.

Besides that, some of the others look like they are obsolete as well while others still contain good ideas that should be merged or redone based on 0.12 -- maybe somebody with more insight into the project can make a call on these branches?
* compiler-warnings
* dpt-de/encode
* feature/merge_tpuart
* fixes-core/cemi-busmonitor-package
* ft12cemi
* next
* p156
* p188
* switch-to-cmake

**Comment by smurfix** [comment]
I cleaned up most of these. merge_tpuart and cemi-busmonitor-package should be -merged- ported to 0.12.

**Comment by smurfix** [comment]
OK, did it.

**Comment by smurfix** [comment]
I'm leaving the dpt-de/encode branch because the code might be useful, if only for reference.
However, nothing actually uses it, thus I'm not merging.

**Comment by dallmair** [comment]
Perfect, thanks for the quick response!
