### ISSUE TITLE
knxd stops working after 10 min

### ISSUE THREAD

**Issue by KNXnewbie** [knxd/knxd#211]
Hello,

i have installed knxd on my raspberry pi. All works fine but after 10 min (+/-1) it seems knxd stops working. The service and socket are still running:
![grafik](https://cloud.githubusercontent.com/assets/25402687/22396983/6ba05196-e566-11e6-9990-608f023b3914.png)
and the first groupswrite after 10 min has this failure and nothing happens:
![grafik](https://cloud.githubusercontent.com/assets/25402687/22397000/deb922de-e566-11e6-90b3-9a61f3a02391.png)

I start knxd with these parameters: -e 1.1.128 -E 1.1.5:10 -f -t1020 -u /tmp/eib -DTRS -b usb:1:4:1:0:0

What's wrong? Anybody an idea?

THX!

**Comment by smurfix** [comment]
This seems to occur because knxd thinks it's running out of addresses for clients. I'm investigating.

You can help by turning on logging (-t1022 as the first argument in KNXD_OPTS) and sending me the resulting log, preferably in a pastebin.

**Comment by KNXnewbie** [comment]
Hi,
thanks for your help!

I think you are right. At line 1910 (http://pastebin.com/5xpGiw6Z) is a message that shows that are no more addresses avaiable. What does it mean? Do i have to increase the range in the -E parameter?

**Comment by smurfix** [comment]
No, that means I need to figure out why knxd sometimes doesn't free the address.

I'll check the log.

**Comment by smurfix** [comment]
Should now be fixed. The problem is gateways that echo the packets you write to them.

If not, please re-open this bug and attach a pastebin with the current version's log.

**Comment by KNXnewbie** [comment]
Hi,
this behavior occurs without writing packets to the gateway (at least I do not trigger any commands to the gateway, but maybe the system himself). How can I extract the version's log?

THX
