### ISSUE TITLE
Baudrate bugs with ncn5120 in v0.12.8

### ISSUE THREAD

**Issue by bertouttier** [knxd/knxd#215]
Hi! I have some feedback when using the ncn5120 back-end in v0.12.8:

1. When you want to use the baudrate 38400 for ncn5120, you need to extend the switch-case in tpuartserial.cpp. Patch:
```
diff --git a/src/backend/tpuartserial.cpp b/src/backend/tpuartserial.cpp
index ea82ba9..eaf24f9 100644
--- a/src/backend/tpuartserial.cpp
+++ b/src/backend/tpuartserial.cpp
@@ -48,6 +48,8 @@ static speed_t getbaud(int baud) {
             return B9600;
         case 19200:
             return B19200;
+        case 38400:
+            return B38400;
         case 115200:
             return B115200;
         default:
```

2. The way that you set the default baudrate of the ncn5120 (by overriding the default_baudrate() function of TPUARTSerialLayer2Driver) is not correct if you call default_baudrate() in the constructor of your parent class TPUARTSerialLayer2Driver. The default baudrate returned  when constructing a NCN5120SerialLayer2Driver object will always be 19200 (and not 38400).

Could you please also remove the dependency on .git/index to configure? It's a pitty that people downloading a knxd project tarball (instead of cloning with git) cannot build properly due to this dependency.

Thanks!

**Comment by smurfix** [comment]
The current stable version should fix all of this.
Note that I have rewritten tpuart (and thus ncn5120) support quite extensively. I'll work through the data sheet and create a v0.12.10 version later.

**Comment by smurfix** [comment]
I found two more features … including one that says parity is optional. Fun. :-/

**Comment by JoeRu** [comment]
+1 

---
  CXX      ncn5120.o
In file included from ncn5120.cpp:23:0:
ncn5120.h:36:8: error: extra qualification ‘NCN5120SerialLayer2Driver::’ on member ‘setstate’ [-fpermissive]
   void NCN5120SerialLayer2Driver::setstate(enum TSTATE state);
        ^
In file included from ncn5120.h:24:0,
                 from ncn5120.cpp:23:
tpuartserial.h: In member function ‘virtual void NCN5120SerialLayer2Driver::setstate(TSTATE)’:
tpuartserial.h:36:8: error: ‘virtual void TPUARTSerialLayer2Driver::setstate(TSTATE)’ is private
   void setstate(enum TSTATE state);
        ^
ncn5120.cpp:66:47: error: within this context
   TPUARTSerialLayer2Driver::setstate(new_state);
                                               ^
ncn5120.cpp:66:48: error: expected ‘}’ at end of input
   TPUARTSerialLayer2Driver::setstate(new_state);
                                                ^
Makefile:452: recipe for target 'ncn5120.o' failed
make[4]: *** [ncn5120.o] Error 1
make[4]: Leaving directory '/home/pi/knxd/src/backend'
Makefile:385: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/pi/knxd/src'
Makefile:434: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/pi/knxd'
Makefile:369: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/pi/knxd'
dh_auto_build: make -j1 returned exit code 2
debian/rules:14: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: Fehler: Fehler-Exitstatus von debian/rules build war 2

**Comment by JoeRu** [comment]
at the moment master as well as stable break at this point when trying to compile it.

**Comment by smurfix** [comment]
Fixed. Sorry about that.

**Comment by smurfix** [comment]
v0.12.12 is supposed to work. ;-) Please re-test.

**Comment by smurfix** [comment]
No feedback; closed, presumed fixed. Please re-open as appropriate.
