### ISSUE TITLE
knxtool not working

### ISSUE THREAD

**Issue by phimic** [knxd/knxd#217]
I have a problem with the knxtool on knxd 0.12.6 on debian 8. I try to execute 

> knxtool busmonitor3 ip:localhost

 and just get `Open Busmonitor failed: Device or resource busy`

The same issue for all others knxtool applets e.g. vbusmonitor3. If i start knxd with logging i can see, that the usb interface is working and getting data from the bus:

```
root@openHABianPi:/home/pi/Download# knxd --trace=5 --error=5 --eibaddr=1.1.128 --client-addrs=1.1.129:1  -D -T -R -S -i --listen-local=/tmp/knx usb:1:4:1:0:0

knxd: Layer 0 [ 6:usb:1:4:1:0:0 25.222] RecvEMI(011): 29 00 BC E0 11 0F 0C 10 01 00 40
knxd: Layer 2 [ 6:usb:1:4:1:0:0 25.222] Recv L_Data low from 1.1.15 to 1/4/16 hops: 06 T_DATA_XXX_REQ A_GroupValue_Response (small) 00 

```

How i get the knxtool back working?

**Comment by smurfix** [comment]
Works here. Do you have another connected client? If you use --client-addrs=XXX:1 you only get one slot.

**Comment by phimic** [comment]
I start knxd now without the --client-addrs parameter and the knxtool now don't return any errors. But i did not get any data from the applets, i just get an empty response.

**Comment by smurfix** [comment]
Error handling in the clients isn't too good. Please use -E XXX:10 or however many clients you use (plus a couple of spares for vbusmonitor, groupwrite and such).

**Comment by phimic** [comment]
Thank you  @smurfix  for your fast response. If i start knxd with --client-addrs=XXX:10 i get still the error
`Open Busmonitor failed: Device or resource busy`

The trace of knxd returns:
```
[...]
nxd: Layer 2 [ 6:usb:1:4:1:0:0 16.494] Recv L_Data low from 1.1.9 to 1/4/5 hops: 06 T_DATA_XXX_REQ A_GroupValue_Read
knxd: Layer 2 [ 6:usb:1:4:1:0:0 16.518] Recv L_Data low from 1.1.57 to 1/4/5 hops: 06 T_DATA_XXX_REQ A_GroupValue_Response (small) 01 

knxd: Layer 2 [ 6:usb:1:4:1:0:0    25.721] CloseL2
knxd: Layer 2 [ 6:usb:1:4:1:0:0    25.721] (CEMILayer2)  OpenBusmon not implemented

```

**Comment by smurfix** [comment]
Don't use busmonitor. It is broken because it picks a random interface and detaches it from the rest of the system.

Use vbusmonitor.

I plan to add an option to mark the interface to be used for destructive bus monitoring (if any).

**Comment by phimic** [comment]
perfect, the knxtool applet vbusmonitor1 works as expected.
