### ISSUE TITLE
The connection doesn´t support the necessary layer

### ISSUE THREAD

**Issue by fohnbit** [knxd/knxd#223]
Hello,

I have knxd on a beaglebone running:
Version: 0.10.0

I install on a new beaglebone black:
Version: 0.12.3

with the new beaglebone, I can´t connect with the ETS4:
The connection doesn´t support the necessary layer

How can I made some tests? I hope I setup the tty connect correct. I use serial driver:
**_ps aux:_**
**/usr/bin/knxd -n knxd Gateway -e 1.1.200:10 -t 0 -D -T -R -S -c tpuarts:/dev/ttyS1**

**_root@bbb:/dev# ls ttyS1 -l_**
crw-rw---- 1 knxd knxd 4, 65 Feb 16 09:32 ttyS1

**_knxtool vbusmonitor1 ip:192.168.0.148_**
return nothing

Can I test the communication in the command line? To get all KNX telegrams to see if the serial device is working?

**Comment by fohnbit** [comment]
I setup a deeper log:
Feb 16 09:38:43 Layer 8 [ 6:systemd                     0.026] OpenSystemdSocket
Feb 16 09:38:43 Layer 8 [ 6:systemd                     0.026] SystemdSocket opened
Feb 16 09:38:43 Layer 3 [ 3:layer3                      0.026] registerLayer2 6:systemd
Feb 16 09:38:43 Layer 3 [ 3:layer3                      0.026] registerLayer2 6:systemd = 1
Feb 16 09:38:43 Layer 8 [ 7:systemd                     0.026] OpenSystemdSocket
Feb 16 09:38:43 Layer 8 [ 7:systemd                     0.026] SystemdSocket opened
Feb 16 09:38:43 Layer 3 [ 3:layer3                      0.026] registerLayer2 7:systemd
Feb 16 09:38:43 Layer 3 [ 3:layer3                      0.026] registerLayer2 7:systemd = 1
Feb 16 09:38:43 systemd[1]: Started KNX Daemon.
Feb 16 09:38:46 Layer 8 [ 2:mcast:domolink connect CO-1 2.861] SEARCH_REQ
Feb 16 09:38:51 Layer 8 [ 2:mcast:domolink connect CO-1 7.911] SEARCH_REQ
Feb 16 09:38:53 Layer 2 [ 5:tpuarts:/dev/ttyS1          10.001] Watchdog Reset(001): 01
Feb 16 09:38:56 Layer 8 [ 2:mcast:domolink connect CO-1 12.966] SEARCH_REQ
Feb 16 09:39:01 Layer 8 [ 2:mcast:domolink connect CO-1 18.022] SEARCH_REQ
Feb 16 09:39:05 Layer 3 [ 3:layer3                      21.594] Allocate: falling back to 1.1.200
Feb 16 09:39:05 Layer 8 [ 2:mcast:domolink connect CO-1 21.594] Tunnel CONNECTION_REQ with 0.0.0
Feb 16 09:39:05 Layer 8 [ 2:mcast:domolink connect CO-1 21.594] Tunnel CONNECTION_REQ, ignored, no free addresses
Feb 16 09:39:05 Layer 8 [ 2:mcast:domolink connect CO-1 21.595] CONNECTION_REQ: no free channel
Feb 16 09:39:10 Layer 8 [ 2:mcast:domolink connect CO-1 26.719] SEARCH_REQ
Feb 16 09:39:12 Layer 2 [ 5:tpuarts:/dev/ttyS1          28.922] Watchdog Status(001): 02
Feb 16 09:39:15 Layer 8 [ 2:mcast:domolink connect CO-1 31.799] SEARCH_REQ
Feb 16 09:39:20 Layer 8 [ 2:mcast:domolink connect CO-1 36.841] SEARCH_REQ
Feb 16 09:39:22 Layer 2 [ 5:tpuarts:/dev/ttyS1          38.922] Watchdog Reset(001): 01

What did it mean with: "no free channel" and "Watchdog Reset"?
Is there a communication problem with my serial device?

Thank you!

**Comment by snowdd1** [comment]
Please read https://github.com/knxd/knxd#migrating-to-012  
For clients to connect you need `-E <address:count>` like -E 0.0.2:10  
I am not convinced having a space in the name -n <name> is a good idea.

**Comment by fohnbit** [comment]
Hello,

well, I have Version 0.12.3
When I replace the -e to -E then I get:

Feb 16 11:14:17 systemd[1]: Starting KNX Daemon...
-- Subject: Unit knxd.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit knxd.service has begun starting up.
Feb 16 11:14:17 Layer 8 [ 2:mcast:domolink connect CO-1 0.002] Open
Feb 16 11:14:17 Layer 8 [ 2:mcast:domolink connect CO-1 0.006] OpenD
Feb 16 11:14:17 Layer 8 [ 2:mcast:domolink connect CO-1 0.016] OpenedD
Feb 16 11:14:17 Layer 8 [ 2:mcast:domolink connect CO-1 0.019] Opened
Feb 16 11:14:17 knxd requires a bus address (option -e)!: No such file or directory
Feb 16 11:14:17 knxd.service: Main process exited, code=exited, status=1/FAILURE
Feb 16 11:14:17 systemd[1]: Failed to start KNX Daemon.
-- Subject: Unit knxd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit knxd.service has failed.
--
-- The result is failed.
Feb 16 11:14:17 systemd[1]: knxd.service: Unit entered failed state.
Feb 16 11:14:17 systemd[1]: knxd.service: Failed with result 'exit-code'.

**Comment by fohnbit** [comment]
Hello,

thank you ... I change now to:
KNXD_OPTS="-n 'knxdGW' -e 1.1.200:10 -E 0.0.2:10 -t 0xffc -f 9 -D -T -R -S -c tpuarts:/dev/ttyS1"

now I can connect, but get no data (receive/send).

Can I check this in Linux? Maybe a busmonitor to proof if I receive KNX telegramms?
Maybe my Rs232 KNX Module has a fail.

Thank you!

**Comment by snowdd1** [comment]
sure, use `knxdtool grouplisten local:`  

Just to make sure: you don't have two knxd's with -R -S running at the same time?

**Comment by fohnbit** [comment]
Hello,

thank you for your help!
knxdtool: command not found

knxd's: you mean in the same network or on the same Linux controller?

**Comment by fohnbit** [comment]
Sorry, guess you mean knxtool:
root@gw:/home/gd# knxtool grouplisten local:
usage: grouplisten url eibaddr: Success

This means it has connected? All ok?

**Comment by tru7** [comment]
No. this means it has failed.
try this way (look at -e)
KNXD_OPTS="-n 'knxdGW' -e 1.1.200 -E 0.0.2:10 -t 0xffc -f 9 -D -T -R -S -c tpuarts:/dev/ttyS1"

**Comment by snowdd1** [comment]
Sorry for the typo.  
Do you start knxd via systemd? Then you could see the status with `systemctl status knxd`, it also prints the last lines from the `journald`

**Comment by fohnbit** [comment]
root@foxc0a80094:/home/gedomo# systemctl status knxd
● knxd.service - KNX Daemon
   Loaded: loaded (/lib/systemd/system/knxd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2017-02-16 12:24:48 CET; 1h 15min ago
 Main PID: 1582 (knxd)
   CGroup: /system.slice/knxd.service
           └─1582 /usr/bin/knxd -n knxdGW -e 1.1.200:10 -E 1.1.210:10 -t 0xffc -f 9 -D -T -R -S -c tpuarts:/dev/ttyS1

Feb 16 13:38:04 Layer 8 [ 8:mcast:knxdGW:1.1.210 4396.759] CONNECTIONSTATE_REQUEST on 1
Feb 16 13:38:19 Layer 8 [ 8:mcast:knxdGW:1.1.210 4411.761] CONNECTIONSTATE_REQUEST on 1
Feb 16 13:38:34 Layer 8 [ 8:mcast:knxdGW:1.1.210 4426.762] CONNECTIONSTATE_REQUEST on 1
Feb 16 13:38:49 Layer 8 [ 8:mcast:knxdGW:1.1.210 4441.765] CONNECTIONSTATE_REQUEST on 1
Feb 16 13:39:04 Layer 8 [ 8:mcast:knxdGW:1.1.210 4456.767] CONNECTIONSTATE_REQUEST on 1
Feb 16 13:39:10 Layer 2 [ 5:tpuarts:/dev/ttyS1   4461.986] Watchdog Status(001): 02
Feb 16 13:39:19 Layer 8 [ 8:mcast:knxdGW:1.1.210 4471.769] CONNECTIONSTATE_REQUEST on 1
Feb 16 13:39:21 Layer 2 [ 5:tpuarts:/dev/ttyS1   4473.033] Watchdog Status(001): 02
Feb 16 13:39:34 Layer 8 [ 8:mcast:knxdGW:1.1.210 4486.771] CONNECTIONSTATE_REQUEST on 1
Feb 16 13:39:49 Layer 8 [ 8:mcast:knxdGW:1.1.210 4501.773] CONNECTIONSTATE_REQUEST on 1

**Comment by snowdd1** [comment]
... and I completely mixed up the syntax. The better test is using the vbusmonitor1  
`knxtool vbusmonitor local:` or `knxtool vbusmonitor ip:localhost` on the same machine as the knxd is supposed to be running.

**Comment by fohnbit** [comment]
Hello,

again thank you for our help:
knxtool vbusmonitor1 local:
show nothing.

Maybe my KNX module has a problem ... not sure.

**Comment by tru7** [comment]
you still use the wrong syntax on -e

**Comment by fohnbit** [comment]
Hello,

can you please tell me, what is wrong?

Thank you!

**Comment by fohnbit** [comment]
Hello,

ok, this is correct?:
KNXD_OPTS="-n 'knxdGW' -e 1.1.200 -E 1.1.210:10 -t 0xffc -f 9 -D -T -R -S -c tpuarts:/dev/ttyS1"

It doesn´t solve my problem

**Comment by tru7** [comment]
too bad. Please also add a "-b" before the interface definition. With this you should have a valid command:
KNXD_OPTS="-n 'knxdGW' -e 1.1.200 -E 1.1.210:10 -t 0xffc -f 9 -D -T -R -S -c -b tpuarts:/dev/ttyS1"
Just make sure the addresses match your local situation. Hope this helps.

**Comment by fohnbit** [comment]
Thank you ... I added, but same problem ... no KNX data.
I guess my RS232 module has a problem.

Need to replace and test again.

Thank you!

**Comment by smurfix** [comment]
> knxtool grouplisten local:
> usage: grouplisten url eibaddr: Success
> 
> This means it has connected?

No, this means (a) knxtool's error messages are crap and need to be improved, (b) so do its command names. You probably want vbusmonitor1, not grouplisten.

Yes there are some strange problems with interfaces. One common problem is that it doesn't have a KNX bus signal, the other is that a getty or similar process also listens on it. Please use "-t 0xfff" in front of the "-b tpuarts:…", and "lsof /dev/ttyS1" to check if knxd is the only process that holds it.

**Comment by fohnbit** [comment]
Good morning,

I replaced the KNX module ... now I get some data in the log:
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   42.777] Read(001): 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   42.777] unknown 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   42.783] Read(001): 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   42.783] unknown 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   42.785] Read(001): 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   42.785] unknown 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   42.788] Read(002): FE 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   42.788] unknown FE
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   42.788] unknown 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   42.789] Read(001): 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   42.789] unknown 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   42.792] Read(002): E3 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   42.792] unknown E3
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   42.792] unknown 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   42.795] Read(003): 80 0D 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   42.796] unknown 80
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   42.796] unknown 0D
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   42.796] unknown 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   42.797] Read(001): 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   42.798] unknown 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   43.331] Read(002): BC 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   43.334] Read(001): 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   43.338] Read(004): 2F 01 E3 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   43.338] SendAck 11
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   43.340] Read(001): 80
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   43.342] Read(002): 01 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 0 [ 5:tpuarts:/dev/ttyS1   43.343] Read(001): 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 1 [ 5:tpuarts:/dev/ttyS1   43.343] RecvLP(011): BC 00 00 2F 01 E3 00 80 01 00 00
Feb 17 07:42:46 knxd[1784]: knxdGW: Layer 1 [ 5:tpuarts:/dev/ttyS1   43.343] dropping packet: type 1 0, valid 21992

But I get no data in the ETS4

Thank you!

**Comment by fohnbit** [comment]
Here are again alle settings:
KNX Module is the Weinzierl KNX TinySerial Interface 810

`root@:/home/knxgw# ps aux | grep knxd
knxd      1926  0.1  0.5   5304  2828 ?        Ss   07:53   0:00 /usr/bin/knxd -n knxdGW -e 1.1.200 -E 1.1.210:10 -f 9 -D -T -R -S -c -t 0xfff -b tpuarts:/dev/ttyO1`

`root@:/home/knxgw# ls -ahl /dev/ttyS1
crw-rw---- 1 knxd dialout 4, 65 Feb 17 07:58 /dev/ttyS1`

`root@:/home/knxgw# lsof /dev/ttyS1
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF  NODE NAME
knxd    1926 knxd    8u   CHR   4,65      0t0 12416 /dev/ttyS1`
`

**Comment by snowdd1** [comment]
If you make the \` to three \`\`\` then one could even read it!

**Comment by snowdd1** [comment]
Did you notice that the tty is different?

**Comment by fohnbit** [comment]
Hello,

ups, sorry. I updated the posting. ttyO1 was a symlink and just tested both

**Comment by fohnbit** [comment]
I plug the KNX module now on the older controller with knxd 0.10 .. it work fine
When I connect it to the new controller (newer Linux and knxd 0.12) I get no KNX communication.

**Comment by smurfix** [comment]
Exactly which knxd version are you using (-V)?

**Comment by fohnbit** [comment]
On new controller:
knxd 0.12.3

On old controller:
knxd 0.10.0

**Comment by smurfix** [comment]
Your log is not complete, please place the whole thing into a pastebin.

**Comment by smurfix** [comment]
Please update to latest 0.12. This bug should already be fixed.

**Comment by fohnbit** [comment]
cool, thank you .. I updated to 0.12.12 .. now all is working.

Thank you!
