### ISSUE TITLE
libfmt: don't know how to get that on Ubuntu

### ISSUE THREAD

**Issue by tru7** [knxd/knxd#224]
I'm on Ubuntu 16.04 and don't know how to get support for libfmt. Cannot find a package for it. Is this really something you can rely on in a common development environment?

**Comment by bmxp** [comment]
Seems as if Ubuntu 17 is the first to provide libfmt3-dev, see at http://packages.ubuntu.com/zesty/libfmt3-dev

**Comment by smurfix** [comment]
Meh. Apparently not. But it's on github and not a dynamic library anyway, so I should probably add it as a submodule and use that on older systems.

Using a std::string is no fun if you need to remember to add .c_str() anywhere you use it during logging, with no type safety and a random memory dump instead of a string in the log when you forget; besides that kind of thing doesn't help with code readability.

The alternate solutions I've found are strictly worse.

**Comment by tru7** [comment]
Well I can somewhat understand your situation but basically anyone has to build that libfmt3-dev himself as stable linux releases don't have that package, neither Ubuntu nor Debian.
I have built and installed it in /usr/local. Configure now works but make failes to find it. I have to check that further.

**Comment by tru7** [comment]
Now Travis fails on the same reason.
I can't make it run with the locally installed libfmt. First I had to preset LIBUSB_CFLAGS as '-I/usr/include/libusb-1.0 -I/usr/local/include/fmt' because global CFLAGS is not honoured. But now I get tons of complaints like this: /usr/include/c++/5/bits/cpp_type_traits.h:72:3: error: template with C linkage

**Comment by smurfix** [comment]
Please use the stable branch. Master isn't working right now anyway.

**Comment by tru7** [comment]
No problem, this is just to keep up with your outstanding work. For production I use stable of course.

**Comment by tobnukem** [comment]
How can I build libfmt on Raspbian Jessie?

**Comment by tru7** [comment]
I did on Ubuntu like this:
git clone https://github.com/fmtlib/fmt.git
cd fmt
cmake CMakeLists.txt
make
sudo make install

**Comment by tru7** [comment]
good move: with the recent commits fmtlib builds fine locally and make runs successfully

**Comment by Robert46** [comment]
a bit late but it seems I just ran into this issue on a Raspberry Pi3. Added the -d option to make dpkg-builpackage run and indeed, it automatically checked out libfmt. But it did not work. Why? It could donwload libfmt but it could not build! Cmake was also missing.
So, delete libfmt again, install cmake and retried. It worked like a charm!
Nice work, Smurfix, thank you!

**Comment by smurfix** [comment]
@Robert46  Adding `-d` to dpkg-builpackage call is seldom a good idea. Why didn't you install libfmt3-dev like it told you to? Current Debian or Ubuntu have that package.

**Comment by Robert46** [comment]
Hm, I believe I have read, seems in a different post, that you would automatically download and install libfmt if it can't be found. And really, it does, but only with -d.

**Comment by smurfix** [comment]
Yes it does, but it's still a sub-optimal solution. I generally advise against ever running dpkg-buildpackage with `-d` …
