### ISSUE TITLE
Installing on Raspberry PI 3 with Ubuntu Mate 16.04

### ISSUE THREAD

**Issue by Monkda** [knxd/knxd#225]
Hi,

I have a new Ubuntu Mate 16.04 on a Rasperry Pi 3 and I get the following error:

/usr/include/fmt/format.h:1123:3: error: ‘fmt::internal::MakeValue<Formatter>::MakeValue(T*) [with T = unsigned char; Formatter = fmt::BasicFormatter<char>]’ is private
   MakeValue(T *value);
   ^
/usr/include/fmt/format.h:2076:38: error: within this context
     return MakeValue<Formatter>(value);
                                      ^
cc1plus: warning: unrecognized command line option ‘-Wno-subobject-linkage’
Makefile:465: recipe for target 'tpuart.o' failed
make[4]: *** [tpuart.o] Error 1
make[4]: Leaving directory '/home/monkey/Downloads/knxd/src/backend'
Makefile:397: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/monkey/Downloads/knxd/src'
Makefile:445: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/monkey/Downloads/knxd'
Makefile:381: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/monkey/Downloads/knxd'
dh_auto_build: make -j1 returned exit code 2
debian/rules:14: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

Can anybody help me?

**Comment by tru7** [comment]
Probably similar to #224. Just go for stable branch (git checkout stable) if you just need a running knxd

**Comment by tru7** [comment]
I personally wonder where you got your /usr/include/fmt/format.h from because it's not part of standard Ubuntu 16.04. What does "dpkg -S /usr/include/fmt/format.h" tell you? Thank you.

**Comment by smurfix** [comment]
Please use the stable branch.
