### ISSUE TITLE
ETS5 does not program completely through KNXD

### ISSUE THREAD

**Issue by Mforcen** [knxd/knxd#227]
When you try to program a device, ETS5 asks you to press the program button, but, once pressed, ETS does not start the programming process.
Any advice to that?

**Comment by bmxp** [comment]
No, unless you can provide more about which version you are using, which interface, which settings, ...

**Comment by Mforcen** [comment]
Sorry for that. I'm using ETS5.5.3 Build 871.
I have a Raspberry Pi 2 with uname -a output like this:
Linux raspberrypi 4.4.49-v7+ #968 SMP Fri Feb 17 14:22:28 GMT 2017 armv7l GNU/Linux
I have installed knxd from git. Version command reports this:
knxd 0.12.13-2
Execution parameters for knxd are the following:
knxd --eibaddr=1.1.128 --client-addrs=1.1.129:1 -d -DTRS -i --listen-local=/tmp/knx -B single -b ft12:/dev/ttyAMA0
I have a BCU device attached to serial port.
I'm able to see telegrams in bus monitor, but I can't program devices.
Any ideas?

**Comment by smurfix** [comment]
Probably best to start with packet tracing on the interface, "-t 1022" in front of the "-b ft12:".

**Comment by Mforcen** [comment]
The output is that:
`knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 0.001] Open
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 0.002] Opened
knxd: Layer 2 [ 6:ft12:/dev/ttyAMA0 0.002] Open
knxd: Layer 2 [ 6:ft12:/dev/ttyAMA0 0.003] Opened
knxd: Layer 2 [ 6:ft12:/dev/ttyAMA0 0.003] OpenL2
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 0.003] SendReset
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 0.004] Send(007): A9 1E 12 34 56 78 9A
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 0.004] Send(007): A9 00 18 34 56 78 0A
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 4.990] RecvEMI(009): 29 BC 11 02 0B 1B E1 00 81
knxd: Layer 2 [ 6:ft12:/dev/ttyAMA0 4.990] Recv L_Data low from 1.1.2 to 1/3/27 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
knxd: Layer 9 [ 6:ft12:/dev/ttyAMA0 4.990] Queue L_Data low from 1.1.2 to 1/3/27 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 5.224] RecvEMI(009): 29 BC 11 02 0B 1B E1 00 80
knxd: Layer 2 [ 6:ft12:/dev/ttyAMA0 5.224] Recv L_Data low from 1.1.2 to 1/3/27 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 00
knxd: Layer 9 [ 6:ft12:/dev/ttyAMA0 5.224] Queue L_Data low from 1.1.2 to 1/3/27 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 00
knxd: Layer 8 [ 6:ft12:/dev/ttyAMA0 5.224] found addr 1.1.2
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 5.463] RecvEMI(009): 29 BC 11 02 0B 1B E1 00 81
knxd: Layer 2 [ 6:ft12:/dev/ttyAMA0 5.463] Recv L_Data low from 1.1.2 to 1/3/27 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
knxd: Layer 9 [ 6:ft12:/dev/ttyAMA0 5.463] Queue L_Data low from 1.1.2 to 1/3/27 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
knxd: Layer 8 [ 6:ft12:/dev/ttyAMA0 5.463] found addr 1.1.2
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 5.589] RecvEMI(009): 29 BC 11 02 0B 1B E1 00 80
knxd: Layer 2 [ 6:ft12:/dev/ttyAMA0 5.589] Recv L_Data low from 1.1.2 to 1/3/27 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 00
knxd: Layer 9 [ 6:ft12:/dev/ttyAMA0 5.590] Queue L_Data low from 1.1.2 to 1/3/27 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 00
knxd: Layer 8 [ 6:ft12:/dev/ttyAMA0 5.590] found addr 1.1.2
knxd: Layer 2 [ 6:ft12:/dev/ttyAMA0 30.643] Send L_Data system from 0.0.2 to 1.1.2 hops: 05 T_CONNECT_REQ
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 30.643] Send L_Data system from 0.0.2 to 1.1.2 hops: 05 T_CONNECT_REQ
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 30.643] Send(008): 11 00 00 00 11 02 50 80
knxd: Layer 2 [ 6:ft12:/dev/ttyAMA0 30.662] Send L_Data system from 0.0.2 to 0/0/0 hops: 05 T_DATA_XXX_REQ A_IndividualAddress_Read
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 30.663] Send L_Data system from 0.0.2 to 0/0/0 hops: 05 T_DATA_XXX_REQ A_IndividualAddress_Read
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 30.663] Send(009): 11 00 00 00 00 00 D1 01 00
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 30.681] RecvEMI(008): 2E B0 FF FF 11 02 50 80
knxd: Layer 2 [ 6:ft12:/dev/ttyAMA0 30.683] Send L_Data system from 0.0.2 to 1.1.2 hops: 05 T_DATA_CONNECTED_REQ serno:00 A_DeviceDescriptor_Read Type:00
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 30.684] Send L_Data system from 0.0.2 to 1.1.2 hops: 05 T_DATA_CONNECTED_REQ serno:00 A_DeviceDescriptor_Read Type:00
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 30.685] Send(009): 11 00 00 00 11 02 51 43 00
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 30.706] RecvEMI(009): 2E B0 FF FF 00 00 D1 01 00
knxd: Layer 2 [ 6:ft12:/dev/ttyAMA0 33.659] Send L_Data system from 0.0.2 to 0/0/0 hops: 05 T_DATA_XXX_REQ A_IndividualAddress_Read
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 33.659] Send L_Data system from 0.0.2 to 0/0/0 hops: 05 T_DATA_XXX_REQ A_IndividualAddress_Read
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 33.659] Send(009): 11 00 00 00 00 00 D1 01 00
knxd: Layer 2 [ 6:ft12:/dev/ttyAMA0 36.670] Send L_Data system from 0.0.2 to 0/0/0 hops: 05 T_DATA_XXX_REQ A_IndividualAddress_Read
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 36.670] Send L_Data system from 0.0.2 to 0/0/0 hops: 05 T_DATA_XXX_REQ A_IndividualAddress_Read
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 36.670] Send(009): 11 00 00 00 00 00 D1 01 00
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 36.959] RecvEMI(008): 29 B0 11 02 FF FF 60 81
knxd: Layer 2 [ 6:ft12:/dev/ttyAMA0 36.959] Recv L_Data system from 1.1.2 to 15.15.255 hops: 06 T_DISCONNECT_REQ
knxd: Layer 9 [ 6:ft12:/dev/ttyAMA0 36.960] Queue L_Data system from 1.1.2 to 15.15.255 hops: 06 T_DISCONNECT_REQ
knxd: Layer 8 [ 6:ft12:/dev/ttyAMA0 36.960] found addr 1.1.2
knxd: Layer 2 [ 6:ft12:/dev/ttyAMA0 39.681] Send L_Data system from 0.0.2 to 0/0/0 hops: 05 T_DATA_XXX_REQ A_IndividualAddress_Read
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 39.682] Send L_Data system from 0.0.2 to 0/0/0 hops: 05 T_DATA_XXX_REQ A_IndividualAddress_Read
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 39.682] Send(009): 11 00 00 00 00 00 D1 01 00
knxd: Layer 2 [ 6:ft12:/dev/ttyAMA0 42.692] Send L_Data system from 0.0.2 to 0/0/0 hops: 05 T_DATA_XXX_REQ A_IndividualAddress_Read
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 42.693] Send L_Data system from 0.0.2 to 0/0/0 hops: 05 T_DATA_XXX_REQ A_IndividualAddress_Read
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 42.693] Send(009): 11 00 00 00 00 00 D1 01 00
knxd: Layer 2 [ 6:ft12:/dev/ttyAMA0 45.703] Send L_Data system from 0.0.2 to 0/0/0 hops: 05 T_DATA_XXX_REQ A_IndividualAddress_Read
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 45.703] Send L_Data system from 0.0.2 to 0/0/0 hops: 05 T_DATA_XXX_REQ A_IndividualAddress_Read
knxd: Layer 1 [ 6:ft12:/dev/ttyAMA0 45.703] Send(009): 11 00 00 00 00 00 D1 01 00`

At the begining I have pressed some buttons on the bus, I initialized the bus monitor, but programming does not start.
Any ideas?

**Comment by bmxp** [comment]
Could you please use three times ` ` ` around your code? This is quite unreadable ...

**Comment by Mforcen** [comment]
Sorry for that. I'm not accomodated with this ^^''

**Comment by tru7** [comment]
You may need more than one address for -E. What happens if you set :10 for example?

**Comment by smurfix** [comment]
Hmm. Looks like `EMI_Common::on_recv_cb` doesn't forward the packet. Can you check with gdb why that is?

**Comment by smurfix** [comment]
I can walk you through the necessary steps if you'd like …

**Comment by chefkoch009** [comment]
Tried programming Gira Switching actuator with ETS5.
`#  knxd -t 1023 -f9 -e1.1.155 -E1.1.156:8 -n test -DTRS -i -c  tpuarts:/dev/ttyKNX1`
failed with:
`knxd: tpuart.cpp:123: virtual void TPUART_Base::send_L_Data(LDataPtr): Assertion `out.size() == 0' failed.`

and 

[programmierfehler.zip](https://github.com/knxd/knxd/files/882225/programmierfehler.zip)

**Comment by smurfix** [comment]
*Sigh*.

Again: Please repeat with `-B log -b tpuarts:…`

**Comment by chefkoch009** [comment]
With the build  73175ca from yesterday .

There is some strange behavior:
1.1) ETS5 startet and opened "interface configuration dialog"
1.2) start knxd with your suggested params:
` knxd -t1023 -f9 -e1.1.155 -t 1023 -E1.1.156:8 -D -T -R -S -i -c -B log -b tpuarts:/dev/ttyKNX1`
In ETS5 the interface is shown as 
![ets5-schnittstellen](https://cloud.githubusercontent.com/assets/20514664/24539676/e3497a74-15ef-11e7-84ff-c904f9572f09.PNG)
suddenly the knxd breaks down with:
![knxd-error-ets5-with interface-config-dialog](https://cloud.githubusercontent.com/assets/20514664/24539794/6b61f238-15f0-11e7-8146-623c0e61f5a1.PNG)

2.2) ETS5 closed
2.2) same startup parameter
2.3) starting ETS and changing to interface parameter dialog:
![knxd-error-ets5-with reopened ets5](https://cloud.githubusercontent.com/assets/20514664/24539992/775d7d9a-15f1-11e7-96ad-3effc442dd96.PNG)

Tell me, what for informations you further need for debugging.

**Comment by smurfix** [comment]
Thanks. Should be better now.

**Comment by chefkoch009** [comment]
thanks for fast response. even building package and testing....could take a while.

**Comment by chefkoch009** [comment]
Same startup parameters.
The interface is recognized correctly and available. This works.
Then I tried to get KNX-device informations and i get this:
from GroupMonitor:
![knxd-error-ets5-get-deviceinfo](https://cloud.githubusercontent.com/assets/20514664/24542307/6eef0516-15fb-11e7-89e2-fc55bccc67ad.PNG)
and this from ETS5 History:
![knxd-error-ets5-get-deviceinfo-errmsg](https://cloud.githubusercontent.com/assets/20514664/24542341/9470b6ae-15fb-11e7-872f-48a07b70d456.PNG)

the log fom knxd:
![knxd-error-get-deviceinfo](https://cloud.githubusercontent.com/assets/20514664/24542449/f59d651c-15fb-11e7-8da1-a32ec4dc09fe.PNG)

**Comment by chefkoch009** [comment]
same behavior with 8701889.

**Comment by smurfix** [comment]
Meh.
Please retry with current 06b6f55. I haven't found the root cause yet but the debug code in there should catch it earlier.

**Comment by chefkoch009** [comment]
I build the package, installed it and tested it. Looks good. My setup at the moment: ETS5 =>WLAN=>VPN=>LAN=>knxd-box. 
Readout deviceinformations works. Programming devices also works! Busmonitor traffic looks also good.

Great job!!  I'll test it tomorrow from LAN directly.

But I don't understand the -E option. And why I'm not able to use the loopback (127.0.0.1)?

**Comment by smurfix** [comment]
knxd has a physical address which it uses for itself. Clients like ETS require separate physical addresses, so you use -E to specify a block from which to allocate them. Previously (pre-0.12) knxd used its own address, but it then had to guess which client gets the replies from a device. That was unreliable and caused problems.

What do you want to do with the loopback? config example please.

**Comment by chefkoch009** [comment]
If I want to use a visu on the same machine. Then i don't need  to open the ports on LAN side.

**Comment by smurfix** [comment]
There are three solutions.
* tell the visu's back-end to use /run/knxd instead of TCP
* firewall the port off. Using "-d !lo" on the INPUT rule ignores the loopback packets.
* modify src/libserver/inetserver.cpp to accept an address to bind to. Call the config parameter "bind-address". How to resolve an address can be seen in src/backend/eibnettunnel.cpp. Send me a patch when you're done.

Obviously I'd prefer the third solution ;-)

**Comment by chefkoch009** [comment]
This thread can be closed. Last statements are offtopic.

**Comment by lklic** [comment]
can someone confirm that ETS5 programming should function using ft12cemi?

I have a kBerry 838 attached to a rPi3, and I am able to send commands with openHab, but cannot program through ETS5. The interface is discovered, I can see packets on the bus, I am able to connect, but responses are not coming back to ETS5 (I am not able to read any device, but again I can see packets on the bus when monitoring).

My config:
 KNXD_OPTIONS=”–eibaddr=1.1.128 –client-addrs=1.1.129:8 -d -D -T -R -S -i –listen-local=/tmp/knx -b ft12cemi:/dev/ttyAMA0″

Installed as per michls tech blog:
https://michlstechblog.info/blog/raspberry-pi-eibknx-ip-gateway-and-router-with-knxd/

**Comment by soeffi** [comment]
@lklic and @cfopen:
Is some time now since you reported the issues with the Weinzierl interface. Did you have any success solving that issue? It seems that the behaviour you observed is also described in this ticket: https://github.com/knxd/knxd/issues/296#

- Stefan

**Comment by lklic** [comment]
I never got this working after days of trying. I gave up and bought an IP router. Since KNXD also acts as a router the kberry interface was rebroadcasting all of the packets on the bus and so I couldn't do any programming with it connected. I ended up pulling the kberry altogether as it was causing more problems than it was solving.

**Comment by ersingencturk** [comment]
same here like all others, diagnostics work but programming with ets doesn't. has anyone ever was able to program through knxd ? if so what was your parameters ?

**Comment by onenils** [comment]
I finally got it to work! The trick is to add a "-A address=15.15.255 -B single". My complete KNXD_OPTS line looks as following:
`KNXD_OPTS="-e 1.1.1 -E 1.1.2:3 -u /tmp/eib -D -T -R -S -B log -B log -A address=15.15.255 -B single -b ft12cemi:/dev/ttyAMA0"`

Now the programming via ETS5 works.

**Comment by lklic** [comment]
@onenils what device are you using to connect to the KNX bus, and what hardware are you running this on?

**Comment by smurfix** [comment]
Huh. 15.15.255 is the "programming wildcard" address. knxd will not filter it, and so will most other adapters. Something is not quite right with your adapter if forcing this address helps.

NB, this assumes that you're using the latest knxd. I fixed a couple of programming-related bugs lately; with earlier versions this hack might have been required, but no longer.

**Comment by fcaspelherr** [comment]
I had problems using the ETS5 for programming (application and physical address) in combination with the Weinzierl 838 kBerry interface on an RPI3 and knxd but got it working with the following KNXD_OPTS:
"-e 1.1.240 -E 1.1.241:4 -u/tmp/eib -B log -A address=15.15.255 -B single -b ft12cemi:/dev/ttyAMA0 -D -B log -T -B pace -R -S -c"

(found at: https://knx-user-forum.de/forum/projektforen/knxd/1070372-weinzierl-knx-baos-module-838-kberry/page17)

But when I now tried  to setup a new MDT SCN-G360D3.03 it didn't work.
It always stops when trying to assign the physical address of a new device for the first time..

I found a possibility to get it working:
1. I started the knxd without "-A address=15.15.255 -B single", so basically using following opts: 
"-e 1.1.240 -E 1.1.241:4 -u/tmp/eib -B log -B single -b ft12cemi:/dev/ttyAMA0 -D -B log -T -B pace -R -S -c"
2. I used ETS5 to assign the physical address -> It may show an error, but the device got the address. At this point I was not able to transfer the application programm, but the address worked..
3. I stopped and started the knxd again with "-A address...": 
"-e 1.1.240 -E 1.1.241:4 -u/tmp/eib -B log -A address=15.15.255 -B single -b ft12cemi:/dev/ttyAMA0 -D -B log -T -B pace -R -S -c"  
4 Now I can use ETS5 to change the application.

-> It seems like ETS needs opts ""-A address=15.15.255 -B single" for transfer of applcation data and it shouldn't have these for the first assignment of the physical address.

Since I only have one new device here I am not able to reproduce the behaviour mentioned above for other new ones.

**Comment by lklic** [comment]
@fcaspelherr what version of Knxd are you running?

**Comment by fcaspelherr** [comment]
> @fcaspelherr what version of Knxd are you running?

sorry I forgot to mention that info.., I updated my original post in order to have everything at one place..
I am using knxd version 0.14.35:fc9ba78

**Comment by smurfix** [comment]
This bug should be long fixed. Please use the current version and re-open if this persists.
NB, 15.15.255 is NEVER a good address to force.

**Comment by fcaspelherr** [comment]
> This bug should be long fixed. Please use the current version and re-open if this persists.
> NB, 15.15.255 is NEVER a good address to force.

I'm sorry, but isn't version 0.14.35 the latest one one the deb branch?

You say its not a god idea to force the adress 15.15.255 but for me (and same for onenils) it seems to be the only possibility to get the combination of knxd, weinzierl 838 and ETS5 working...

**Comment by smurfix** [comment]
That's because the branch is named "debian" these days.

I'll push to "deb" also for now, thanks.

**Comment by TravisWilder** [comment]
Hi

fyi .. I used the knxd from openhabian and also the most recent self compiled.
with devices tpuarts:/dev/ttyAMA0 and ft12cemi:/dev/ttyAMA0
with both HW and KnxD Versions I was not able to get the ETS Programming working.
The Trick was to add -A address=15.15.255 -B single then it worked 

Thanks fcaspelherr

**Comment by flowztul** [comment]
Can confirm, was also fighting with knxd and ETS, and that addition solved the issue. My current working command line args are:
```
KNXD_OPTS="--eibaddr=1.0.240 --client-addrs=1.0.241:8  --listen-local=/tmp/eib --filter=log --arg=address=15.15.255 --filter=single --layer2=ft12cemi:/dev/ttyAMA0 --Discovery --filter=log --Tunnelling --filter=pace --Routing --Server --GroupCache"
```

`knxd` was compiled from the debian branch of the repo today:
```
# dpkg -l | grep knxd
ii  knxd                             0.14.51-1                          arm64        daemon to access the KNX bus
```
