### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by besitzer** [knxd/knxd#228]
After fixing all dependencies I receive this error message while compiling the files with this command dpkg-buildpackage -b -uc:

+ knxd -e 1.2.3 --stop-right-now
+ knxd -e 1.2.3 --stop-right-now -b dummy:
+ knxd -e 1.2.3 --stop-right-now -b dummy: -b dummy:
+ echo 'Bad argument C'
Bad argument C
+ cat /tmp/fileMkudyS
could not exec knxd_args helper: No such file or directory
E00000055: There is no KNX addr= in section 'main'.
F00000000: Error setting up the KNX router.
+ exit 1
debian/rules:48: die Regel für Ziel „override_dh_auto_test“ scheiterte
make[1]: *** [override_dh_auto_test] Fehler 1
make[1]: Verzeichnis „/home/sven/knxd“ wird verlassen
debian/rules:14: die Regel für Ziel „build“ scheiterte
make: *** [build] Fehler 2
dpkg-buildpackage: Fehler: Fehler-Exitstatus von debian/rules build war 2

What can I do?

Rgards Sven

**Comment by smurfix** [comment]
The master branch does not work yet, as I'm busy rewriting it for config file support.
 You should use the "stable" branch instead. See the README.
