### ISSUE TITLE
KNXD does not route above group address 15/x/xxx

### ISSUE THREAD

**Issue by tss68nl** [knxd/knxd#229]
As simple as that: above group-address 15/x/xxx, nothing comes in from the KNX bus. However, commands emitted for 16/0/0 and higher (to 31/x/xxx) do actually get emitted to the bus.

The 16 to 31 range is normally used by units that come pre-programmed / are automated. However, there is no reason not to relay these messages I think as they are part of the KNX protocol.

**Comment by smurfix** [comment]
"knxd" certainly can do that and there's nothing in the code that prevents routing these packets. Probably your adapter doesn't? Which version did you test, and how?

`Layer 0 [ 5:log     24.176] Send L_Data low from 3.3.4 to 16/3/4 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write (small) 05 
`

**Comment by tss68nl** [comment]
The author of homebridge-knx has tracked it down to KNXD: https://github.com/snowdd1/homebridge-knx/issues/40

It seems to be in decoding the message that uses the restricted address range.  Because the busmonitor does actually show the data. (I just downloaded the new KNXD 0.12 and verified it still does the same).

**Comment by snowdd1** [comment]
Being quoted here: that was the node-eibd package and has been fixed some weeks ago. It never had anything to do with knxd.

**Comment by smurfix** [comment]
Thanks.
