### ISSUE TITLE
Compiling fails - APDUPtr does not name a type

### ISSUE THREAD

**Issue by H4RR1S** [knxd/knxd#230]
I use Arch Linux on a Raspberry Pi (so armv6 architecture).
Output of uname -a: Linux XXXXX 4.4.49-1-ARCH #1 Fri Feb 17 18:29:22 MST 2017 armv6l GNU/Linux

Steps to reproduce:
1. `wget https://github.com/knxd/knxd/archive/v0.12.10.tar.gz`
2. `tar xvzf v0.12.10.tar.gz`
3. `cd knxd-0.12.10`
4. `./bootstrap.sh && ./configure --enable-busmonitor --enable-management --enable-ft12 --enable-usb --enable-eibnetip --enable-eibnetserver --enable-eibnetiptunnel --enable-eibnetipserver && make`

It also works with the following steps:
1. goto your local git clone of knxd project
2. `git checkout stable`
3. `git pull`
4. `./bootstrap.sh && ./configure --enable-busmonitor --enable-management --enable-ft12 --enable-usb --enable-eibnetip --enable-eibnetserver --enable-eibnetiptunnel --enable-eibnetipserver && make`

OR
1. goto your local git clone of knxd project
2. `git checkout master`
3. `git pull`
4. `./bootstrap.sh && ./configure --enable-busmonitor --enable-management --enable-ft12 --enable-usb --enable-eibnetip --enable-eibnetserver --enable-eibnetiptunnel --enable-eibnetipserver && make`

I get a compile error  with some APDUPtr problem:

```
g++ -DHAVE_CONFIG_H -I. -I../..  -I../../src/include -I../../src/common   -g -O2 -std=c++0x -MT management.o -MD -MP -MF .deps/management.Tpo -c -o management.o management.cpp
In file included from management.h:23:0,
                 from management.cpp:20:
layer7.h:54:3: error: ‘APDUPtr’ does not name a type
   APDUPtr Request_Response (APDU * r);
   ^~~~~~~
layer7.h:109:3: error: ‘APDUPtr’ does not name a type
   APDUPtr Request_Response (APDU * r);
   ^~~~~~~
make[3]: *** [Makefile:508: management.o] Error 1
make[3]: Leaving directory '/root/knxd-0.12.10/src/libserver'
make[2]: *** [Makefile:396: all-recursive] Error 1
make[2]: Leaving directory '/root/knxd-0.12.10/src'
make[1]: *** [Makefile:448: all-recursive] Error 1
make[1]: Leaving directory '/root/knxd-0.12.10'
make: *** [Makefile:380: all] Error 2
```

Maybe there are some dependencies on special versions of libev and stuff that I miss?

thanks for your help!

**Comment by smurfix** [comment]
`--enable-management` does not work yet. Use oldstable if you need it (hint: you probably do not).
