### ISSUE TITLE
Schneider Electric (Merten) MTN681829 USB Interface initialisation of backend 'usb:' failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by magd1978** [knxd/knxd#231]
Hello.

My name is Alberto and I am KNX partner.
First of all, I would like to thank the developers of knxd for their work.

On Monday, February 6, I set up a virtual machine Debian 8.7.1 x86_64 (kernel 3.16 amd64) on vmware workstation 12.5 (Windows 10 host).

My intention was to test with knxd as KNXnet/IP router (routing an tunneling) prior to its installation on a Raspberry Pi 3. I want to build a KNX IP router.

For this I compiled knxd 0.12.8:02c7b7c stable version and connected a Schneider Electric (Merten) MTN681829 USB Interface to the virtual machine.

I could not make USB Interface work, not even as root (initialisation of backend 'usb:' failed: Resource temporarily unavailable). What did I do wrong?

Attached screenshots:
```
root@debian:/home/usuario# knxd --version
knxd 0.12.8:02c7b7c

root@debian:/home/usuario# knxd -t 1023 -f 9 -e 1.1.0 -E 1.1.201:8 -u /tmp/eib -n SEIDO -D -R -T -S -b usb:
knxd: Layer 8 [ 2:/tmp/eib 0.000] OpenLocalSocket /tmp/eib
knxd: Layer 8 [ 2:/tmp/eib 0.001] LocalSocket opened
knxd: Layer 3 [ 3:layer3   0.002] Open
knxd: Layer 3 [ 3:layer3   0.003] L3 started
knxd: Layer 3 [ 3:layer3   0.004] registerLayer2 2:/tmp/eib
knxd: Layer 3 [ 3:layer3   0.004] registerLayer2 2:/tmp/eib = 1
SEIDO: Layer 8 [ 4:mcast:SEIDO 0.004] Open
SEIDO: Layer 0 [ 4:mcast:SEIDO 0.004] Open
SEIDO: Layer 0 [ 4:mcast:SEIDO 0.004] Openend
SEIDO: Layer 8 [ 4:mcast:SEIDO 0.004] OpenD
SEIDO: Layer 8 [ 4:mcast:SEIDO 0.006] OpenedD
SEIDO: Layer 8 [ 4:mcast:SEIDO 0.007] Opened
SEIDO: Layer 3 [ 3:layer3      0.008] registerLayer2 4:mcast:SEIDO
SEIDO: Layer 3 [ 3:layer3      0.008] registerLayer2 4:mcast:SEIDO = 1
SEIDO: Layer 1 [ 5:usb:        0.010] Detect
SEIDO: Layer 1 [ 5:usb:        0.011] Using 2:4:1:0:0 (2:129)
SEIDO: Layer 1 [ 5:usb:        0.012] Open
SEIDO: Layer 1 [ 5:usb:        1.896] Claimed
SEIDO: Layer 1 [ 5:usb:        1.896] Opened
SEIDO: Layer 0 [ 5:usb:        1.896] StartRecv
SEIDO: Layer 1 [ 5:usb:        1.896] Send(064): 01 13 09 00 08 00 01 0F 01 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
SEIDO: Layer 0 [ 5:usb:        1.896] Send(064): 01 13 09 00 08 00 01 0F 01 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
SEIDO: Layer 0 [ 5:usb:        1.896] StartSend
SEIDO: Layer 0 [ 5:usb:        1.909] SendComplete 64
SEIDO: Layer 0 [ 5:usb:        1.912] RecvComplete 64
SEIDO: Layer 0 [ 5:usb:        1.912] RecvUSB(064): 01 13 0B 00 08 00 03 0F 02 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
SEIDO: Layer 0 [ 5:usb:        1.912] StartRecv
SEIDO: Layer 1 [ 5:usb:        1.912] Error reading EMI version
initialisation of backend 'usb:' failed: Resource temporarily unavailable

root@debian:/home/usuario# dmesg
[  546.727626] usb 2-2.1: new full-speed USB device number 4 using uhci_hcd
[  547.205058] usb 2-2.1: New USB device found, idVendor=135e, idProduct=0024
[  547.205068] usb 2-2.1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  547.205073] usb 2-2.1: Product: KNX-USB Data Interface
[  547.205077] usb 2-2.1: Manufacturer: Merten GmbH & Co. KG
[  547.394344] hid-generic 0003:135E:0024.0002: hiddev0,hidraw1: USB HID v1.01 Device [Merten GmbH & Co. KG KNX-USB Data Interface] on usb-0000:02:00.0-2.1/input0
```

Thank you in advance.

**Comment by smurfix** [comment]
This device seems buggy. It does not set the EMI version (in the answer, there's "01 00 00"; the last "00" should be something else). Could you please find out which EMI version (EMI1, EMI2 or CEMI) this device supports?

**Comment by magd1978** [comment]
I don't know how to find out which EMI version (EMI1, EMI2 or CEMI) this device supports.

This is the manufacturer's page, and nothing is mentioned about the EMI version:
http://www.schneider-electric.com/en/product/MTN681829/usb-interface-reg-k,-light-grey/?range=1424-knx&node=166314498-knx&parent-category-id=2200

I'll try to load a more up-to-date version of the USB inteface application program.

I'll keep you informed.

**Comment by magd1978** [comment]
Interface is EMI1.
I downloaded lastest manufacturer application application to the USB interface and... it's works!!!

Thank you very much.

This is the log:

root@debian:/home/usuario# knxd -t 1023 -f 9 -e 1.1.0 -E 1.1.201:8 -u /tmp/eib -n SEIDO -D -R -T -S -b usb:
knxd: Layer 8 [ 2:/tmp/eib 0.000] OpenLocalSocket /tmp/eib
knxd: Layer 8 [ 2:/tmp/eib 0.001] LocalSocket opened
knxd: Layer 3 [ 3:layer3   0.002] Open
knxd: Layer 3 [ 3:layer3   0.002] L3 started
knxd: Layer 3 [ 3:layer3   0.003] registerLayer2 2:/tmp/eib
knxd: Layer 3 [ 3:layer3   0.003] registerLayer2 2:/tmp/eib = 1
SEIDO: Layer 8 [ 4:mcast:SEIDO 0.004] Open
SEIDO: Layer 0 [ 4:mcast:SEIDO 0.004] Open
SEIDO: Layer 0 [ 4:mcast:SEIDO 0.004] Openend
SEIDO: Layer 8 [ 4:mcast:SEIDO 0.004] OpenD
SEIDO: Layer 8 [ 4:mcast:SEIDO 0.006] OpenedD
SEIDO: Layer 8 [ 4:mcast:SEIDO 0.007] Opened
SEIDO: Layer 3 [ 3:layer3      0.008] registerLayer2 4:mcast:SEIDO
SEIDO: Layer 3 [ 3:layer3      0.008] registerLayer2 4:mcast:SEIDO = 1
SEIDO: Layer 1 [ 5:usb:        0.011] Detect
SEIDO: Layer 1 [ 5:usb:        0.012] Using 2:6:1:0:0 (2:129)
SEIDO: Layer 1 [ 5:usb:        0.012] Open
SEIDO: Layer 1 [ 5:usb:        0.203] Claimed
SEIDO: Layer 1 [ 5:usb:        0.204] Opened
SEIDO: Layer 0 [ 5:usb:        0.204] StartRecv
SEIDO: Layer 1 [ 5:usb:        0.204] Send(064): 01 13 09 00 08 00 01 0F 01 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
SEIDO: Layer 0 [ 5:usb:        0.204] Send(064): 01 13 09 00 08 00 01 0F 01 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
SEIDO: Layer 0 [ 5:usb:        0.204] StartSend
SEIDO: Layer 0 [ 5:usb:        0.207] SendComplete 64
SEIDO: Layer 1 [ 5:usb:        5.005] Send(064): 01 13 09 00 08 00 01 0F 01 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
SEIDO: Layer 0 [ 5:usb:        5.005] Send(064): 01 13 09 00 08 00 01 0F 01 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
SEIDO: Layer 0 [ 5:usb:        5.005] StartSend
SEIDO: Layer 0 [ 5:usb:        5.243] SendComplete 64
SEIDO: Layer 1 [ 5:usb:        10.010] Send(064): 01 13 09 00 08 00 01 0F 01 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
SEIDO: Layer 0 [ 5:usb:        10.010] Send(064): 01 13 09 00 08 00 01 0F 01 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
SEIDO: Layer 0 [ 5:usb:        10.010] StartSend
SEIDO: Layer 0 [ 5:usb:        10.280] SendComplete 64
SEIDO: Layer 0 [ 5:usb:        10.283] RecvComplete 64
SEIDO: Layer 0 [ 5:usb:        10.283] RecvUSB(064): 01 13 0B 00 08 00 03 0F 02 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
SEIDO: Layer 0 [ 5:usb:        10.283] StartRecv
SEIDO: Layer 1 [ 5:usb:        10.283] Send(064): 01 13 0A 00 08 00 02 0F 03 00 00 05 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
SEIDO: Layer 1 [ 5:usb:        10.283] EMI1
SEIDO: Layer 2 [ 5:usb:        10.283] Open
SEIDO: Layer 2 [ 5:usb:        10.283] Opened
SEIDO: Layer 3 [ 3:layer3      10.283] registerLayer2 5:usb:
SEIDO: Layer 2 [ 5:usb:        10.283] OpenL2
SEIDO: Layer 0 [ 5:usb:        10.283] Send-EMI(005): 46 01 00 60 12
SEIDO: Layer 1 [ 5:usb:        10.283] Send(064): 01 13 0D 00 08 00 05 01 01 00 00 46 01 00 60 12 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
SEIDO: Layer 3 [ 3:layer3      10.284] registerLayer2 5:usb: = 1
SEIDO: Layer 0 [ 1:main        10.284] knxd should not run as root
SEIDO: W00000020: knxd should not run as root
SEIDO: Layer 0 [ 5:usb:        10.284] Send(064): 01 13 0A 00 08 00 02 0F 03 00 00 05 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
SEIDO: Layer 0 [ 5:usb:        10.284] StartSend
SEIDO: Layer 0 [ 5:usb:        10.289] SendComplete 64
SEIDO: Layer 0 [ 5:usb:        10.289] Send(064): 01 13 0D 00 08 00 05 01 01 00 00 46 01 00 60 12 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
SEIDO: Layer 0 [ 5:usb:        10.289] StartSend
SEIDO: Layer 0 [ 5:usb:        10.295] SendComplete 64
