### ISSUE TITLE
Dependencies for apt

### ISSUE THREAD

**Issue by JoeRu** [knxd/knxd#232]
Hi,
maybe someone like to add this to the README.md - as i had (again) the opportunity to build on a fresh ubuntu server - this may be a complete list of required packages:

`sudo apt-get install debhelper autotools-dev autoconf automake libtool libusb-1.0-0-dev pkg-config libsystemd-dev base-files dh-systemd cmake libev-dev git-core build-essential`

Also: Build on Master-Branch seems to fail actually - should i go for stable?

> dh_install: knxd-tools missing files: /usr/bin/eibnetdescribe
> dh_install: knxd-tools missing files: /usr/bin/eibnetsearch
> dh_install: missing files, aborting
> debian/rules:27: die Regel für Ziel „override_dh_install“ scheiterte
> make[1]: *** [override_dh_install] Fehler 2
> make[1]: Verzeichnis „/home/joe/knxd“ wird verlassen
> debian/rules:14: die Regel für Ziel „binary“ scheiterte
> make: *** [binary] Fehler 2
> dpkg-buildpackage: Fehler: Fehler-Exitstatus von fakeroot debian/rules binary war 2
> 

Joe

**Comment by smurfix** [comment]
Yes, you should use the stable branch. (See the README.)

Actually, I do not want to add the list of dependencies to yet another place where they'll get copied from, to third-party HOWTOs that get out of date quickly. The list of packages is supposed to be in debian/control only.
