### ISSUE TITLE
Disconnects after ETS connection test

### ISSUE THREAD

**Issue by chefkoch009** [knxd/knxd#235]
After pushing the button "test" in the ETS the knxd shuts down.
```testverbindung: Layer 9 [20:tunnel/0.0.0      3.466] has 0.0.0
testverbindung: Layer 8 [20:tunnel/0.0.0      3.466] Start Conn 3
testverbindung: Layer 5 [19:tunnel/ConnC      3.466] Starting
testverbindung: Layer 5 [19:tunnel/ConnC      3.466] Started
testverbindung: Layer 6 [ 1:main              3.466] SN: send_more set
testverbindung: Layer 1 [ 6:server/Server     3.466] Send(012): 03 00 08 01 C0 A8 65 6B 0E 57 02 03
testverbindung: Layer 0 [ 6:server/Server     3.466] Send(018): 06 10 02 06 00 12 03 00 08 01 C0 A8 65 6B 0E 57 02 03
testverbindung: Layer 0 [ 6:server/Server     3.473] Recv(017): 06 10 03 10 00 11 04 03 00 00 FC 00 00 01 53 10 01
testverbindung: Layer 8 [ 6:server/Server     3.473] CONFIG_REQ on 3
testverbindung: Layer 1 [ 6:server/Server     3.473] Send(004): 04 03 00 00
testverbindung: Layer 1 [ 6:server/Server     3.473] Send(012): 04 03 00 00 FB 00 00 01 53 00 01 00
testverbindung: Layer 0 [ 6:server/Server     3.473] Send(010): 06 10 03 11 00 0A 04 03 00 00
testverbindung: Layer 0 [ 6:server/Server     3.473] Send(018): 06 10 03 10 00 12 04 03 00 00 FB 00 00 01 53 00 01 00
testverbindung: Layer 0 [ 6:server/Server     3.474] Recv(010): 06 10 03 11 00 0A 04 03 00 00
testverbindung: Layer 8 [20:tunnel/0.0.0      3.474] CONFIG_ACK
testverbindung: Layer 0 [ 6:server/Server     3.478] Recv(017): 06 10 03 10 00 11 04 03 01 00 FC 00 00 01 38 10 01
testverbindung: Layer 8 [ 6:server/Server     3.478] CONFIG_REQ on 3
testverbindung: Layer 1 [ 6:server/Server     3.478] Send(004): 04 03 01 00
testverbindung: Layer 1 [ 6:server/Server     3.478] Send(012): 04 03 01 00 FB 00 00 01 38 00 01 00
testverbindung: Layer 0 [ 6:server/Server     3.478] Send(010): 06 10 03 11 00 0A 04 03 01 00
testverbindung: Layer 0 [ 6:server/Server     3.479] Send(018): 06 10 03 10 00 12 04 03 01 00 FB 00 00 01 38 00 01 00
testverbindung: Layer 0 [ 6:server/Server     3.479] Recv(010): 06 10 03 11 00 0A 04 03 01 00
testverbindung: Layer 8 [20:tunnel/0.0.0      3.479] CONFIG_ACK
testverbindung: Layer 0 [ 6:server/Server     3.483] Recv(016): 06 10 02 09 00 10 03 00 08 01 C0 A8 65 64 CB 8A
testverbindung: Layer 8 [20:tunnel/0.0.0      3.483] DISCONNECT_REQUEST
testverbindung: Layer 8 [20:tunnel/0.0.0      3.483] Stop Conn 3
testverbindung: Layer 5 [19:tunnel/ConnC      3.484] Stopped
testverbindung: Layer 1 [ 6:server/Server     3.484] Send(002): 03 00
testverbindung: Layer 5 [17:tunnel/ConnC      3.484] Stopping
testverbindung: Layer 8 [18:tunnel/1.1.101    3.484] Stop Conn 2
testverbindung: Layer 5 [17:tunnel/ConnC      3.484] Stopped
testverbindung: Layer 5 [15:tunnel/ConnC      3.484] Stopping
testverbindung: Layer 8 [16:tunnel/1.1.100    3.484] Stop Conn 1
testverbindung: Layer 5 [15:tunnel/ConnC      3.484] Stopped
testverbindung: Layer 5 [13:router/ConnC      3.484] Stopping
testverbindung: Layer 5 [13:router/ConnC      3.484] Stopped
testverbindung: Layer 8 [20:tunnel/0.0.0      3.484] Stop Conn 3
testverbindung: Layer 5 [19:tunnel/ConnC      3.484] Stopped
testverbindung: Layer 8 [18:tunnel/1.1.101    3.484] Stop Conn 2
testverbindung: Layer 5 [17:tunnel/ConnC      3.484] Stopped
testverbindung: Layer 8 [16:tunnel/1.1.100    3.484] Stop Conn 1
testverbindung: Layer 5 [15:tunnel/ConnC      3.484] Stopped
testverbindung: Layer 8 [14:router/driver     3.484] CloseD
testverbindung: Layer 0 [ 6:server/Server     3.484] Close
testverbindung: Layer 5 [ 6:server/Server     3.485] Stopped
testverbindung: Layer 5 [11:B.tpuarts/Conn    3.485] Stopping
testverbindung: Layer 8 [12:B.tpuarts/Base    3.485] ser state 20>0
testverbindung: Layer 8 [12:B.tpuarts/Base    3.485] state: wait > new
testverbindung: Layer 5 [11:B.tpuarts/Conn    3.485] Stopped
testverbindung: Layer 5 [ 4:A.cache/Conn      3.485] Stopping
testverbindung: Layer 5 [ 4:A.cache/Conn      3.485] Stopped
testverbindung: Layer 2 [12:B.tpuarts/Base    3.485] Close
```
the config is generated with 
`/usr/lib/knxd_args -t 2023 -e1.1.99 -E 1.1.99:3 -D -T -R -S -c -n testverbindung  tpuarts:/dev/ttyKNX1 > /etc/knxd.ini`

and it is executet with:
`knxd /etc/knxd.ini`

Kind regards
Kay

**Comment by smurfix** [comment]
Owch.

`-t 2023` doesn't make sense, you want 1023 (0xfff).

You can't use 1.1.99 for both knxd and its clients; knxd skips its own address.
 
Could you please repeat the test with
`knxd -A name=main -B log -t 1023 -e1.1.99 -E 1.1.99:3 -D -A name=tunnel -B log -T -R  -S -c -n test tpuarts:/dev/ttyKNX1` (or the .ini file resulting from that)?

**Comment by smurfix** [comment]
NB: when you paste multi-line data, please use three backquotes to enclose it.
(Or use a pastebin.)

**Comment by chefkoch009** [comment]
Thanks for your fast response and sorry for my terrible code format in the first post.
while executing your suggested line i get:
`# knxd -A name=main -B log -t 1023 -e1.1.99 -E 1.1.99:3 -D -A name=tunnel -B log -T -R -S -c -n test tpuarts:/dev/ttyKNX1`
`test: Layer 4 [ 1:main       0.000] R state: initialized`
`test: Layer 4 [ 1:main       0.000] R state: setting up`
`test: Layer 4 [ 5:C.cache/G     0.000] GroupCacheInit`
`test: Layer 3 [ 4:C.cache/Conn  0.000] registerLink: C.cache`
`test: Layer 0 [ 6:A.log/main    0.000] State setup`
`test: Layer 0 [10:B.log/tunnel      0.000] State setup`
`test: Layer 3 [ 7:server/Server     0.001] registerLink: server`
`test: Layer 3 [13:D.tpuarts/Conn    0.001] registerLink: D.tpuarts`
`test: [ 1:main] F00000000: Section 'A.log': unrecognized argument 'name = main'`
`test: [ 1:main] F00000000: Section 'B.log': unrecognized argument 'name = tunnel'`
`test: Layer 4 [ 1:main              0.001] R state: setup BROKEN`
`test: [ 1:main] F00000000: Error setting up the KNX router.`

I get the same if I change the -E option to a different from -e. 

Hope this are the informations, you need.

**Comment by smurfix** [comment]
Oops, my fault, that was an experimental build which I didn't check in.
Please do it without the new -A … options.

**Comment by chefkoch009** [comment]
Without -A it didn't work, or I don't understand, what you have mentioned.
`#knxd name=main -B log -t 1023 -e1.1.99 -E 1.1.100:3 -D name=tunnel -B log -T -R -S -c -n test tpuarts:/dev/ttyKNX1`
`You need -S after -D/-T/-R`
`[ 1:main] E00000055: There is no KNX addr= in section 'main'.`
`[ 1:main] F00000000: Error setting up the KNX router.`

Setting -TRS to an other position:
`# knxd name=main -B log -t 1023 -e1.1.99 -E 1.1.100:3 -D -T -R -S name=tunnel -B log -c -n test tpuarts:/dev/ttyKNX1`
`test: Layer 4 [ 1:main       0.000] R state: initialized`
`test: Layer 4 [ 1:main       0.000] R state: setting up`
`test: Layer 4 [ 5:B.cache/G     0.000] GroupCacheInit`
`test: Layer 0 [ 6:log/B.cache   0.000] State setup`
`test: Layer 3 [ 4:B.cache/Conn  0.000] registerLink: B.cache`
`test: Layer 0 [ 7:log/main      0.000] State setup`
`test: [ 1:main] E00000055: Driver 'name=main' not found.`
`test: [ 1:main] E00000055: Section 'A.name=main' has no known server nor driver.`
`test: Layer 4 [ 1:main              0.001] R state: setup BROKEN`
`test: [ 1:main] F00000000: Error setting up the KNX router.`

is also not good.

**Comment by smurfix** [comment]
I meant without `-A name=XXX`.

**Comment by chefkoch009** [comment]
there is also the line with "DISCONNECT_REQUEST"

`# knxd -B log -t 1023 -e1.1.99 -E 1.1.99:3 -D -B log -T -R -S -c -n test tpuarts:/dev/ttyKNX1`
`test: Layer 8 [18:tunnel/1.1.100    29.944] TUNNEL_ACK`
`test: Layer 0 [ 7:server/Server     29.973] Recv(016): 06 10 02 07 00 10 02 00 08 01 00 00 00 00 00 00`
`test: Layer 8 [21:tunnel/1.1.101    29.973] CONNECTIONSTATE_REQUEST on 2`
`test: Layer 1 [ 7:server/Server     29.973] Send(002): 02 00`
`test: Layer 0 [ 7:server/Server     29.973] Send(008): 06 10 02 08 00 08 02 00`
`test: Layer 0 [ 7:server/Server     29.991] Recv(010): 06 10 04 21 00 0A 04 02 00 00`
`test: Layer 8 [21:tunnel/1.1.101    29.991] TUNNEL_ACK`
`test: Layer 0 [ 7:server/Server     30.031] Recv(016): 06 10 02 09 00 10 02 00 08 01 00 00 00 00 00 00`
`test: Layer 8 [21:tunnel/1.1.101    30.031] DISCONNECT_REQUEST`
`test: Layer 8 [21:tunnel/1.1.101    30.031] Stop Conn 2`
`test: Layer 3 [ 1:main              30.031] Release 1.1.101`
`test: Layer 0 [22:log/tunnel        30.031] State stopped`
`test: Layer 5 [20:tunnel/ConnC      30.031] Stopped`
`test: Layer 4 [20:tunnel/ConnC      30.031] R state: stopped`
`test: Layer 1 [ 7:server/Server     30.031] Send(002): 02 00`
`test: Layer 4 [ 1:main              30.032] R state: trigger Going down`
`test: Layer 0 [ 6:log/main          30.032] State stop`
`test: Layer 3 [17:tunnel/ConnC      30.032] Stop: cfg:tunnel`
`test: Layer 5 [17:tunnel/ConnC      30.032] Stopping`
`test: Layer 0 [19:log/tunnel        30.032] State stop`
`test: Layer 8 [18:tunnel/1.1.100    30.032] Stop Conn 1`
`test: Layer 3 [ 1:main              30.032] Release 1.1.100`
`test: Layer 0 [19:log/tunnel        30.032] State stopped`
`test: Layer 5 [17:tunnel/ConnC      30.032] Stopped`
`test: Layer 4 [17:tunnel/ConnC      30.032] R state: stopped`
`test: Layer 3 [15:router/ConnC      30.032] Stop: cfg:router`
`test: Layer 5 [15:router/ConnC      30.032] Stopping`
`test: Layer 5 [15:router/ConnC      30.032] Stopped`
`test: Layer 4 [15:router/ConnC      30.032] R state: stopped`
`test: Layer 3 [ 7:server/Server     30.032] Stop: cfg:server`
`test: Layer 8 [21:tunnel/1.1.101    30.032] Stop Conn 2`
`test: Layer 0 [22:log/tunnel        30.032] State stopped`
`test: Layer 5 [20:tunnel/ConnC      30.032] Stopped`
`test: Layer 4 [20:tunnel/ConnC      30.032] R state: stopped`
`test: Layer 8 [18:tunnel/1.1.100    30.032] Stop Conn 1`
`test: Layer 0 [19:log/tunnel        30.032] State stopped`
`test: Layer 5 [17:tunnel/ConnC      30.032] Stopped`
`test: Layer 4 [17:tunnel/ConnC      30.032] R state: stopped`
`test: Layer 3 [15:router/ConnC      30.032] unregisterLink: router_15`
`test: Layer 8 [16:router/driver     30.032] CloseD`
`test: Layer 0 [ 7:server/Server     30.032] Close`
`test: Layer 5 [ 7:server/Server     30.032] Stopped`
`test: Layer 4 [ 7:server/Server     30.032] R state: stopped`
`test: Layer 3 [13:B.tpuarts/Conn    30.032] Stop: cfg:B.tpuarts`
`test: Layer 5 [13:B.tpuarts/Conn    30.032] Stopping`
`test: Layer 8 [14:B.tpuarts/Base    30.033] ser state 20>0`
`test: Layer 8 [14:B.tpuarts/Base    30.033] state: wait > new`
`test: Layer 5 [13:B.tpuarts/Conn    30.033] Stopped`
`test: Layer 4 [13:B.tpuarts/Conn    30.033] R state: stopped`
`test: Layer 3 [ 4:A.cache/Conn      30.033] Stop: cfg:A.cache`
`test: Layer 5 [ 4:A.cache/Conn      30.033] Stopping`
`test: Layer 5 [ 4:A.cache/Conn      30.033] Stopped`
`test: Layer 4 [ 4:A.cache/Conn      30.033] R state: stopped`
`test: Layer 0 [ 6:log/main          30.033] State stopped`
`test: Layer 4 [ 1:main              30.033] R state: down`
`test: Layer 4 [ 1:main              30.033] R state: deleting`
`test: Layer 2 [14:B.tpuarts/Base    30.033] Close`
`test: Layer 4 [ 5:A.cache/G         30.033] GroupCacheDestroy`
`test: Layer 4 [ 5:A.cache/G         30.033] GroupCacheClear`
`test: Layer 4 [ 1:main              30.033] R state: deleted.`

and by the way, if i send a command to knx-bus, I'd get a received from device. but with eibd I get it.

**Comment by smurfix** [comment]
> if i send a command to knx-bus, I'd get a received from device. but with eibd I get it.

I don't understand that. What exactly are you doing?

**Comment by chefkoch009** [comment]
I've checked out your last version, made deb-packages, installed them and now it seems to work as expected.

Really good job...thank you. 

Now i try to create a scenario to show you what i mean with the other problem.

**Comment by chefkoch009** [comment]
this is what i mean:

`Layer 1 [ 6:server/Server     49.501] Send(011): 29 00 BC D0 71 03 07 01 01 00 80`
`Layer 6 [ 1:main              49.501] SN: OK`
`Layer 6 [ 2:main/L            49.501] SN: OK L`
`Layer 1 [ 6:server/Server     49.501] Send(015): 04 01 21 00 29 00 BC D0 71 03 07 01 01 00 80`
`Layer 1 [ 6:server/Server     49.501] Send(015): 04 02 21 00 29 00 BC D0 71 03 07 01 01 00 80`
`Layer 0 [ 6:server/Server     49.501] Send(017): 06 10 05 30 00 11 29 00 BC D0 71 03 07 01 01 00 80`
`Layer 0 [ 6:server/Server     49.501] Dropped(017): 06 10 05 30 00 11 29 00 BC D0 71 03 07 01 01 00 80`
`Layer 0 [ 6:server/Server     49.501] Send(021): 06 10 04 20 00 15 04 01 21 00 29 00 BC D0 71 03 07 01 01 00 80`
`Layer 0 [ 6:server/Server     49.501] Send(021): 06 10 04 20 00 15 04 02 21 00 29 00 BC D0 71 03 07 01 01 00 80`
`Layer 0 [ 6:server/Server     49.506] Recv(010): 06 10 04 21 00 0A 04 02 21 00`
`Layer 8 [18:tunnel/1.1.101    49.506] TUNNEL_ACK`
`Layer 0 [ 6:server/Server     49.558] Recv(010): 06 10 04 21 00 0A 04 01 21 00`
`Layer 8 [16:tunnel/1.1.100    49.558] TUNNEL_ACK`
`Layer 0 [12:B.tpuarts/Base    49.565] Read(008): BC 71 6B 3C 08 E3 00 80`
`Layer 8 [12:B.tpuarts/Base    49.565] ser state 20>21`
`Layer 8 [12:B.tpuarts/Base    49.565] state: wait > wait_more`
`Layer 8 [12:B.tpuarts/Base    49.565] ser state 21>21`
`Layer 8 [12:B.tpuarts/Base    49.565] state: wait_more > wait_more`
`Layer 8 [12:B.tpuarts/Base    49.566] ser state 21>21`
`Layer 8 [12:B.tpuarts/Base    49.566] state: wait_more > wait_more`
`Layer 8 [12:B.tpuarts/Base    49.566] ser state 21>21`
`Layer 8 [12:B.tpuarts/Base    49.566] state: wait_more > wait_more`
`Layer 0 [12:B.tpuarts/Base    49.566] SendAck 11`
`Layer 8 [12:B.tpuarts/Base    49.566] ser state 21>21`
`Layer 8 [12:B.tpuarts/Base    49.566] state: wait_more > wait_more`
`Layer 8 [12:B.tpuarts/Base    49.566] ser state 21>21`
`Layer 8 [12:B.tpuarts/Base    49.566] state: wait_more > wait_more`
`Layer 8 [12:B.tpuarts/Base    49.566] ser state 21>21`
`Layer 8 [12:B.tpuarts/Base    49.566] state: wait_more > wait_more`
`Layer 0 [12:B.tpuarts/Base    49.571] Read(003): 14 01 1B`
`Layer 8 [12:B.tpuarts/Base    49.571] ser state 21>21`
`Layer 8 [12:B.tpuarts/Base    49.571] state: wait_more > wait_more`
`Layer 8 [12:B.tpuarts/Base    49.571] ser state 21>21`
`Layer 8 [12:B.tpuarts/Base    49.571] state: wait_more > wait_more`

do you have an idea for this phenomenon? with the 0.10 eibd version, I don't have this problem.
