### ISSUE TITLE
Driver 'iptn' not found

### ISSUE THREAD

**Issue by ghost** [knxd/knxd#239]
Hi,
I just migrated from 0.12.12 to 0.14.7, on a RaspberryPi3 with Jessie and the same command line is now failing:
`knxd -t 1023 -e 0.0.1 -E 2.2.20:10 -RTS -i 6720 -b iptn:192.168.1.13`

Here is the output on 0.14.7:
```Layer 4 [ 1:main        0.000] R state: initialized
Layer 4 [ 1:main        0.000] R state: setting up
Layer 3 [ 4:server/Server     0.000] registerLink: 4:server
E00000055: [ 1:main] Driver 'iptn' not found.
E00000055: [ 1:main] Section 'B.iptn' has no known server nor driver.
F00000000: [ 1:main] Error setting up the KNX router.
Layer 3 [ 9:A.tcp/inet        0.001] registerLink: 9:A.tcp
Layer 4 [ 1:main              0.001] R state: setup BROKEN
```

Is it due to a command line parameter that was updated?
Or is it a bug in this version ?

Thanks for your help !

**Comment by smurfix** [comment]
No, it's a bug in the converter.
Please test 9d81d70

**Comment by f-dubuisson** [comment]
This is going further but still failing:
```
Layer 4 [ 1:main        0.000] R state: initialized
Layer 4 [ 1:main        0.000] R state: setting up
Layer 3 [ 4:server/Server     0.000] registerLink: 4:server
Layer 3 [ 9:A.tcp/inet        0.000] registerLink: 9:A.tcp
Layer 3 [12:B.iptn/Conn       0.000] registerLink: 12:B.iptn
Layer 4 [ 1:main              0.000] R state: setup OK
Layer 4 [ 1:main              0.000] R state: trigger going up
Layer 3 [12:B.iptn/Conn       0.000] Start: cfg:B.iptn
Layer 5 [12:B.iptn/Conn       0.000] Starting
Layer 2 [13:B.iptn/ipt        0.000] Open
Layer 0 [13:B.iptn/ipt        0.001] Open
Layer 0 [13:B.iptn/ipt        0.001] Openend
Layer 1 [13:B.iptn/ipt        0.001] Send(020): 08 01 AC 11 00 02 00 00 08 01 AC 11 00 02 00 00 04 04 02 00
Layer 2 [13:B.iptn/ipt        0.001] Opened
Layer 3 [ 9:A.tcp/inet        0.001] Start: cfg:A.tcp
Layer 8 [ 9:A.tcp/inet        0.001] OpenInetSocket 6720
Layer 8 [ 9:A.tcp/inet        0.001] InetSocket opened
Layer 5 [ 9:A.tcp/inet        0.001] Started
Layer 4 [ 9:A.tcp/inet        0.001] R state: started
Layer 6 [ 1:main              0.001] OK
Layer 6 [ 2:main/L            0.001] OK L
Layer 3 [ 4:server/Server     0.001] Start: cfg:server
Layer 8 [ 4:server/Server     0.001] Open
Layer 0 [ 4:server/Server     0.001] Open
Layer 0 [ 4:server/Server     0.001] Openend
Layer 8 [16:router/driver     0.001] OpenD
Layer 8 [16:router/driver     0.002] OpenedD
Layer 3 [15:router/ConnC      0.002] registerLink: 15:router_15
Layer 3 [15:router/ConnC      0.002] Start: cfg:router
Layer 5 [15:router/ConnC      0.002] Starting
Layer 5 [15:router/ConnC      0.002] Started
Layer 4 [15:router/ConnC      0.002] R state: started
Layer 6 [ 1:main              0.002] send_more set
Layer 8 [ 4:server/Server     0.002] Opened
Layer 5 [ 4:server/Server     0.002] Started
Layer 4 [ 4:server/Server     0.002] R state: started
Layer 6 [ 1:main              0.002] send_more set
Layer 4 [ 1:main              0.002] R state: going up triggered
Layer 4 [ 1:main              0.003] R state: check start
Layer 4 [12:B.iptn/Conn       0.003] is going up
Layer 4 [ 1:main              0.003] R state: check end: want_up 1 some 1>1 all 0>0, going 1 up 3 down 0
Layer 0 [13:B.iptn/ipt        0.003] Send(026): 06 10 02 05 00 1A 08 01 AC 11 00 02 00 00 08 01 AC 11 00 02 00 00 04 04 02 00
Layer 4 [ 1:main              1.980] R state: trigger Going down
Layer 3 [12:B.iptn/Conn       1.980] Stop: cfg:B.iptn
Layer 3 [ 9:A.tcp/inet        1.980] Stop: cfg:A.tcp
Layer 8 [ 9:A.tcp/inet        1.981] StopServer
Layer 5 [ 9:A.tcp/inet        1.981] Stopped
Layer 4 [ 9:A.tcp/inet        1.981] R state: stopped
E00000000: [ 1:main] Startup not successful.
Layer 3 [15:router/ConnC      1.981] Stop: cfg:router
Layer 5 [15:router/ConnC      1.981] Stopping
Layer 5 [15:router/ConnC      1.981] Stopped
Layer 4 [15:router/ConnC      1.981] R state: stopped
Layer 3 [ 4:server/Server     1.981] Stop: cfg:server
Layer 3 [15:router/ConnC      1.981] unregisterLink: router_15
Layer 8 [16:router/driver     1.981] CloseD
Layer 0 [ 4:server/Server     1.981] Close
Layer 5 [ 4:server/Server     1.982] Stopped
Layer 4 [ 4:server/Server     1.982] R state: stopped
Layer 4 [ 1:main              1.982] R state: check start
Layer 4 [12:B.iptn/Conn       1.982] is going up
Layer 4 [ 9:A.tcp/inet        1.982] is down
Layer 4 [ 4:server/Server     1.982] is down
Layer 4 [ 1:main              1.982] R state: check end: want_up 0 some 1>1 all 0>0, going 1 up 0 down 2
Layer 1 [13:B.iptn/ipt        9.986] Connect timed out
Layer 0 [13:B.iptn/ipt        9.986] Close
Layer 5 [12:B.iptn/Conn       9.986] Stopped
Layer 4 [12:B.iptn/Conn       9.986] R state: stopped
Layer 4 [ 1:main              9.987] R state: check start
Layer 4 [12:B.iptn/Conn       9.987] is down
Layer 4 [ 9:A.tcp/inet        9.987] is down
Layer 4 [ 4:server/Server     9.987] is down
Layer 4 [ 1:main              9.987] R state: check end: want_up 0 some 1>0 all 0>0, going 0 up 0 down 3
Layer 4 [ 1:main              9.987] R state: down
Layer 4 [ 1:main              9.987] R state: deleting
Layer 2 [13:B.iptn/ipt        9.987] Close
Layer 8 [ 9:A.tcp/inet        9.987] StopServer
Layer 8 [ 4:server/Server     9.987] Close
Layer 4 [ 1:main              9.987] R state: deleted.
```

**Comment by f-dubuisson** [comment]
Just checked again with b7257435fb1c9dc68e16096b5a9749868ae1e5c6 but no improvement. 
Do you need some additional tests ?

Layer 4 [ 1:main        0.000] initialized
Layer 4 [ 1:main        0.000] setting up
Layer 3 [ 4:server/Server     0.001] registerLink: 4:server
Layer 3 [ 9:A.tcp/inet        0.002] registerLink: 9:A.tcp
Layer 3 [12:B.iptn/Conn       0.002] registerLink: 12:B.iptn
Layer 4 [ 1:main              0.002] setup OK
Layer 4 [ 1:main              0.002] trigger going up
Layer 3 [12:B.iptn/Conn       0.002] Start: cfg:B.iptn
Layer 5 [12:B.iptn/Conn       0.002] down => >up
Layer 5 [12:B.iptn/Conn       0.002] Starting
Layer 2 [13:B.iptn/ipt        0.002] Open
Layer 0 [13:B.iptn/ipt        0.003] Open
Layer 0 [13:B.iptn/ipt        0.003] Openend
Layer 1 [13:B.iptn/ipt        0.004] Send(020): 08 01 AC 11 00 02 00 00 08 01 AC 11 00 02 00 00 04 04 02 00
Layer 2 [13:B.iptn/ipt        0.004] Opened
Layer 4 [12:B.iptn/Conn       0.004] >up
Layer 3 [ 9:A.tcp/inet        0.004] Start: cfg:A.tcp
Layer 5 [ 9:A.tcp/inet        0.004] down => >up
Layer 8 [ 9:A.tcp/inet        0.004] OpenInetSocket 6721
Layer 8 [ 9:A.tcp/inet        0.004] InetSocket opened
Layer 5 [ 9:A.tcp/inet        0.004] >up => up
Layer 4 [ 9:A.tcp/inet        0.004] up
Layer 5 [ 9:A.tcp/inet        0.004] Started
Layer 4 [ 9:A.tcp/inet        0.004] up
Layer 3 [ 4:server/Server     0.004] Start: cfg:server
Layer 5 [ 4:server/Server     0.004] down => >up
Layer 8 [ 4:server/Server     0.004] Open
Layer 0 [ 4:server/Server     0.004] Open
Layer 0 [ 4:server/Server     0.004] Openend
Layer 8 [16:router/driver     0.005] OpenD
Layer 8 [16:router/driver     0.005] OpenedD
Layer 3 [15:router/ConnC      0.006] registerLink: 15:router_15
Layer 3 [15:router/ConnC      0.006] Start: cfg:router
Layer 5 [15:router/ConnC      0.006] down => >up
Layer 5 [15:router/ConnC      0.006] Starting
Layer 5 [15:router/ConnC      0.006] >up => up
Layer 4 [15:router/ConnC      0.006] up
Layer 5 [15:router/ConnC      0.006] Started
Layer 4 [15:router/ConnC      0.006] up
Layer 8 [ 4:server/Server     0.006] Opened
Layer 5 [ 4:server/Server     0.006] >up => up
Layer 4 [ 4:server/Server     0.006] up
Layer 5 [ 4:server/Server     0.006] Started
Layer 4 [ 4:server/Server     0.006] up
Layer 4 [ 1:main              0.006] going up triggered
Layer 4 [ 1:main              0.006] check start
Layer 4 [12:B.iptn/Conn       0.006] is >up
Layer 4 [ 1:main              0.006] check end: want_up 1 some 1>1 all 0>0, going 1 up 3 down 0
Layer 0 [13:B.iptn/ipt        0.006] Send(026): 06 10 02 05 00 1A 08 01 AC 11 00 02 00 00 08 01 AC 11 00 02 00 00 04 04 02 00
Layer 1 [13:B.iptn/ipt        9.995] Connect timed out
Layer 0 [13:B.iptn/ipt        9.995] Close
Layer 5 [12:B.iptn/Conn       9.995] >up => down/error
Layer 4 [12:B.iptn/Conn       9.995] up/error
Layer 4 [ 1:main              9.995] check start
Layer 5 [12:B.iptn/Conn       9.995] Stopping
Layer 5 [12:B.iptn/Conn       9.996] up/error => down
Layer 4 [12:B.iptn/Conn       9.996] is down
Layer 4 [ 1:main              9.996] check end: want_up 1 some 1>1 all 0>0, going 0 up 3 down 1
Layer 4 [ 1:main              9.996] trigger Going down
Layer 4 [12:B.iptn/Conn       9.996] Stopping
Layer 5 [12:B.iptn/Conn       9.996] down/error => >down
Layer 4 [12:B.iptn/Conn       9.996] down/error
Layer 4 [ 9:A.tcp/inet        9.996] Stopping
Layer 5 [ 9:A.tcp/inet        9.996] up => >down
Layer 8 [ 9:A.tcp/inet        9.996] StopServer
Layer 5 [ 9:A.tcp/inet        9.996] >down => down
Layer 4 [ 9:A.tcp/inet        9.996] down
Layer 4 [ 9:A.tcp/inet        9.996] down
Layer 4 [15:router/ConnC      9.996] Stopping
Layer 5 [15:router/ConnC      9.996] up => >down
Layer 5 [15:router/ConnC      9.996] Stopping
Layer 5 [15:router/ConnC      9.996] >down => down
Layer 4 [15:router/ConnC      9.996] down
Layer 4 [15:router/ConnC      9.996] down
Layer 4 [ 4:server/Server     9.996] Stopping
Layer 5 [ 4:server/Server     9.996] up => >down
Layer 5 [15:router/ConnC      9.996] Stopping
Layer 3 [15:router/ConnC      9.996] unregisterLink: router_15
Layer 0 [ 4:server/Server     9.996] Close
Layer 5 [ 4:server/Server     9.996] >down => down
Layer 4 [ 4:server/Server     9.996] down
Layer 4 [ 4:server/Server     9.996] down
Layer 4 [ 1:main              9.996] check start
Layer 8 [16:router/driver     9.996] CloseD
Layer 4 [12:B.iptn/Conn       9.996] is down
Layer 4 [ 9:A.tcp/inet        9.996] is down
Layer 4 [ 4:server/Server     9.996] is down
Layer 4 [ 1:main              9.996] check end: want_up 0 some 1>0 all 0>0, going 0 up 0 down 3
Layer 4 [ 1:main              9.996] down
Layer 4 [ 1:main              9.996] deleting
Layer 2 [13:B.iptn/ipt        9.996] Close
Layer 8 [ 9:A.tcp/inet        9.996] StopServer
Layer 8 [ 4:server/Server     9.996] Close
Layer 4 [ 1:main              9.996] deleted.

**Comment by smurfix** [comment]
Well …
```Layer 1 [13:B.iptn/ipt        9.995] Connect timed out```
I assume you're able to ping 192.168.1.13.
Could you watch 0.12 and 0.14 with wireshark to check whether the initial packet is different?

**Comment by f-dubuisson** [comment]
Please find the 2 captures, with 0.12.12 (successfull) and 0.14.12 (timeout). 
[captures.zip](https://github.com/knxd/knxd/files/962689/captures.zip)

I'm using the exact same command with both versions:
`knxd -t 1023 -e 0.0.1 -E 2.2.20:10 -RTS -i 6720 -b iptn:192.168.1.13`

The only difference I can see in the traces is that the 0.14.12 packets references an IP 172.17.0.3 that does not exist on my network.
Hope this helps !

**Comment by smurfix** [comment]
Mmh. Could you please test 0.14 with ipt: instead of iptn:?

**Comment by f-dubuisson** [comment]
Here they are, for 0.12.12 and 0.14.12:
[captures-ipt.zip](https://github.com/knxd/knxd/files/963667/captures-ipt.zip)

This configuration does not work on my network, for both versions. 0.12 retries to connect whilst 0.14 gives up but in both cases, the communication is not set up.

**Comment by f-dubuisson** [comment]
I finally found the reason why the 0.14 build could not connect. I'm testing the build in a docker container (which is very useful to build without caring about the system configuration) and it looks like the 'bridge' network is breaking knxd (this is where the 172.17.0.3 address was coming from).
This was working fine on 0.12 but I don't know which version has the 'expected' behavior.

With the 'host' network configuration, 0.14 is connecting correctly, with ipt: and iptn:.

**Comment by onkelandy** [comment]
I had the same problem with docker, thanks for the hint. It works now. Anyhow.. What exactly is wrong with this config:
```
[A.tcp]
server = knxd_tcp
port = 6720

[B.ipt]
driver = iptn
filters = C.pace
ip-address = 10.0.0.101

[C.pace]
delay = 50
filter = pace

[E.debug]
error-level = 0x9
trace-mask = 0xfc

[main]
addr = 0.0.1
debug = E.debug
client-addrs=0.0.2:8
cache = D.cache
connections = A.tcp,B.ipt
background = false
```
Whether I name B.iptn or B.ipt does not matter. I always get the error that the driver iptn is not found. Using 0.14.12

**Comment by onkelandy** [comment]
Here's the log:
```
22:38:16 Starting knxd service. stdout
22:38:16 ARGS: /etc/knxd/knxd.ini stdout
22:38:16 Press <ctrl>-c to abort stdout
22:38:16 Layer 4 [ 1:main 0.000] initialized stdout
22:38:16 I00000000: [ 1:main] 0.14.12: knxd /etc/knxd/knxd.ini stdout
22:38:16 Layer 4 [ 1:main 0.000] setting up stdout
22:38:16 Layer 4 [ 5:D.cache/G 0.000] GroupCacheInit stdout
22:38:16 Layer 3 [ 4:D.cache/Conn 0.001] registerLink: 4:D.cache stdout
22:38:16 Layer 3 [ 6:A tcp/inet 0 001] registerLink: 6:A tcp stdout 22:38:16 E00000055: [ 1:main] Driver 'iptn' not found. stdout
22:38:16 E00000055: [ 1:main] Section 'B.ipt' has no known server nor driver. stdout
22:38:16 Layer 4 [ 1:main 0.002] setup BROKEN stdout
22:38:16 F00000000: [ 1:main] Error setting up the KNX router
```

**Comment by smurfix** [comment]
There is no such thing as an "iptn" driver; also the section names don't matter. You want
```
[whatever]
driver = ipt
nat = true
```

**Comment by onkelandy** [comment]
Thx gonna try that. 
Iptn is listed as a driver here:
https://github.com/knxd/knxd/wiki/Command-line-parameters
