### ISSUE TITLE
Driver stops immediately while starting a portscan 

### ISSUE THREAD

**Issue by chefkoch009** [knxd/knxd#240]
I started knxd up with:
`# knxd -e 1.1.155 -E 1.1.156:8 -n test -c tpuarts:/dev/ttyKNX1 -b ipt:<ip of knxd running component> -DTRS`

While checking remotly if knxd is up and running, the driver stops if doing a 
`# nmap -sU -p 3671 <ip of knxd running component>`

**Comment by smurfix** [comment]
You don't use an -i option and you either don't start it with systemd, or forgot to start `knxd.socket` before `knxd.service`.

> While checking remotly if knxd is up and running, the driver stops if doing a
> # nmap -sU -p 3671 <ip of knxd running component>
That seems to be a bug. I'll investigate:

**Comment by chefkoch009** [comment]
With -i option i've seen....my fault, sorry. I already corrected my first post.

**Comment by smurfix** [comment]
Should be solved in commit ffda798

**Comment by chefkoch009** [comment]
Tested and working.
thanks a lot.
