### ISSUE TITLE
compile error on ubuntu server 16.04 x86_64

### ISSUE THREAD

**Issue by chefkoch009** [knxd/knxd#241]
I set up an ubuntu server for faster testing of package and I tried to build the package, wich works perfect on armhf, on ubuntu server 16.04 x86_64 with this error:
`# dpkg-buildpackage -b -uc`
`....`
`  CXX      lowlevel.o`
`  CXX      router.o`
`router.cpp: In member function ‘bool Router::setup()’:`
`router.cpp:107:7: error: ‘::isnan’ has not been declared`
`   if (::isnan(start_timeout) || start_timeout <= 0)`
`       ^`
`router.cpp:107:7: note: suggested alternatives:`
`In file included from /root/knxd/knxd/libfmt/fmt/format.h:33:0,`
`                 from trace.h:27,`
`                 from common.h:82,`
`                 from link.h:23,`
`                 from router.cpp:20:`
`/usr/include/c++/5/cmath:641:5: note:   ‘std::isnan’`
`     isnan(_Tp __x)`
`     ^`
`In file included from trace.h:27:0,`
`                 from common.h:82,`
`                 from link.h:23,`
`                 from router.cpp:20` 
`/root/knxd/knxd/libfmt/fmt/format.h:372:17: note:   ‘fmt::internal::isnan’`
` inline DummyInt isnan(...) { return DummyInt(); }`
`                ^`
`At global scope:`
`cc1plus: warning: unrecognized command line option ‘-Wno-subobject-linkage’`
`Makefile:518: die Regel für Ziel „router.o“ scheiterte`
`make[4]: *** [router.o] Fehler 1`
`make[4]: Verzeichnis „/root/knxd/knxd/src/libserver“ wird verlassen`
`Makefile:394: die Regel für Ziel „all-recursive“ scheiterte`
`make[3]: *** [all-recursive] Fehler 1`

**Comment by smurfix** [comment]
That seems simple. Try commit d39a6df please.

**Comment by chefkoch009** [comment]
for you ;-)  
thank you...now it works

**Comment by karls0** [comment]
Hi smurfix, I have pretty much the same problem. I run Ubuntu 14.04.5 LTS in a VM (along with Asterisk ans OMD. When I try to build I get 
`At global scope:
cc1plus: warning: unrecognized command line option "-Wno-subobject-linkage" [enabled by default]
make[4]: *** [knxd-knxd.o] Fehler 1
make[4]: Verzeichnis »/root/knxd/src/server« wird verlassen
make[3]: *** [all-recursive] Fehler 1
make[3]: Verzeichnis »/root/knxd/src« wird verlassen
make[2]: *** [all-recursive] Fehler 1
make[2]: Verzeichnis »/root/knxd« wird verlassen
make[1]: *** [all] Fehler 2
make[1]: Verzeichnis »/root/knxd« wird verlassen
dh_auto_build: make -j1 returned exit code 2
make: *** [build] Fehler 2
dpkg-buildpackage: Fehler: Fehler-Exitstatus von debian/rules build war 2
`
I looked at your commit, but my line 107 is completely different. What can I do to build knxd?
TIA, regards  Karl
