### ISSUE TITLE
Driver tpuarts not found in 0.14.10

### ISSUE THREAD

**Issue by chefkoch009** [knxd/knxd#243]
with this Release I get the message "Driver tpuarts not found" with the same startup parameters like in the prev. version.

**Comment by chefkoch009** [comment]
And if I use it in that way:

KNX/LAN-GW === [eth1 -> knxd ->eth0] === LAN with ETS 

with:
`knxd -t1023 -e1.1.1 -E1.1.2:8 -D -R -T -S -n test --Interface=ens3  -b ipt:10.9.8.6`

the knxd isn't shown in ETS5 automaticly.

**Comment by chefkoch009** [comment]
in rel 0.14.10 also no tpuarts driver

**Comment by smurfix** [comment]
It's now called "tpuart" in the .ini file. 
```
desk ~/src/knxd$ src/server/knxd -l driver
usb
dummy
ipt
ft12cemi
ft12
ip
tpuart
desk ~/src/knxd$ src/server/knxd_args -b tpuarts:/dev/null
[A.tpuarts]
device = /dev/null
driver = tpuart
[main]
connections = A.tpuarts
systemd = systemd

```

**Comment by smurfix** [comment]
As to your "knxd isn't shown in ETS5" problem: please show the output of "ip addr" and "ip route".

**Comment by chefkoch009** [comment]
ah, ok...nice to know. now I get with:
` knxd -e 1.1.1 -E 1.1.2:5  -DTRS -c -b tpuart:/dev/ttyKNX1`
this message:
`I don't know of options for tpuart`
`E00000055: [ 1:main] There is no KNX addr= in section 'main'.`
`F00000000: [ 1:main] Error setting up the KNX router.`

I haven't found a docu of the new option-set.

**Comment by chefkoch009** [comment]
found the error....my mistake... i took the old version of knxd_args.
The connection with direct IP works perfect. Programming, getting deviceinfos also working great.
 But it isn't recognized by ETS.
`knxd_args -t200 -f9 -e1.1.1 -E1.1.2:3  -DTR -S -i 6720 --Interface=ens3  -b ipt:10.9.8.6`

**Comment by smurfix** [comment]
Again: please show the output of "ip addr" and "ip route".

**Comment by chefkoch009** [comment]
the ens3 interface points not to default route. because i've to nic's. can I contact you with PN or something else to explain some things. I think it would be interesting for you.

**Comment by smurfix** [comment]
Sure. email matthias@urlichs.de
