### ISSUE TITLE
Apple Home -> Homebridge -> KNXD: no reaction

### ISSUE THREAD

**Issue by RossMax2** [knxd/knxd#248]
Hallo,

I finally managed to install my rapsi according to the tutorial "boerny blog"

Systemctl. Status shows no errors for homebridge and Knxd
Homebridge is connected to the Home App

but Switching a light in Home App doesn't has an effect on the real light.

In the Busmonitor (ETS4) no entry shows up.
in the Busmonitor: knxtool groupsocketlisten ip:localhost on the rapsi an entry show up.

my Knxd.service is as follows:

KNXD_OPTS="-e 1.1.201 -E 1.1.202:10 - B single --send-delay=70 -b ipt: 192.168.178.xx"
I use an MDT IP Interface scn ip 000.01, which has the above mentioned IP-Adress

I hope somebody can give me a hint how to solve the problem.
If more information is needed, please call for

I´m not an expert, so I would appreciate an answer which is not to complex. Tank you.

Greetings Max

**Comment by snowdd1** [comment]
I guess the blank in `- B single` is only a typo here and not copied from the actual knxd.service, is it?

**Comment by snowdd1** [comment]
Apart from that, your tests show that homebridge is speaking with knxd (you can see the telegram using the knxtool commands) but knxd is not speaking to your MDT IP interface.

If you do `knxtool groupsocketlisten ip:localhost` os the raspi, do any other telegrams show? Test it using a physical wall switch e.g.?

**Comment by RossMax2** [comment]
1) You are right about the space between - and B.
2) There can be seen many more entries in the KNXTOOL-Monitor than only the ones triggered by home-app. 
3) yes, there ist a switch

**Comment by smurfix** [comment]
Let's start with the knxd version you're using. stable/v0.12 or master/v0.14? 

Please add "-f 9 -t 1023" to the start of the command line, try again(*), put the resulting log into a pastebin, and add the paste's link to this issue.

(*) Please do this with the wall switch responsible for the light in question as well as using Homebridge.

**Comment by RossMax2** [comment]
Sorry for late replay. Had to leave the house yesterday very suddenly.

1) pi@raspberrypi:~ $ knxd -V
knxd 0.14.11:88b5653
Usage: knxd configfile [main-section]

2) # configuration for knxd.service

KNXD_OPTS="-f9 -t 1023 -e 1.1.201 -E 1.1.202:10 -B single --send-delay=70 -b ipt:192.168.178.16"

Is that what you ment?
Where do I find the log?

I added some information into a pastebin. Maybe it is already helpful.
https://pastebin.com/uqSPiUpm

**Comment by smurfix** [comment]
>  Where do I find the log?

*Sigh*. journalctl -uknxd --since="10 min ago" (or whatever).

**Comment by RossMax2** [comment]
I get the reply: no journal files were found

**Comment by snowdd1** [comment]
Try `sudo journalctl -uknxd --since="10 min ago" `

**Comment by RossMax2** [comment]
That worked!

The Log ist Minute 15:40 - 15:41.
During that time I first turned on the light by switch (and off)
Then I turned in on by the home-app (and off)

Pastebin: https://pastebin.com/KnjE8cBP

**Comment by smurfix** [comment]
Sorry, that's still not enough logging. Or rather, it is but I'm getting blind decoding all the packets.

Please repeat with
`
KNXD_OPTS="-f9 -t 1023 -e 1.1.201 -E 1.1.202:10 -B single -B log --send-delay=70 -b ipt:192.168.178.16 -B log"`

**Comment by RossMax2** [comment]
I hope, this will do:

https://pastebin.com/7HbpptaC

**Comment by smurfix** [comment]
Possibly, as soon as you turn off the pastebin's "private" flag …

**Comment by RossMax2** [comment]
Sorry

https://pastebin.com/PsTfQgLJ

**Comment by smurfix** [comment]
Those updated options did not take. Did you run "systemctl daemon-reload" before restarting knxd? In fact, did you restart knxd at all before generating this log, given that it's been running for almost an hour?

**Comment by RossMax2** [comment]
Now I did the following:

sudo systemctl daemon-reload
sudo systemctl restart knxd.service
Light on (switch)
Light off (switch)
Light on (App)
Light off (App)

https://pastebin.com/AD7eCV4e

**Comment by smurfix** [comment]
*Gah*. Please send the journalctl output to a file and paste that. Or at least make the teminal window wide enough that stuff doesn't get cut off. :-(

**Comment by RossMax2** [comment]
Sorry, I am pretty much a beginner and really appreciate your patience.

https://pastebin.com/KpqJcZHJ

**Comment by smurfix** [comment]
```
Apr 20 10:12:59 raspberrypi knxd[2451]: Layer 0 [15:log/A.ipt             361.091] Recv L_Data urgent from 1.1.200 to 15/5/10 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
Apr 20 10:12:59 raspberrypi knxd[2451]: Layer 5 [14:single/A.ipt          361.091] drop packet from 1.1.200

```
Is 1.1.200 the address of your KNX/IP interface?
There are a lot of packets which get dropped because their source address is 1.1.200. This makes no sense. What kind of interface (manufacturer/type) is that?

**Comment by RossMax2** [comment]
Yes, 1.1.200 is the Adress of my MDT SCN 000.01 IP-Interface

**Comment by RossMax2** [comment]
Do you think there could be a relationship to the Gira HS Settings?

![einstellungen hs](https://cloud.githubusercontent.com/assets/27732703/25276502/d5583c6e-269a-11e7-8ae7-b58eb3118922.JPG)

Are the packages just unnormal or do you think they are the reason for the main problem?

**Comment by Makki1** [comment]
Am 21.04.2017 um 14:02 schrieb RossMax2:
> Do you think there could be a relationship to the Gira HS Settings?
> 

No, at least not this setting; Thats not related to KNX, it's for
something different.. (HS Monitor or qHSMon)

If I remeber your last posts correectly, though, it might be some loop
in your topology

Michael

**Comment by RossMax2** [comment]
KNXD_OPTS="-f9 -t 1023 -e 1.1.201 -E 1.1.202:10 -B single -B log --send-delay=70 -b ipt:192.168.178.16 -B log"

Can somebody explain what the two adresses (1.1.201 and 1.1.202) exactly mean and what ist the meaning of :10

**Comment by snowdd1** [comment]
`-e 1.1.201` is the physical address of the knxd itself.  
`-E 1.1.202:10` the clients connecting to knxd get the addresses from 1.1.202 to 1.1.212 (202+10)

Maybe `--eibaddr=1.1.201` is more readable than -e 1.1.201  
And `--client-addrs=1.1.202:10` more than -E

**Comment by RossMax2** [comment]
It works !!!!!!! First Light switched on by Siri!

new programming of the IP-Interface and the following line:
KNXD_OPTS="-e 1.1.251 -E 1.1.252:4 -u /tmp/eib -b ipt:192.168.178.16"

Thank you very much for your support !!!!
