### ISSUE TITLE
Changed Logging from 0.14.12 to 0.14.13? Not verbose any more ...

### ISSUE THREAD

**Issue by bmxp** [knxd/knxd#252]
I updated knxd from 0.12 to 0.14 but communication to SmartHomeNG broke somehow. Unfortunately the communication at another site from SmartHomeNG to 0.14.12 work with the same Siemens Ip Interface.
Now going back to 0.12 it works again. Strange.

**Comment by bmxp** [comment]
And it does not work any more. Hm, can I pull a specific commit like 0.14.12 somehow?

**Comment by smurfix** [comment]
Possibly something broke in 0.14.13. Investigating.

**Comment by smurfix** [comment]
Does v0.14.14 work for you? If not, what's your configuration?

**Comment by bmxp** [comment]
Did not try it so far. I will test ASAP...

**Comment by bmxp** [comment]
Now tested v0.14.15 and I get the same verbose logging as with v0.12.
