### ISSUE TITLE
TPUART USB interface: no startup possbile

### ISSUE THREAD

**Issue by vniklas123** [knxd/knxd#253]
Trying to start knxd with TPUART USB interface without success:

Command line parameter:
knxd -e 0.0.1 -E 0.0.2:8 -D -T -R -S -f9 -t1023 -b tpuarts:/dev/ttyKNX1

Result:

> Layer 0 [12:A.tpuarts/log       0.002] Insert 11:LowF / 10:tpuart
Layer 0 [12:A.tpuarts/log       0.003] Setup
Layer 0 [14:A.tpuarts/log       0.005] Insert 13:TPU_ser / 11:LowF
Layer 0 [12:A.tpuarts/log       0.007] Filter single not found
Layer 0 [14:A.tpuarts/log       0.008] Setup
Layer 0 [14:A.tpuarts/log       0.008] Setup OK: yes
Layer 0 [12:A.tpuarts/log       0.009] Setup OK: yes
Layer 3 [ 9:A.tpuarts/Conn      0.009] registerLink: 9:A.tpuarts
Layer 3 [ 9:A.tpuarts/Conn      0.009] Start: cfg:A.tpuarts
Layer 5 [ 9:A.tpuarts/Conn      0.011] down => >up
Layer 5 [ 9:A.tpuarts/Conn      0.011] Starting
Layer 0 [12:A.tpuarts/log       0.012] Start
Layer 0 [14:A.tpuarts/log       0.012] Start
Layer 0 [13:A.tpuarts/TPU_ser   0.015] Opened /dev/ttyKNX1 with baud 19200
Layer 2 [13:A.tpuarts/TPU_ser   0.016] Opened
Layer 2 [13:A.tpuarts/TPU_ser   0.017] Buffer Setup on fd 4
Layer 0 [14:A.tpuarts/log       0.017] Started
Layer 8 [11:A.tpuarts/LowF      0.017] state: new > start
Layer 0 [11:A.tpuarts/LowF      0.017] SendReset 01
Layer 0 [14:A.tpuarts/log       0.017] Send(001): 01
Layer 4 [ 9:A.tpuarts/Conn      0.019] >up
Layer 4 [ 9:A.tpuarts/Conn      0.022] is >up
Layer 0 [11:A.tpuarts/LowF      0.471] SendReset 01
Layer 0 [14:A.tpuarts/log       0.473] Send(001): 01
Layer 0 [11:A.tpuarts/LowF      0.972] SendReset 01
Layer 0 [14:A.tpuarts/log       0.972] Send(001): 01
Layer 8 [11:A.tpuarts/LowF      1.472] state: in_reset > error
Layer 0 [14:A.tpuarts/log       2.474] Stop
Layer 0 [14:A.tpuarts/log       2.474] Stopped
Layer 8 [11:A.tpuarts/LowF      2.474] state: error > new
Layer 0 [12:A.tpuarts/log       2.474] Stopped
Layer 5 [ 9:A.tpuarts/Conn      2.475] >up => down
Layer 4 [ 9:A.tpuarts/Conn      5.606] is down
F00000000: [ 9:A.tpuarts] Link down, terminating
Layer 4 [ 9:A.tpuarts/Conn      5.609] Stopping
Layer 5 [ 9:A.tpuarts/Conn      5.610] down/error => >down
Layer 4 [ 9:A.tpuarts/Conn      5.610] down/error
Layer 4 [ 9:A.tpuarts/Conn      5.611] is down
Layer 0 [12:A.tpuarts/log       5.612] Closing
Layer 2 [11:A.tpuarts/LowF      5.612] Close
Layer 0 [14:A.tpuarts/log       5.612] Closing
Layer 2 [13:A.tpuarts/TPU_ser   5.612] Close

Any idea?

**Comment by smurfix** [comment]
You don't get a reply to the Reset command. Bad firmware on the tpuart?

**Comment by vniklas123** [comment]
The firmware is coming from the manufacturer busware and should do the following:
"This will allow native access to TPUART providing an emulated serial port (CDC ACM) on host PC"
I reflashed the TPUART, the green lamp is on.
Do you think it is an hardware problem?
How can I check?

**Comment by smurfix** [comment]
Is the red LED on? that's the bus power. The tpuart will not reply without a bus connection.

**Comment by vniklas123** [comment]
Yes, the red light is also on. My knx environment should be ok. I tested with a different interface.
I can send the stick to you if you have a chance for testing.

**Comment by smurfix** [comment]
Basically, the TPUART is supposed to reply with a 0x03 byte when you send it a reset (0x01).
If it does not, then either another program is also listening on the device and eating the byte, or it's broken and you should send it to the manufacturer.

**Comment by vniklas123** [comment]
Hello,
I've checked with a new TPUART, but the same error.
How can I check if another program is eating the byte?

**Comment by Bl00d-B0b** [comment]
Hello,

I have very similar issue. I use raspberry PI 2, and I use Busware ROT http://busware.de/tiki-index.php?page=ROT.... I install KNXD, and receiving very similar problem:

Opened /dev/ttyKNX0 with baud 19200
Opened
Buffer Setup on fd 8
Started
state: new > start
SendReset 01
Send(001): 01
>up
is >up
SendReset 01
Send(001): 01
SendReset 01
Send(001): 01
**state: in_reset > error**
Stop
Stopped

My assumption, than my  /dev/ttyAMA0 (link to: /dev/ttyKNX0) is used by some other service. my raspberry is in last build with last firmware....

My boot/cmdline.txt file is look like:
 dwc_otg.lpm_enable=0 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait

I also disable serial-getty
 sudo systemctl stop serial-getty@ttyAMA0.service
 sudo systemctl disable serial-getty@ttyAMA0.service

but does not help. how I can debug, to see which service possible can use ttyAMA0... or where is a problem?

Edward

**Comment by Bl00d-B0b** [comment]
My KNX bus is not yet connected. I just install and configure knxd. 

Maybe when I connect a bus, then it's start to work? maybe this is an issue?

Ed

**Comment by smurfix** [comment]
The tpuart chip will not work without a bus connection.
I'll add that to the README.

**Comment by Bl00d-B0b** [comment]
Hello,

Connect my KNX Bus (Just FYI: I use this device on raspberry PI 2: http://busware.de/tiki-index.php?page=ROT) to http://zennio.com/products/lighting/lumento-x4 LED Light controller.

connection is simple (Red to Red, Black to Black, Distance 10 cm). LED light controller is powered with 24V. 

But I have the same issue with errors:
up
 is >up
 SendReset 01
 Send(001): 01
 SendReset 01
 Send(001): 01
state: in_reset > error
 Stop
 Stopped

Any ideas? how I can check, where is a problem?

Ed

**Comment by smurfix** [comment]
So is the red LED on the KNX adapter on?
Your description lacks a KNX power supply. That is *not* optional.

**Comment by Bl00d-B0b** [comment]
Yes, i connect 24v power supply to my LED controller. And when I press and hold test button, then i see a test. But i am not sure about other programm button.

**Comment by Bl00d-B0b** [comment]
But the led is off. I am new in knx. Where i can get description how to connect knx bus and power supply?
