### ISSUE TITLE
compilation on Debian Jessie 

### ISSUE THREAD

**Issue by Ambly** [knxd/knxd#257]
I had an old version ("stable" from february) running very fine on Jessie (i386) for some time using a Siemens interface IP/ KNX N148/21, together with linknx, and wanted to upgrade to "master" (so v0.14.13 as of today).

"dpkg-buildpackage -b -uc" runs almost fine (configuration is fine, compilation is OK), but at the end the script "tools/test.sh" is issuing an error, leading to no .deb being produced:

```
+ E=54321
+ test -z 54321
+ echo T3
T3
+ rm -f /tmp/filePwWcoi /tmp/fileEyJ1Ig /tmp/filezseWEh /tmp/fileoOIVch /tmp/filee9Yvuk /tmp/fileFbSedl /tmp/fileu3n8Gk /tmp/fileSqj3lj /tmp/file3ecVZj /tmp/fileSipEMj /tmp/fileWt7uJ7
debian/rules:48: recipe for target 'override_dh_auto_test' failed
make[1]: *** [override_dh_auto_test] Error 1
make[1]: Leaving directory '/home/ambly/knxd'
debian/rules:14: recipe for target 'build' failed
make: *** [build] Error 2
```

I then tried the "stable" branch (0.12.16, as of today) and got the very same issue.

So I commented out the line 48 in debian/rules, and got "stable" branch .deb, which I installed. Socket and service are both running fine, but "knxtool groupswrite ..." has no effect on the bus (I cannot switch a light on or off).

Doing the same (commenting out line 48 in debian.rules) on the "master" branch also results in a .deb, which I installed, but then knxd.service has trouble starting.

I moved back to "v0.10", and compilation was perfect (no need to comment anything in the sources). After installation of the .deb, everything works fine, as it used to be.

for v0.10, I use (and it works):
KNXD_OPTS="-f9 -t65400 -e 1.2.1 -u /tmp/eib -b ipt:192.168.1.10"
for v0.12.xx, I use (and the bus is not responding):
KNXD_OPTS="-f9 -t65400 -e 1.2.1 -E 1.2.2:8 -u /tmp/eib -b ipt:192.168.1.10"

I think I have all the dependencies installed, including the newly required (libev-dev for v0.12, cmake , ...). I also think I should not try to by-pass/comment the tests in the dpkg-buildpackage process. As I do not now how to interpret the tests results, I wonder how to solve the trouble.

[
On a side note (unrelated I guess): I had no "indent" program installed, so the corresponding .configure step was issuing:
checking for indent... no
and the answer "no" was later used by dpkg-buildpackage in the building of EIBConnection.php and EIBConnection.cs, which was causing some warning, but no drama.
]

**Comment by smurfix** [comment]
Well, the 30 lines or so before that E=… message would have been nice.

**Comment by Ambly** [comment]
Sure. Sorry about that.

As the output is large, I wasn't sure how much to put here. I redirected everything to a file:
`
git checkout stable

dpkg-buildpackage -b -uc > output.txt
`
but some lines were on the console only, and some (most) in the output.txt file only...

So here is a complete (sorry) output (copied/pasted from the console), when I try to compile the stable branch:
[console-output.txt](https://github.com/knxd/knxd/files/991378/console-output.txt)
the last 40 lines being:

`
+ diff -u tools/logs/monitor3 /tmp/filewCZnHY
--- tools/logs/monitor3	2017-05-10 22:09:05.577766005 +0200
+++ /tmp/filewCZnHY	2017-05-11 00:15:55.690093937 +0200
@@ -1,7 +1,4 @@
-LPDU: BC 41 00 0A 03 C1 00 00 CA :L_Data low from 4.1.0 to 1/2/3 hops: 04 T_DATA_XXX_REQ A_GroupValue_Read
-LPDU: BC 41 03 0A 03 C1 00 84 4D :L_Data low from 4.1.3 to 1/2/3 hops: 04 T_DATA_XXX_REQ A_GroupValue_Write (small) 04 
 LPDU: BC 42 04 0A 03 D1 00 85 58 :L_Data low from 4.2.4 to 1/2/3 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write (small) 05 
 LPDU: BC 43 02 0A 03 E1 00 86 6C :L_Data low from 4.3.2 to 1/2/3 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 06 
-LPDU: BC 41 04 0A 03 C1 00 87 49 :L_Data low from 4.1.4 to 1/2/3 hops: 04 T_DATA_XXX_REQ A_GroupValue_Write (small) 07 
 LPDU: BC 43 03 0A 03 E1 00 88 63 :L_Data low from 4.3.3 to 1/2/3 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 08 
 LPDU: BC 42 05 0A 03 D4 00 80 04 05 06 5E :L_Data low from 4.2.5 to 1/2/3 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write 04 05 06 
+ E=321
++ dirname tools/test.sh
+ diff -u tools/logs/cache /tmp/file3fxMG1
--- tools/logs/cache	2017-05-10 22:09:05.573766055 +0200
+++ /tmp/file3fxMG1	2017-05-11 00:15:57.770067788 +0200
@@ -1,4 +1,3 @@
-Write from 4.2.5: 04 05 06 
-new position: 6
-1/2/3
+Write from 4.1.4: 07
+new position: 2
 
+ E=4321
++ dirname tools/test.sh
+ diff -u tools/logs/listen /tmp/filePm7ve1
--- tools/logs/listen	2017-05-10 22:09:05.573766055 +0200
+++ /tmp/filePm7ve1	2017-05-11 00:15:55.686093987 +0200
@@ -1,7 +1,4 @@
-Read from 4.1.0
-Write from 4.1.3: 04
 Write from 4.2.4: 05
 Write from 4.3.2: 06
-Write from 4.1.4: 07
 Write from 4.3.3: 08
 Write from 4.2.5: 04 05 06 
+ E=54321
+ test -z 54321
+ echo T3
T3
+ rm -f /tmp/fileJloTcY /tmp/fileVeUeGX /tmp/filewCZnHY /tmp/file3fxMG1 /tmp/filePm7ve1 /tmp/filermuHa2 /tmp/fileou6Xx0 /tmp/file2DvEj0 /tmp/file9Kou20 /tmp/fileqygJ13 /tmp/fileALCEdS
debian/rules:48: recipe for target 'override_dh_auto_test' failed
make[1]: *** [override_dh_auto_test] Error 1
make[1]: Leaving directory '/home/ngarnier/tmp/knxd'
debian/rules:14: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: erreur: debian/rules build a produit une erreur de sortie de type 2
`

Thank you.

**Comment by chewy21** [comment]
sudo apt-get install debhelper cdbs autoconf automake libtool libusb-1.0-0-dev libsystemd-daemon-dev dh-systemd cmake libev-dev 

try this, it just work for me last night ... knxd service isup !

**Comment by Ambly** [comment]
Thanks @chewy21 . 
I've just checked, all these packages were already installed, in their latest version.

I'm going to try on another Debian box, on which I also need to upgrade knxd from v0.10.

**Comment by smurfix** [comment]
This is not a problem with the installed packages (or not).
Please re-try with current v0.14.

**Comment by Ambly** [comment]
Thanks @smurfix 

I've just tried with "v0.14" (complete output: [output-v0.14.txt](https://github.com/knxd/knxd/files/998524/output-v0.14.txt) ) and then "master" (complete output:
 [output-master.txt](https://github.com/knxd/knxd/files/998525/output-master.txt) ); both compile fine, up to the tests, which both give:

```
make[1]: Entering directory '/home/ngarnier/knxd'
bash tools/test.sh
++ pwd
++ pwd
++ pwd
++ pwd
++ pwd
+ export PATH=/home/ngarnier/knxd/src/tools/.libs:/home/ngarnier/knxd/src/tools:/home/ngarnier/knxd/src/server/.libs:/home/ngarnier/knxd/src/server:/home/ngarnier/knxd/src/server:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
+ PATH=/home/ngarnier/knxd/src/tools/.libs:/home/ngarnier/knxd/src/tools:/home/ngarnier/knxd/src/server/.libs:/home/ngarnier/knxd/src/server:/home/ngarnier/knxd/src/server:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
++ tempfile
+ EF=/tmp/fileFTOC1w
+ knxd -e 1.2.3 --stop-right-now
+ knxd -e 1.2.3 --stop-right-now -b dummy:
+ knxd -B log -e 1.2.3 --stop-right-now -b dummy: -b dummy:
+ echo 'Bad argument C'
Bad argument C
+ cat /tmp/fileFTOC1w
E00000055: [ 1:main] There is no KNX addr= in section 'main'.
F00000000: [ 1:main] Error setting up the KNX router.
+ exit 1
debian/rules:48: recipe for target 'override_dh_auto_test' failed
make[1]: *** [override_dh_auto_test] Error 1
make[1]: Leaving directory '/home/ngarnier/knxd'
debian/rules:14: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: erreur: debian/rules build a produit une erreur de sortie de type 2
```

I'm not familiar with the way the tests are performed, and I admit I have no clue to search for what is going wrong.

I've tried older versions on another Debian box, and all versions before v0.14.8 (included) are compiling/testing fine there, while all version after v0.14.9 (included) are failing tools/tests.sh.

On the "production" server (the one I'm the most interested in upgrading knxd on, and the one for which I'm reporting compilation outputs), the last v0.10 is compiling/testing fine, but not the last v0.12 (v0.12.16), and none of the v0.14.

There are no obvious differences between the two boxes, beside RAM amount. The only thing that may be related is that the "production" one (which fails with earlier versions) has pthsem and pthsem-dev installed (required by linknx). Although the other box has no trace of pthsem but also fails with last versions, could that be an issue?

**Comment by smurfix** [comment]
This test simply runs `knxd -B log -e 1.2.3 --stop-right-now -b dummy: -b dummy:` and checks whether that fails. It should not, and it does not fail this test on my system (or on Travis). Are all libraries up-to-date? Which Debian version are you using?

This requires some debugging with gdb, ideally on your system. Can we set up a teamviewer session or similar? please email me directly (matthias@urlichs.de).

No, libpth is not a problem. knxd ignores it.

**Comment by Ambly** [comment]
Thank you @smurfix for you kind message. I'll send you an e-mail shortly.

I believe everything is up-to-date (Debian 8.8), although along the years, the system got several dist-upgrades, which might have left subtle traces (e.g., when systemd arrived with jessie), but should be negligible.

**Comment by Ambly** [comment]
version v0.14.15 (current master) is compiling, testing, and installing fine.

What I completely missed was that the firewall should allow multicast adresses for tools/test.sh to run properly.

Now I have to set the configuration options properly.
Thank you.

**Comment by Ambly** [comment]
tested on another box (different hardware and different configuration) with Jessie 8.8, and v0.14.15 (current master) is again compiling, testing, and installing fine.
