### ISSUE TITLE
exampels with dialog and KNXD. or other uses with knxd

### ISSUE THREAD

**Issue by espenbo** [knxd/knxd#258]
Hello

I would like more examples of how I can use knxd.
I thought of making a simple dialogue bash script, that have menus with rooms and can turn lights on/off. Sett room temperature, read room temperature.

I  hope more people can share what you're using knxd for.
So please share your bash scripts, setup with conky, LCD screens, node-red....

My start with dialog. Not everything working yet. And I haven’t found a good way to show status yet.

https://github.com/espenbo/dialog_knxd/blob/master/test-menu.sh

**Comment by smurfix** [comment]
Umm, this is not really an issue per se. Please ask on the mailing list; examples should probably go to the wiki.

**Comment by espenbo** [comment]
Sorry for placing it the wrong place.
I can't find any mailing list, but I did find a group on googel groups. I will post it there.

Thanks for your support on knxd
