### ISSUE TITLE
v0.14.15 does not build with --disable-groupcache

### ISSUE THREAD

**Issue by mike-kfed** [knxd/knxd#264]
running `./configure --disable-groupcache` causes the error at the end of this report. configure help says groupcache is yes by default, this implies it can be turned off - if it cannot be switched off I would vote for removing the config option. If it should be possible to disable it, then this issue is valid too.

```
Making all in server
libtool: link: x86_64-pc-linux-gnu-g++ -std=gnu++11 -march=core2 -O2 -pipe -msse4.1 -std=c++0x -Wno-subobject-linkage -Wl,--whole-archive -Wl,../backend/libbackend.a -Wl,../libserver/libserver.a -Wl,--no-whole-archive -Wl,-O1 -o knxd knxd-knxd.o  -Wl,--as-needed ../libserver/libeibstack.a ../common/libcommon.a ../usb/libusb.a -lusb-1.0 -lev -lfmt
libtool: link: x86_64-pc-linux-gnu-g++ -std=gnu++11 -march=core2 -O2 -pipe -msse4.1 -std=c++0x -Wno-subobject-linkage -Wl,-O1 -o knxd_args knxd_args.o  -Wl,--as-needed ../common/libcommon.a -lev -lfmt
../libserver/libeibstack.a(router.o): In function `Router::setup()':
router.cpp:(.text+0x840a): undefined reference to `CreateGroupCache(Router&, std::shared_ptr<IniSection>&)'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:486: knxd] Error 1
make[2]: *** [Makefile:393: all-recursive] Error 1
make[1]: *** [Makefile:441: all-recursive] Error 1
make: *** [Makefile:377: all] Error 2
```

**Comment by smurfix** [comment]
Thanks. Should be fixed now (in master / v0.14). Please test.

**Comment by Makki1** [comment]
Just my 5ct:

It should *NOT* be possible to disable groupcache at all, because it's
an really essential feature which other applications should be able to
rely on.

So, if there are no really good reasons to disable it (save some few
bytes of ram? really?), I'd vote to remove the config-option and enable
it always (the hard way).
Any of the programs I know (80% and some of them I also wrote, sigh)
will get into serious troubles without groupcache.. And/or it will flood
the high-performance KNX with thousands of read/response datagrams..

I admit, a long time ago, maybe I (amongst others) introduced groupcache
into eibd - but it is still a very good concept to address some flaws of
the event-driven KNX like a visualisation waking up from standby - for
example - needing to know all current states.
Thats the idea behind groupcache.

Michael

Am 17.05.2017 um 17:53 schrieb Michael Kefeder:
> running |./configure --disable-groupcache| causes the error at the end
> of this report. configure help says groupcache is yes by default, this
> implies it can be turned off - if it cannot be switched off I would vote
> for removing the config option. If it should be possible to disable it,
> then this issue is valid too.
> 
> |Making all in server libtool: link: x86_64-pc-linux-gnu-g++ -std=gnu++11
> -march=core2 -O2 -pipe -msse4.1 -std=c++0x -Wno-subobject-linkage
> -Wl,--whole-archive -Wl,../backend/libbackend.a
> -Wl,../libserver/libserver.a -Wl,--no-whole-archive -Wl,-O1 -o knxd
> knxd-knxd.o -Wl,--as-needed ../libserver/libeibstack.a
> ../common/libcommon.a ../usb/libusb.a -lusb-1.0 -lev -lfmt libtool:
> link: x86_64-pc-linux-gnu-g++ -std=gnu++11 -march=core2 -O2 -pipe
> -msse4.1 -std=c++0x -Wno-subobject-linkage -Wl,-O1 -o knxd_args
> knxd_args.o -Wl,--as-needed ../common/libcommon.a -lev -lfmt
> ../libserver/libeibstack.a(router.o): In function `Router::setup()':
> router.cpp:(.text+0x840a): undefined reference to
> `CreateGroupCache(Router&, std::shared_ptr<IniSection>&)' collect2:
> error: ld returned 1 exit status make[3]: *** [Makefile:486: knxd] Error
> 1 make[2]: *** [Makefile:393: all-recursive] Error 1 make[1]: ***
> [Makefile:441: all-recursive] Error 1 make: *** [Makefile:377: all]
> Error 2 |

**Comment by smurfix** [comment]
@Makki1 Thanks, you raise a valid point. That `configure.ac` option pre-dates my involvement with knxd …

**Comment by mike-kfed** [comment]
I confirm that `--disable-groupcache` configure works now, and I have no comparison between running with groupcache off and on, therefore I cannot give a meaningful input if it should be mandatory or optional. I just found that this option misbehaves ;)

**Comment by Makki1** [comment]
Understood, I still vote to just remove --disable-groupcache from configure.ac at all, it doesnt save anything or is (not) needed by anyone;
The history was: after adding this feature to eibd many years ago, it was added as a "safeguard" in case groupcache causes troubles - which has never been the case..
(and we see here, people are using it still, without seeing the dramatic implications..)
