### ISSUE TITLE
KNXD stops working after KNX bus power failure

### ISSUE THREAD

**Issue by 1337bacon** [knxd/knxd#268]
Hi,
I found a problem during knx bus power failure. I am using Raspberry Pi, Busware KNX tpuart interface and knxd v0.12.16. 
Problem occurs if you try to read/write group address when KNX bus is offline and of course you don't get a reply in that moment, but when the KNX bus is online again writing or reading from the KNX bus still doesn't work. 
It is easily to recreate the problem by following this steps:

- everything up and running and you can read/write group address from ETS
- disconnect only KNX bus from the KNX-TPUART interface 
- read/write group address from ETS while the KNX bus is disconnected
- re-connect KNX bus to the KNX-TPUART interface
- try to read/write group address from ETS again, writing to bus doesn't work but receiving data from works
- after restarting of knxd service, everything works ok

If you don't read/write group address when the bus is disconnected, then everything works normally after reconnecting the bus.

**Comment by smurfix** [comment]
The tpuart driver should discover this situation (the IC fails to reply to keepalive inquiries when it has no power) and take down the interface temporarily.

Please provide your command line, and paste the log (use "-B log -t 1023 -b tpuart:…").

**Comment by 1337bacon** [comment]
I couldn't use -B log option
it says:
 [root@CC comfort]# knxd -e1.1.155 -E1.1.156:8 -D -T -S -B log -t1023 -f9 -b tpuarts:/dev/ttyKNX1
knxd: Layer 2 [ 4:tpuarts:/dev/ttyKNX1 0.001] Open
knxd: Layer 2 [ 4:tpuarts:/dev/ttyKNX1 0.001] Open
Filter 'log' not supported

First the knx bus was connected and I could turn on/off output on knx actuator, then I disconnected knx bus and tried to send some read/write requests then I connected the bus back and again tried to read/write but it didn't work any more.

[knxd_log.txt](https://github.com/knxd/knxd/files/1041608/knxd_log.txt)

**Comment by 1337bacon** [comment]
Cannot build the master version: (v0.14.16)

```
ar cru libbackend.a ft12.o tpuart.o ncn5120.o eibnetrouter.o eibnettunnel.o log.o dummy.o nat.o fqueue.o fpace.o
ar: `u' modifier ignored since `D' is the default (see `U')
ranlib libbackend.a
make[3]: Leaving directory '/home/comfort/knxd/contrib/arch-build-system/src/knxd/src/backend'
Making all in server
make[3]: Entering directory '/home/comfort/knxd/contrib/arch-build-system/src/knxd/src/server'
g++ -DHAVE_CONFIG_H -I. -I../..  -I../../src/libserver -I../../src/backend -I../../src/common -I../../src/usb -I/usr/include/libusb-1.0  -Wno-missing-field-initializers -DLIBEXECDIR="\"/usr/lib\"" -D_FORTIFY_SOURCE=2  -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -std=c++0x -Wno-subobject-linkage -MT knxd-knxd.o -MD -MP -MF .deps/knxd-knxd.Tpo -c -o knxd-knxd.o `test -f 'knxd.cpp' || echo './'`knxd.cpp
mv -f .deps/knxd-knxd.Tpo .deps/knxd-knxd.Po
/bin/sh ../../libtool  --tag=CXX   --mode=link g++  -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -std=c++0x -Wno-subobject-linkage -Wl,--whole-archive,../backend/libbackend.a,../libserver/libserver.a,--no-whole-archive -Wl,-O1,--sort-common,--as-needed,-z,relro -o knxd knxd-knxd.o ../libserver/libeibstack.a ../common/libcommon.a ../usb/libusb.a -lusb-1.0 -lsystemd -lev -lev -lfmt
libtool: link: g++ -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -std=c++0x -Wno-subobject-linkage -Wl,--whole-archive -Wl,../backend/libbackend.a -Wl,../libserver/libserver.a -Wl,--no-whole-archive -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z -Wl,relro -o knxd knxd-knxd.o  ../libserver/libeibstack.a ../common/libcommon.a ../usb/libusb.a -lusb-1.0 -lsystemd -lev -lfmt
g++ -DHAVE_CONFIG_H -I. -I../..  -I../../src/libserver -I../../src/backend -I../../src/common -I../../src/usb -I/usr/include/libusb-1.0  -Wno-missing-field-initializers -D_FORTIFY_SOURCE=2  -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -std=c++0x -Wno-subobject-linkage -MT knxd_args.o -MD -MP -MF .deps/knxd_args.Tpo -c -o knxd_args.o knxd_args.cpp
mv -f .deps/knxd_args.Tpo .deps/knxd_args.Po
/bin/sh ../../libtool  --tag=CXX   --mode=link g++  -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -std=c++0x -Wno-subobject-linkage  -Wl,-O1,--sort-common,--as-needed,-z,relro -o knxd_args knxd_args.o ../common/libcommon.a -lev -lfmt
libtool: link: g++ -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -std=c++0x -Wno-subobject-linkage -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z -Wl,relro -o knxd_args knxd_args.o  ../common/libcommon.a -lev -lfmt
knxd_args.o: In function `driver_argsv(char const, char, ...)':
knxd_args.cpp:(.text+0x104): undefined reference to `IniSection::operator[](char const*)'
knxd_args.cpp:(.text+0x1b8): undefined reference to `IniSection::operator[](char const*)'
knxd_args.o: In function `driver_args(char const*, char*)':
knxd_args.cpp:(.text+0x564): undefined reference to `IniSection::operator[](char const*)'
knxd_args.o: In function `readaddr(char const*)':
knxd_args.cpp:(.text+0x5f8): undefined reference to `IniSection::operator[](char const*)'
knxd_args.o: In function `readaddrblock(char const*)':
knxd_args.cpp:(.text+0x68c): undefined reference to `IniSection::operator[](char const*)'
knxd_args.o:knxd_args.cpp:(.text+0x770): more undefined references to `IniSection::operator[](char const*)' follow
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:490: knxd_args] Error 1
make[3]: Leaving directory '/home/comfort/knxd/contrib/arch-build-system/src/knxd/src/server'
make[2]: *** [Makefile:393: all-recursive] Error 1
make[2]: Leaving directory '/home/comfort/knxd/contrib/arch-build-system/src/knxd/src'
make[1]: *** [Makefile:441: all-recursive] Error 1
make[1]: Leaving directory '/home/comfort/knxd/contrib/arch-build-system/src/knxd'
make: *** [Makefile:377: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by smurfix** [comment]
That should not be possible. This function is defined in `src/common/inifile.cpp`, so there must be something wrong with your build environment.
Please run `make clean`, or remove `src/common/libcommon.a`, then try again.

If that doesn't help: which gcc version / Raspbian release / … are you using?

**Comment by 1337bacon** [comment]
I'm using Arch Linux Arm 4.4.13-2-ARCH.
I tried to make clean but error is thrown: ` "No rule to make target 'clean'.  Stop."`
I also tried to delete the` src/common/libcommon.a` but it's not there.

**Comment by smurfix** [comment]
After the above, you definitely have a Makefile and the src/common/libcommon.a archive, otherwise all of this would not work.

Again: which GCC version?

**Comment by 1337bacon** [comment]
Here's the  Gcc version: 6.1.1 20160602 (GCC).

**Comment by 1337bacon** [comment]
Hi, indeed there was a problem on my side. Thanks for your time.

**Comment by smurfix** [comment]
No problem.
Does the new version still exhibit the problem?

**Comment by 1337bacon** [comment]
No, the new version appears to solve the issue.
