### ISSUE TITLE
Many subsequent GroupCacheRead requests to knxd will fail

### ISSUE THREAD

**Issue by bmxp** [knxd/knxd#272]
I got an installation with SmartHomeNG. Within it I have 257 group addresses that are to be read from knxd as cached values.
When I start knxd 0.12 (latest build) I get 127 from those 257.
When I start knxd 0.14 (latest build) I get just 62 from those 257.
I've figured out these numbers with journalctl -u knxd -f running on knxd side and the debuglog of SmartHomeNG on the other side.
I was able to circumvent this init problem while integrating a little sleep of 0.35s between the read requests to knxd but I thought there might be a problem deeper within the knxd core.
If I can investigate and give you more detailed info on this issue, please let me know.

**Comment by smurfix** [comment]
Command line options you start knxd with?

**Comment by bmxp** [comment]
KNXD_OPTS="-f9 -t1023 -e 0.0.1 -E 0.0.2:8 -f9 -t1023 -c500 -b ipt:192.168.20.5"

**Comment by smurfix** [comment]
Most likely explanation: Your gateway is broken. It acknowledges packets before it's sent them to the bus and knxd is too fast. Thus, you need to tell knxd to slow down. Use the "pace" filter: `-B pace`, in front of `-b ipt:`.
To adjust the timing, use `-A delay=50` (that's in milliseconds) in front of the `-B pace`.

**Comment by bmxp** [comment]
I'll try out and let you know as this will probably oft interest for others, too

**Comment by bmxp** [comment]
I am using now ``KNXD_OPTS="-f9 -t1023 -e 0.0.1 -E 0.0.2:8 -f9 -t1023 -c -A delay = 50 -B pace -b ipt:192.168.20.5"`` and after testing and restarting I can confirm that this works with knxd 0.14.16.

I am using a Siemens N148/22 as interface. Thus it shows that there is a need for pace and delay parameters. Thank you for your help and support!
