### ISSUE TITLE
Don't understand how to connect to a siemens N148 IP gateway knxd 0.14.16

### ISSUE THREAD

**Issue by Basilic** [knxd/knxd#276]
Hello,

I usaly use EIBD for my usage but it's not longer support and for update my dev I would like to use knxd.

I have install all dependencies on a Debian Jessie 8.7.1 and compiled without error.

But I can't find the good way to connect to my IP gateway.

My actual EIBD argument is: export "-d -D  -i  ipt:192.168.1.1"

Please help me to understand the need arguments.

Best regards

**Comment by tru7** [comment]
Take a look at the README, specifically at "Migrating to 0.12" and "Migrating to 0.14". More arguments are now manadatory, knxd.socket takes care of the sockets and knxd.service runs the daemon. So you may run it like "-e 0.0.1 -E 0.0.2:9 -b ipt:192.168.1.1", maybe also adding -DTS before -b. Arguments for -e and -E depend on your enviroment.
You may start knxd manually in the shell in foreground to verify all arguments and only this way you need the -i. You may also add -t for logging.

**Comment by Basilic** [comment]
Thank for you quickly answer.

It's seem work with the command with: knxd -e 0.0.1 -E 0.0.2:9 -D -T -S -b ipt:192.168.1.1

But... If I launch a groupsocketlisten (on EIBD) and one other (other machine) knxtool groupsocketlisten, the EIBD see message but not knxd and after launch some command knxd return:

F00000000: [ 7:A.ipt] Link down, terminating

**Comment by Basilic** [comment]
hello,

After add the opts_arg in knxd.conf, and start with sudo all work fine, thank a lot for you help.
