### ISSUE TITLE
KNXD install and starting Raspberry Pi 3

### ISSUE THREAD

**Issue by BMatlosz** [knxd/knxd#279]
Hi,
I have problem with configure and started daemona KNXD.
Used model with this page:
https://michlstechblog.info/blog/raspberry-pi-eibknx-ip-gateway-and-router-with-knxd/#comment-2119
After installed knxd, I get failed to start KNX Daemon. Content error:
Aug 16 12:29:33 Hunter1 knxd[1053]: initialisation of backend ‘usb:1:4:1:0:0’ failed: Resource temporarily unavailable
Aug 16 12:29:33 pi systemd[1]: knxd.service: control process exited, code=exited status=1
Aug 16 12:29:33 pi systemd[1]: Failed to start KNX Daemon.
Aug 16 12:29:33 pi systemd[1]: Unit knxd.service entered failed state.

I try in Raspberry Pi 3 and don’t working…
I setting inside file /etc/default/knxd:
KNXD_OPTIONS=”–eibaddr=1.1.128 -d -D -T -R -S -i –listen-local=/tmp/knx usb:%DEVICEID%”

And add file /usr/local/bin/knxd-findusb.sh to get serial address usb which join interface KNX/USB.

Can you explain, how I must to setting raspberry pi 3 ?

**Comment by smurfix** [comment]
Please don't open issues for questions.
`knxd-findusb` is superfluous, knxd is able to find the interface by itself. Just use "-b usb:".
Also, read the README. You need a `--client-addrs=…` option.
