### ISSUE TITLE
logo for knxd

### ISSUE THREAD

**Issue by mjoe** [knxd/knxd#282]
Team, do we want to add a simple logo? 
![knxd-256](https://user-images.githubusercontent.com/745660/29485167-c3c3033a-84cd-11e7-9fd6-0d5d56d789a1.png)

**Comment by smurfix** [comment]
On 19.08.2017 11:04, Joerg Mattiello wrote:
>
> Team, do we want to add a simple logo?
>
Good idea.

pull request w/ SVG please?

-- 
-- Matthias Urlichs

**Comment by mjoe** [comment]
Sure, if there are no other opinions, i'll do that (incl. SVG)

**Comment by mjoe** [comment]
Thanks Michael for making that clear, pull request will follow.

**Comment by mjoe** [comment]
Just committed 2 variants of the logo under /res. @Makki1 or @ChristianMayer you can add the logo to the knxd Organisation profile if you like.
