### ISSUE TITLE
Only Version 0.10 works with FHEM

### ISSUE THREAD

**Issue by NehCoy** [knxd/knxd#283]
Hi all!

I setup a new FHEM environment on an Raspberry PI. I installed the latest versions of Raspian (Stretch), FHEM (v5.8) and knxd (v 0.14). However, I've problems to use knxd with FHEM. Furthermore simple groupswrites (knxtool groupswrite) doesn't work.
I've read this post within the FHEM forum: https://forum.fhem.de/index.php/topic,65396.msg577905.html#msg577905
As you can see, the solution is to install version 0.10! Do you know this issue?
Or did we something wrong during the installation, or configuration of the system?

Thanks and best regards,
NehCoy

**Comment by smurfix** [comment]
No, the solution is to use the new -E option. Or to switch to v0.14.
