### ISSUE TITLE
knxd_args missing (in deb file)

### ISSUE THREAD

**Issue by ThomasCr** [knxd/knxd#289]
Today I wanted to use knxd_args, but could not find it on my system.
So I checked the build folder and have seen, that knxd_args is also not in debian/tmp
Im not a Makefile guru, but it looks like it is not installed by "make install"

But I could find it in src/server/ folder... so it is build.

**Comment by smurfix** [comment]
/usr/lib/knxd_args

**Comment by ThomasCr** [comment]
urrg.. how could I not see that.

But I don't think that this is the right place?! When not in a bin folder, than better in /usr/lib/knxd/ or something. See Linux Standard Base (LSB)
