### ISSUE TITLE
user "knxd" does not exist

### ISSUE THREAD

**Issue by shreckxie** [knxd/knxd#293]
Hello,

I am new here and try to use the Raspberry Pi3 + PIGATOR Onewire + KNX/EIB. I have flowed the introduction [hier](https://github.com/knxd/knxd/wiki/Adding-a-busware-pigator-KNX-TPUART-(Raspberry)#make-it-work-on-a-raspberry-pi3). 

When I give this code 
$ sudo usermod -a -G dialout knxd

I get the issue: user "knxd" does not exist

can someone tell me what should I do? I have not found any comparable solution to it.

Thank you for your HELP!!

BR

Z.Xie

**Comment by smurfix** [comment]
Yeah. It's outdated and superfluous. Ignore it.
(Fixed in the wiki)
