### ISSUE TITLE
Inbetriebnahme Raspberry Pi3 + Busware PIGATOR + KNX/EIB

### ISSUE THREAD

**Issue by shreckxie** [knxd/knxd#294]
Hallo Zusammen,

vor einpaar Tagen habe ich das Set PIGATOR + KNX/EIB Modul bei Busware gekauft.
http://busware.de/tiki-index.php?page=PIGATOR

Nach ein paar Tagen intensiven Testen und Versuchungen bin ich aktuelle frustriert. Von Busware bekommt man die Unterstützung so gut wie nichts.

Die Anleitungen, die ich gefunden habe, sind  für diejenige, die mehr oder wenig schon Ahnung haben. Ich habe leider frisch mit Linux angefangen. Daher gar keine Anleitung klärt mir, was und warum.

Ich hoffe, dass ich hier ein paar Antwort bekommen könnte.

Folgende Schritte wurden meiner Meinung nach erfolgreich durchgeführt. 
Die Installation mit KNXD nach der Anleitung: https://github.com/knxd/knxd/blob/stable/README.md
Dann Installation PIGATOR nach der Anleitung: https://github.com/knxd/knxd/wiki/Adding-a-busware-pigator-KNX-TPUART-(Raspberry)

Aber ich habe folgende Problem/Frage:
1. unter /etc/ finde ich knx.ini nicht.
2. welche Parameter sollte ich konkret nehmen für knxd_args?
 `sudo /usr/lib/knxd_args -e 0.0.1 -E 0.0.2:8 -u /tmp/eib -b tpuarts:/dev/knx1 -D -T -R -S`
oder
`sudo /usr/lib/knxd_args -e 0.0.1 -E 0.0.2:8 -u /tmp/eib -b ip:192.168.1.73`
oder anders?
3. Unter dieser Kombination (Raspberry Pi3 + Busware PIGATOR + KNX/EIB) verstehe ich, dass die ETS über WLAN mit Raspberry PI verbindet, und das KNX Bussystem verbindet mit PIGATOR + KNX/EIB Modul über KNX-Kabel. D.h. die ETS sollte über WLAN durch Raspberry die anderen KNX-Geräte zugreifen bzw. programmieren können. Ist es richtig?
4. Wenn ich unter Punkt 3 richtig verstanden habe, brauche ich in die KNX.ini Datei sowohl die Definition für TPUARTS als auch IP Adresse. Wie sieht dann die Parameter für knxd_args aus?

Ich glaube, dass ich grundsätzlich das ganze System noch nicht verstanden habe.

Ich bedanke mich mehrmals für die Erklärung.

Beste Grüße aus Ingolstadt.
Z.Xie

**Comment by smurfix** [comment]
Hi,
> -b ip:192.168.1.73

Fangen wir mal damit an. Das ist kompletter Unfug. Wo hast du das her? Schimpfen. Sehr laut.

Die andere Befehlszeile sollte eigentlich funktionieren, so du die anderen Punkte beachtet hast, die die Doku beschreibt – nämlich "serielle Konsole ausschalten" und "udev-Regel anlegen".

Es gibt noch keine automatisch generierte knx.ini. Die kannst du dir mit knxd_args selber anlegen (und dann als einziges Argument in die knxd.conf eintragen). Standard ist nach wie vor, in der knx.conf Argumente zu hinterlassen. Es funktioniert (noch) beides.

NB: das hier ist der Bugtracker und kein Supportbereich. Für Support gibt es das Wiki und die im README verlinkten Foren. Ich mache daher hier zu.

**Comment by shreckxie** [comment]
@smurfix ooops，nicht drauf geachtet, dass es hier nur um Bugtracker geht. Vielen Dank erstmal für die Antwort. Ich probiere mal weiter....
