### ISSUE TITLE
Raspbian Stretch + Pigator Busware + latest KNXD won't work

### ISSUE THREAD

**Issue by Geoffreydm** [knxd/knxd#304]
Dear,

Apparently the combination of the latest Raspbian Stretch with the Pigator of Busware and the latest KNXD is not working anymore.

Multiple people already explainned the situation on the link
https://knx-user-forum.de/forum/projektforen/knxd/1107634-raspi-b-mit-busware-rot/page2

I've been trying so many things but none of them are working. 

What I found out
sudo udevadm info -a /dev/ttyAMA0

Udevadm info starts with the device specified by the devpath and then
walks up the chain of parent devices. It prints for every device
found, all possible attributes in the udev rules key format.
A rule to match, can be composed by the attributes of the device
and the attributes from one single parent device.

  looking at device '/devices/platform/soc/3f201000.serial/tty/ttyAMA0':
    KERNEL=="ttyAMA0"
    SUBSYSTEM=="tty"
    DRIVER==""
    ATTR{close_delay}=="50"
    ATTR{closing_wait}=="3000"
    ATTR{custom_divisor}=="0"
    ATTR{flags}=="0x10002000"
    ATTR{io_type}=="2"
    ATTR{iomem_base}=="0x3F201000"
    ATTR{iomem_reg_shift}=="0"
    ATTR{irq}=="87"
    ATTR{line}=="0"
    ATTR{port}=="0x0"
    ATTR{type}=="32"
    ATTR{uartclk}=="48000000"
    ATTR{xmit_fifo_size}=="16"

  looking at parent device '/devices/platform/soc/3f201000.serial':
    KERNELS=="3f201000.serial"
    SUBSYSTEMS=="amba"
    DRIVERS=="uart-pl011"
    ATTRS{driver_override}==""
    ATTRS{id}=="00241011"
    ATTRS{irq0}=="87"

  looking at parent device '/devices/platform/soc':
    KERNELS=="soc"
    SUBSYSTEMS=="platform"
    DRIVERS==""
    ATTRS{driver_override}=="(null)"

  looking at parent device '/devices/platform':
    KERNELS=="platform"
    SUBSYSTEMS==""
    DRIVERS==""

/etc/udev/rules.d/70-knxd.rules
ACTION=="add", SUBSYSTEM=="tty", ATTRS{id}=="00241011", KERNELS=="3f201000.serial", SYMLINK+="ttyKNX1", OWNER="knxd"
● knxd.service - KNX Daemon
   Loaded: loaded (/lib/systemd/system/knxd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2017-12-08 14:11:46 UTC; 14min ago
 Main PID: 865 (knxd)
   CGroup: /system.slice/knxd.service
           └─865 /usr/bin/knxd -e 1.1.200 -E 1.1.201:10 -t 0xffc -f 9 -DTRS -b tpuarts:/dev/ttyKNX1

Dec 08 14:11:46 raspberrypi knxd[865]: Layer 5 [19:router/ConnC        0.005] Started
Dec 08 14:11:46 raspberrypi knxd[865]: Layer 4 [19:router/ConnC        0.005] up
Dec 08 14:11:46 raspberrypi knxd[865]: Layer 8 [10:server/Server       0.005] Opened
Dec 08 14:11:46 raspberrypi knxd[865]: Layer 5 [10:server/Server       0.005] >up => up
Dec 08 14:11:46 raspberrypi knxd[865]: Layer 4 [10:server/Server       0.005] up
Dec 08 14:11:46 raspberrypi knxd[865]: Layer 5 [10:server/Server       0.005] Started
Dec 08 14:11:46 raspberrypi knxd[865]: Layer 4 [10:server/Server       0.005] up
Dec 08 14:11:46 raspberrypi knxd[865]: Layer 6 [19:router/ConnC        0.014] is OK
Dec 08 14:11:46 raspberrypi knxd[865]: Layer 6 [10:server/Server       0.015] is OK
Dec 08 14:11:46 raspberrypi systemd[1]: Started KNX Daemon.

 ls -l /dev
lrwxrwxrwx 1 root root           7 Dec  8 14:11 serial0 -> ttyAMA0
lrwxrwxrwx 1 root root           7 Dec  8 14:11 ttyKNX1 -> ttyAMA0

Is the latest version incompatible?

Many thanks

**Comment by Geoffreydm** [comment]
Problem solved just by explaining the problem.

**Comment by AKimby** [comment]
what exactly was you solution?
