### ISSUE TITLE
USB: Driver timed out trying to send

### ISSUE THREAD

**Issue by nwpr** [knxd/knxd#306]
Unfortunately I'm not able to use knxd using a Weinzierl KNX USB Interface Stick 332.
As soon as I'm sending a request, knxd stops. The monitor also doesn't work.
The bus traffic also doesn't show up in the logs.
I'm running knxd using the following options: `/usr/bin/knxd -t 0xfff -f 9 -B log -t 0xfff -f 9 -B log -b usb: -e 1.6.51 -E 1.6.52:10 -c -D -T -R -S`

Could someone please help me finding out the problem?

Here are the logs:
> Dec 20 17:07:17 BUSdriver-linx systemd[1]: Starting KNX Daemon...
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 0 [14:log/A.usb        0.000] State setup
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 0 [15:log/A.usb        0.000] State setup
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL       0.001] USBLoop read 9
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL       0.001] USBLoop read 11
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL       0.001] USBLoop-Create
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 1 [17:A.usb/usbL       0.001] Detect
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [timestamp] [threadID] facility level [function call] <message>
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: --------------------------------------------------------------------------------
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.000954] [0000086b] libusb: debug [libusb_get_device_list]
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.000970] [0000086b] libusb: debug [libusb_get_device_descriptor]
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.000973] [0000086b] libusb: debug [libusb_get_config_descriptor] index 0
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.000980] [0000086b] libusb: debug [libusb_open] open 1.2
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.000994] [0000086b] libusb: debug [usbi_add_pollfd] add fd 12 events 4
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL       0.001] USBLoop read 9
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL       0.001] USBLoop read 11
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL       0.001] USBLoop write 12
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001008] [0000086b] libusb: debug [libusb_close]
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001011] [0000086b] libusb: debug [usbi_remove_pollfd] remove fd 12
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL       0.001] USBLoop read 9
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL       0.001] USBLoop read 11
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 1 [17:A.usb/usbL       0.001] Using 1:2:1:0:0 (1:129)
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001028] [0000086b] libusb: debug [libusb_init] libusb v1.0.20.11004
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001038] [0000086b] libusb: debug [find_usbfs_path] found usbfs at /dev/bus/usb
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001041] [0000086b] libusb: debug [op_init] bulk continuation flag supported
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001043] [0000086b] libusb: debug [op_init] zero length packet flag supported
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001048] [0000086b] libusb: debug [op_init] sysfs can relate devices
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001056] [0000086b] libusb: debug [op_init] sysfs has complete descriptors
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001414] [0000086b] libusb: debug [linux_get_device_address] getting address for device: usb1 detached: 0
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001420] [0000086b] libusb: debug [linux_get_device_address] scan usb1
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001445] [0000086b] libusb: debug [linux_get_device_address] bus=1 dev=1
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001448] [0000086b] libusb: debug [linux_enumerate_device] busnum 1 devaddr 1 session_id 257
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001451] [0000086b] libusb: debug [linux_enumerate_device] allocating new device for 1/1 (session 257)
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001544] [0000086b] libusb: debug [linux_get_device_address] getting address for device: 1-1 detached: 0
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001548] [0000086b] libusb: debug [linux_get_device_address] scan 1-1
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001572] [0000086b] libusb: debug [linux_get_device_address] bus=1 dev=2
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001575] [0000086b] libusb: debug [linux_enumerate_device] busnum 1 devaddr 2 session_id 258
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001577] [0000086b] libusb: debug [linux_enumerate_device] allocating new device for 1/2 (session 258)
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001599] [0000086b] libusb: debug [linux_get_parent_info] Dev 0x774b70 (1-1) has parent 0x78a1c0 (usb1) port 1
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001644] [0000086b] libusb: debug [usbi_add_pollfd] add fd 12 events 1
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001651] [0000086b] libusb: debug [usbi_io_init] using timerfd for timeouts
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001653] [0000086b] libusb: debug [usbi_add_pollfd] add fd 14 events 1
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL       0.001] USBLoop read 12
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL       0.001] USBLoop read 14
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL       0.001] USBLoop-Create
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 1 [17:A.usb/usbL       0.001] Detect
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001669] [0000086b] libusb: debug [libusb_get_device_list]
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001673] [0000086b] libusb: debug [libusb_get_device_descriptor]
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001675] [0000086b] libusb: debug [libusb_get_config_descriptor] index 0
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001679] [0000086b] libusb: debug [libusb_open] open 1.2
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001687] [0000086b] libusb: debug [usbi_add_pollfd] add fd 15 events 4
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL       0.001] USBLoop read 12
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL       0.001] USBLoop read 14
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL       0.001] USBLoop write 15
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001698] [0000086b] libusb: debug [libusb_close]
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001701] [0000086b] libusb: debug [usbi_remove_pollfd] remove fd 15
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL       0.001] USBLoop read 12
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL       0.001] USBLoop read 14
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 1 [17:A.usb/usbL       0.001] Using 1:2:1:0:0 (1:129)
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 3 [12:A.usb/Conn       0.001] registerLink: 12:A.usb
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 3 [12:A.usb/Conn        0.002] Start: cfg:A.usb
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 5 [12:A.usb/Conn        0.002] down => >up
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 5 [12:A.usb/Conn        0.002] Starting
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 0 [14:log/A.usb         0.002] State start
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 0 [15:log/A.usb         0.002] State start
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001934] [0000086b] libusb: debug [libusb_open] open 1.2
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001946] [0000086b] libusb: debug [usbi_add_pollfd] add fd 17 events 4
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL        0.002] USBLoop read 12
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL        0.002] USBLoop read 14
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL        0.002] USBLoop write 17
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 1 [17:A.usb/usbL        0.002] Open
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.001961] [0000086b] libusb: debug [libusb_detach_kernel_driver] interface 0
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.002595] [0000086b] libusb: debug [libusb_set_configuration] configuration 1
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.009991] [0000086b] libusb: debug [libusb_claim_interface] interface 0
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.010012] [0000086b] libusb: debug [libusb_set_interface_alt_setting] interface 0 altsetting 0
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 1 [17:A.usb/usbL        0.011] Claimed
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 1 [17:A.usb/usbL        0.011] Opened
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.011804] [0000086b] libusb: debug [libusb_alloc_transfer] transfer 0x78d5c8
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.011809] [0000086b] libusb: debug [libusb_submit_transfer] transfer 0x78d5c8
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.011813] [0000086b] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL        0.011] StartRecv
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 0 [13:A.usb/USBdr       0.011] starting send_Local
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 0 [17:A.usb/usbL        0.011] SendUSB(064): 01 13 09 00 08 00 01 0F 01 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.011861] [0000086b] libusb: debug [libusb_alloc_transfer] transfer 0x78d818
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.011864] [0000086b] libusb: debug [libusb_submit_transfer] transfer 0x78d818
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.011867] [0000086b] libusb: debug [add_to_flying_list] arm timerfd for timeout in 1000ms (first in line)
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.011873] [0000086b] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 0 [17:A.usb/usbL        0.012] StartSend 78d818
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 4 [12:A.usb/Conn        0.012] >up
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: Layer 4 [12:A.usb/Conn        0.012] is >up
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.012442] [0000086b] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.012447] [0000086b] libusb: debug [handle_events] poll fds modified, reallocating
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.012452] [0000086b] libusb: debug [handle_events] poll() 2 fds with timeout in 0ms
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.012455] [0000086b] libusb: debug [handle_events] poll() returned 0
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.012459] [0000086b] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.012461] [0000086b] libusb: debug [handle_events] poll fds modified, reallocating
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.012464] [0000086b] libusb: debug [handle_events] poll() 3 fds with timeout in 0ms
Dec 20 17:07:17 BUSdriver-linx knxd[2155]: [ 0.012466] [0000086b] libusb: debug [handle_events] poll() returned 0
Dec 20 17:07:17 BUSdriver-linx systemd[1]: Started KNX Daemon.
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.019332] [0000086b] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.019346] [0000086b] libusb: debug [handle_events] poll() 3 fds with timeout in 0ms
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.019350] [0000086b] libusb: debug [handle_events] poll() returned 1
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.019353] [0000086b] libusb: debug [reap_for_handle] urb type=1 status=0 transferred=64
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.019356] [0000086b] libusb: debug [handle_bulk_completion] handling completion status 0 of bulk urb 1/1
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.019359] [0000086b] libusb: debug [handle_bulk_completion] last URB in transfer --> complete!
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.019361] [0000086b] libusb: debug [disarm_timerfd]
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.019364] [0000086b] libusb: debug [usbi_handle_transfer_completion] transfer 0x78d818 has callback 0x436410
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL        0.019] SendCB 78d818
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL        0.019] SendComplete 78d818 64
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.019382] [0000086b] libusb: debug [libusb_free_transfer] transfer 0x78d818
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 0 [13:A.usb/USBdr       0.019] send_Local done
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.020319] [0000086b] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.020326] [0000086b] libusb: debug [handle_events] poll() 3 fds with timeout in 0ms
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.020329] [0000086b] libusb: debug [handle_events] poll() returned 1
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.020332] [0000086b] libusb: debug [reap_for_handle] urb type=1 status=0 transferred=64
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.020335] [0000086b] libusb: debug [handle_bulk_completion] handling completion status 0 of bulk urb 1/1
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.020337] [0000086b] libusb: debug [handle_bulk_completion] last URB in transfer --> complete!
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.020369] [0000086b] libusb: debug [usbi_handle_transfer_completion] transfer 0x78d5c8 has callback 0x436270
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL        0.020] RecvCB 78d5c8
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL        0.020] RecvComplete 78d5c8 64
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 0 [17:A.usb/usbL        0.020] RecvUSB(064): 01 13 0B 00 08 00 03 0F 02 00 00 01 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 2 [13:A.usb/USBdr       0.020] recv_Data(064): 01 13 0B 00 08 00 03 0F 02 00 00 01 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 1 [13:A.usb/USBdr       0.020] Using EMI version 3
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 2 [16:A.usb/Conv        0.020] send_Init 3
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 0 [16:A.usb/Conv        0.020] starting send_Local
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 0 [17:A.usb/usbL        0.020] SendUSB(064): 01 13 0A 00 08 00 02 0F 03 00 00 05 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.020422] [0000086b] libusb: debug [libusb_alloc_transfer] transfer 0x78dab8
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.020424] [0000086b] libusb: debug [libusb_submit_transfer] transfer 0x78dab8
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.020427] [0000086b] libusb: debug [add_to_flying_list] arm timerfd for timeout in 1000ms (first in line)
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.020430] [0000086b] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 0 [17:A.usb/usbL        0.020] StartSend 78dab8
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.020469] [0000086b] libusb: debug [libusb_submit_transfer] transfer 0x78d5c8
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.020474] [0000086b] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL        0.020] StartRecv
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.021792] [0000086b] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.021799] [0000086b] libusb: debug [handle_events] poll() 3 fds with timeout in 0ms
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.021802] [0000086b] libusb: debug [handle_events] poll() returned 1
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.021805] [0000086b] libusb: debug [reap_for_handle] urb type=1 status=0 transferred=64
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.021808] [0000086b] libusb: debug [handle_bulk_completion] handling completion status 0 of bulk urb 1/1
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.021810] [0000086b] libusb: debug [handle_bulk_completion] last URB in transfer --> complete!
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.021812] [0000086b] libusb: debug [disarm_timerfd]
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.021815] [0000086b] libusb: debug [usbi_handle_transfer_completion] transfer 0x78dab8 has callback 0x436410
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL        0.021] SendCB 78dab8
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL        0.021] SendComplete 78dab8 64
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: [ 0.021829] [0000086b] libusb: debug [libusb_free_transfer] transfer 0x78dab8
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 0 [16:A.usb/Conv        0.021] send_Local done
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 2 [26:A.usb/CEMI        0.021] OpenL2
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 0 [15:log/A.usb         0.021] State started
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 0 [14:log/A.usb         0.021] State started
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 5 [12:A.usb/Conn        0.021] >up => up
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 4 [12:A.usb/Conn        0.021] up
Dec 20 17:07:18 BUSdriver-linx knxd[2155]: Layer 5 [12:A.usb/Conn        0.021] Started
Dec 20 17:07:28 BUSdriver-linx knxd[2155]: Layer 6 [12:A.usb/Conn           10.478] sending, send_more clear
Dec 20 17:07:28 BUSdriver-linx knxd[2155]: Layer 0 [14:log/A.usb            10.478] Send L_Data low from 1.6.52 to 1/2/22 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write (small) 3F
Dec 20 17:07:28 BUSdriver-linx knxd[2155]: Layer 0 [15:log/A.usb            10.478] Send L_Data low from 1.6.52 to 1/2/22 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write (small) 3F
Dec 20 17:07:28 BUSdriver-linx knxd[2155]: E00000000: [26:A.usb] EMI_common: send while waiting
Dec 20 17:07:28 BUSdriver-linx knxd[2155]: Layer 6 [12:A.usb/Conn           10.495] still waiting
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: E00000055: [12:A.usb] Driver timed out trying to send (A.usb)
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: Layer 5 [12:A.usb/Conn           20.488] up => down/error
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: Layer 4 [12:A.usb/Conn           20.488] up/error
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: Layer 5 [12:A.usb/Conn           20.488] Stopping
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: Layer 0 [14:log/A.usb            20.488] State stop
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: Layer 0 [15:log/A.usb            20.488] State stop
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: Layer 2 [26:A.usb/CEMI           20.488] CloseL2
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: Layer 0 [15:log/A.usb            20.488] State stopped
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: Layer 0 [14:log/A.usb            20.488] State stopped
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: Layer 5 [12:A.usb/Conn           20.488] up/error => down
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: Layer 4 [12:A.usb/Conn           20.488] down/error
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: Layer 4 [12:A.usb/Conn           20.488] is down
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: F00000000: [12:A.usb] Link down, terminating
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: Layer 4 [12:A.usb/Conn           20.488] Stopping
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: Layer 5 [12:A.usb/Conn           20.488] down/error => >down
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: Layer 4 [12:A.usb/Conn           20.488] down/error
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: Layer 4 [12:A.usb/Conn           20.488] is down
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: Layer 1 [17:A.usb/usbL           20.488] Close
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: [20.488772] [0000086b] libusb: debug [libusb_cancel_transfer] transfer 0x78d5c8
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: [20.489957] [0000086b] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: [20.489964] [0000086b] libusb: debug [handle_events] poll() 3 fds with timeout in 0ms
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: [20.489967] [0000086b] libusb: debug [handle_events] poll() returned 1
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: [20.489971] [0000086b] libusb: debug [reap_for_handle] urb type=1 status=-2 transferred=0
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: [20.489974] [0000086b] libusb: debug [handle_bulk_completion] handling completion status -2 of bulk urb 1/1
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: [20.489976] [0000086b] libusb: debug [handle_bulk_completion] abnormal reap: urb status -2
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: [20.489979] [0000086b] libusb: debug [handle_bulk_completion] abnormal reap: last URB handled, reporting
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: [20.489981] [0000086b] libusb: debug [usbi_handle_transfer_completion] transfer 0x78d5c8 has callback 0x436270
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL           20.490] RecvCB 78d5c8
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: Layer 10 [17:A.usb/usbL           20.490] RecvComplete 78d5c8 0
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: W00000033: [17:A.usb] RecvError 3
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: Layer 1 [17:A.usb/usbL           20.490] Release
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: [20.490003] [0000086b] libusb: debug [libusb_release_interface] interface 0
Dec 20 17:07:38 BUSdriver-linx knxd[2155]: [20.490017] [0000086b] libusb: debug [libusb_attach_kernel_driver] interface 0
Dec 20 17:07:38 BUSdriver-linx systemd[1]: knxd.service: Main process exited, code=exited, status=1/FAILURE
Dec 20 17:07:38 BUSdriver-linx systemd[1]: knxd.service: Unit entered failed state.
Dec 20 17:07:38 BUSdriver-linx systemd[1]: knxd.service: Failed with result 'exit-code'.

**Comment by nwpr** [comment]
After more investigation it seems to me that this problem is related to #233 
knxd does work sometimes, but not always. And if it's working, I can only send telegrams and not receive any.

**Comment by DanielFroehlichPrivate** [comment]
Same problem here with knxd 0.14.19-2 and Hager KNX-USB Data Interface on a raspberry with  4.9.59-v7

I am using  KNXD_OPTS="--error=9 --trace=0xffff -B log -e 1.1.99 -E 1.1.100:10 --send-delay=100 --error=9 --trace 0xFFF -B log -b usb:" 

knxd V0.12.16 works fine, so it does not seem to be a hardware issue.

Full logs are here: [ https://pastebin.com/yDXSQUpS]( https://pastebin.com/yDXSQUpS)
Central Snippet:
```
Dec 23 18:17:20 franzipi knxd[593]: Layer 6 [10:A.usb/Conn            30.676] sending, send_more clear
Dec 23 18:17:20 franzipi knxd[593]: Layer 0 [12:log/A.usb             30.676] Send L_Data low from 1.1.100 to 0/0/21 hops: 05 T_DATA_XXX_REQ A_GroupValue_Read
Dec 23 18:17:20 franzipi knxd[593]: Layer 0 [13:log/A.usb             30.676] Send L_Data low from 1.1.100 to 0/0/21 hops: 05 T_DATA_XXX_REQ A_GroupValue_Read
Dec 23 18:17:20 franzipi knxd[593]: E00000000: [16:A.usb] EMI_common: send while waiting
Dec 23 18:17:20 franzipi knxd[593]: Layer 6 [10:A.usb/Conn            30.676] still waiting
Dec 23 18:17:30 franzipi knxd[593]: E00000055: [10:A.usb] Driver timed out trying to send (A.usb)
Dec 23 18:17:30 franzipi knxd[593]: Layer 5 [10:A.usb/Conn            40.686] up => down/error
Dec 23 18:17:30 franzipi knxd[593]: Layer 4 [10:A.usb/Conn            40.686] up/error
Dec 23 18:17:30 franzipi knxd[593]: Layer 5 [10:A.usb/Conn            40.686] Stopping
Dec 23 18:17:30 franzipi knxd[593]: Layer 0 [12:log/A.usb             40.686] State stop
Dec 23 18:17:30 franzipi knxd[593]: Layer 0 [13:log/A.usb             40.686] State stop
```

Any help is appreciated!

**Comment by ersingencturk** [comment]
apply my patch: https://github.com/knxd/knxd/pull/291

**Comment by dallmair** [comment]
Per [this comment](https://github.com/knxd/knxd/pull/291#issuecomment-607211474) and commit 76f399ae4d3ae618811abf420af36c8496212c8b, the USB timeout has been increased two 2 seconds in version 0.14.33, and AFAICT no new reports of USB timeouts have surfaced since then. Therefore, I think this issue is solved and should be closed.

In case you can still reproduce this with a recent version of knxd, please reopen.
