### ISSUE TITLE
When I reboot ,knxd.service couldnot start

### ISSUE THREAD

**Issue by wuhanwang** [knxd/knxd#307]
it's said you need a client-addrs=X.Y.Z:N option in your main section 
and Error setting up the KNX router.

**Comment by brammahh** [comment]
Experiencing the same issue. Is `--client-addrs` a mandatory parameter when using IPT?

**Comment by smurfix** [comment]
`--client-addrs` is mandatory when knxd serves clients, simply because it needs to give them unique addresses. So, not with `ipt:` but with -u -i -T, i.e. almost always.
