### ISSUE TITLE
MDT usb interface stops working with 0.14

### ISSUE THREAD

**Issue by pre-martin** [knxd/knxd#308]
Hi,

I have connected knxd to the USB interface from MDT. This setup works with knxd 0.12.16, but does not work with knxd 0.14.17.

Debug output with 0.14.17 is as follows:

```
Layer 0 [16:log/B.usb         0.000] State setup
Layer 1 [18:B.usb/usbL        0.002] Detect
Layer 1 [18:B.usb/usbL        0.002] Using 1:3:1:0:0 (1:130)
Layer 1 [18:B.usb/usbL        0.004] Detect
Layer 1 [18:B.usb/usbL        0.004] Using 1:3:1:0:0 (1:130)
Layer 3 [14:B.usb/Conn        0.004] registerLink: 14:B.usb
Layer 3 [14:B.usb/Conn        0.004] Start: cfg:B.usb
Layer 5 [14:B.usb/Conn        0.004] down => >up
Layer 5 [14:B.usb/Conn        0.004] Starting
Layer 0 [16:log/B.usb         0.004] State start
Layer 1 [18:B.usb/usbL        0.004] Open
Layer 1 [18:B.usb/usbL        0.007] Claimed
Layer 1 [18:B.usb/usbL        0.007] Opened
Layer 0 [15:B.usb/USBdr       0.007] starting send_Local
Layer 0 [18:B.usb/usbL        0.007] SendUSB(064): 01 13 09 00 08 00 01 0F 01 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0 [18:B.usb/usbL        0.007] StartSend 2544e70
Layer 4 [14:B.usb/Conn        0.007] >up
Layer 4 [14:B.usb/Conn        0.007] is >up
Layer 0 [18:B.usb/usbL        0.010] RecvUSB(064): 01 13 15 00 08 00 0D 01 03 00 00 29 00 BC E0 10 7E 1D 7E 03 00 80 0C 4D 10 06 00 00 01 00 00 F3 0B 1D 00 00 F1 2C A9 BC FB E8 FE F8 BC C0 AD 03 90 1F EA 9E FD 64 CD DA B4 4F 28 93 2A B2 87 08
Layer 2 [15:B.usb/USBdr       0.010] recv_Data(064): 01 13 15 00 08 00 0D 01 03 00 00 29 00 BC E0 10 7E 1D 7E 03 00 80 0C 4D 10 06 00 00 01 00 00 F3 0B 1D 00 00 F1 2C A9 BC FB E8 FE F8 BC C0 AD 03 90 1F EA 9E FD 64 CD DA B4 4F 28 93 2A B2 87 08
Layer 2 [15:B.usb/USBdr       0.010] not recognized
Layer 0 [15:B.usb/USBdr       0.011] send_Local done
Layer 0 [18:B.usb/usbL        0.014] RecvUSB(064): 01 13 15 00 08 00 0D 01 03 00 00 29 00 BC E0 10 7B 1D 7B 03 00 80 0C 38 10 06 00 00 01 00 00 F3 FE C3 00 00 CB 9D BE 53 FD 9C 87 36 EF 4F 93 16 A7 11 82 33 52 F5 FE 67 41 E7 F0 D9 7D 6F 0E 92
Layer 2 [15:B.usb/USBdr       0.014] recv_Data(064): 01 13 15 00 08 00 0D 01 03 00 00 29 00 BC E0 10 7B 1D 7B 03 00 80 0C 38 10 06 00 00 01 00 00 F3 FE C3 00 00 CB 9D BE 53 FD 9C 87 36 EF 4F 93 16 A7 11 82 33 52 F5 FE 67 41 E7 F0 D9 7D 6F 0E 92
Layer 2 [15:B.usb/USBdr       0.014] not recognized
Layer 0 [18:B.usb/usbL        0.018] RecvUSB(064): 01 13 15 00 08 00 0D 01 03 00 00 29 00 BC E0 10 8F 1D 8F 03 00 80 0C 1B 10 06 00 00 01 00 00 F3 0B 1D 00 00 F1 2C A9 BC FB E8 FE F8 BC C0 AD 03 90 1F EA 9E FD 64 CD DA B4 4F 28 93 2A B2 87 08
Layer 2 [15:B.usb/USBdr       0.018] recv_Data(064): 01 13 15 00 08 00 0D 01 03 00 00 29 00 BC E0 10 8F 1D 8F 03 00 80 0C 1B 10 06 00 00 01 00 00 F3 0B 1D 00 00 F1 2C A9 BC FB E8 FE F8 BC C0 AD 03 90 1F EA 9E FD 64 CD DA B4 4F 28 93 2A B2 87 08
Layer 2 [15:B.usb/USBdr       0.018] not recognized
Layer 0 [18:B.usb/usbL        0.022] RecvUSB(064): 01 13 0B 00 08 00 03 0F 02 00 00 01 00 04 E0 10 7B 1D 7B 03 00 80 0C 38 10 06 00 00 01 00 00 F3 FE C3 00 00 CB 9D BE 53 FD 9C 87 36 EF 4F 93 16 A7 11 82 33 52 F5 FE 67 41 E7 F0 D9 7D 6F 0E 92
Layer 2 [15:B.usb/USBdr       0.022] recv_Data(064): 01 13 0B 00 08 00 03 0F 02 00 00 01 00 04 E0 10 7B 1D 7B 03 00 80 0C 38 10 06 00 00 01 00 00 F3 FE C3 00 00 CB 9D BE 53 FD 9C 87 36 EF 4F 93 16 A7 11 82 33 52 F5 FE 67 41 E7 F0 D9 7D 6F 0E 92
Layer 1 [15:B.usb/USBdr       0.022] Using EMI version 3
Layer 2 [17:B.usb/Conv        0.022] send_Init 3
Layer 0 [17:B.usb/Conv        0.022] starting send_Local
Layer 0 [18:B.usb/usbL        0.022] SendUSB(064): 01 13 0A 00 08 00 02 0F 03 00 00 05 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0 [18:B.usb/usbL        0.022] StartSend 2545040
Layer 0 [17:B.usb/Conv        0.023] send_Local done
Layer 2 [22:B.usb/CEMI        0.023] OpenL2
Layer 0 [16:log/B.usb         0.023] State started
Layer 5 [14:B.usb/Conn        0.023] >up => up
Layer 4 [14:B.usb/Conn        0.023] up
Layer 5 [14:B.usb/Conn        0.023] Started
Layer 6 [14:B.usb/Conn         4.341] sending, send_more clear
Layer 0 [16:log/B.usb          4.341] Send L_Data low from 1.0.240 to 1/0/41 hops: 05 T_DATA_XXX_REQ A_GroupValue_Read
E00000000: [22:B.usb] EMI_common: send while waiting
Layer 6 [14:B.usb/Conn         4.358] still waiting
Layer 0 [18:B.usb/usbL         5.918] RecvUSB(064): 01 13 15 00 08 00 0D 01 03 00 00 29 00 BC E0 10 93 1D 93 03 00 80 0C 09 10 06 00 00 01 00 00 F3 0B 1D 00 00 F1 2C A9 BC FB E8 FE F8 BC C0 AD 03 90 1F EA 9E FD 64 CD DA B4 4F 28 93 2A B2 87 08
Layer 0 [17:B.usb/Conv         5.918] RecvEMI(013): 29 00 BC E0 10 93 1D 93 03 00 80 0C 09
Layer 0 [16:log/B.usb          5.918] Recv L_Data low from 1.0.147 to 3/5/147 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write 0C 09
E00000055: [14:B.usb] Driver timed out trying to send (B.usb)
Layer 5 [14:B.usb/Conn         14.343] up => down/error
Layer 4 [14:B.usb/Conn         14.343] up/error
Layer 5 [14:B.usb/Conn         14.343] Stopping
Layer 0 [16:log/B.usb          14.343] State stop
Layer 2 [22:B.usb/CEMI         14.343] CloseL2
Layer 0 [16:log/B.usb          14.343] State stopped
Layer 5 [14:B.usb/Conn         14.343] up/error => down
Layer 5 [14:B.usb/Conn         14.343] retry in 30 sec
```

Interestingly it looks like if something was received from the device 1.0.147 on group address 3/5/147.

Regards,
Martin

**Comment by DanielFroehlichPrivate** [comment]
From the logs, this looks pretty much the same as #306: "send while waiting" send "timed out".

**Comment by planetrenner-martin** [comment]
Indeed, `sending, send_more clear`, `send while waiting` and `Driver timed out trying to send` are the same log entries as in my case.

**Comment by Race666** [comment]
It seems it's also the same issue like [#290](https://github.com/knxd/knxd/issues/290)  If've add the patch (send-timeout=6000, send-retries=5) to my [script](https://michlstechblog.info/blog/download/electronic/install_knxd_systemd.sh) and feedback was  positve.

**Comment by planetrenner-martin** [comment]
I tried these values in the config file (see my comment in #290), but then there is nothing transfered at all to/from the USB device.

What makes my problem (maybe) special: My MDT USB interface works nice with 0.12.16, but not with the 0.14 branch.

**Comment by tosate** [comment]
I have exactly the same problem with my Hager USB interface. I have spent weeks trying to find the right combination of parameters, but the 0.14.17 version keeps crashing with USB time out errors all the time.
Then I went back to version 0.12.16 and with this it works perfectly stable.

**Comment by oss83** [comment]
> I have exactly the same problem with my Hager USB interface. I have spent weeks trying to find the right combination of parameters, but the 0.14.17 version keeps crashing with USB time out errors all the time.
> Then I went back to version 0.12.16 and with this it works perfectly stable.

How can you install older versions of knxd?

**Comment by smurfix** [comment]
You check them out and compile them. That being said those problems should by now be solved, we're at 0.14.51. If not I'd appreciate feedback,

**Comment by oss83** [comment]
Hello smurfix,

that was a quick response! :-D

I thought using the older version would probably solve my problem. Let me quickly summarize:
I had a running system on my Raspberry pi 3 with openhab 2.5 and knxd installed. I could even use ETS to program my KNX bus and everything was working as expected with the MDT USB interface.
But then for some other reason I had to reflash my raspberry. Now I am on openhab 3 and try to get the connection running to the KNX bus via knxd. But so far, I did not find the right configuration. I can even see the interface in ETS and when I start the busmonitor I can see the telegrams. But I am not able to write on the bus. 
When I saw some comments that there might be some problems with version 0.14 and USB interfaces, I wanted to give it a shot and get back to 0.12.
If there are some other things to try first, I am open for suggestions ;-) 

Th

**Comment by smurfix** [comment]
Please repeat this with the current main version. Then post your options and a log of the problem if it isn't fixed.

Not being able to write is most often a problem with colliding phys addresses, knxd filters messages from interface A when it has previously seen the same phys address from bus B. That includes the -E option. Never use an address range for it that's also used anywhere else.

**Comment by oss83** [comment]
knxd Version
`knxd 0.14.30`

Starting knxd with this configuration 
`KNXD_OPTS="-e 0.0.1 -E 0.0.2:8 -u /tmp/eib -D -T -R -S -b usb:"`

then I tried to switch a light with
`sudo knxtool groupswrite ip:localhost 0/1/0 1`

results in the following log and nothing happens, meaning light is not turned on
#
Apr 15 13:13:34 openhabian systemd[1]: Starting KNX Daemon...
Apr 15 13:13:34 openhabian systemd[1]: Started KNX Daemon.
Apr 15 13:13:42 openhabian knxd[19119]: E00000059: [25:B.usb] EMI_common: send while waiting (49)
Apr 15 13:13:52 openhabian knxd[19119]: E00000055: [18:B.usb] Driver timed out trying to send (B.usb)
Apr 15 13:13:52 openhabian knxd[19119]: F00000105: [18:B.usb] Link down, terminating
Apr 15 13:13:52 openhabian systemd[1]: knxd.service: Main process exited, code=exited, status=1/FAILURE
Apr 15 13:13:52 openhabian systemd[1]: knxd.service: Failed with result 'exit-code'.
Apr 15 13:14:02 openhabian systemd[1]: knxd.service: Service RestartSec=10s expired, scheduling restart.
Apr 15 13:14:02 openhabian systemd[1]: knxd.service: Scheduled restart job, restart counter is at 1.
Apr 15 13:14:02 openhabian systemd[1]: Stopped KNX Daemon.
Apr 15 13:14:02 openhabian systemd[1]: Starting KNX Daemon...
Apr 15 13:14:02 openhabian systemd[1]: Started KNX Daemon.
#

Using this configuration without -D -T -R -S
`KNXD_OPTS="-e 0.0.1 -E 0.0.2:8 -u /tmp/eib -b usb:"`

I can switch the light on and off with `sudo knxtool groupswrite ip:localhost 0/1/0 1`

**Comment by smurfix** [comment]
Umm … I explicitly wrote "current main version", which 0.14.30 is not. Please also turn on logging: `-t1022 -B log -b usb:`.

Also, please repeat that with and without -DTRS. I have no freakin' idea why that should affect the USB driver in any way, and suspect that something else is going on here.

**Comment by oss83** [comment]
Sorry for the version, but I thought you are talking about the latest version. This is what I get when I install via openhab 3 and run an update via `apt-get install knxd`
Maybe, it is a dumb question, but what do you mean by "current main version"? 

Here is the log with the following options
`KNXD_OPTS="-e 0.0.1 -E 0.0.2:8 -u /tmp/eib -t1022 -B log -b usb:"`
`sudo knxtool groupswrite ip:localhost 0/1/0 0`
But now the light is not switching

#
Apr 15 13:43:04 openhabian knxd[20332]: Layer 6 [13:B.usb/Conn       74.548] is OK
Apr 15 13:43:05 openhabian knxd[20332]: Layer 0 [15:log/B.usb        75.334] Recv L_Data low from 1.1.30 to 0/3/2 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write 07 C6
Apr 15 13:43:05 openhabian knxd[20332]: Layer 6 [13:B.usb/Conn       75.334] is OK
Apr 15 13:43:06 openhabian knxd[20332]: Layer 0 [15:log/B.usb        76.084] Recv L_Data low from 1.1.43 to 3/3/1 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write 00 00
Apr 15 13:43:06 openhabian knxd[20332]: Layer 8 [13:B.usb/Conn       76.084] found addr 1.1.43
Apr 15 13:43:06 openhabian knxd[20332]: Layer 6 [13:B.usb/Conn       76.084] is OK
Apr 15 13:43:06 openhabian knxd[20332]: Layer 0 [15:log/B.usb        76.106] Recv L_Data low from 1.1.43 to 3/3/2 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write 6C 50
Apr 15 13:43:06 openhabian knxd[20332]: Layer 8 [13:B.usb/Conn       76.106] found addr 1.1.43
Apr 15 13:43:06 openhabian knxd[20332]: Layer 6 [13:B.usb/Conn       76.106] is OK
Apr 15 13:43:06 openhabian knxd[20332]: Layer 0 [15:log/B.usb        76.296] Recv L_Data low from 1.1.43 to 3/3/3 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 00
Apr 15 13:43:06 openhabian knxd[20332]: Layer 8 [13:B.usb/Conn       76.296] found addr 1.1.43
Apr 15 13:43:06 openhabian knxd[20332]: Layer 6 [13:B.usb/Conn       76.296] is OK
Apr 15 13:43:09 openhabian knxd[20332]: Layer 0 [15:log/B.usb        79.190] Recv L_Data low from 15.15.250 to 3/3/4 hops: 06 T_DATA_XXX_REQ A_GroupValue_Read
Apr 15 13:43:09 openhabian knxd[20332]: Layer 8 [13:B.usb/Conn       79.190] found addr 15.15.250
Apr 15 13:43:09 openhabian knxd[20332]: Layer 6 [13:B.usb/Conn       79.190] is OK
_**_Apr 15 13:43:13 openhabian knxd[20332]: Layer 6 [13:B.usb/Conn          83.269] sending, send_more clear
Apr 15 13:43:13 openhabian knxd[20332]: Layer 0 [15:log/B.usb           83.269] Send L_Data low from 0.0.2 to 0/1/0 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write (small) 0
Apr 15 13:43:13 openhabian knxd[20332]: E00000059: [18:B.usb] EMI_common: send while waiting (17)
Apr 15 13:43:13 openhabian knxd[20332]: Layer 6 [13:B.usb/Conn          83.269] still waiting_**_
Apr 15 13:43:13 openhabian knxd[20332]: Layer 0 [15:log/B.usb           83.316] Recv L_Data low from 1.1.43 to 3/3/2 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write 6C 2E
Apr 15 13:43:13 openhabian knxd[20332]: Layer 8 [13:B.usb/Conn          83.316] found addr 1.1.43
Apr 15 13:43:14 openhabian knxd[20332]: Layer 0 [15:log/B.usb           84.186] Recv L_Data low from 15.15.250 to 3/3/4 hops: 06 T_DATA_XXX_REQ A_GroupValue_Read
Apr 15 13:43:14 openhabian knxd[20332]: Layer 8 [13:B.usb/Conn          84.186] found addr 15.15.250
Apr 15 13:43:16 openhabian knxd[20332]: Layer 0 [15:log/B.usb           86.088] Recv L_Data low from 1.1.43 to 3/3/1 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write 00 00
Apr 15 13:43:16 openhabian knxd[20332]: Layer 8 [13:B.usb/Conn          86.088] found addr 1.1.43
Apr 15 13:43:16 openhabian knxd[20332]: Layer 0 [15:log/B.usb           86.110] Recv L_Data low from 1.1.43 to 3/3/2 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write 6C 26
Apr 15 13:43:16 openhabian knxd[20332]: Layer 8 [13:B.usb/Conn          86.110] found addr 1.1.43
Apr 15 13:43:16 openhabian knxd[20332]: Layer 0 [15:log/B.usb           86.756] Recv L_Data low from 1.1.43 to 3/3/3 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small)
Apr 15 13:43:16 openhabian knxd[20332]: Layer 8 [13:B.usb/Conn          86.756] found addr 1.1.43
#

Here is the log log for 
`KNXD_OPTS="-e 0.0.1 -E 0.0.2:8 -u /tmp/eib -DTRS -t1022 -B log -b usb:"`
as before, no light switching

#
-- Logs begin at Thu 2021-04-15 03:29:46 CEST, end at Thu 2021-04-15 15:07:11 CEST. --
Apr 15 15:06:31 openhabian knxd[23443]: Layer 3 [18:B.usb/Conn        0.023] Start: cfg:B.usb
Apr 15 15:06:31 openhabian knxd[23443]: Layer 5 [18:B.usb/Conn        0.023] down => >up
Apr 15 15:06:31 openhabian knxd[23443]: Layer 5 [18:B.usb/Conn        0.023] Starting
Apr 15 15:06:31 openhabian knxd[23443]: Layer 0 [20:log/B.usb         0.023] State start
Apr 15 15:06:31 openhabian knxd[23443]: Layer 1 [22:B.usb/usbL        0.023] Open
Apr 15 15:06:31 openhabian knxd[23443]: Layer 1 [22:B.usb/usbL        0.028] Claimed
Apr 15 15:06:31 openhabian knxd[23443]: Layer 1 [22:B.usb/usbL        0.029] Opened
Apr 15 15:06:31 openhabian knxd[23443]: Layer 4 [18:B.usb/Conn        0.029] >up
Apr 15 15:06:31 openhabian knxd[23443]: Layer 4 [18:B.usb/Conn        0.030] is >up
Apr 15 15:06:31 openhabian systemd[1]: Started KNX Daemon.
Apr 15 15:06:31 openhabian knxd[23443]: Layer 2 [19:B.usb/USBdr       0.035] recv_Data(064): 01 13 15 00 08 00 0D 01 03 00 00 29 00 BC E0 11 2B 1B 02 03 00 80 56 3C BD
Apr 15 15:06:31 openhabian knxd[23443]: Layer 2 [19:B.usb/USBdr       0.035] not recognized
Apr 15 15:06:31 openhabian knxd[23443]: Layer 2 [19:B.usb/USBdr       0.037] recv_Data(064): 01 13 15 00 08 00 0D 01 03 00 00 29 00 BC E0 11 2B 1B 01 03 00 80 00 00 57
Apr 15 15:06:31 openhabian knxd[23443]: Layer 2 [19:B.usb/USBdr       0.037] not recognized
Apr 15 15:06:31 openhabian knxd[23443]: Layer 2 [19:B.usb/USBdr       0.039] recv_Data(064): 01 13 13 00 08 00 0B 01 03 00 00 29 00 BC E0 11 2B 1B 03 01 00 81 56 3C BD
Apr 15 15:06:31 openhabian knxd[23443]: Layer 2 [19:B.usb/USBdr       0.039] not recognized
Apr 15 15:06:31 openhabian knxd[23443]: Layer 2 [19:B.usb/USBdr       0.041] recv_Data(064): 01 13 13 00 08 00 0B 01 03 00 00 29 00 BC E0 FF FA 1B 04 01 00 00 00 00 57
Apr 15 15:06:31 openhabian knxd[23443]: Layer 2 [19:B.usb/USBdr       0.041] not recognized
Apr 15 15:06:31 openhabian knxd[23443]: Layer 2 [19:B.usb/USBdr       0.043] recv_Data(064): 01 13 0B 00 08 00 03 0F 02 00 00 01 00 04 E0 11 2B 1B 03 01 00 81 56 3C BD
Apr 15 15:06:31 openhabian knxd[23443]: Layer 1 [19:B.usb/USBdr       0.043] Using EMI version 3
Apr 15 15:06:31 openhabian knxd[23443]: Layer 2 [21:B.usb/Conv        0.043] send_Init 3
Apr 15 15:06:31 openhabian knxd[23443]: Layer 2 [26:B.usb/CEMI        0.045] OpenL2
Apr 15 15:06:31 openhabian knxd[23443]: Layer 0 [20:log/B.usb         0.045] State started
Apr 15 15:06:31 openhabian knxd[23443]: Layer 5 [18:B.usb/Conn        0.045] >up => up
Apr 15 15:06:31 openhabian knxd[23443]: Layer 4 [18:B.usb/Conn        0.045] up
Apr 15 15:06:31 openhabian knxd[23443]: Layer 5 [18:B.usb/Conn        0.045] Started
Apr 15 15:06:35 openhabian knxd[23443]: Layer 0 [20:log/B.usb         4.445] Recv L_Data low from 15.15.250 to 3/3/4 hops: 06 T_DATA_XXX_REQ A_GroupValue_Read
Apr 15 15:06:35 openhabian knxd[23443]: Layer 6 [18:B.usb/Conn        4.463] is OK
Apr 15 15:06:36 openhabian knxd[23443]: Layer 0 [20:log/B.usb         4.715] Recv L_Data low from 1.1.43 to 3/3/2 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write 56 3C
Apr 15 15:06:36 openhabian knxd[23443]: Layer 6 [18:B.usb/Conn        4.734] is OK
Apr 15 15:06:36 openhabian knxd[23443]: Layer 0 [20:log/B.usb         4.737] Recv L_Data low from 1.1.43 to 3/3/0 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write 15 DC
Apr 15 15:06:36 openhabian knxd[23443]: Layer 8 [18:B.usb/Conn        4.737] found addr 1.1.43
Apr 15 15:06:36 openhabian knxd[23443]: Layer 6 [18:B.usb/Conn        4.756] is OK
Apr 15 15:06:36 openhabian knxd[23443]: Layer 0 [20:log/B.usb         4.759] Recv L_Data low from 1.1.43 to 3/3/1 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write 00 00
Apr 15 15:06:36 openhabian knxd[23443]: Layer 8 [18:B.usb/Conn        4.759] found addr 1.1.43
Apr 15 15:06:36 openhabian knxd[23443]: Layer 6 [18:B.usb/Conn        4.778] is OK
Apr 15 15:06:38 openhabian knxd[23443]: Layer 0 [20:log/B.usb         7.541] Recv L_Data low from 1.1.43 to 3/3/3 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
Apr 15 15:06:38 openhabian knxd[23443]: Layer 8 [18:B.usb/Conn        7.541] found addr 1.1.43
Apr 15 15:06:38 openhabian knxd[23443]: Layer 6 [18:B.usb/Conn        7.559] is OK
Apr 15 15:06:39 openhabian knxd[23443]: Layer 0 [20:log/B.usb         8.127] Recv L_Data low from 1.1.43 to 3/3/5 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
Apr 15 15:06:39 openhabian knxd[23443]: Layer 8 [18:B.usb/Conn        8.127] found addr 1.1.43
Apr 15 15:06:39 openhabian knxd[23443]: Layer 6 [18:B.usb/Conn        8.144] is OK
Apr 15 15:06:40 openhabian knxd[23443]: Layer 0 [20:log/B.usb         9.449] Recv L_Data low from 15.15.250 to 3/3/4 hops: 06 T_DATA_XXX_REQ A_GroupValue_Read
Apr 15 15:06:40 openhabian knxd[23443]: Layer 8 [18:B.usb/Conn        9.449] found addr 15.15.250
Apr 15 15:06:40 openhabian knxd[23443]: Layer 6 [18:B.usb/Conn        9.466] is OK
Apr 15 15:06:45 openhabian knxd[23443]: Layer 0 [20:log/B.usb         14.447] Recv L_Data low from 15.15.250 to 3/3/4 hops: 06 T_DATA_XXX_REQ A_GroupValue_Read
Apr 15 15:06:45 openhabian knxd[23443]: Layer 8 [18:B.usb/Conn        14.447] found addr 15.15.250
Apr 15 15:06:45 openhabian knxd[23443]: Layer 6 [18:B.usb/Conn        14.464] is OK
Apr 15 15:06:46 openhabian knxd[23443]: Layer 0 [20:log/B.usb         14.677] Recv L_Data low from 1.1.43 to 3/3/2 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write 56 3C
Apr 15 15:06:46 openhabian knxd[23443]: Layer 8 [18:B.usb/Conn        14.677] found addr 1.1.43
Apr 15 15:06:46 openhabian knxd[23443]: Layer 6 [18:B.usb/Conn        14.696] is OK
Apr 15 15:06:46 openhabian knxd[23443]: Layer 0 [20:log/B.usb         14.699] Recv L_Data low from 1.1.43 to 3/3/1 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write 00 00
Apr 15 15:06:46 openhabian knxd[23443]: Layer 8 [18:B.usb/Conn        14.699] found addr 1.1.43
Apr 15 15:06:46 openhabian knxd[23443]: Layer 6 [18:B.usb/Conn        14.718] is OK
Apr 15 15:06:49 openhabian knxd[23443]: Layer 0 [20:log/B.usb         17.953] Recv L_Data low from 1.1.43 to 3/3/3 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
Apr 15 15:06:49 openhabian knxd[23443]: Layer 8 [18:B.usb/Conn        17.953] found addr 1.1.43
Apr 15 15:06:49 openhabian knxd[23443]: Layer 6 [18:B.usb/Conn        17.970] is OK
#

**Comment by smurfix** [comment]
Umm, your second log doesn't contain a send command and the first doesn't start at the beginning.

>  Maybe, it is a dumb question, but what do you mean by "current main version"?

You get the current version from github, check out the "debian" branch, compile it yourself, and install that. How to do this is described in the `README.md` file.

Would it be possible to remotely log onto your system? I could then try to debug this myself if you'd like.

**Comment by oss83** [comment]
> Would it be possible to remotely log onto your system? I could then try to debug this myself if you'd like.

Yeah, sure. We can do that.

**Comment by smurfix** [comment]
Cool. My ssh pubkey is `ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIECKIg5nuBzRrX/ins4rNR7uPy58M026w7bFQmzT5L13 matthias@urlichs.de`.

Just send me whatever else I need to find my way to and around your system and I'll see what I can do to fix this problem.

**Comment by oss83** [comment]
> Just send me whatever else I need to find my way to and around your system and I'll see what I can do to fix this problem.

I've sent you an email...

**Comment by smurfix** [comment]
Didn't yet get anything, please retry. Where from and exactly when?

**Comment by oss83** [comment]
> Didn't yet get anything, please retry. Where from and exactly when?

yesterday at 18:21 and resent today at 9:42
I also sent you a dm on Facebook :-)

**Comment by oss83** [comment]
@smurfix thanks a lot for your help! Everything is working now

**Comment by smurfix** [comment]
Solution: upgrade to current version.
