### ISSUE TITLE
service init.d debian didn't run into background

### ISSUE THREAD

**Issue by zobi** [knxd/knxd#313]
I just reinstall knxd 0.14.20 on my debian (upgrade to stretch 9.3)

i edit the /etc/default/knxd to : 
`─
START_KNXD=YES
DAEMON_ARGS="-e 0.5.5 -E 0.5.5:3 -c -D -T -R -S -i -b ipt:192.168.2.50"
`

and try to run : `/etc/init.d/knxd start` (or service knxd start)
command is execute but never end (the process knxd is fully running)
if i run "`service knxd start &`" it works but it is not normal ...

Thanks  a lot for your help

**Comment by smurfix** [comment]
Thanks for the bug report. The logic to do backgrounding is somewhat broken. Either wait for 0.14.21, or specify a logfile ("-d /var/log/knxd.log" or whatever).

**Comment by zobi** [comment]
Thanks a lot ;)
