### ISSUE TITLE
knxd no ip communication w/ Siemens N148/21 interface

### ISSUE THREAD

**Issue by cyberways** [knxd/knxd#314]
Hi all,
I'm trying to connect knxd to my Siemens N148/21 ip interface for days now without success. The interface works in ipt mode for several years with ancient eibd 0.0.5.
New server now (Debian 9 lastest, all intalled/compiled from scratch) and I don't get the ipt connection with knxd going.

knxd starts, contacts the N148 ip address but never gets an answer. knxd resends the connect request every 10s, knxd 0.12 just does not work, 0.14 quits because of timeout. 
Wireshark ip trace on the knxd host shows that the gateway answers to port 0 with a malformed packet instead of the source port of the request.
Wireshark trace with eibd shows normal two-way communication as expected. Of course I quit eibd on the old server and even powercycled the ip interface before starting knxd on the new one.

As it works with eibd, can the reason be in the ip message sent by knxd or do I have a misconfiguration?
I have knxd 0.10 running in another site with an ABB ip interface without any problem.

Any ideas what is going on (or a working config) are highly welcome. Thank you for looking into this.
Jan

IP addresses are anonymized to 10.11.12.59 (Siemens N148/21) and 10.11.12.60 (knxd server).
Newlines inserted into both logs/traces to show timing.

jan@hab:~$ knxd -f9 -t1023 -e 0.0.250 -E 0.0.200:8 -i -DTS -b ipt:10.11.12.59

knxd: Layer 8 [ 2:inet 0.000] OpenInetSocket 6720
knxd: Layer 8 [ 2:inet 0.000] InetSocket opened
knxd: Layer 3 [ 3:layer3 0.000] Open
knxd: Layer 3 [ 3:layer3 0.000] L3 started
knxd: Layer 3 [ 3:layer3 0.000] registerLayer2 2:inet
knxd: Layer 3 [ 3:layer3 0.000] registerLayer2 2:inet = 1
knxd: Layer 8 [ 4:mcast:knxd 0.000] Open
knxd: Layer 0 [ 4:mcast:knxd 0.000] Open
knxd: Layer 0 [ 4:mcast:knxd 0.000] Openend
knxd: Layer 8 [ 4:mcast:knxd 0.000] OpenD
knxd: Layer 8 [ 4:mcast:knxd 0.000] OpenedD
knxd: Layer 8 [ 4:mcast:knxd 0.000] Opened
knxd: Layer 3 [ 3:layer3     0.000] registerLayer2 4:mcast:knxd
knxd: Layer 3 [ 3:layer3     0.000] registerLayer2 4:mcast:knxd = 1
knxd: Layer 2 [ 5:ipt:10.11.12.59 0.000] Open
knxd: Layer 0 [ 5:ipt:10.11.12.59 0.000] Open
knxd: Layer 0 [ 5:ipt:10.11.12.59 0.000] Openend
knxd: Layer 2 [ 5:ipt:10.11.12.59 0.000] Opened
knxd: Layer 1 [ 5:ipt:10.11.12.59 0.000] Send(020): 08 01 D4 7D 68 3C 00 00 08 01 D4 7D 68 3C 00 00 04 04 02 00
knxd: Layer 3 [ 3:layer3             0.000] registerLayer2 5:ipt:10.11.12.59
knxd: Layer 3 [ 3:layer3             0.000] registerLayer2 5:ipt:10.11.12.59 = 1
knxd: Layer 0 [ 1:main               0.000] 0.12.16: knxd -f9 -t1023 -e 0.0.250 -E 0.0.200:8 -i -DTS -b ipt:10.11.12.59
knxd: I00000000: 0.12.16: knxd -f9 -t1023 -e 0.0.250 -E 0.0.200:8 -i -DTS -b ipt:10.11.12.59
knxd: Layer 0 [ 5:ipt:10.11.12.59 0.000] Send(026): 06 10 02 05 00 1A 08 01 D4 7D 68 3C 00 00 08 01 D4 7D 68 3C 00 00 04 04 02 00

knxd: Layer 1 [ 5:ipt:10.11.12.59 10.010] Connectretry
knxd: Layer 1 [ 5:ipt:10.11.12.59 10.010] Send(020): 08 01 D4 7D 68 3C 00 00 08 01 D4 7D 68 3C 00 00 04 04 02 00
knxd: Layer 0 [ 5:ipt:10.11.12.59 10.010] Send(026): 06 10 02 05 00 1A 08 01 D4 7D 68 3C 00 00 08 01 D4 7D 68 3C 00 00 04 04 02 00

knxd: Layer 1 [ 5:ipt:10.11.12.59 20.020] Connectretry
knxd: Layer 1 [ 5:ipt:10.11.12.59 20.020] Send(020): 08 01 D4 7D 68 3C 00 00 08 01 D4 7D 68 3C 00 00 04 04 02 00
knxd: Layer 0 [ 5:ipt:10.11.12.59 20.020] Send(026): 06 10 02 05 00 1A 08 01 D4 7D 68 3C 00 00 08 01 D4 7D 68 3C 00 00 04 04 02 00

root@hab:~# tshark port 3671
Capturing on 'ens192'
    1 0.000000000 10.11.12.60 → 10.11.12.59 KNXnetIP 68 CONNECT_REQUEST 55424 > 3671
    2 0.002020964 10.11.12.59 → 10.11.12.60 KNXnetIP 60 CONNECT_RESPONSE 3671 > 0[Malformed Packet]

    3 10.009295117 10.11.12.60 → 10.11.12.59 KNXnetIP 68 CONNECT_REQUEST 55424 > 3671
    4 10.011281076 10.11.12.59 → 10.11.12.60 KNXnetIP 60 CONNECT_RESPONSE 3671 > 0[Malformed Packet]

    5 20.019416175 10.11.12.60 → 10.11.12.59 KNXnetIP 68 CONNECT_REQUEST 55424 > 3671
    6 20.021379919 10.11.12.59 → 10.11.12.60 KNXnetIP 60 CONNECT_RESPONSE 3671 > 0[Malformed Packet]

**Comment by GeminiServer** [comment]
Is working here with Siemens N148 & knxd 0.14.21
Here my knxd_opts: `KNXD_OPTS="--Name=knxd-pi --eibaddr=0.0.2 --client-addrs=0.0.3:20 --listen-local=/tmp/knxd --GroupCache --layer2=ipt:11.11.0.5 --Discovery --Tunnelling --Routing --Server"
`
Only Bug i have is that the KNX-Device Programming seems to be brocken.

**Comment by cyberways** [comment]
Thank you. Do you know if you have the old N148/21 like me or the newer N148/22 interface?

**Comment by GeminiServer** [comment]
i also have the good old 1ab21 ;)

**Comment by FrankEisi** [comment]
Same interface here works with this ini (knxd 0.14.21):

`[B.ipt]
driver = ipt
filters = single,C.pace
ip-address = 192.168.178.44

[C.pace]
delay = 10
filter = pace

#[debug-main]
#error-level = 0x9
#trace-mask = 0xffc

[debug-server]
name = mcast:knxd

[main]
addr = 1.1.200
cache = A.cache
client-addrs = 1.1.200:8
connections = server,B.ipt
debug = debug-main
systemd = systemd

[server]
debug = debug-server
discover = true
server = ets_router
tunnel = tunnel
`

Also prgramming with ETS5 works perfect.

**Comment by cyberways** [comment]
Hi again,
thank you for your answers and suggestions. Good to hear that the N148 is able to talk to knxd principally. But still not here.

I have further investigated with wiresharks KNXnet protocol decoder and by reading http://www.eb-systeme.de/?page_id=479

The communication takes place as expected, but reply packets from the N148 are all addressed to ip port 0 of the knxd host:


```
Frame 1: 68 bytes on wire (544 bits), 68 bytes captured (544 bits) on interface 0
User Datagram Protocol, Src Port: 56679, Dst Port: 3671
    Source Port: 56679
    Destination Port: 3671
    Length: 34
    Checksum: 0x79a6 [unverified]
    [Checksum Status: Unverified]
    [Stream index: 0]
KNXnet/IP
    Header
        Header Length: 0x06
        Protocol Version: 0x10
        Service Type Identifier: CONNECT_REQUEST (0x0205)
        Total Length: 26 octets
    Body
        HPAI: Discovery endpoint
            Structure Length: 8 octets
            Host Protocol Code: IPV4_UDP (0x01)
            IP Address: 212.125.104.60
            IP Port: 0
        HPAI: Data endpoint
            Structure Length: 8 octets
            Host Protocol Code: IPV4_UDP (0x01)
            IP Address: 212.125.104.60
            IP Port: 0
        Connection Request Information
            Structure Length: 4 octets
            Connection Type: TUNNEL_CONNECTION (0x04)
            KNX Layer: TUNNEL_LINKLAYER (0x02)
            reserved: 00

Frame 2: 62 bytes on wire (496 bits), 62 bytes captured (496 bits) on interface 0
User Datagram Protocol, Src Port: 3671, Dst Port: 0
    Source Port: 3671
    Destination Port: 0
    Length: 28
    Checksum: 0xc4ab [unverified]
    [Checksum Status: Unverified]
    [Stream index: 1]
KNXnet/IP
    Header
        Header Length: 0x06
        Protocol Version: 0x10
        Service Type Identifier: CONNECT_RESPONSE (0x0206)
        Total Length: 20 octets
    Body
        Communication Channel ID: 84
        Status: E_NO_ERROR - The connection was established successfully (0x00)
        HPAI: Data endpoint
            Structure Length: 8 octets
            Host Protocol Code: IPV4_UDP (0x01)
            IP Address: 212.125.104.59
            IP Port: 3671
        Connection Response Data Block
            Structure Length: 4 octets
            Connection Type: TUNNEL_CONNECTION (0x04)
            KNX Address 0.0.1

```

So far so good. N148 gets and accepts the connection request, but answers to ip port 0 as requested in the HPAI message. I think this is wrong and the port number is actually missing (= zero) in the HPAI messages of knxd. HPAI messages sent by N148 have correct port 3671.
knxd doesn't seem to get the reply packets from the os (debian 9 on esxi) and does connect retries forever.

Thank you for looking again.
Regards, Jan

**Comment by smurfix** [comment]
Please check if this change fixes the problem.

Frankly, the device should use the port the packet is from when the HPAI port is zero. knxd isn't the only client which does this.
```
diff --git a/src/backend/eibnettunnel.cpp b/src/backend/eibnettunnel.cpp
index 07b6030..961b286 100644
--- a/src/backend/eibnettunnel.cpp
+++ b/src/backend/eibnettunnel.cpp
@@ -103,6 +103,7 @@ EIBNetIPTunnel::start()
   sock = new EIBNetIPSocket (raddr, (sport != 0), t);
   if (!sock->init ())
     goto ex;
+  raddr.sin_port = sock->port();
   sock->on_recv.set<EIBNetIPTunnel,&EIBNetIPTunnel::read_cb>(this);
   sock->on_error.set<EIBNetIPTunnel,&EIBNetIPTunnel::error_cb>(this);

```

**Comment by cyberways** [comment]
compiles, starts, works... 
I can switch lights locally with knxtool and relay the eibd from the old server through the new knxd to the N148. Perfect!

> Frankly, the device should use the port the packet is from when the HPAI port is zero.
There is no doubt about it. But it's from ... 

Thank you VERY MUCH for the patch! You made my day after a weekend of troubleshooting.

**Comment by smurfix** [comment]
You're welcome. Go forth and send something nice to my Paypal account. ;-)
(If you want to.)
