### ISSUE TITLE
included libfmt cannot be built anymore

### ISSUE THREAD

**Issue by tru7** [knxd/knxd#321]
configure fails because included libfmt cannot be built anymore. It returns:
configure: error: libfmt just built is not usable!?!
        "tail -v -n +0 config.log"
building says:
[ 50%] Building CXX object CMakeFiles/fmt.dir/include/fmt/posix.cc.o
[100%] Building CXX object CMakeFiles/fmt.dir/include/fmt/format.cc.o
Linking CXX static library libfmt.a

Compaired to times when building libfmt still was successful, building said:
[ 20%] Building CXX object fmt/CMakeFiles/fmt.dir/posix.cc.o
[ 40%] Building CXX object fmt/CMakeFiles/fmt.dir/format.cc.o
[ 60%] Building CXX object fmt/CMakeFiles/fmt.dir/ostream.cc.o
[ 80%] Building CXX object fmt/CMakeFiles/fmt.dir/printf.cc.o
[100%] Linking CXX static library libfmt.a

**Comment by smurfix** [comment]
libfmt has undergone a couple of incompatible changes. Header and built library have moved, but even correcting for that doesn't help.
This may also be related to GCC 7.2 being more strict with objects it considers to be read-only.
```
configure:18938: g++ -o conftest -g -O2 -fdebug-prefix-map=/home/smurf/src/knxd=. -fstack-protector-strong -std=c++0x -Wno-subobject-linkage -Wdate-time -D_FORTIFY_SOURCE=2 -I/home/smurf/src/knxd/libfmt/include -Wl,-z,relro -L/home/smurf/src/knxd/libfmt conftest.cpp -lfmt  >&5
In file included from /home/smurf/src/knxd/libfmt/include/fmt/format.h:40:0,
                 from conftest.cpp:42:
/home/smurf/src/knxd/libfmt/include/fmt/core.h: In member function 'constexpr void fmt::basic_string_view<Char>::remove_prefix(size_t) const':
/home/smurf/src/knxd/libfmt/include/fmt/core.h:210:14: error: assignment of read-only location 'static_cast<const size_t&>(((const fmt::basic_string_view<Char>*)this)->fmt::basic_string_view<Char>::size_)'
     size_ -= n;
```

Investigating.

**Comment by smurfix** [comment]
libfmt master is now on version "whatever". There is no version 3 branch on github, which is annoying. Reporting a bug. Uploaded 0.14.24 which uses the 4.x branch.

**Comment by tru7** [comment]
building on Debian 8.2 works again with 0.14.24, thanks for that.
However crosscompiling still fails for a similar error you mentioned above:
`[ 33%] Building CXX object CMakeFiles/fmt.dir/include/fmt/posix.cc.o
In file included from /var/local/lede/build_dir/target-mips_24kc_musl/knxd/libfmt/include/fmt/posix.h:28:0,
                 from /var/local/lede/build_dir/target-mips_24kc_musl/knxd/libfmt/include/fmt/posix.cc:13:
/var/local/lede/build_dir/target-mips_24kc_musl/knxd/libfmt/include/fmt/format.h:646:35: error: 'constexpr' is not allowed in declaration of friend template specialization 'const Char* pointer_from<Char>(fmt::internal::null_terminating_iterator<Char>)'
       null_terminating_iterator it);
                                   ^
/var/local/lede/build_dir/target-mips_24kc_musl/knxd/libfmt/include/fmt/format.h: In instantiation of 'constexpr const Char* fmt::internal::pointer_from(fmt::internal::null_terminating_iterator<Char>) [with Char = char]':
`
Compiler is gcc version 5.5.0 (LEDE GCC 5.5.0 r5171-bca01fd)
