### ISSUE TITLE
ETS programming fails.

### ISSUE THREAD

**Issue by bramroelandts** [knxd/knxd#324]
While reading and writing works flawlessly, I can't get ETS programming to work. For easier debugging, I made a Wireshark capture of programming an actor using the IP Interface and another capture of programming the same actor, but using knxd. Programming succeeds on the IP interface, but fails on knxd.

I'm using the latest version of the knxd master branch on a Raspberry Pi 3, connected to a Zennio IP-Interface (ZSY-IPI-PL) for bus communication. The ETS version I'm using is 5.6.3. These are the knxd startup parameters I'm using: 

> --eibaddr=0.1.250 --client-addrs=0.1.80:8 -t 1023 -f 9 -d -D -T -S -i 6719 --listen-local=/tmp/knx -b iptn:'192.168.1.67'
 
**IP addresses in Wireshark captures:**

> Windows 10 VM with **ETS:** 192.168.1.16
> Raspberry Pi with **knxd:** 192.168.1.50
> Zennio KNX IP-interface: 192.168.1.67

### Packet sequence when using IP interface:

> 46: **ETS** sends A_DeviceDescriptor_Read
> 47: **IP** sends ack
> 48: **IP** sends A_DeviceDescriptor_Read
> 49: **ETS** sends ack
> 50: **IP** sends TPCI NCD

### Packet sequence when using knxd:

> 47: **ETS** sends A_DeviceDescriptor_Read
> 48: **knxd** sends ack
> 49: **knxd** sends A_DeviceDescriptor_Read
> 50: **ETS** sends ack
> 51: **ETS** sends A_DeviceDescriptor_Read (once again)
> 52: **knxd** sends ack
> 53: **knxd** sends A_DeviceDescriptor_Read

### Analysis:

When programming on the IP interface, ETS sends A_DeviceDescriptor_Read, the IP interface replies and the programming sequence continues. With knxd, however, ETS receives the A_DeviceDescriptor_Read from knxd and does not seem to be satisfied with it, so ETS keeps repeating the same request.

When trying to determine why ETS wasn't satisfied with knxd's reponse, I noticed the source address sent back by knxd was set to 0.0.0. The original ETS packet was also sent with 0.0.0, so knxd assigns a physical address itself, but then knxd returns the packet with source address 0.0.0. It seems as though the packet returned by knxd flies under ETS's radar. The IP interface, however, sets the source address in that packet to 0.1.100, which is the actual address used by ETS. I therefore think the 0.0.0 address is what makes ETS refuse programming with knxd.

How would I go about debugging this issue? Can I solve this myself with some basic C knowledge? Does what I'm saying make any sense, or is there something I'm completely missing?

In any case, thanks a lot for this awesome open-source project!

[Wireshark captures.zip](https://github.com/knxd/knxd/files/1782155/Wireshark.captures.zip)

**Comment by GeminiServer** [comment]
Got also trouble with Programming! 

Check your configuration. After reading knxd [documentation](https://github.com/knxd/knxd/wiki/Command-line-parameters) i found a solution. Now it's working perfect for me.

Here is my ini, may it will help you to find the problem (start with "knxd knxd.ini" ):
`[A.unix]
path = /tmp/knxd
server = knxd_unix
systemd-ignore = false

[B.ipt]
driver = ipt
filters = single,C.pace
ip-address = 10.0.0.2

[C.pace]
delay = 10
filter = pace

[debug-main]
error-level = 0x9
trace-mask = 0xffc

[debug-server]
name = mcast:knxd

[main]
name = knxd
addr = 1.1.255
cache = A.cache
client-addrs = 1.1.255:8
connections = A.unix,B.ipt,server
debug = debug-main
systemd = systemd

[server]
debug = debug-server
discover = true
router = router
server = ets_router
tunnel = tunnel
`

**Comment by smurfix** [comment]
```client-addrs = 1.1.255:8```

That actually translates to `1.2.0:7`, since you're using 1.1.255 for knxd itself.

**Comment by dallmair** [comment]
An issue with ETS programming has also been reported in #550, and that one was also about physical address 0.0.0, has been fixed in commit 3fa3794e5bca2ac7ca18793e7aa9a39f2042f8df, and released in 0.14.59. I have programmed a bunch of devices successfully with recent versions of knxd, so I think this is fixed and will close this issue now.

Please reopen if you're still facing this problem in a current version of knxd.
