### ISSUE TITLE
Include path for ev++.h missing

### ISSUE THREAD

**Issue by kbernloehr** [knxd/knxd#330]
The ev++.h header file, at least on my Mageia6 system, is located under /usr/include/libev.
Let configure check for that location (patch for configure.ac following):

diff --git a/configure.ac b/configure.ac
index f7025e3..23fb5e3 100644
--- a/configure.ac
+++ b/configure.ac
@@ -260,6 +260,10 @@ else
 LDFLAGS="$LDFLAGS -L$(pwd)/libfmt/fmt"
 fi
 
+if test -f /usr/include/libev/ev++.h ; then
+CPPFLAGS="$CPPFLAGS -I/usr/include/libev"
+fi
+
 AC_LINK_IFELSE([AC_LANG_PROGRAM([#include <fmt/format.h>], [fmt::format("The answer is {}", 42);
 ])],
 [],

**Comment by dallmair** [comment]
Thanks for your contribution @kbernloehr ! I've committed the proposed changes in your name and created a PR to get these in, finally...
