### ISSUE TITLE
Want to setup room automation using Raspberry Pi 3, TPUART, KNXD and OpenHAB

### ISSUE THREAD

**Issue by harshi3** [knxd/knxd#338]
I have installed latest Raspbian on my Raspberry Pi 3 B+ model and have configured it with an IP. I have also installed KNX Daemon on it. 
I have connected the electric bus to Raspberry Pi using TPUART.
I don't know how to proceed further.

**Comment by smurfix** [comment]
You read the docs, or ask in the google group.
Then you add what you've learned to the wiki or the README. ;-)

Github issues are not a support forum.
