### ISSUE TITLE
knxd configfile

### ISSUE THREAD

**Issue by fohnbit** [knxd/knxd#347]
Hello,

I upgraded from .12 to .15 ... now her write to use a configfile.
my /etc/knxd.conf:
KNXD_OPTS="-n 'knxd' -e 1.1.240 -E 1.1.240:10 -f 9 -D -T -S -c -t 0 -b tpuarts:/dev/ttyS1"

where I has to set the new config file and with which content?

Thank you!

**Comment by skevnet** [comment]
You can find the information you need on knxd's wiki page here.
[Command line parameters](https://github.com/knxd/knxd/wiki/Command-line-parameters)

**Comment by dallmair** [comment]
Also, [inifile.rst](https://github.com/knxd/knxd/blob/main/doc/inifile.rst) covers a lot of the config file based configuration.
