### ISSUE TITLE
Error while compiling with --enable-management

### ISSUE THREAD

**Issue by Ks89** [knxd/knxd#349]
Hi @smurfix, 
I compiled knxd on a raspberry pi3 and everything it worked perfectly using your readme.md and wiki.

Now, I'm trying to compile knxd on a different linux os (embedded distribution) and I can build it, with all --enable params, except for --enable-management.

When I'm compiling with "--enable-management" i get this error:
```
In file included from ../../../knxd-0.14.25/src/libserver/management.h:23:0,
                 from ../../../knxd-0.14.25/src/libserver/management.cpp:20:
../../../knxd-0.14.25/src/libserver/layer7.h:54:3: error: 'APDUPtr' does not name a type
   APDUPtr Request_Response (APDU * r);
   ^~~~~~~
../../../knxd-0.14.25/src/libserver/layer7.h:109:3: error: 'APDUPtr' does not name a type
   APDUPtr Request_Response (APDU * r);
   ^~~~~~~
In file included from ../../../knxd-0.14.25/src/libserver/management.cpp:20:0:
../../../knxd-0.14.25/src/libserver/management.h: In constructor 'Management_Connection::Management_Connection(TracePtr, eibaddr_t)':
../../../knxd-0.14.25/src/libserver/management.h:46:5: error: 'TracePtr Layer7_Connection::t' is private within this context
     t->setAuxName("Mgr");
     ^
In file included from ../../../knxd-0.14.25/src/libserver/management.h:23:0,
                 from ../../../knxd-0.14.25/src/libserver/management.cpp:20:
../../../knxd-0.14.25/src/libserver/layer7.h:48:12: note: declared private here
   TracePtr t;
            ^
Makefile:516: recipe for target 'management.o' failed
make[3]: *** [management.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory 'MY_PATH/knxd/0.14.25/build/src/libserver'
Makefile:386: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory 'MY_PATH/knxd/0.14.25/build/src'
ERROR: oe_runmake failed
Makefile:434: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory 'MY_PATH/knxd/0.14.25/build'
Makefile:370: recipe for target 'all' failed
make: *** [all] Error 2
WARNING: exit code 1 from a shell command.
```

I don't understand this error, what does it mean?

Also, I don't understand the purpose of "--enable-management". What does it mean "management"?

**Comment by smurfix** [comment]
The management subsystem does not work because nobody has ported it to knxd's new architecture yet.

> Also, I don't understand the purpose of "--enable-management". What does it mean "management"?

I'd suggest that if you don't understand an option, you don't try to use it. You're very unlikely to need that code.

**Comment by Ks89** [comment]
Ok, so management subsystem is not required to use knxd with ft12, tpuarts, iptn and so on. Right?
And what about ETS programming?

I'm sorry for these stupid questions, but I want to be sure that I can remove "--enable-management" without missing features (that I need) and so on.
