### ISSUE TITLE
KNXD not receiving messages on physical inputs

### ISSUE THREAD

**Issue by coxfrederic** [knxd/knxd#353]
Hi,

Disclaimer: I am new to knxd and KNX alltogether, so please bear with me.

I have setup Homebridge on my Raspberry Pi and using knxd for the communication with my ETS5 programmed KNX installation so I can use Apple HomeKit.

Everything is working fine there, meaning that I can control my lights from HomeKit and this works fine.

However, now I have integrated the physical switches. When I switch a light it turns on and off perfectly, no problem there. The problem is in the updating of HomeKit. If a light is turned off and I turn it on with the physical switch, then HomeKit is not showing the light as "on".

I narrowed it down (I think) to the fact that knxd is not receiving the messages when the physical switch is handled. However in ETS5 when I monitor the group communication I can see messages appear. In knxd using vbusmonitor1 I only see the messages when controlling the switches through HomeKit (and nothing is echoed when I use a physical switch).

In ETS5 I have setup my router to enable multicast.

knx_config.json excerpt:

`"knxd_ip": "127.0.0.1",
    "knxd_port": 6720,
    "AllowWebserver": true,
    "AllowKillHomebridge": false,
    "Devices": [
        {
            "DeviceName": "Keuken licht tafel",
            "Services": [
                {
                    "ServiceType": "Lightbulb",
                    "ServiceName": "Keuken tafel licht",
                    "Characteristics": [
                        {
                            "Type": "On",
                            "Set": [
                                "1/1/1"
                            ],
                            "Listen": [
                                "1/1/1"
                            ],
                            "Lists": [
                                "1/1/1"
                            ]
                        }
                    ],
                    "subtype": "SUB_a8b7da58-9d37-47c3-814e-e1abcfdf8eca"
                }
            ],
            "UUID": "4acbb74d-900e-4f3b-b9ca-88c0d9ac869b"
        }`

/etc/knxd.conf excerpt:

`KNXD_OPTS="-e 1.1.0 -E 1.1.0:255 -u /tmp/eib -b ip: -R -S"`

Can anyone help me on this? If you need more info please let me know

**Comment by coxfrederic** [comment]
Changed KNXD_OPTS to -f9 -t 1023 -e 1.1.0 -E 1.1.0:255 -u /tmp/eib -b ip: -R -S

When I switch the physical switch I get the following output from `sudo systemctl status knxd`

`● knxd.service - KNX Daemon
   Loaded: loaded (/lib/systemd/system/knxd.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2018-08-11 01:34:00 CEST; 2min 42s ago
 Main PID: 1116 (knxd)
   CGroup: /system.slice/knxd.service
           └─1116 /usr/bin/knxd -f9 -t 1023 -e 1.1.0 -E 1.1.0:255 -u /tmp/eib -b ip: -R -S

Aug 11 01:36:21 raspberrypi knxd[1116]: Layer 6 [24:systemd_/ConnS      140.311] is OK
Aug 11 01:36:21 raspberrypi knxd[1116]: Layer 6 [13:B.ip/Conn           140.311] is OK
Aug 11 01:36:21 raspberrypi knxd[1116]: Layer 6 [ 1:main                140.311] OK
Aug 11 01:36:21 raspberrypi knxd[1116]: Layer 6 [ 2:main/L              140.311] OK L
Aug 11 01:36:37 raspberrypi knxd[1116]: Layer 0 [16:server/Server       156.793] Recv(017): 06 10 05 30 00 11 29 00 BC D0 11 01 09 1E 01 00 81
Aug 11 01:36:37 raspberrypi knxd[1116]: Layer 8 [24:systemd_/ConnS      156.793] found addr 1.1.1
Aug 11 01:36:37 raspberrypi knxd[1116]: Layer 3 [19:router/ConnC        156.793] Packet not from 24:systemd_: L_Data low from 1.1.1 to 1/1/30 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write (
Aug 11 01:36:37 raspberrypi knxd[1116]: Layer 0 [14:B.ip/ip             156.793] Recv(017): 06 10 05 30 00 11 29 00 BC D0 11 01 09 1E 01 00 81
Aug 11 01:36:37 raspberrypi knxd[1116]: Layer 8 [24:systemd_/ConnS      156.793] found addr 1.1.1
Aug 11 01:36:37 raspberrypi knxd[1116]: Layer 3 [13:B.ip/Conn           156.793] Packet not from 24:systemd_: L_Data low from 1.1.1 to 1/1/30 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write (
`

What does this mean?

**Comment by coxfrederic** [comment]
Presuming the error is in `Aug 11 01:41:06 raspberrypi knxd[1116]: Layer 3 [13:B.ip/Conn 425.961] Packet not from 24:systemd_: L_Data low from 1.1.1 to 1/1/30 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write (small) 01`

I searched this repository for https://github.com/knxd/knxd/search?q=%22Packet+not+from%22&unscoped_q=%22Packet+not+from%22

Anyone with a clue on this one?

**Comment by smurfix** [comment]
Yes. Do not use your real bus addresses in the -E option.

**Comment by coxfrederic** [comment]
Hi @smurfix , thanks for helping out on this issue. Can you please elaborate a bit more on that? What should I use (what's it for?).

Thanks just trying to learn here!

**Comment by smurfix** [comment]
-E is documented as the KNX address range available for dynamic clients. As such it obviously can't overlap with anything that's in use elsewhere on your bus.

**Comment by coxfrederic** [comment]
Thanks for your help! I've changed it to `KNXD_OPTS="-e 0.0.1 -E 0.0.2:255 -u /tmp/eib -b ip: -R -S"`
and this works like a charm now! 👍
