### ISSUE TITLE
KNX Binding - maximum send attempts error

### ISSUE THREAD

**Issue by dennys78** [knxd/knxd#356]
I have this message in the logs :
changed from OFFLINE (COMMUNICATION_ERROR): maximum send attempts to OFFLINE (COMMUNICATION_ERROR): timeout connecting to control endpoint

And this :
KNX Binding - maximum send attempts error
I Try new installation and test different type of connection, TUNNEL and ROUTER but nothing!!!

I’m about to go crazy! please help me !!

**Comment by smurfix** [comment]
Please tell us which program you're talking about, besides knxd, and how you configured it (and knxd).

**Comment by dennys78** [comment]
Oooo of course... I use OpenHab 2

I try different type of connection .... TUNNEL and Router

Tk

**Comment by dennys78** [comment]
Now ! 
2018-09-21 08:57:56.106 [ERROR] [NXnet/IP Tunneling 192.168.1.35:3671] - close connection - maximum send attempts

**Comment by smurfix** [comment]
Frankly, I am not interested in OpenHAB error messages.
Again: Please provide OpenHAB and knxd configuration details. gist.github.com is your friend.
