### ISSUE TITLE
help installing and making knxd work 

### ISSUE THREAD

**Issue by galeag** [knxd/knxd#357]
is there somewhere a procedure step by step on how to install, setting the knxd.conf file and starting up knxd please? i am trying to make it work wit homebridge using homebridge-knx on the same raspberry pi.

**Comment by smurfix** [comment]
You mean, other than the README?
Starting up is done by systemd (see the README) or whatever other mechanism your Linux distribution uses (ask them).

**Comment by galeag** [comment]
i have tried several times and Im always getting an error when doing dpkg-buildpackage -b -uc when checking dependencies and when trying sudo dpkg -i knxd_*.deb knxd-tools_*.deb it fails on some of the dependencies. I admit im not good on linux and some things that might be natural to some are probably not for me. if someone is ready to give me a hand please my email is galeag@gmail.com

**Comment by smurfix** [comment]
What to do when dependencies are missing is in the README. If you can't install with "dpkg -i", use "apt-get instapp MISSING_PACKAGE". knxd is not in the business of writing yet another replication of "how to build and install a Debian package" document.
