### ISSUE TITLE
Missing group address check

### ISSUE THREAD

**Issue by TrondKjeldas** [knxd/knxd#359]
There is a change in behavior compared to eibd 0.0.5

I'm using the EIBConnection.py client code to connect to knxd using the EIBOpenT_Group() and EIBGetAPDU_Src() methods, the former taking a group address as a parameter.

In eibd 0.0.5 this would cause the EIBGetAPDU_Src() method to return only when the group address specified were received by eibd.

However, when using knxd, version 0.14, the EIBGetAPDU_Src() method returns for all group addresses.

Digging around in the knxd source I have found (in layer4.h) that the T_Group class keeps the g.a. used when client connects, but that it do not implement its own checkGroupAddress() method and actually compares the group address of the telegram being handled with the address provided in the connect, but relies on the checkGroupAddress() method of it parent class, Layer4commonWO, which only checks for !write_only.

Below is a patch that seems to fix this issue for me, but it could very well be that the fix is completely inappropriate, since I do not have any familiarity with the code base.

Any advice on how to properly fix this would be appreciated.

/Trond 

```
diff --git a/src/libserver/layer4.h b/src/libserver/layer4.h
index 264b4b0..ff8f1d2 100644
--- a/src/libserver/layer4.h
+++ b/src/libserver/layer4.h
@@ -96,7 +96,7 @@ public:
     { this->write_only = write_only; }
 
   bool checkAddress(eibaddr_t addr) { return !write_only && addr == this->getAddress(); }
-  bool checkGroupAddress(eibaddr_t addr UNUSED) { return !write_only; }
+  virtual bool checkGroupAddress(eibaddr_t addr UNUSED) { return !write_only; }
 };
 
 /** Broadcast Layer 4 connection */
@@ -141,6 +141,9 @@ public:
   void send_L_Data (LDataPtr l);
   /** send APDU to L3 */
   void recv_Data (const CArray & c);
+
+  virtual bool checkGroupAddress(eibaddr_t addr) { return (addr == groupaddr); }
+
 };
 typedef std::shared_ptr<T_Group> T_GroupPtr;
 
```

**Comment by smurfix** [comment]
Looks sane. Could you please prepare this as a pull request?

**Comment by TrondKjeldas** [comment]
Ok, will do.

**Comment by TrondKjeldas** [comment]
Closing this old issue, since it has been fixed twice since then.
