### ISSUE TITLE
Help needed for basic installation of KNXD

### ISSUE THREAD

**Issue by marcocastellano** [knxd/knxd#364]
Hello everyone and sorry in advance the banality of my questions, unfortunately I do not have the basics of programming, but I am a KNX certificate (At least this!)
I have Stretch and Homebridge with KNX plugin installed on my new RB pi 3(static ip 192.168.1.6)
I have a KNX IP router interface (EKINEX https://en.ekinex.com/technical-area_knx-system-devices/ip-router_136.html) with static ip 192.168.1.60 in my network
With not a few difficulties I installed KNXD and now I have to configure it
How could I enter in edit mode?what parameters do I have to use?

I also have configured and put in place the KNX_CONFIG.JSON file (I can see all the KNX objects in the homekit without communications on the bus).

Of which device is the IP In the first line of Json file " knxd_ip | "192.168.1.6" ? of the KNX/IP router? of the RB pi?
I am working on 1.0.X area/sector on ETS 5
Thanks a lot for your big help!

Marco

**Comment by tru7** [comment]
Please ask your questions in https://groups.google.com/forum/#!forum/knxd if you cannot help yourself with the wiki and the readme

**Comment by rohithanayady** [comment]
hello 
i am trying to install knxd on a debian based module . After completing all the installation procedures , when i tried to start the knxd it was showing "Unit knxd.servie.service could not be found"
There weren't any issues during the installation but its not working.
Can Anyone help resolve this issue.
