### ISSUE TITLE
compile fails with recents commits

### ISSUE THREAD

**Issue by tru7** [knxd/knxd#372]
with g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0 compile now fails with this error messages:
` g++ -DHAVE_CONFIG_H -I. -I../..  -I../../src/include -I../../src/common -I../../src/usb -I/usr/include/libusb-1.0   -g -O2 -std=c++0           x -Wno-subobject-linkage -MT llserial.o -MD -MP -MF .deps/llserial.Tpo -c -o llserial.o llserial.cpp
llserial.cpp: In member function ‘virtual void LLserial::start()’:
llserial.cpp:138:33: error: too few arguments to function ‘void restore_low_latency(int, low_latency_save*, bool)’
   restore_low_latency (fd, &sold);
                                 ^
In file included from llserial.h:26:0,
                 from llserial.cpp:33:
lowlatency.h:38:6: note: declared here
 void restore_low_latency (int fd, low_latency_save * save, bool really);
      ^~~~~~~~~~~~~~~~~~~
Makefile:520: recipe for target 'llserial.o' failed`

Same problem on Openwrt trunk toolchain

**Comment by Race666** [comment]
src/libserver/llserial.cpp Line 138 
restore_low_latency (fd, &sold);
must replaced with:
restore_low_latency (fd, &sold, low_latency);

**Comment by tru7** [comment]
yes, that works for me too

**Comment by smurfix** [comment]
Fixed. Sorry about that.
