### ISSUE TITLE
Weinzierl USB Interface 332

### ISSUE THREAD

**Issue by waldo16** [knxd/knxd#379]
Mit KNXD kann ich die KNX Anlage nicht schalten.

Installation und Anlage
- Betriebssystem ist Linux Mint 18.3 Cinnamon 64bit
- FHEM 5.8 und knxd 0.14.28 amd64 beides .deb Packete
- Winzierl KNX USB Interface 332 und funktionierender KNX Anlage

- Inhalt von /etc/knxd.conf
START_KNXD=NO
KNXD_OPTS="-e 1.0.20 -E 1.1.245:5 -u /tmp/eib -D -T -S -b usb:"

- Inhalt von /etc/udev/rules.d/70-knxusb-devices.rules
ACTION=="add", SUBSYSTEM=="tty", ATTRS{idVendor}=="0e77", ATTRS{idProduct}=="0104", KERNELS=="usb", SYMLINK+="ttyKNX1", OWNER="knxd"
LABEL="knxd_end"

- PC hochfahren oder Start KNXD mit: sudo systemctl start knxd

- Rückmeldung ist: systemctl status knxd.service
● knxd.service - KNX Daemon
   Loaded: loaded (/lib/systemd/system/knxd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fre 2018-12-21 11:20:29 CET; 3s ago
 Main PID: 23421 (knxd)
   CGroup: /system.slice/knxd.service
           └─23421 /usr/bin/knxd -e 1.0.20 -E 1.1.245:5 -u /tmp/eib -D -T -S -b usb:

   systemd[1]: Starting KNX Daemon...
   systemd[1]: Started KNX Daemon.

Senden mit: knxtool groupswrite ip:localhost 0/0/2 1
Send request

Rückmeldung ist: knxtool vbusmonitor1 local:
LPDU: BC 11 F6 00 02 E1 00 81 C6 :L_Data low from 1.1.246 to 0/0/2 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01 

Etwas wird gesendet, am Stick blinkt die USB LED jedeoch nicht die KNX LED und es wird nichts geschaltet.
Was fehlt hier noch damit auch geschaltet wird ?

**Comment by smurfix** [comment]
Aus meiner Sicht fehlt da gar nix. Was passiert denn,w enn du das Gerät mit einem KNX-Taster schalten willst?

NB, bitte frag sowas im Forum – der Tracker in github ist für knxd-Bugs reserviert, und das scheint keiner zu sein.
