### ISSUE TITLE
decent version naming

### ISSUE THREAD

**Issue by tru7** [knxd/knxd#381]
May I please ask for a decent naming for future releases. Neither v- nor subfolder nor Debian prefix, just plan version number. This helps using streamlined download URLs fetching tar-balls from github.
Thank you very much.

**Comment by tru7** [comment]
May I ask why the new release again has a DEBIAN- prefix? I hoped it would just be named 0.14.29-1

**Comment by smurfix** [comment]
Sorry, my mistake, will tag correctly in a moment.
