### ISSUE TITLE
Is there commercial support for knxd available

### ISSUE THREAD

**Issue by cdonat** [knxd/knxd#388]
Sorry to misuse the issues here, but I couldn't find a mailinglist or anything similar.

Is there already a company providing commercial support for knxd?

**Comment by henfri** [comment]
Hello,

here https://knx-user-forum.de/forum/projektforen/knxd/1049547-grundlagen-zum-knxd-mit-installationsanleitung-vor-dem-schreiben-lesen?p=1050001#post1050001
the author asks for donations but also writes, that he can issue a bill -so, there is some hope ;-)

I suggest you ask via the mentioned mail adress.

Regards,
Hendrik

**Comment by cdonat** [comment]
Thank you very much. I'll do that.

**Comment by smurfix** [comment]
I am much more interested in people who collaborate on knxd … money is appreciated but secondary.
