### ISSUE TITLE
Switch to CMake

### ISSUE THREAD

**Issue by tasptz** [knxd/knxd#39]
I tried out the switch-to-cmake branch and found two issues.
1. Minor issue with character escaping in python client generation
2. Problem with multiple build jobs
The parallel generation of c files in src/client/c/CMakeLists.txt is problematic as described in the documentation of add_custom_command. My suggestion is to simply generate the files instantly with cmake's file write command, as can be seen in my fork.

**Comment by timowi** [comment]
Thanks for testing it.

> Minor issue with character escaping in python client generation

This was just a quick try to test generating in general. I had some problems with escaping too. On Windows this does not work at all. I thought about moving the cammands in a (bash) script and calling this from cmake.

> The parallel generation of c files in src/client/c/CMakeLists.txt is problematic [...]

Whats the problem there? The binary depends on the .o files and the object files in the generated c files. Parallel building should work.

> as can be seen in my fork.

There are no commits by you in your fork. Forgot to commit and push your changes?

**Comment by tasptz** [comment]
Regarding parallel building:
If I do a fresh build with multiple jobs I get "corrupted" c files.
E.g.
client/c/gen/loadimage.c looks like this:

    #include "c/eibclient-int.h"
    #include "def/loadimage.inc"
    #include "def/loadimage.inc"

which leads to errors like

    src/client/def/loadimage.inc:30:16: error: redefinition of ‘EIB_LoadImage_complete’
     EIBC_COMPLETE (EIB_LoadImage,
                    ^

Of course the file should look like this

   #include "c/eibclient-int.h"
   #include "def/loadimage.inc"

I believe this is because of

    Do not list the output in more than one independent target that may build in parallel or the two instances of the rule may conflict (instead use add_custom_target to drive the command and make the other targets depend on that one).

(http://www.cmake.org/cmake/help/v3.1/command/add_custom_command.html).

**Comment by tasptz** [comment]
Regarding my fork - have you looked in the right (switch-to-cmake) branch?

https://github.com/tasptz/knxd/commit/b81881b5624c74a539bc7c897cfec26d8ba38748

This was just a quick solution and other may be better.
