### ISSUE TITLE
Support for Debian 8 Jessie dropped?

### ISSUE THREAD

**Issue by sseide** [knxd/knxd#390]
Due to recent updates of the debhelper dependency to a version >=10 knxd cannot build on Debian jessie anymore. Latest version there is 9.x.

Was this done by intent / needed due to newer features?
Just stumbled accross this because the tests failed after updating to latest TAG for my Ansible role i created to install knxd... (http://github.com/sseide/ansible-role-knxd).

Thanks,
Stefan Seide

**Comment by smurfix** [comment]
It was required to get knxd into Debian.
Easiest workaround: edit the dependency (add a "lineinfile" rule …).

**Comment by sseide** [comment]
Thanks for the info - changed ansible role accordingly for jessie and now its running on all systems again (jessie stretch buster).
