### ISSUE TITLE
KNXD and STKNX

### ISSUE THREAD

**Issue by irrabb** [knxd/knxd#393]
Hi!

I'm trying to use the STKNX transceiver connected to a RBPi CM3 running KNXD. 

The configruation is good so far, but I'm having problems while interfacing the UART with the STKNX. 
It seems like there's no answer to the reset pretition:

Layer 0 [18:C.tpuarts/log       0.000] Insert 17:LowF / 16:tpuart
Layer 0 [18:C.tpuarts/log       0.000] Setup
Layer 0 [20:C.tpuarts/log       0.000] Insert 19:TPU_ser / 17:LowF
Layer 0 [18:C.tpuarts/log       0.000] Filter single not found
Layer 0 [20:C.tpuarts/log       0.000] Setup
Layer 0 [20:C.tpuarts/log       0.000] Setup OK: yes
Layer 0 [18:C.tpuarts/log       0.000] Setup OK: yes
Layer 3 [15:C.tpuarts/Conn      0.001] registerLink: 15:C.tpuarts
Layer 3 [15:C.tpuarts/Conn      0.001] Start: cfg:C.tpuarts
Layer 5 [15:C.tpuarts/Conn      0.001] down => >up
Layer 5 [15:C.tpuarts/Conn      0.001] Starting
Layer 0 [18:C.tpuarts/log       0.001] Start
Layer 0 [20:C.tpuarts/log       0.001] Start
Layer 0 [19:C.tpuarts/TPU_ser   0.001] Opened /dev/ttyAMA0 with baud 9600
Layer 2 [19:C.tpuarts/TPU_ser   0.001] Opened
Layer 2 [19:C.tpuarts/TPU_ser   0.001] Buffer Setup on fd 4
Layer 0 [20:C.tpuarts/log       0.001] Started
Layer 8 [17:C.tpuarts/LowF      0.001] state: new > start
Layer 0 [17:C.tpuarts/LowF      0.001] SendReset 01
Layer 0 [20:C.tpuarts/log       0.001] Send(001): 01
Layer 4 [15:C.tpuarts/Conn      0.002] >up
Layer 4 [15:C.tpuarts/Conn      0.003] is >up
Layer 0 [20:C.tpuarts/log       0.008] Recv(001): 00
Layer 0 [17:C.tpuarts/LowF      0.008] unknown 00
Layer 0 [17:C.tpuarts/LowF      0.487] SendReset 01
Layer 0 [20:C.tpuarts/log       0.487] Send(001): 01
Layer 0 [20:C.tpuarts/log       0.493] Recv(001): 00
Layer 0 [17:C.tpuarts/LowF      0.493] unknown 00
Layer 0 [17:C.tpuarts/LowF      0.987] SendReset 01
Layer 0 [20:C.tpuarts/log       0.987] Send(001): 01
Layer 0 [20:C.tpuarts/log       0.993] Recv(001): 00
Layer 0 [17:C.tpuarts/LowF      0.993] unknown 00
Layer 8 [17:C.tpuarts/LowF      1.488] state: in_reset > error
Layer 0 [20:C.tpuarts/log       2.488] Stop

I've been told that the STKNX is fully compatible with TPUART and with NCN5120.
What do you think the problem can be? Have any of you interfaced KNXD with STKNX?

Thank you guys.

**Comment by smurfix** [comment]
You've been told wrong. This chip is a simple transceiver. knxd does not support it and in fact cannot support it without a real-time-capable microcontroller in between.

**Comment by irrabb** [comment]
Hi,

Thanks for answering. 

Why then this solution works: 
https://www.acmesystems.it/CM3-HOME_tp-bus

Are the TPUART and the NCN5120 different from the STKNX?

Thanks.

**Comment by smurfix** [comment]
> Are the TPUART and the NCN5120 different from the STKNX?

Yes they are different. A STKNX does not use the common serial protocol on its `Tx` and `Rx` pins, you therefore cannot connect it to the Pi's serial pins, and the idea that it can be used as a replacement for a TPUART or NCN5120 is Just Plain Wrong.

**Comment by irrabb** [comment]
Ok. 

Thank you very much.
So to clarify it: if I change the STKNX, for example, for the NCN5120, it should work without having to place any microprocessor in between right?

Thanks again!

**Comment by smurfix** [comment]
Sure. The NCN works, as does the TPUART2.

**Comment by irrabb** [comment]
Hi, 

Sorry to keep bothering you with this subject:

On Semi does not recommend anymore the NCN5120 for new designs. Have you tried, or do you know about anyone who has tried the NCN5121 or the 5130 or the 5110? Does KNXD support them as well?


Thanks.

**Comment by irrabb** [comment]
Hi,

Sorry to keep bothering you with this subject:

On Semi does not recommend anymore the NCN5120 for new designs. Have you tried, or do you know about anyone who has tried the NCN5121 or the 5130 or the 5110? Does KNXD support them as well?

Thanks.

**Comment by smurfix** [comment]
Never tested either. Get the data sheets and check what's different WRt talking to these chips; if the answer is "nothing" or "not too much" knxd will support the thing easily.
