### ISSUE TITLE
Configure stage errors out on FreeBSD

### ISSUE THREAD

**Issue by Foxi352** [knxd/knxd#397]
Hi !

I want to install KNXD in a FreeBSD 11.2 jail on FreeNAS.
I have search older issues and found that @mike-kfed did some work and got it running on FreeBSD 11.2 and Darwin.

I tried to reproduce this with current master and it hangs on the configure stage.

What i did:
```
env ASSUME_ALWAYS_YES=YES  pkg install gcc8 libtool automake
git clone https://github.com/knxd/knxd.git
cd knxd
./bootstrap.sh
./configure --disable-systemd --disable-usb
```
Error:

```
[....]
checking for build system preprocessor... cc -E
checking for build system executable suffix...
checking for compiler option -std=c++0x... yes
./configure: 18532: Syntax error: word unexpected (expecting ")")
```

Did i make a mistake, or is it currently not building on FreeBSD based platforms ? @mike-kfed maybe ? :-)

Thank you

Serge

**Comment by mike-kfed** [comment]
```bash
pkg install nano git clang-devel libtool automake autoconf
./configure --disable-systemd --disable-usb CPPFLAGS=-I/usr/local/include/ LDFLAGS=-L/usr/local/lib
gmake```

**Comment by mike-kfed** [comment]
gcc8 does not work, learned this the hard way, it builds fine with clang

**Comment by Foxi352** [comment]
Thanks for the hint. Does clang-devel exists ?

```
FreeBSD repository is up to date.
All repositories are up to date.
pkg: No packages available to install matching 'clang-devel' have been found in the repositories

```

**Comment by Foxi352** [comment]
Still `./configure --disable-systemd --disable-usb CPPFLAGS=-I/usr/local/include/ LDFLAGS=-L/usr/local/lib` yields:

```
[...]
checking build system compiler cc... yes
checking for build system preprocessor... cc -E
checking for build system executable suffix...
checking for compiler option -std=c++0x... yes
./configure: 18532: Syntax error: word unexpected (expecting ")")
```

**Comment by smurfix** [comment]
> ./configure: 18532: Syntax error: word unexpected (expecting ")")

So (a) did `bootstrap.sh` complain about anything (I suppose it did), and/or (b) what's on or around line 18532 of `./configure`?

**Comment by Foxi352** [comment]
No complaints:

```
root@Test:/usr/local/knxd # ./bootstrap.sh
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './config.guess'
libtoolize: copying file './config.sub'
libtoolize: copying file './install-sh'
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:31: installing './compile'
configure.ac:30: installing './missing'
src/backend/Makefile.am: installing './depcomp'
root@Test:/usr/local/knxd #

```
Line 18532 is the following according to vi:
`PKG_CHECK_MODULES(SYSTEMD, libsystemd-daemon)
`
here is the relevant block:

```
        if test "$old" = y ; then
        PKG_CHECK_MODULES(SYSTEMD, libsystemd-daemon)
        else
        PKG_CHECK_MODULES(SYSTEMD, libsystemd)
        fi
```

**Comment by smurfix** [comment]
>        PKG_CHECK_MODULES(SYSTEMD, libsystemd-daemon)

Well, there you are, that's a M4 macro that didn't get defined, so it's replicated in-place. Check your pkg-config installation.

**Comment by Foxi352** [comment]
Yes, thank you ! :-) Bear with me, i am not really into all that M4 thingy.

For the sake of completeness if someone finds this Issue later via search, here is what i did to compile and install knxd on a frechly installed FreeBSD 11.2:

```
pkg install libtool automake autoconf pkgconf argp_standalone cmake libev gmake
git clone https://github.com/knxd/knxd.git
cd knxd
./bootstrap.sh
./configure --disable-systemd --disable-usb CPPFLAGS=-I/usr/local/include/ LDFLAGS=-L/usr/local/lib
gmake
gmake install
```

I still have to create the service file in rc.d, the knxd.ini file e.t.c. but the binary is working:

```
$ knxd
Usage: knxd [-l?V] [--list] [--help] [--usage] [--version]
       knxd configfile [main_section]
Please consult /usr/share/doc/knxd/inifile.rst

```
