### ISSUE TITLE
Parity/Framing bug with TPUART and FTDI USB/UART

### ISSUE THREAD

**Issue by iomode** [knxd/knxd#403]
Hi,

I am using a custom hardware which is based on a TPUART2 chip and a FTDI FT230X usb<->uart converter.  
I set up knxd to work with the hardware but unfortunately it never came out of the reset state.

So I wrote a small python script which sends the reset command (0x01) and successfully received the reset ack (0x00 0x03).

After figuring this out I started debugging into knxd and recognized that the read callback is never called after sending the reset.  
I compared the termios settings of the python script and knxd using stty and recognized that one flag is additionally set by knxd -> "INPCK = Enable input parity checking.".  
Disabling it in knxd makes the communication working.  

Additionally, I hacked a Prolific PL2303 usb<->uart converter to the hardware and tried to use it with INPCK enabled/disabled, both variants are working.

Based on the termios documentation (https://ftp.gnu.org/old-gnu/Manuals/glibc-2.2.3/html_chapter/libc_17.html#SEC361)
the PARENB flag enables the parity generation and detection by hardware while INPCK controls how the parity input error is handled.
However, I was not able to track down the INPCK/parity handling in glibc or the kernel driver.

According to the TPUART2 datasheet (as well as the TPUART1) the reset behavior is to pull down the TX for 5.4ms before sending the reset ack (0x03).
By the definition of the UART protocol (which is idle high) this reset is interpreted as a framing/parity error.
I also decoded it using a logic analyzer which shows the framing error.

As both, the PL2303 and the FT230X (with INPCK disabled), decode the framing error as 0x0 
I would recommend to disable the INPCK on startup and enable it after the reset is acknowledged. 
I think even with parity check disabled the only way to interpret a continuous low signal on TX is 0x0.
This would allow knxd to work with all currently used usb<->uart converters as well as the FT230X series (more may be affected...).

Another solution would be toggling the parity check if the reset fails.

Kernel version: 4.19.42
knxd version: 0.14.29-5
libc version: (Debian GLIBC 2.24-11+deb9u4) 2.24

**Comment by dallmair** [comment]
This has been fixed in #534 and the fix was released in version 0.14.57, therefore it's time to close this issue.
