### ISSUE TITLE
Start KNXD with deamon

### ISSUE THREAD

**Issue by mika-nt28** [knxd/knxd#404]
I want started knxd with this parmeter list

`knxd --daemon=/var/log/knx.log --pid-file=/var/run/knx.pid -t1023 --eibaddr=0.0.1 --client-addrs=0.0.1:2 --Name=JeedomKnx -D -T -S --listen-tcp=6720 ipt:192.168.0.101:3671`

But I have this error

`JeedomKnx: Layer 4 [ 1:main        0.000] initialized
JeedomKnx: Layer 4 [ 1:main        0.000] setting up
JeedomKnx: Layer 3 [ 4:server/Server     0.000] registerLink: 4:server
JeedomKnx: Layer 3 [ 7:A.tcp/inet        0.000] registerLink: 7:A.tcp
JeedomKnx: Layer 3 [10:B.ipt/Conn        0.000] registerLink: 10:B.ipt
JeedomKnx: F00000104: [ 1:main] Section 'main': unrecognized argument 'background = true'
JeedomKnx: F00000104: [ 1:main] Section 'main': unrecognized argument 'logfile = /var/log/knx.log'
JeedomKnx: F00000104: [ 1:main] Section 'main': unrecognized argument 'pidfile = /var/run/knx.pid'
JeedomKnx: Layer 4 [ 1:main              0.000] setup BROKEN
JeedomKnx: F00000109: [ 1:main] Error setting up the KNX router.`

**Comment by smurfix** [comment]
I assume you're using systemd. There are no --daemon or --pid-file arguments with systemd because they make nosense there.

**Comment by mika-nt28** [comment]
Hello,

No, I desable systemd knxd service.
I want to let my home automation app run the launch options

**Comment by tru7** [comment]
@mika-nt28 strange, your command works fine on my ubuntu system. You should improve your -E argument as you only give 1 address for clients this way. Take something like 0.0.2:10. That will make no difference though.
What is your operating system? Does it use glibc or argp_standalone?

**Comment by mika-nt28** [comment]
@tru7 
I remake installation KNXd and change my software domotique.
Now I run KNXd with this cmd
`knxd -t1023 --eibaddr=0.1.0 --client-addrs=0.1.1:8 --Name=Jeedom -D  -T  -S --listen-tcp=6720 ip:192.168.0.101:3671`
But if add --daemon=/var/log/knx.log  or --pid-file=/var/run/knx.pid parameter I obtain the same message.

My operating systeme are debian 9 with docker container
For the KNXd installation I install this dependancy
`sudo apt-get -qy install pkg-config
sudo apt-get -qy install build-essential 
sudo apt-get -qy install libev-dev
sudo apt-get -qy install git-core
sudo apt-get -qy install dpkg-buildpackage
sudo apt-get -qy install cdb
sudo apt-get -qy install git-core
sudo apt-get -qy install debhelper
sudo apt-get -qy install autoconf
sudo apt-get -qy install automake
sudo apt-get -qy install libtool
sudo apt-get -qy install libusb-1.0-0-dev
sudo apt-get -qy install libsystemd-daemon-dev
sudo apt-get -qy install libsystemd-dev
sudo apt-get -qy install dh-systemd
sudo apt-get -qy install cmake`

**Comment by tru7** [comment]
"ip:192.168.0.101:3671" cannot work. If you connect your knxd to a KNX interface you need the ipt driver. Please also add a -b for it, you cannot ommit the port. So use "-b ipt:192.168.0.101" for a tunnel connection.

**Comment by mika-nt28** [comment]
Yes with -b the demon is correctly start
