### ISSUE TITLE
knxd complains about missing -E option

### ISSUE THREAD

**Issue by abc2006** [knxd/knxd#408]
Hi, 
i set up a knxd on my server. It's needed to connect my automation-Software (FHEM) to the KNX-Router (Weinzierl KNX Line Master 760).
On my old server it's running with 
DAEMON_ARGS="-e 1.1.2 -c -DTS -i -u -t 1023 ipt:192.168.0.43"
As described in the new config file /etc/knxd.conf, i removed the -i and -u options and tried to start.
I also added the -b option in front of the ipt-part.
KNXD_OPTS="-e 1.1.2 -c -DTS -t1023 -b ipt:192.168.0.43"
After this, knxd complained 

Jul 29 20:33:14 newfhem systemd[1]: Starting KNX Daemon...
Jul 29 20:33:14 newfhem knxd[28339]: E00000051: [ 1:main] You need a client-addrs=X.Y.Z:N option in your main section.
Jul 29 20:33:14 newfhem knxd[28339]: F00000109: [ 1:main] Error setting up the KNX router.
Jul 29 20:33:14 newfhem systemd[1]: knxd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 29 20:33:14 newfhem systemd[1]: knxd.service: Failed with result 'exit-code'.
Jul 29 20:33:14 newfhem systemd[1]: Failed to start KNX Daemon.
Jul 29 20:33:25 newfhem systemd[1]: knxd.service: Service hold-off time over, scheduling restart.
Jul 29 20:33:25 newfhem systemd[1]: knxd.service: Scheduled restart job, restart counter is at 8820.
Jul 29 20:33:25 newfhem systemd[1]: Stopped KNX Daemon.

Finally, i added the -E option, and it works:
KNXD_OPTS="-e 1.1.2 -c -DTS -E 0.0.2:2 -f9 -t1023 -b ipt:192.168.0.43"

Unfortunately, i didn't get it from the help, didn't find the man-page and also found no Information anywhere via google with the error message.
Hopefully one can explain me, why i need to tell knxd addresses to assign, if i actually don't want knxd to do.

Maybe it's the wrong approach to use knxd; also in this case i was thankful for a hint.

Cheers, 
Stephan

**Comment by smurfix** [comment]
You have clients which use knxd. FHEM for example. Each device (and each client) needs a distinct physical address.

Yes it's documented. It's mentioned in the README. New since 0.14 which probably is why you couldn't find it.

Pull requests to improve the documentation welcome.
