### ISSUE TITLE
Multiple knxd instances on a single machine

### ISSUE THREAD

**Issue by gabrielruiu** [knxd/knxd#409]
Not familiar with the system dependencies of knxd, but is it possible to have multiple running `knxd` instances on the same machine? 

Each would have different configurations, connected to different KNX gateways.

**Comment by gabrielruiu** [comment]
First impression is that this seems possible. Running, as mentioned above, multiple instances of the `knxd` binary seems to work.

So running 
`sudo /usr/bin/knxd -e 1.0.1 -E 1.0.200:10 -u /tmp/eib -i -b ipt:<some-ip-gateway>`

doesn't conflict with the other running instance:
`sudo /usr/bin/knxd -e 1.0.1 -E 1.0.200:10 -u /tmp/eib2 -i 6721 -b ipt:<some-other-ip-gateway>`

So they don't conflict as long as the `-u` and `-i` arguments don't have the same values.

**Comment by gabrielruiu** [comment]
Please let me know if I am missing some important aspect that might still lead to conflicts later on.

**Comment by tru7** [comment]
You should only open issues for errors, and discuss usage of knxd and interfaces in the forum on https://groups.google.com/forum/#!forum/knxd
BTW: I don't think two independent knxd instances will work correctly this way. I'm happy to discuss that in the forum.

**Comment by mfechner** [comment]
> https://groups.google.com/forum/#!forum/knxd

If I try to access this, I get an error message that the group does not exist?

**Comment by tru7** [comment]
thank you for reporting. It looks like they recently changed the settings to make it invisible to non-members. @smurfix : can you please verify this? Would it make sense to first subscribe to a group before getting it visible - how could you know about then? Was it ever the intention to keep this group invisible? Please correct if I did a mistake.

**Comment by smurfix** [comment]
Umm, the settings for the group say that it's public. I have no idea why it's invisible to you. The public link is supposed to be

https://groups.google.com/d/forum/knxd

Does that work?

**Comment by tru7** [comment]
@smurfix yes, I changed it and wanted you to verify. Sorry I was not clear enough
