### ISSUE TITLE
Trouble with Berker USB - unreliable

### ISSUE THREAD

**Issue by Robert46** [knxd/knxd#411]
I installed KNXD on a Raspberry PI3 and began writing a small testprogramm to get used to it.
It basically opens a vBusmonitor on one connection (over local socket) and tries to switch a light from time to time.
Sometimes it works for a while but sometimes, immediately after sending, the busmonitor breaks and returns only -1 as length.
Now I noticed that this also happens if I leave one knxtool-busmon running and doing a "knxtool off ..." in another shell.
I also get the "send while waiting" in my knxd-logs.
Where could be the problem?
If interested, here is my code:

```
#define PATH "/run/knx"
int main()
{
int	res,res_openT,len,i;
uint8_t	buf[20];

con=EIBSocketLocal(PATH);
printf("con: %lx\n",(long)con);
con2=EIBSocketLocal(PATH);
printf("con2: %lx\n",(long)con2);
res_openT=EIBOpen_GroupSocket(con2,1);
printf("OpenT_Group: %d\n",res_openT);
if(con)
	{
	res=EIBOpenVBusmonitor(con);
	printf("OpenVBusmonitor:%d\n",res);
	i=1;
	while(i<25) {
		len=EIBGetBusmonitorPacket(con,sizeof(buf),buf);
		printf("i:%d len:%d\n",i,len);
		if ((res_openT==0) && (i%5==0)) {
			buf[0]=0;
			buf[1]=0x80;
			len = EIBSendGroup (con2, dot3toi("0.2.0"), 2, buf);
			printf("APDU %d bytes\n",len);
		}
		i++;
	}
	printf("Closing...\n");
	EIBClose(con);
	EIBClose(con2);
	}
}
```
My options:
`KNXD_OPTS="-e 0.0.1 -E 0.0.2:8 -b usb:"`
Btw, what's the difference between /run/knx and /tmp/eib?

**Comment by palhaland** [comment]
have you tried with the single and queue filter? https://github.com/knxd/knxd/blob/master/doc/inifile.rst#single

I have the berker as well, and those fixed the issues for me at least. (Symptom not getting responses from the bus when transmitting multiple packets).

**Comment by Robert46** [comment]
Palhaland, I didn't try but unfortunately I also cannot do this in the near future. But I'll keep it in mind, thank you!
My symptoms are different, I think. If I have a knxtool vbusmonitor1 running in one shell and send a commant, the busmonitor stops with "Read failed: Connection reset by peer".
I've learned that usb is broken by design, so I'm thinking about an IP-Interface. Not sure if the Weinzierl 732 secure would be the right thing...

**Comment by smurfix** [comment]
Yes, USB is broken by design. No, this bug is really a `knxd` bug, this worked in 0.12 – but nobody has managed to fix it yet and it doesn't show up in my test environment.

**Comment by smurfix** [comment]
`/run/knx` is the new and sensible path to knxd's contol socket. `/tmp/eib` is the old path.
Storing sockets in /tmp does not make sense. Your system might clean up anything in /tmp that's older than 7 days or whatever, oops you can't talk to knxd any more.
In contrast, /run is and never cleaned up explicitly, It's on a RAM disk, thus there can't be a stale socket lying around after reboot.

**Comment by ScanxTaz** [comment]
Hey Smurfix, 

looking at your last comment, does that mean that chaning from /tmp/eib to /run/knx would solve this issue ?

If I remember well, I've managed to change the timeout in the driver before compiling, but it introduces a very loooooon delay for some operation (while the KNXD process does not stop anymore now).

So, I'm searching to recover from this, either by upgrading (if it works), either by buying an IP gateway...

Thanks.

**Comment by ScanxTaz** [comment]
Thanks for your amazing job Smurfix ! I don't know if there's an official container on docker for KNXD, I created one, works like a charm. Thanks thanks thanks...
