### ISSUE TITLE
Connexion crash with ABB 6136/APP-500 Busch-ControlTouch

### ISSUE THREAD

**Issue by mika-nt28** [knxd/knxd#441]
I manualy start KNXD with this commande
> knxd --daemon=/var/log/knx.log --pid-file=/var/run/knx.pid -t1023 --eibaddr=1.1.200 --client-addrs=1.1.201:1.1.211 --Name=Jeedom_LR -D -T -S --listen-tcp=6720 -b ipt:192.168.100.28:3671

5minute after run the connexion crash

do you have an idea where is the probleme

**Comment by tru7** [comment]
use --client-addrs=1.1.201:11 and try again. Use https://groups.google.com/forum/#!forum/knxd to discuss your setup and debug log.

**Comment by mika-nt28** [comment]
Hi

it's an error to repporting cmd
This errors is allways present
