### ISSUE TITLE
ETS5 compatibility 

### ISSUE THREAD

**Issue by stelar68480** [knxd/knxd#442]
Dear all

I can't open an line coupler plugin (TR131) on ETS5 Lite over knxd. It work on ETS4 demo.
The ETS bus is connected to knxd (0.0.0) phys Addr: 0.0.8 
I can assign a group adress (1.5.0) to Media coupler.

Here the Group Monitor:
By opening the Plugin on ETS4 that work:
**| Time | Service | Flags | Prio | Source Address | Source Name | Destination Address | Destination Name | Rout | Type | DPT | Info**
12 | 19.10.2019 09:23:02.519 | from bus |   | System | 0.0.6 | - | 0/0/0 | Broadcast | 5 | PhysAddrSnoRead |   | 00 09 40 29 D7 09
13 | 19.10.2019 09:23:02.617 | from bus |   | System | 1.5.0 | Coupleur de média | 0/0/0 | Broadcast | 5 | PhysAddrSnoResponse |   | 00 09 40 29 D7 09 00 00 00 00

By opening the Plugin on ETS5:
**| Time | Service | Flags | Prio | Source Address | Source Name | Destination Address | Destination Name | Rout | Type | DPT | Info**
2 | 19.10.2019 09:22:12.630 | to bus |   | System | 0.0.0 | - | 1.5.0 | Coupleur de média | 6 | DeviceDescriptorRead |   | DescriptorType=0
3 | 19.10.2019 09:22:12.690 | from bus |   | System | 1.5.0 | Coupleur de média | 0.0.4 | - | 5 | DeviceDescriptorResponse |   | DescriptorType=0, DescriptorData=07 01
4 | 19.10.2019 09:22:13.832 | to bus |   | System | 0.0.0 | - | 1.5.0 | Coupleur de média | 6 | PropertyValueWrite |   | ObjectIndex=3, PropertyId=244, Count=1, StartIndex=1, Data=00 00 00 00 00 00 00 00 00 00
5 | 19.10.2019 09:22:13.958 | from bus |   | System | 1.5.0 | Coupleur de média | 0.0.4 | - | 5 | PropertyValueResponse |   | ObjectIndex=3, PropertyId=244, Count=1, StartIndex=1, Data=00 00 00 00 00 00 00 00 00 00
6 | 19.10.2019 09:22:14.036 | to bus |   | System | 0.0.0 | - | 1.5.0 | Coupleur de média | 6 | PropertyValueRead |   | ObjectIndex=3, PropertyId=244, Count=1, StartIndex=1
7 | 19.10.2019 09:22:14.132 | from bus |   | System | 1.5.0 | Coupleur de média | 0.0.4 | - | 5 | PropertyValueResponse |   | ObjectIndex=3, PropertyId=244, Count=1, StartIndex=1, Data=00 01 03 00 00 00 00 00 00 00
8 | 19.10.2019 09:22:14.208 | to bus |   | System | 0.0.0 | - | 1.5.0 | Coupleur de média | 6 | PropertyValueRead |   | ObjectIndex=0, PropertyId=11, Count=1, StartIndex=1
9 | 19.10.2019 09:22:14.295 | from bus |   | System | 1.5.0 | Coupleur de média | 0.0.4 | - | 5 | PropertyValueResponse |   | ObjectIndex=0, PropertyId=11, Count=1, StartIndex=1, Data=00 09 40 29 D7 09

Any idea how to get a Hager TR131 working with KNXD?

Thanks a lot
regards

**Comment by smurfix** [comment]
Your 1.5.0 is not a "group address". In any case this is not the correct place for debugging ETS plugins; the fact that ETS has deprecated the whole plugin idea for years unfortunately doesn't help.
