### ISSUE TITLE
Redirect command line output to sql server

### ISSUE THREAD

**Issue by K4yl** [knxd/knxd#444]
Dear all, 

Thanks for your great work. 

Is there any way to store the command line outputs of knxtools to a sql server? 

E.g. 
```
$ knxtool groupsocketlisten ip:localhost
Write from 1.1.46 to 2/2/31: 00
Write from 1.1.22 to 2/1/103: 00
Write from 1.1.10 to 4/1/8: 0C 1A
```
This output should be stored in a SQL server including a timestamp, e.g. 
`Insert Into knx (timestamp, message) values ($time, [Command Output])`

Any ideas? 

Thanks,
K4yl

**Comment by smurfix** [comment]
On 05.11.19 23:23, K4yl wrote:
>
> Any ideas?
>
I'm doing this with pyknyx.

-- 
-- Matthias Urlichs

**Comment by mike-kfed** [comment]
If you're using postgresql you may be interested in my datatype https://github.com/mike-kfed/pgknx allows for compact binary storage and only valid values. I too am using python3 to groupsocketlisten on knxd and store it in DB.

**Comment by K4yl** [comment]
Thanks for your ideas. 

I am using MariaDB. Not sure how I can incorporate python3 for this purpose. I will have a look at pyknyx soon. 

For now, I helped me out with the following command line: 
`$ knxtool groupsocketlisten ip:localhost | while IFS= read -r line; do mysql -u knxDB -pXXXX knx -e "INSERT INTO knx ( message ) VALUES ( "\"" $line "\""  )"; done`
