### ISSUE TITLE
knxd problem ...

### ISSUE THREAD

**Issue by ErwinGuilliams** [knxd/knxd#445]
Hey,

I use Raspberry Pi 4 and trying to config knxd.conf

KNXD_OPTS="-e 0.0.1 -E 0.0.2:8 -u /tmp/eib -b usb:"

That gives me the following error :

journalctl -u knxd

What could be the problem?

-- Logs begin at Tue 2019-11-05 18:50:47 GMT, end at Wed 2019-11-06 07:00:18 GMT. --
Nov 05 18:50:51 raspberrypi systemd[1]: Starting KNX Daemon...
Nov 05 18:50:51 raspberrypi knxd[454]: libusb: error [_get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/001/005: Permission denied
Nov 05 18:50:51 raspberrypi knxd[454]: libusb: error [_get_usbfs_fd] libusb requires write access to USB device nodes.
Nov 05 18:50:51 raspberrypi knxd[454]: E00000064: [13:B.usb] B.usb: setup B.usb: failed
Nov 05 18:50:51 raspberrypi knxd[454]: F00000109: [ 1:main] Error setting up the KNX router.
Nov 05 18:50:51 raspberrypi systemd[1]: knxd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 05 18:50:51 raspberrypi systemd[1]: knxd.service: Failed with result 'exit-code'.
Nov 05 18:50:51 raspberrypi systemd[1]: Failed to start KNX Daemon.
Nov 05 18:51:02 raspberrypi systemd[1]: knxd.service: Service RestartSec=10s expired, scheduling restart.
Nov 05 18:51:02 raspberrypi systemd[1]: knxd.service: Scheduled restart job, restart counter is at 1.
Nov 05 18:51:02 raspberrypi systemd[1]: Stopped KNX Daemon.
Nov 05 18:51:02 raspberrypi systemd[1]: Starting KNX Daemon...
Nov 05 18:51:02 raspberrypi knxd[935]: libusb: error [_get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/001/005: Permission denied
Nov 05 18:51:02 raspberrypi knxd[935]: libusb: error [_get_usbfs_fd] libusb requires write access to USB device nodes.
Nov 05 18:51:02 raspberrypi knxd[935]: E00000064: [13:B.usb] B.usb: setup B.usb: failed
Nov 05 18:51:02 raspberrypi knxd[935]: F00000109: [ 1:main] Error setting up the KNX router.
Nov 05 18:51:02 raspberrypi systemd[1]: knxd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 05 18:51:02 raspberrypi systemd[1]: knxd.service: Failed with result 'exit-code'.
Nov 05 18:51:02 raspberrypi systemd[1]: Failed to start KNX Daemon.
Nov 05 18:51:12 raspberrypi systemd[1]: knxd.service: Service RestartSec=10s expired, scheduling restart.
Nov 05 18:51:12 raspberrypi systemd[1]: knxd.service: Scheduled restart job, restart counter is at 2.
Nov 05 18:51:12 raspberrypi systemd[1]: Stopped KNX Daemon.
Nov 05 18:51:12 raspberrypi systemd[1]: Starting KNX Daemon...
Nov 05 18:51:12 raspberrypi knxd[996]: libusb: error [_get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/001/005: Permission denied
Nov 05 18:51:12 raspberrypi knxd[996]: libusb: error [_get_usbfs_fd] libusb requires write access to USB device nodes.
Nov 05 18:51:12 raspberrypi knxd[996]: E00000064: [13:B.usb] B.usb: setup B.usb: failed
Nov 05 18:51:12 raspberrypi knxd[996]: F00000109: [ 1:main] Error setting up the KNX router.
Nov 05 18:51:12 raspberrypi systemd[1]: knxd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 05 18:51:12 raspberrypi systemd[1]: knxd.service: Failed with result 'exit-code'.
Nov 05 18:51:12 raspberrypi systemd[1]: Failed to start KNX Daemon.
Nov 05 18:51:53 raspberrypi systemd[1]: knxd.service: Service RestartSec=10s expired, scheduling restart.
Nov 05 18:51:53 raspberrypi systemd[1]: knxd.service: Scheduled restart job, restart counter is at 3.
Nov 05 18:51:53 raspberrypi systemd[1]: Stopped KNX Daemon.
Nov 05 18:51:53 raspberrypi systemd[1]: Starting KNX Daemon...
Nov 05 18:51:53 raspberrypi knxd[1021]: libusb: error [_get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/001/005: Permission denied
Nov 05 18:51:53 raspberrypi knxd[1021]: libusb: error [_get_usbfs_fd] libusb requires write access to USB device nodes.
Nov 05 18:51:53 raspberrypi knxd[1021]: E00000064: [13:B.usb] B.usb: setup B.usb: failed
Nov 05 18:51:53 raspberrypi knxd[1021]: F00000109: [ 1:main] Error setting up the KNX router.
Nov 05 18:51:53 raspberrypi systemd[1]: knxd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 05 18:51:53 raspberrypi systemd[1]: knxd.service: Failed with result 'exit-code'.
Nov 05 18:51:53 raspberrypi systemd[1]: Failed to start KNX Daemon.
Nov 05 18:52:03 raspberrypi systemd[1]: knxd.service: Service RestartSec=10s expired, scheduling restart.
Nov 05 18:52:03 raspberrypi systemd[1]: knxd.service: Scheduled restart job, restart counter is at 4.
Nov 05 18:52:03 raspberrypi systemd[1]: Stopped KNX Daemon.
Nov 05 18:52:03 raspberrypi systemd[1]: Starting KNX Daemon...
Nov 05 18:52:03 raspberrypi knxd[1028]: libusb: error [_get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/001/005: Permission denied
Nov 05 18:52:03 raspberrypi knxd[1028]: libusb: error [_get_usbfs_fd] libusb requires write access to USB device nodes.
Nov 05 18:52:03 raspberrypi knxd[1028]: E00000064: [13:B.usb] B.usb: setup B.usb: failed
Nov 05 18:52:03 raspberrypi knxd[1028]: F00000109: [ 1:main] Error setting up the KNX router.
Nov 05 18:52:03 raspberrypi systemd[1]: knxd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 05 18:52:03 raspberrypi systemd[1]: knxd.service: Failed with result 'exit-code'.
Nov 05 18:52:03 raspberrypi systemd[1]: Failed to start KNX Daemon.
Nov 05 18:52:13 raspberrypi systemd[1]: knxd.service: Service RestartSec=10s expired, scheduling restart.
Nov 05 18:52:13 raspberrypi systemd[1]: knxd.service: Scheduled restart job, restart counter is at 5.
Nov 05 18:52:13 raspberrypi systemd[1]: Stopped KNX Daemon.
Nov 05 18:52:13 raspberrypi systemd[1]: Starting KNX Daemon...
Nov 05 18:52:13 raspberrypi knxd[1033]: libusb: error [_get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/001/005: Permission denied
Nov 05 18:52:13 raspberrypi knxd[1033]: libusb: error [_get_usbfs_fd] libusb requires write access to USB device nodes.
Nov 05 18:52:13 raspberrypi knxd[1033]: E00000064: [13:B.usb] B.usb: setup B.usb: failed

**Comment by mike-kfed** [comment]
says right at the start `libusb couldn't open USB device /dev/bus/usb/001/005: Permission denied` so you have to make sure the user that runs knxd is member of the group that is allowed to access USB devices (or any other solution that gives permission to the device file).

**Comment by ErwinGuilliams** [comment]
Hey, 

Thanx. 

But I don't know how to do that on a standard Raspberry Pi 4 with Debian Buster installation... 

Suggestions? 

Greetz, 

Erwin 

Van: "Michael Kefeder" <notifications@github.com> 
Aan: "knxd/knxd" <knxd@noreply.github.com> 
Cc: "erwin" <erwin.guilliams@pandora.be>, "Author" <author@noreply.github.com> 
Verzonden: Woensdag 6 november 2019 12:49:06 
Onderwerp: Re: [knxd/knxd] knxd problem ... (#445) 



says right at the start libusb couldn't open USB device /dev/bus/usb/001/005: Permission denied so you have to make sure the user that runs knxd is member of the group that is allowed to access USB devices (or any other solution that gives permission to the device file).

**Comment by mike-kfed** [comment]
google for "linux introduction permissions" or ask your local linux user group to understand what needs to be done to give knxd access to the needed devices/files. This is the issue tracker for knxd not a linux help forum.

**Comment by smurfix** [comment]
knxd comes with a bunch of udev rules that set the appropriate permissions. How to set and extend that list is (a) documented (b) reasonably easy (c) not a knxd problem, unless the ruleset is installed wrongly, in which case please submit a new issue with appropriate evidence. ;-)
