### ISSUE TITLE
convert KNX IP Interface to multicast IP interface with KNXD

### ISSUE THREAD

**Issue by fluppie** [knxd/knxd#446]
Can I use knxd to "convert" my current MDT IP Interface to a multicast IP Interface. I have a Raspberry Pi 3B available for this task. So the RPI3 would make a connection to the MDT IP Interface and then broadcast all bus/group messages over Multicast IP.
Or is this not the right software to do this?

**Comment by smurfix** [comment]
No problem. But please ask about details in the knxd group; this is not an "issue".
