### ISSUE TITLE
missing dpt 251.600 RGBW

### ISSUE THREAD

**Issue by pakka11** [knxd/knxd#448]
missing dpt 251.600 (6byte).
the 4 first bytes for RGBW, last 2 bytes as check sum (00 0F to write all 4 color-bytes).

**Comment by smurfix** [comment]
knxd is concerned with raw KNX data and doesn't know, or care, care which DPT these data might fall under.
I have no idea what your problem is but suspect that you're confusing knxd with whichever software you're using to talk to it.
