### ISSUE TITLE
Routingcounter = 7 when using tpuart

### ISSUE THREAD

**Issue by mode2k** [knxd/knxd#45]
Hello,

i found a possible bug in eibd 0.0.5 described in knx uf:
http://knx-user-forum.de/knx-eib-forum/41082-routingzaehler-7-beim-eibd.html
Makki asked me to post this issue here, so that we can fix it in knxd.

For testing i used eibd with tpuart and a MDT USB bus interface.
On my ubuntu system i used groupswrite to write data to the knx bus over eibd:
    groupswrite ip:localhost 0/0/222 1

eibd is started with these parameters:
    eibd --eibaddr=1.0.254 --GroupCache --Server --Discovery --listen-tcp --Tunnelling --Routing --tpuarts-disch-reset --tpuarts-ack-all-group -t 5 --daemon=/var/log/eibd.log --listen-local --pid-file=/var/run/eibd.pid tpuarts:/dev/ttyUSB_KNX

In the ETS busmonitor the telegrams are shown with these routingcounters:
eibd direct: Not working!
eibd routing: routingcounter 6
MDT USB If: routingcounter 7

In the ETS groupmonitor the telegrams are shown with these routingcounters:
eibd direct: routingcounter 6
eibd routing: routingcounter 6
MDT USB If: routingcounter 7

Why is eibd sending telegramms with routingcounter 7 to the bus, but showing them in ets busmonitor using eibd as interface with routingcounter = 6? Without a third party interface (MDT USB interface in my case) its not possible to discover this behaviour.
Telegramms send by eibd (groupswrite, smarthome.py etc) have routingcounter = 7. But telegramms send by ETS groupmonitor over eibd have a correct routingcounter = 5.

Why i began checking this issue? Telegramms with routingcounter 7 are routed over every linecoupler, even if they are not listed in the filter table. 

Best regards

Mode

**Comment by Makki1** [comment]
I second this to be a bug.

**Comment by smurfix** [comment]
Routing counter 7 is supposed to not be decremented. That's specified in the KNX specs. However I happen to really dislike that "feature" as it serves no useful purpose and ensures that any bus which is improperly connected gets flooded. 
Current knxd happily ignores this and sends the packets on with counter 6.
Still TODO: fix groupswrite et al. to set the counter to 6, not 7. Would anybody care to do that?

**Comment by smurfix** [comment]
The secondary use of routing counter =7 seems to be to specifically circumvent routing restrictions so that a packet will get forwarded everywhere. That's also not implemented at the moment. At minimum this should be controllable by an option.

**Comment by smurfix** [comment]
Fixed in 2965ab2; controlled by a flag that is normally off.
TODO: eibtool sends packets with hop count 7. This is unacceptable.

**Comment by smurfix** [comment]
If somebody could take the time to find the place where that value is set, I'd be happy …

**Comment by mode2k** [comment]
Can confirm that knxd is now sending with hop count 6. linecouplers are happy with this!

**Comment by Makki1** [comment]
Sorry, I was off a little..
So can we tag that as resolved in knxd?
And still be broken in knxtool? (which is just a multi-call binary for examples/*)
Or should I try/verify again..

**Comment by smurfix** [comment]
knxtool does set that value somewhere. I'd be happier if somebody could fix that too.

**Comment by Makki1** [comment]
ok, I'll have a look (because knxtool is just a compressed [useful!] tool but than it might be present in other clients also..)

**Comment by dallmair** [comment]
Found the culprit :)

With this change, not a single packet with hopcount=7 was sent anymore by knxtool in my tests (knxtool doesn't have a feature to broadcast packets, as far as I could see).

Thinking about the consequences, I have one question/proposal: When this change is merged, wouldn't it make sense to remove the --allow-forced-broadcasts option or have an inverted version of said switch (e.g. --stop-broadcasts, --prevent-broadcasts, --break-broadcasts, --break-routing-loops)? In general, I think it's best to follow the specs by default and provide switches to enable non-compliant behavior. And with this PR we're indeed spec-compliant regarding the routing counter if and only if --allow-forced-broadcasts is set, aren't we?

**Comment by smurfix** [comment]
Thank you. Merged.

I'm of two minds whether to allow these broadcasts by default. The main reason I turned them off is that I haven't seen a good reason for them. The IP specs, on the other hand, have large prominent MUST declarations for decrementing the hop count (and dropping packets when that reaches zero).
