### ISSUE TITLE
new release 0.14.26??

### ISSUE THREAD

**Issue by tru7** [knxd/knxd#455]
shoudn't the newest release be named 0.14.31

**Comment by tru7** [comment]
Well, would you mind name it "0.14.31" instead of "v0.14.31". this way automatic repo download with <name>-<version> is broken.

**Comment by smurfix** [comment]
Bah. Sorry about that.

**Comment by smurfix** [comment]
Umm, actually, I take that back, 0.14.29 was the one release tag that didn't have a 'v' in front, besides the ancient 0.0.5.1 tag.
I deleted the 0.14.29 tag.

**Comment by tru7** [comment]
I and some others are not happy with that. After we finally had convinced you to use a common numbering scheme with 0.14.29 you now switch back. There are some tools and macros around which automatically check und download new upstream versions. And they usually use <name>-<version> syntax to search for new releases. And you name knxd knxd-0.14.31 and not knxd-v0.14.31, right? Please consider again.

**Comment by smurfix** [comment]
Well, that was not "convincing" but a mistake on my part. But, OK, fair enough, I'll revert that and switch to a numeric prefix.

**Comment by tru7** [comment]
thank you, that's very much appreciated
