### ISSUE TITLE
knxd.service - KNX Daemon [Error]

### ISSUE THREAD

**Issue by Lerox1** [knxd/knxd#461]
Folgender Fehler wird andgezegt sobald ich den status von knxd.service überprüfen will.

root@smarthome-VirtualBox:~#  systemctl status knxd.service
● knxd.service - KNX Daemon
   Loaded: loaded (/lib/systemd/system/knxd.service; enabled; vendor preset: ena
   Active: activating (auto-restart) (Result: exit-code) since Fr 2020-03-06 13:
  Process: 2292 ExecStart=/usr/bin/knxd $KNXD_OPTS (code=exited, status=2)
 Main PID: 2292 (code=exited, status=2)

Mär 06 13:54:33 smarthome-VirtualBox systemd[1]: Failed to start KNX Daemon.
Mär 06 13:54:33 smarthome-VirtualBox systemd[1]: knxd.service: Unit entered fail
Mär 06 13:54:33 smarthome-VirtualBox systemd[1]: knxd.service: Failed with resul

Finde keine Information und hilfen im Internet und hoffe das hier jemand weiter weiß und mir helfen kann

**Comment by smurfix** [comment]
(a) bitte verwende für solche Fragen das Forum. (https://knx-user-forum.de)
(b) bitte verwende `-l` damit systemctl deine Ausgabe nicht abschneidet.
(c) bitte verwendet `journalctl -u knxd -n100`, weil die letzten drei Zeilen etwas wenig sind.
(d) bitte poste deine Konfigdatei. So ist das wie wenn du den Mechaniker anrufst und ihm sagst, dass am Auto was kaputt ist und was du tun sollst.
