### ISSUE TITLE
is there plan to support STKNX? 

### ISSUE THREAD

**Issue by leoujz** [knxd/knxd#462]
We are currently using tpuart knx chipset, is there a plan to support STKNX? If no plan, can u tell me the probable steps need to do for converting the STKNX bit interface to TPUART INTERFACE. We do want to use STKNX because its low price. If the workload is acceptable, we do want to do this under knxd project.

**Comment by smurfix** [comment]
Do you have a patch? Or documentation? Can you lend me a sample device which I can test against?

**Comment by leoujz** [comment]
> Do you have a patch? Or documentation? Can you lend me a sample device which I can test against?

I don't have a patch, didn't write any code yet. I also don't have any documentation. Most of my knowledge comes from https://github.com/mistay/stknx/issues/2 and Q&A from STKNX dealer.

According to the repository, reading bytes from STKNX works, I'm not sure that writing bytes to STKNX is okay. And according to the author, bytes from STKNX is very close to TPUART data. 

I have a STKNX evaluation board, but I do not have any code yet, and I think it needs lots of work amount which I can not afford in this stage. If needed, I can mail the board to u.

**Comment by smurfix** [comment]
Meh. This is not very helpful: successfully receiving a KNX datagram requires writing an acknowledge packet which this code does not do. Also, that code does not handle bus collisions.

Unfortunately I do not have free time to write firmware to talk to KNX, thus I am closing this bug. Feel free to come back when there's something useable.
