### ISSUE TITLE
replacement for debian/changelog needed

### ISSUE THREAD

**Issue by tru7** [knxd/knxd#463]
@smurfix I guess you already realized that you need a replacement for generating the version number when you drop debian/changelog out of master branch. Thank you.

**Comment by dngferreira** [comment]
Try using release debian/0.14.34-1
The debian packaging was moved to another branch

**Comment by smurfix** [comment]
Sory, I haven't been able to update the various instructions yet. Please use the "deb" branch.

**Comment by tru7** [comment]
I'm fine with this for now. I think there should be a changelog in the master tree eventually.
