### ISSUE TITLE
unable to install knxd after fresh install raspbian buster (probably same issue as the other debian/changelog issue)

### ISSUE THREAD

**Issue by coolbox13** [knxd/knxd#464]
After setting up a fresh sd card with 2020-02-13-raspbian-buster-lite.img I installed domoticz, pihole and therafter tried to install knxd. 
The process stops with "dpkg-buildpackage: error: cannot open file debian/changelog: No such file or directory". 
I tried copying over all the binaries etc from the old sd-card but did not get it to work. Somehow I can't compile knxd on this new sd-card. It worked flawlessly on the old sd card. 
Any suggestions?
thanks in advance!

**Comment by dngferreira** [comment]
try using release debian/0.14.34-1 
The debian packaging was moved to another branch

**Comment by coolbox13** [comment]
Thanks! Works like a charm.
