### ISSUE TITLE
Can’t install knxd because of dpkg-buildpackage error

### ISSUE THREAD

**Issue by baumph** [knxd/knxd#468]
Installing knxd went all smooth till I had to run dpkg-buildpackage -b -uc in the knxd folder. I get the error :dpkg-buildpackage: error: cannot open file Debian/changelog: no such file or directory. 
I am installing it on a rasperrypi 4. 
any ideas on what’s causing it?

**Comment by tru7** [comment]
you cannot use master branch with dpkg-buildpackage for now, use "git checkout deb" first. It's mentioned in the readme.md
