### ISSUE TITLE
Only able to compile knxd deb branch on Alpine linux?

### ISSUE THREAD

**Issue by da-anda** [knxd/knxd#470]
I've been using knxd for some years now and managed to create a HomeAssistant add-on for it a couple years back by compiling the stable branch in an Alpine based image. For some reason after your split of the debian build env the compilation of my container seems to be broken, since it tries to resolve some debian based stuff even though I'm compiling on Alpine.
To make it even weirder, only the `deb` branch seems to compile for me now. I was looking for new build instructions, but didn't manage to find anything but the debian ones (which are still in all readme's and not just in the one of the debian branch, super confusing). Please bear with me, I'm not really a Linux guy and even less a command line crack, nor have I any idea of autotools, cmake or any other build system. Could you please point me to the correct compile instructions for non-debian linux or check if there are still some leftovers?

This is what my docker file looks like: https://github.com/da-anda/hass-io-addons/blob/master/knxd/Dockerfile
And this is the stdout when trying to compile the docker image along with knxd: https://paste.kodi.tv/orilucovut

Thanks.

**Comment by da-anda** [comment]
I suppose it could be related because the Makefile of the stable branch still contains stuff like `CONFIGURE_DEPENDENCIES=debian/changelog` and `configure: debian/changelog`?

**Comment by smurfix** [comment]
Well … I have no idea where your Makefile comes from, but the files in the knxd repository's current master branch contain no such thing. Did you get 0.14.36?

**Comment by da-anda** [comment]
@smurfix check the `stable` branch, the makefile there misses some fixes that had been done in master already, just as the `tools/version.sh` file. And `stable` is supposed to be the latest stable version, isn't it? Which is why I used this over the last couple years instead of master.

I also tried to compile master, but there I also get some error regarding some version related issues:
```
...
libtoolize: copying file 'm4/lt~obsolete.m4'
fatal: No names found, cannot describe anything.
configure.ac:30: error: AC_INIT should be called with package and version arguments
/usr/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:30: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
```
hope this helps

**Comment by smurfix** [comment]
How did you do that? Works here.

**Comment by da-anda** [comment]
see my Docker file for the entire compilation process and all the dependencies I install for it:

https://github.com/da-anda/hass-io-addons/blob/master/knxd/Dockerfile
but as said, this file worked just fine for the last 2 years+ building the `stable` branch. The Dockerfile has since today an arg for the branch to build and I passed the master branch to it for testing. Stdout showed that I was checked out correctly.

**Comment by da-anda** [comment]
ok, looks like master compiles fine now, but stable branch is still broken on non-debian systems. Will stick to tagged versions now which it seems are based on master these days and no longer on stable branch.
