### ISSUE TITLE
request to remove sys/cdefs.h from eibclient.h

### ISSUE THREAD

**Issue by tru7** [knxd/knxd#484]
@smurf I got a request to patch eibclient.h source code to remove sys/cdefs.h for openwrt by one of the maintainers. Please see this pull request: https://github.com/openwrt/packages/pull/13065. It looks like it is one of several similar requests for different projects. What do you think about it? Do you think this could be something to directly change upstream - in knxd?

**Comment by smurfix** [comment]
should be "fixed" by this patch. The real fix would be for the musl people to wake up and face the fact that the real world doesn't always conform to their idea of correctness, but whatever.

**Comment by tru7** [comment]
thank you
