### ISSUE TITLE
issue with DPT9.001

### ISSUE THREAD

**Issue by marcobastianon** [knxd/knxd#488]
hI all, i'm using "knxd 0.14.35:fc9ba78" with homebridge-knx and for 2 months I have problems with all the devices that use temperatures .. from ETS I can see all the temperature variations in my rooms, but if I set "knxtool vbusmonitor1 ip: localhost" on my raspberry, I don't see anything pass .. or better I see pass all the commands DPT1 and DPT5, but no DPT9 .. someone has already happened? am I doing something wrong?

i am using a raspberry pi 3b + and knxd branches deb

**Comment by smurfix** [comment]
knxd is agnostic about your DPTs. It transports data but intentionally has no idea what those data mean.

The most common reason this happens is that the physaddr of the sender(s) of these DPT9 messages is duplicated or within knxd's client address range.

**Comment by marcobastianon** [comment]
> knxd is agnostic about your DPTs. It transports data but intentionally has no idea what those data mean.
> 
> The most common reason this happens is that the physaddr of the sender(s) of these DPT9 messages is duplicated or within knxd's client address range.

OMG.. this solve my problem..
i was using :"KNXD_OPTS="-e 1.1.75 -E 1.1.76:100 -u /tmp/eib -b ipt:10.175.10.90""

and on 1.1.100, 101,102,103,104,105 i have my terostat..

now with: "KNXD_OPTS="-e 1.2.1 -E 1.2.2:100 -u /tmp/eib -b ipt:10.175.10.90" all telegram pass and i can see temperature..

before this edit my kitchen was at 0.0°C ( impossible :/ ).. now i can see 19°C

**Comment by smurfix** [comment]
Thought so …
