### ISSUE TITLE
Question: Which language standard of C++ is your target?

### ISSUE THREAD

**Issue by sichiwai** [knxd/knxd#490]
Hi,
maybe not the right channel or appraoch, but I don't see a better venue (at this point):
What is your target C++ standard?
Cxx11?
Cxx17?
or below?
If Cxx11 or above, using uniq_ptr and shared_ptr might be a good solution for tracking packets and messages (https://github.com/knxd/knxd/wiki/ToDo -> Packet Copying)... If there is interest, I might be ablte to contribute in that regard.

https://github.com/knxd/knxd/wiki/ToDo -> Packet Copying

Cheers

**Comment by smurfix** [comment]
Umm, in case you didn't notice knxd already uses `unique_ptr` as well as `shared_ptr`. You're welcome to improve the code but as a first step I'd recommend actually looking at it. :-P

Cxx17 should probably be OK these days.

In any case that Wiki page is seriously out of date. I probably should update it.

**Comment by sichiwai** [comment]
Actually reading it right now during lunch break. However, startet with the docu and there was no mentioning of a C++ standard version. 
Cheers. 

Sent from MailDroid

-----Original Message-----

**Comment by sichiwai** [comment]
Regardless, I think this issue can be closed ...
