### ISSUE TITLE
Not another issue, but a thank you!

### ISSUE THREAD

**Issue by spa49** [knxd/knxd#496]
Hi all,

so far, for what I do with knxd, it serves like a charm.
So a big thank you to the developers...

I have equipped a Raspberry B+ with a ROT board from Busware to realise TP connection
then installed Raspian Buster and knxd according to this [tutorial](https://michlstechblog.info/blog/raspberry-pi-eibknx-ip-gateway-and-router-with-knxd/).
The only difference is that I configured is the Network to be DHCP instead of static.
I ended up with knxd 0.14.39-4-g9929ed6 - the parameters I chose are as follows

`KNXD_OPTIONS="--Name=KNXgate --eibaddr=0.0.1 --client-addrs=0.0.2:8 -d -D -T -R -S -i --listen-local=/tmp/knx -b tpuarts:/dev/ttyAMA0$
`

First I tried programming via ETS 5.7.4 using IP tuneling  - all good no hiccups.
Even a reconstruction via the designated ETS app worked flawlessly.
Every operation was monitored via the ETS bus- and group monitor, the monitoring resulted in no findings of faulty or suspicious behaviour.

Hence I now own a 100 bugs KNX IP router :-)

I hope others can make use of this information.
Again thanks and regards to the developers, Ill send a little something via the gratitude links ;-)

kindly

spa

**Comment by songzh96** [comment]
Hi @spa49 

try change the knxd config
`KNXD_OPTIONS="--Name=KNXgate --eibaddr=0.0.1 --client-addrs=0.0.2:100 -d -DTS -i --listen-local=/tmp/knx -b tpuarts:/dev/ttyAMA0$`
This is what I usually use, relatively stable

**Comment by smurfix** [comment]
Where does the trailing `$` come from?
You might want to add `-c` to enable the cache.
Don't use `-d` here; the SysV init file already includes it and systemd doesn't want it.
