### ISSUE TITLE
Trying to setup KNXD for OpenHAB and ETS

### ISSUE THREAD

**Issue by klmpencran** [knxd/knxd#497]
Hi everybody,

I don't know if it's the place for obtaining help. In fact I'm not sure it is an issue, rather a misunderstanding of the documentation. I'm perhaps not good enough with all this technical devices.

I'm trying to modify my KNX installation (80 devices that are assuming rollershutters opening/closing, heating, lights, water warming and so on), because I want to add the possibility to drive the sauna heater I'm installing in my bathroom. But I'm fed up with stopping Openhab in order to modify my KNX installation with ETS, because doing both at the same time is not possible.

I've got a KNX/IP Gateway IPS2/1, that is only a gateway and not a router. This seems to mean that only one device can connect to this gateway. That's the reason why I have to stop Openhab when I'm programming with ETS.

I would like to setup a KNXD server that could relay Openhab KNX commands to my ABB gateway, and also be used by ETS when I'm modifying the KNX programmation.

Is it possible ?

My KNX/IP gateway has the IP Address 192.168.0.201. Openhab is running on a Raspberry Pi 4B which has the address 192.168.0.76 (same LAN). Pinging 224.0.23.12 from the Raspberry Pi is answered by the KNX IP/Gateway.

What would be the correct parameters for KNXD to work as I want ?

Thanks in advance for your answers.

**Comment by tru7** [comment]
Preferred location for diskussions about knxd is here: https://groups.google.com/g/knxd
