### ISSUE TITLE
knxd not starting  ExecStart=/usr/local/bin/knxd $KNXD_OPTS (code=exited, status=1/FAILURE)

### ISSUE THREAD

**Issue by sethumadhav96** [knxd/knxd#499]
Iam trying to integrate a ncn5130 transciever with knxd running on a debian platform, when i started the knxd first time with the config KNXD_OPTS="-e 0.0.1 -E 0.0.2:8 -u /tmp/eib -t1023 -b tpuart:ttyO1" , it was working fine . Then next day when i was checking it was saying  ExecStart=/usr/local/bin/knxd $KNXD_OPTS (code=exited, status=1/FAILURE). Is there any more configuration that has to be set up in the daemon. 
But its working fine with the config KNXD_OPTS="-e 0.0.1 -E 0.0.2:8 -u /tmp/eib -b ip:"

Help needed , New to linux and tech field

**Comment by smurfix** [comment]
This is a support problem, not an issue per se. Please use the google group or the knx forum.
