### ISSUE TITLE
move commonly used programs to subdirectory "tools"

### ISSUE THREAD

**Issue by timowi** [knxd/knxd#5]
Move commonly used tools to a new subdirectory. These should be installed by default. 
A list of all examples/tools is in the wiki: https://github.com/Makki1/knxd/wiki/ToolsExamples

The useful/widely used ones must be identified now.

**Comment by smurfix** [comment]
This has been addressed in 8359ff1 and c7153014. Basically, these tools are now called via "knxtool".

You have three choices:
* prefix with "knxtool "
* prefix with "/usr/lib/knxd/"
* add "/usr/lib/knxd" to your path
