### ISSUE TITLE
changed branch name master to main results in invalid install instructions

### ISSUE THREAD

**Issue by mwuerr** [knxd/knxd#504]
´readme.md is still refering to master as the main branch. Resulting in 

~/knxd $ git checkout master
error: Pfadspezifikation 'master' stimmt mit keinen git-bekannten Dateien überein.

please change the instructions to "git checkout main"

**Comment by tru7** [comment]
personally I'd prefer an up-to-date master branch eventuelly with a new release tag

**Comment by smurfix** [comment]
Thanks, fixed. I also created a 0.14.50 tag to clean up the confusion. (*That* nonsense, btw, was caused by a broken system on my side that severely disrupted my workflows. Oh well.)

**Comment by tru7** [comment]
thank you again for your tremendous work
