### ISSUE TITLE
Knxd not starting with TPUART interface

### ISSUE THREAD

**Issue by nickvanbaelen** [knxd/knxd#505]
**Description**
Knxd doesn't start when using a TPUART interface
F00000105: [19:C.tpuarts] Link down, terminating

**Setup**
Using a Siemens Bustranceiver Module BTM UP117 5WG1117-2AB11 via TPUART (ttyAMA0) on a RPI2. Tested that the hardware and connections are fine by using minicom, everything ok there. All other services that might interfere on the TPUART are shut down and disabled (i.e. serial-getty). The knxd setup on the RPI2 works perfectly fine using a MDT SCN-USBR.01 USB interface and ofcourse the option '-b usb:' instead.

**Command:**
/usr/local/bin/knxd -p /run/knxd/knxd.pid --eibaddr=1.1.255 --client-addrs=1.1.250:5 -d -D -T -R -S -i -u /tmp/knx -B single -b tpuarts:dev/ttyAMA0

**Error**
Below you can find the full log. As you can see the knxd is sending out a SendReset on the serial line and the Siemens BTM is responding to it with a '47 47'.

**root@raspberrypi:/home/nick#** /usr/local/bin/knxd -t 1023 -p /run/knxd/knxd.pid --eibaddr=1.1.255 --client-addrs=1.1.250:5 -D -T -R -S -i -u /tmp/knx -B log -b tpuarts:/dev/ttyAMA0
Layer 4 [ 1:main        0.000] initialized
Layer 4 [ 1:main        0.000] setting up
Layer 3 [ 4:server/Server      0.001] registerLink: 4:server
Layer 3 [11:A.tcp/inet         0.001] registerLink: 11:A.tcp
Layer 3 [15:B.unix/local       0.002] registerLink: 15:B.unix
Layer 0 [21:log/C.tpuarts       0.002] State setup
Layer 0 [23:C.tpuarts/log       0.002] Insert 22:LowF / 20:tpuart
Layer 0 [23:C.tpuarts/log       0.002] Setup
Layer 0 [25:C.tpuarts/log       0.003] Insert 24:TPU_ser / 22:LowF
Layer 0 [23:C.tpuarts/log       0.003] Filter single not found
Layer 0 [25:C.tpuarts/log       0.003] Setup
Layer 0 [25:C.tpuarts/log       0.003] Setup OK: yes
Layer 0 [23:C.tpuarts/log       0.003] Setup OK: yes
Layer 3 [19:C.tpuarts/Conn      0.003] registerLink: 19:C.tpuarts
Layer 4 [ 1:main                0.004] setup OK
Layer 4 [ 1:main                0.004] trigger going up
Layer 3 [19:C.tpuarts/Conn      0.004] Start: cfg:C.tpuarts
Layer 5 [19:C.tpuarts/Conn      0.004] down => >up
Layer 5 [19:C.tpuarts/Conn      0.004] Starting
Layer 0 [21:log/C.tpuarts       0.004] State start
Layer 0 [23:C.tpuarts/log       0.005] Start
Layer 0 [25:C.tpuarts/log       0.005] Start
Layer 0 [24:C.tpuarts/TPU_ser   0.006] Opened /dev/ttyAMA0 with baud 19200
Layer 2 [24:C.tpuarts/TPU_ser   0.006] Opened
Layer 2 [24:C.tpuarts/TPU_ser   0.006] Buffer Setup on fd 4
Layer 0 [25:C.tpuarts/log       0.007] Started
Layer 8 [22:C.tpuarts/LowF      0.007] state: new > start
Layer 0 [22:C.tpuarts/LowF      0.007] SendReset 01
Layer 0 [25:C.tpuarts/log       0.007] Send(001): 01
Layer 4 [19:C.tpuarts/Conn      0.007] link state changed: >up
Layer 3 [15:B.unix/local        0.007] Start: cfg:B.unix
Layer 5 [15:B.unix/local        0.008] down => >up
Layer 8 [15:B.unix/local        0.008] OpenLocalSocket /tmp/knx
Layer 8 [15:B.unix/local        0.008] LocalSocket opened
Layer 5 [15:B.unix/local        0.008] >up => up
Layer 4 [15:B.unix/local        0.009] link state changed: up
Layer 5 [15:B.unix/local        0.009] Started
Layer 4 [15:B.unix/local        0.009] link state changed: up
Layer 3 [ 4:server/Server       0.009] Start: cfg:server
Layer 5 [ 4:server/Server       0.009] down => >up
Layer 8 [ 4:server/Server       0.009] Open
Layer 0 [ 4:server/Server       0.010] Open
Layer 0 [ 4:server/Server       0.010] Opened
Layer 8 [28:router/driver       0.010] OpenD
Layer 8 [28:router/driver       0.012] OpenedD
Layer 3 [27:router/ConnC        0.012] registerLink: 27:router_27
Layer 3 [27:router/ConnC        0.012] Start: cfg:router
Layer 5 [27:router/ConnC        0.012] down => >up
Layer 5 [27:router/ConnC        0.012] Starting
Layer 5 [27:router/ConnC        0.013] >up => up
Layer 4 [27:router/ConnC        0.013] link state changed: up
Layer 5 [27:router/ConnC        0.013] Started
Layer 4 [27:router/ConnC        0.013] link state changed: up
Layer 8 [ 4:server/Server       0.013] Opened
Layer 5 [ 4:server/Server       0.013] >up => up
Layer 4 [ 4:server/Server       0.013] link state changed: up
Layer 5 [ 4:server/Server       0.014] Started
Layer 4 [ 4:server/Server       0.014] link state changed: up
Layer 3 [11:A.tcp/inet          0.014] Start: cfg:A.tcp
Layer 5 [11:A.tcp/inet          0.014] down => >up
Layer 8 [11:A.tcp/inet          0.014] OpenInetSocket 6720
Layer 8 [11:A.tcp/inet          0.014] InetSocket opened
Layer 5 [11:A.tcp/inet          0.015] >up => up
Layer 4 [11:A.tcp/inet          0.015] link state changed: up
Layer 5 [11:A.tcp/inet          0.015] Started
Layer 4 [11:A.tcp/inet          0.015] link state changed: up
Layer 4 [ 1:main                0.015] going up triggered
Layer 4 [ 1:main                0.016] check start
Layer 4 [19:C.tpuarts/Conn      0.016] state is >up
Layer 4 [ 1:main                0.016] check end: want_up 1 some 1>1 all 0>0, going 1 up 4 down 0
Layer 0 [25:C.tpuarts/log       0.251] Recv(002): 47 47
Layer 8 [22:C.tpuarts/LowF      0.251] State: 47
Layer 8 [22:C.tpuarts/LowF      0.251] State: 47
Layer 0 [22:C.tpuarts/LowF      0.480] SendReset 01
Layer 0 [25:C.tpuarts/log       0.480] Send(001): 01
Layer 0 [25:C.tpuarts/log       0.717] Recv(002): 47 47
Layer 8 [22:C.tpuarts/LowF      0.717] State: 47
Layer 8 [22:C.tpuarts/LowF      0.717] State: 47
Layer 0 [22:C.tpuarts/LowF      0.980] SendReset 01
Layer 0 [25:C.tpuarts/log       0.980] Send(001): 01
Layer 0 [25:C.tpuarts/log       1.217] Recv(002): 47 47
Layer 8 [22:C.tpuarts/LowF      1.217] State: 47
Layer 8 [22:C.tpuarts/LowF      1.217] State: 47
Layer 8 [22:C.tpuarts/LowF      1.481] state: in_reset > error
Layer 0 [25:C.tpuarts/log       2.482] Stop
Layer 0 [25:C.tpuarts/log       2.482] Errored
Layer 8 [22:C.tpuarts/LowF      2.482] state: error > new
Layer 0 [23:C.tpuarts/log       2.482] Errored
Layer 0 [21:log/C.tpuarts       2.483] State errored
Layer 5 [19:C.tpuarts/Conn      2.483] >up => error
Layer 4 [19:C.tpuarts/Conn      2.483] link state changed: error
Layer 4 [ 1:main                2.483] check start
Layer 4 [ 1:main                2.483] check end: want_up 1 some 1>1 all 0>0, going 0 up 4 down 1
F00000105: [19:C.tpuarts] Link down, terminating
Layer 4 [ 1:main                2.484] trigger Going down
Layer 4 [27:router/ConnC        2.484] R Stopping
Layer 5 [27:router/ConnC        2.484] up => >down
Layer 5 [27:router/ConnC        2.484] L Stopping
Layer 5 [27:router/ConnC        2.484] >down => down
Layer 4 [27:router/ConnC        2.484] link state changed: down
Layer 4 [27:router/ConnC        2.484] link state changed: down
Layer 4 [19:C.tpuarts/Conn      2.485] R Stopping
Layer 5 [19:C.tpuarts/Conn      2.485] error => >down
Layer 4 [19:C.tpuarts/Conn      2.485] link state changed: error
Layer 4 [15:B.unix/local        2.485] R Stopping
Layer 5 [15:B.unix/local        2.485] up => >down
Layer 8 [15:B.unix/local        2.486] StopServer
Layer 5 [15:B.unix/local        2.486] >down => down
Layer 4 [15:B.unix/local        2.486] link state changed: down
Layer 4 [15:B.unix/local        2.486] link state changed: down
Layer 4 [ 4:server/Server       2.486] R Stopping
Layer 5 [ 4:server/Server       2.487] up => >down
Layer 5 [27:router/ConnC        2.487] L Stopping
Layer 3 [27:router/ConnC        2.487] unregisterLink: router_27
Layer 0 [ 4:server/Server       2.487] Close D
Layer 5 [ 4:server/Server       2.487] >down => down
Layer 4 [ 4:server/Server       2.488] link state changed: down
Layer 4 [ 4:server/Server       2.488] link state changed: down
Layer 4 [11:A.tcp/inet          2.488] R Stopping
Layer 5 [11:A.tcp/inet          2.488] up => >down
Layer 8 [11:A.tcp/inet          2.488] StopServer
Layer 5 [11:A.tcp/inet          2.489] >down => down
Layer 4 [11:A.tcp/inet          2.489] link state changed: down
Layer 4 [11:A.tcp/inet          2.489] link state changed: down
Layer 4 [ 1:main                2.489] check start
Layer 8 [28:router/driver       2.489] CloseD
Layer 4 [15:B.unix/local        2.489] is down
Layer 4 [ 4:server/Server       2.489] is down
Layer 4 [11:A.tcp/inet          2.490] is down
Layer 4 [ 1:main                2.490] check end: want_up 0 some 1>0 all 0>0, going 0 up 0 down 4
Layer 4 [ 1:main                2.490] down
Layer 4 [ 1:main                2.490] deleting
Layer 0 [23:C.tpuarts/log       2.490] Closing
Layer 2 [22:C.tpuarts/LowF      2.490] Close C
Layer 0 [25:C.tpuarts/log       2.490] Closing
Layer 2 [24:C.tpuarts/TPU_ser   2.491] Close F
Layer 8 [15:B.unix/local        2.491] StopServer
Layer 8 [ 4:server/Server       2.491] Close E
Layer 8 [11:A.tcp/inet          2.491] StopServer
Layer 4 [ 1:main                2.491] deleted.

**Comment by shyne99** [comment]
This setup is working for a lot of person.

I am no expert, but it looks like a physical error. From the tpuarts datasheet : 
`3.2.3.2.3.2TP-UART-State.indication/response-Service
The TP-UART-State.response-Service is sent if an U_State.request-Service was received
from the host controller. In case of a slave collision, receive error, checksum error or
protocol error the TP-UART-IC sends a State.indication-Service.
TP-UART-Control Field
7 6 5 4 3 2 1 0
SC RE TE PE TW 1 1 1
SC = Slave Collision
RE = Receive Error (checksum, parity or bit error)
TE = Transmitter Error (send 0 receive 1)
PE = Protocol Error (e.g. illegal control byte)
TW = Temperature Warning1)
`

0x47 looks like a receive error. Something is badly read from the bus (error in partity). 

I'll advise to try with the minimal devices on the bus, like you power supply, and a single relay connected, and sse if you still have the issue.

**Comment by da-anda** [comment]
I suppose the missing `/` before `dev/ttyAMA0` in your command example `... -b tpuarts:dev/ttyAMA0` is just a typo here in the ticket?

**Comment by smurfix** [comment]
> I suppose the missing / … is just a typo

Otherwise the code wouldn't even get that far.

Given that the `x47` error is reported after a reset command of all things, at first glance this looks like a severe hardware problem.

**Comment by dallmair** [comment]
This has been fixed in #534 and the fix was released in version 0.14.57, therefore it's time to close this issue.
