### ISSUE TITLE
PhysAddrSnoRead

### ISSUE THREAD

**Issue by bobgodoy** [knxd/knxd#509]
Please, what does it mean when the diagnostics module shows PhysAddrSnoRead?

Best Regards

**Comment by shyne99** [comment]
Hello,

Help us help you. 
Take 5-10 minutes and explain to what you are doing, what's your setup, what are you trying to achieve, what is the expected behaviour, and what is the issue.

**Comment by smurfix** [comment]
This string does not appear in knxd. Looks like some other software. Please ask them.
If you're sure it's knxd, please re-open the issue and provide enough details to reproduce or at least understand the problem.
Thanks.
