### ISSUE TITLE
Include useful defaults in init script

### ISSUE THREAD

**Issue by RichiH** [knxd/knxd#51]
We should have workable defaults/examples for IPT, USB, etc in the init script

**Comment by Morg42** [comment]
Those probably should not be in the init script, but in /etc/default/knxd...

I can add examples for IPT connections... USB should be done by someone who actually has a USB interface :-)

**Comment by smurfix** [comment]
knxd.conf now includes 
# Run `knxd --help` to get a list of available options and drivers.

1f31486 adds a couple of additional examples and such.
