### ISSUE TITLE
Driver timed out trying to send

### ISSUE THREAD

**Issue by HyP3r-** [knxd/knxd#513]
Hello, I have here a Debian 10.9 (5.10.17-v7+ armv7l GNU/Linux) with knxd version 0.14.30.

The service is started by systemd and called with the following parameters:

```
/usr/bin/knxd -e 0.0.21 -E 0.0.22:8 -u /tmp/eib -b ip:
```

As python library to send KNX packets I use [knxdclient](https://github.com/mhthies/knxdclient).

Always after a few hours knxd crashes with the following error message:

```
Mai 24 04:47:14 fg-pbx01 systemd[1]: Starting KNX Daemon...
Mai 24 04:47:14 fg-pbx01 systemd[1]: Started KNX Daemon.
Mai 24 06:04:10 fg-pbx01 knxd[30081]: E00000055: [13:B.ip] Driver timed out trying to send (B.ip)
Mai 24 06:04:10 fg-pbx01 knxd[30081]: F00000105: [13:B.ip] Link down, terminating
Mai 24 06:04:10 fg-pbx01 systemd[1]: knxd.service: Main process exited, code=exited, status=1/FAILURE
Mai 24 06:04:10 fg-pbx01 systemd[1]: knxd.service: Failed with result 'exit-code'.
Mai 24 06:04:20 fg-pbx01 systemd[1]: knxd.service: Service RestartSec=10s expired, scheduling restart.
Mai 24 06:04:20 fg-pbx01 systemd[1]: knxd.service: Scheduled restart job, restart counter is at 20.
Mai 24 06:04:20 fg-pbx01 systemd[1]: Stopped KNX Daemon.
Mai 24 06:04:20 fg-pbx01 systemd[1]: Starting KNX Daemon...
Mai 24 06:04:20 fg-pbx01 systemd[1]: Started KNX Daemon.
Mai 24 07:30:42 fg-pbx01 knxd[1862]: E00000055: [13:B.ip] Driver timed out trying to send (B.ip)
Mai 24 07:30:42 fg-pbx01 knxd[1862]: F00000105: [13:B.ip] Link down, terminating
Mai 24 07:30:42 fg-pbx01 systemd[1]: knxd.service: Main process exited, code=exited, status=1/FAILURE
Mai 24 07:30:42 fg-pbx01 systemd[1]: knxd.service: Failed with result 'exit-code'.
Mai 24 07:30:52 fg-pbx01 systemd[1]: knxd.service: Service RestartSec=10s expired, scheduling restart.
Mai 24 07:30:52 fg-pbx01 systemd[1]: knxd.service: Scheduled restart job, restart counter is at 21.
Mai 24 07:30:52 fg-pbx01 systemd[1]: Stopped KNX Daemon.
Mai 24 07:30:52 fg-pbx01 systemd[1]: Starting KNX Daemon...
Mai 24 07:30:52 fg-pbx01 systemd[1]: Started KNX Daemon.
Mai 24 08:39:10 fg-pbx01 knxd[6651]: E00000055: [13:B.ip] Driver timed out trying to send (B.ip)
Mai 24 08:39:10 fg-pbx01 knxd[6651]: F00000105: [13:B.ip] Link down, terminating
Mai 24 08:39:10 fg-pbx01 systemd[1]: knxd.service: Main process exited, code=exited, status=1/FAILURE
Mai 24 08:39:10 fg-pbx01 systemd[1]: knxd.service: Failed with result 'exit-code'.
Mai 24 08:39:20 fg-pbx01 systemd[1]: knxd.service: Service RestartSec=10s expired, scheduling restart.
Mai 24 08:39:20 fg-pbx01 systemd[1]: knxd.service: Scheduled restart job, restart counter is at 22.
Mai 24 08:39:20 fg-pbx01 systemd[1]: Stopped KNX Daemon.
```

What could be the reason for this?

The reason why I write this is that I see in my logs of my [self-developed automatic shading](https://github.com/HyP3r-/knx-deviced/blob/develop/devices/automatic_shading.py#L359) that this automatic shading sends some packets at certain times, but these packets are then not sent in the ETS group monitor (with which I am simultaneously connected to the bus).

The whole thing surprises me because KNX over Ethernet are in principle only UDP multicast IP frames. How can a connection be lost in this context?

**Comment by smurfix** [comment]
I have no idea but this code has substantially changed since 0.14.30. Please compile the current version from source and check whether the problem is still there.

**Comment by tru7** [comment]
As there is no physical KNX device involved wouldn't it look like interrupts on the network interface?

**Comment by HyP3r-** [comment]
> I have no idea but this code has substantially changed since 0.14.30. Please compile the current version from source and check whether the problem is still there.

I just compiled and installed the latest version on the debian branch. Now I am watching if this happens again. Would be funny if it is again because Debian delivers such ancient packages.

> As there is no physical KNX device involved wouldn't it look like interrupts on the network interface?

I don't know what the problem is. But interruptions at the network interface are not known to me. You don't see anything in the event log of the operating system.

**Comment by HyP3r-** [comment]
After some observation, I have to say that this effect no longer occurs with the newer version. I close the ticket.
