### ISSUE TITLE
F00000105: [15:B.tpuarts] Link down, terminating

### ISSUE THREAD

**Issue by pmwachelka** [knxd/knxd#514]
Hi, I have problem to get the knxd running. I am getting errors:

RPihat: Layer 5 [15:B.tpuarts/Conn      2.487] >up => error
RPihat: Layer 4 [15:B.tpuarts/Conn      2.487] link state changed: error
RPihat: Layer 4 [ 1:main                2.487] check start
RPihat: Layer 4 [ 1:main                2.487] check end: want_up 1 some 1>1 all 0>0, going 0 up 3 down 1
RPihat: F00000105: [15:B.tpuarts] Link down, terminating
RPihat: Layer 4 [ 1:main                2.487] trigger Going down

In /boot/config.txt I added:
dtoverlay=disable-bt
enable_uart=1
dtoverlay=pi3-disable-bt

Starting with params:
knxd -t1023 --eibaddr=1.1.255 -E 1.1.250:5 -n RPihat -D -T -R -S -u /tmp/eib -i --layer2=tpuarts:/dev/ttyKNX1

What could be the reason?

**Comment by smurfix** [comment]
Most likely reasons: (a) the console is still active on that port (b) you didn't connect the KNX wires.

**Comment by pmwachelka** [comment]
The KNX is connected. At least there is power.
What you mean by the console is still active?

**Comment by smurfix** [comment]
The kernel and/or some other program may also have opened the device and reads the data from the serial port so knxd won't get them. You need to remove `console=ttyAMA0` from `/boot/cmdline.txt` and `systemd disable agetty@ttyAMA0`. Assuming that you're using a TPUART hat, that is.

Which hardware *are* you using?

**Comment by pmwachelka** [comment]
My /boot/cmdline.txt: have only tty1:
console=tty1 root=PARTUUID=6c586e13-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait

The root@raspberrypi:/home/pi# systemd disable agetty@ttyAMA0 command generate message:
Excess arguments.

I did:

root@raspberrypi:/home/pi# systemctl stop serial-getty@ttyAMA0.service
root@raspberrypi:/home/pi# systemctl disable serial-getty@ttyAMA0.service

My hardware:
Hardware        : BCM2835
Revision        : a02082
Serial          : 00000000448c0664
Model           : Raspberry Pi 3 Model B Rev 1.2

**Comment by smurfix** [comment]
What hardware are you using to connect to the KNX bus?

Stopping `serial-getty` doesn't do anything on my system, I really need to systemctl-stop `getty`. `ps axuw|grep 'getty.*AMA'` should not print anything-

**Comment by pmwachelka** [comment]
I have only this console active:
root@raspberrypi:/home/pi# ps axuw|grep 'tty*'
root       701  0.0  0.1   4308  1300 tty1     Ss+  16:07   0:00 /sbin/agetty -o -p -- \u --noclear tty1 linux
root      1385  0.0  0.0   7348   516 pts/1    S+   17:12   0:00 grep tty*

**Comment by smurfix** [comment]
Huh. Assuming that you set the jumper to 19200 baud and the red LED is on (bus power) I have admit that I have no idea what could be wrong.

My next step would be to hook a 'scope to the two UART lines and check whether the Pi really sends something and the NCN responds, and go from there.

**Comment by pmwachelka** [comment]
I think I found the reason. I have Razberry z-wave hat (https://z-wave.me/products/razberry/razberry-revisions/ Z-Wave Plus 5th gen chip ZM5202). And it looks that it is using the same pins. I wanted to use it together.

**Comment by smurfix** [comment]
Owch. Yes that explains it.

**Comment by tunm1228** [comment]
> I have only this console active: root@raspberrypi:/home/pi# ps axuw|grep 'tty*' root 701 0.0 0.1 4308 1300 tty1 Ss+ 16:07 0:00 /sbin/agetty -o -p -- \u --noclear tty1 linux root 1385 0.0 0.0 7348 516 pts/1 S+ 17:12 0:00 grep tty*

Have you fixed this error yet? Please guide me

**Comment by smurfix** [comment]
Please do not hijack closed issues.

How to turn off getty on ttyAMA0 is not a KNXD problem.
