### ISSUE TITLE
knxd failing with ABB USB bridge

### ISSUE THREAD

**Issue by ThorbenJ** [knxd/knxd#517]
# Environment

New build with KNX installation (& confiugration) done by the Electricians. Most devices on 1.1.x and groups 0/2/x. In the consumer unit there is:
```
T:  Bus=04 Lev=01 Prnt=01 Port=04 Cnt=01 Dev#=  3 Spd=12  MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=147b ProdID=5120 Rev=04.04
S:  Manufacturer=ABB STOTZ-KONTA
S:  Product=KNX-USB Interface
S:  SerialNumber=000247Dxxxxx
C:  #Ifs= 1 Cfg#= 1 Atr=80 MxPwr=20mA
I:  If#=0x0 Alt= 0 #EPs= 2 Cls=03(HID  ) Sub=00 Prot=00 Driver=(none)
```
Which I've plugged into.

# System

- OS: Debian Linux 11 (bullseye)
- uname: `Linux Graphite 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux`
- knxd: knxd 0.14.46 - I have also compiledand tried from GH master knxd 0.14.51

# What works

I bought ETS5 Home (actually ETS Inside, but since its being discontinued I got a free upgrade to Home edition). The electrians left me a copy of their ETS5 project. I am still learning the ropes, but I can forward the ABB USB device to my windows 10 machine via USBIP and it works fine with ETS5 Home.

However I want to share it with OpenHAB so I need knxd

# What does not work

Start knxd:
```
knxd -e 1.1.100 -E 1.1.101:8 -c -f 9 -t 1023 -B log -b usb: -DTRS -i
```

Any ETS5 group read/write will cause knxd to die, monitor does nothing.

It will also fail with knxtool:
```
root@Graphite:~# knxtool groupread ip:localhost 0/2/19
Send request
root@Graphite:~# 
```

knxd logs:
```
root@Graphite:~# knxd -e 1.1.100 -E 1.1.101:8 -c -f 9 -t 1023 -B log -b usb: -DTRS -i
Layer 0 [ 8:log/B.usb       0.000] State setup
Layer 3 [ 6:B.usb/Conn      0.000] registerLink: 6:B.usb
Layer 3 [ 6:B.usb/Conn         0.001] Start: cfg:B.usb
Layer 5 [ 6:B.usb/Conn         0.001] down => >up
Layer 5 [ 6:B.usb/Conn         0.001] Starting
Layer 0 [ 8:log/B.usb          0.001] State start
Layer 1 [10:B.usb/usbL         0.020] Detect
Layer 1 [10:B.usb/usbL         0.021] Using 4:3:1:0:0 (1:129)
Layer 1 [10:B.usb/usbL         0.021] Open
Layer 1 [10:B.usb/usbL         0.024] Claimed
Layer 1 [10:B.usb/usbL         0.024] Opened
Layer 0 [ 7:B.usb/USBdr        0.024] starting send_Local
Layer 0 [10:B.usb/usbL         0.024] SendUSB(064): 01 13 09 00 08 00 01 0F 01 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0 [10:B.usb/usbL         0.024] StartSend 5574b5373b78
Layer 4 [ 6:B.usb/Conn         0.024] link state changed: >up
Layer 4 [ 6:B.usb/Conn         0.024] state is >up
Layer 0 [ 7:B.usb/USBdr        0.027] send_Local done
Layer 0 [10:B.usb/usbL         0.028] RecvUSB(064): 01 13 0B 00 08 00 03 0F 02 00 00 01 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 2 [ 7:B.usb/USBdr        0.028] recv_Data(064): 01 13 0B 00 08 00 03 0F 02 00 00 01 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 1 [ 7:B.usb/USBdr        0.028] Using EMI version 3
Layer 2 [ 9:B.usb/Conv         0.028] send_Init 3
Layer 0 [ 9:B.usb/Conv         0.028] starting send_Local
Layer 0 [10:B.usb/usbL         0.028] SendUSB(064): 01 13 0A 00 08 00 02 0F 03 00 00 05 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0 [10:B.usb/usbL         0.029] StartSend 5574b538a7c8
Layer 0 [ 9:B.usb/Conv         0.030] send_Local done
Layer 2 [26:B.usb/CEMI         0.030] OpenL2
Layer 0 [ 8:log/B.usb          0.030] State started
Layer 5 [ 6:B.usb/Conn         0.030] >up => up
Layer 4 [ 6:B.usb/Conn         0.030] link state changed: up
Layer 5 [ 6:B.usb/Conn         0.030] Started
Layer 6 [ 6:B.usb/Conn         4.336] sending, send_more clear
Layer 0 [ 8:log/B.usb          4.336] Send L_Data low from 1.1.101 to 0/2/19 hops: 05 T_Data_Group A_GroupValue_Read
Layer 0 [ 9:B.usb/Conv         4.336] Send-EMI(011): 11 00 BC D0 11 65 02 13 01 00 00
Layer 0 [10:B.usb/usbL         4.336] SendUSB(064): 01 13 13 00 08 00 0B 01 03 00 00 11 00 BC D0 11 65 02 13 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0 [10:B.usb/usbL         4.337] StartSend 5574b5388ea8
Layer 6 [ 6:B.usb/Conn         4.354] still waiting
Layer 1 [26:B.usb/CEMI         6.339] No confirm, repeating
Layer 0 [ 9:B.usb/Conv         6.339] Send-EMI(011): 11 00 BC D0 11 65 02 13 01 00 00
Layer 0 [10:B.usb/usbL         6.339] SendUSB(064): 01 13 13 00 08 00 0B 01 03 00 00 11 00 BC D0 11 65 02 13 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0 [10:B.usb/usbL         6.339] StartSend 5574b53739c8
Layer 1 [26:B.usb/CEMI         8.341] No confirm, repeating
Layer 0 [ 9:B.usb/Conv         8.341] Send-EMI(011): 11 00 BC D0 11 65 02 13 01 00 00
Layer 0 [10:B.usb/usbL         8.341] SendUSB(064): 01 13 13 00 08 00 0B 01 03 00 00 11 00 BC D0 11 65 02 13 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Layer 0 [10:B.usb/usbL         8.341] StartSend 5574b5383e58
Layer 2 [26:B.usb/CEMI         9.338] CloseL2
Layer 1 [10:B.usb/usbL         9.338] Close G
Layer 1 [10:B.usb/usbL         9.338] Close G
Layer 6 [ 8:log/B.usb          9.338] send next
Layer 6 [ 6:B.usb/Conn         9.338] sendNext called, send_more set
Layer 6 [ 6:B.usb/Conn         9.338] is OK
Layer 0 [ 8:log/B.usb          9.338] State errored
Layer 5 [ 6:B.usb/Conn         9.338] up => error
Layer 4 [ 6:B.usb/Conn         9.338] link state changed: error
Layer 1 [10:B.usb/usbL         9.338] Release
F00000105: [ 6:B.usb] Link down, terminating
Layer 4 [ 6:B.usb/Conn         9.339] R Stopping
Layer 5 [ 6:B.usb/Conn         9.339] error => >down
Layer 4 [ 6:B.usb/Conn         9.339] link state changed: error
Layer 1 [10:B.usb/usbL         9.340] Close G
```

Almost anything I try with knxd either does nothing or causes knxd to die.
However again, connecting ETS5 "directly" via USBIP works fine.

I have noticed that my attempts did annoy the ABB Touch screen management console. It would no longer switch lights, window blinds, etc., and lost all target temperate settings for heating and cooling. In the end I had to take it off the wall to get it to reboot, it then started working again.

**Comment by smurfix** [comment]
I have no idea why this thing refuses to reply, sorry. I would need a sample device to fix this, presumably by way of monitoring whatever ETS5 does when its talks to the thing.

Generally I recommend to use an IP interface instead. These are made for permanent connections. The USB things are intended for temporary configuration activities where it won't matter much if they misbehave, just unplug and try again …

**Comment by ThorbenJ** [comment]
Hi.

This is what I have. I can unplug the USB cable, but the ABB device is mounted on the DIN rail in the consumer unit, so I can't disconnect it from power or the KNX bus without opening up the consumer unit.. (I have tried unplugging and replugging the the USB cable).

Getting another device is an eventual option; and any recommendation on something DIN mountable is welcome. I will have to check with the electricians as to not break the new builds 2yr warrenty; and it wont be cheap if I commission them to do it...

What I can offer you is a pcap capture (via tcpdump) of the USBIP [https://www.kernel.org/doc/html/latest/usb/usbip_protocol.html] traffic when ETS5 is using the device. (I could do the same for knxd as well)

Would that be helpful?

-Thorben

**Comment by smurfix** [comment]
Yes that would be very helpful. Please (try to …) send the exact same message with ETS and knxtool, and log from the very beginning, i.e. ETS / knxd program startup.

Probably best to email the dumps directly to me: matthias@urlichs.de

Taking the cover off and unplugging the KNX wires from the interface should be reasonably straightforward.

**Comment by ThorbenJ** [comment]
Email "knxd issue #517 pcap traces of usbip traffic" sent

**Comment by steffen-kiess** [comment]
I ran into the same issue (with an ABB USB/S1.2) and compared the communication from ETS and knxd. The difference seems to be that ETS sends a `M_PropWrite.req` request to set the `PID_COMM_MODE` to `0x00` (which means `Data Link Layer`).

According to the `External Message Interface` specification seems to require the client to set the communication mode (see 4.2.2.4.2.1):
> After a power on or a reset, the cEMI Server device may be in an undefined communication mode. If the
> cEMI Client prior to any other communication to or from the bus does not set the Property
> Communication Mode, then the behaviour of the cEMI Server is undefined.

With the attached patch the interface seems to work for me.
[patch-fix-abb-usb-s1.2.txt](https://github.com/knxd/knxd/files/7449396/patch-fix-abb-usb-s1.2.txt)

**Comment by ThorbenJ** [comment]
The pcaps that I shared via email are quite small, and since I see more people are trying to crack this nut I thought I would share it here as well.

The goal here was to get captures of the USB communication by using TCPdump with USBIP. USBIP is currently how I use ETS5 with the device, since my windows machine is nowhere near my electrical cabinet.
I recorded three scenarios involving three machines.

The machines:

A) 172.20.1.17 (graphite)
This host has the ABB USB device attached to it; in all these tests it is just running the usbip server and tcpdump.
Since it has the tools installed I also used it to run knxtool against knxd on host-B in the last scenario.

B) 172.20.24.7 (sindri)
For the purposes of these tests, this host ran knxd in the second and third scenarios. It was using the USBIP client.

C) 172.20.29.203 (blackstar)
This is the windows 10 machine running ETS5 (Home). It used the USBIP client in the first scenario and KNX auto-discovery of knxd in the the second scenario.

Scenarios:

First) Everything working (no knxd)

Host-A -> USBIP_Server -> Host-C -> USBIP_Client -> ETS5 (direct control of the ABB device)

0. [Host-A] Start tcpdump
1. [Host-C] USBIP attach the ABB device
2. Attach "local" USB device in ETS5 Bus screen (current interface now set)
3. Clicked "Test" -> OK
4. On the Overview screen opened the project (from electricians) for my apartment
5. Navigate (via Buildings) to the light switch in my office, and selected the first button
6. Clicked the displayed Group (0/2/19), and selected Read Value -> OK
7. Clicked the displayed Group (0/2/19), and selected Write off -> OK (lights off)
8. Clicked the displayed Group (0/2/19), and selected Write on -> OK (lights on)
9. Closed project
10. USBIP detach USB device
11. [Host-A] Stop tcpdump

Second) knxd dies with ETS5

Host-A -> USBIP_Server -> Host-B -> USBIP_Client -> knxd -> Host-C -> ETS5

0. [Host-A] Start tcpdump
1. [Host-B] USBIP attach the ABB device
2. [Host-B] Start: knxd -e 1.1.100 -E 1.1.101:8 -c -f 9 -t 1023 -B log -b usb: -DTRS -i
2. [Host-C] Discover knxd and connect in the Bus screen (current interface now set)
3. Clicked "Test" -> OK
4. On Overview screen opened the project (from electricians) for my apartment
5. Navigate (via Buildings) to the light switch in my office, and selected the first button
6. Clicked the displayed Group (0/2/19), and selected Read Value -> Fail
7. [Host-B] knxd dies
8. [Host-C] Closed project
9. [Host-B] USBIP detach USB device
10. [Host-A] Stop tcpdump

Third) knxd dies with knxtool

Host-A -> USBIP_Server -> Host-B -> USBIP_Client -> knxd -> Host-A -> knxtool

0. [Host-A] Start tcpdump
1. [Host-B] USBIP attach the ABB device
2. [Host-B] Start: knxd -e 1.1.100 -E 1.1.101:8 -c -f 9 -t 1023 -B log -b usb: -DTRS -i
2. [Host-A] run: knxtool groupread ip:sindri 0/2/19 => Outputs "Send request" and exits
3. [Host-B] knxd dies
4. [Host-B] USBIP detach USB device
5. [Host-A] Stop tcpdump

"Fourth") Confirm ABB device still ok.
Repeated First scenario (no tcpdump) to confirm everything still works, and it does. At no point was the ABB USB device physically disconnected, nor was the USBIP server interrupted.


FYI: tcpdump output
root@Graphite:~/pcap# tcpdump -i eth0 -s 65535 -w first.pcap 'host 172.20.1.17 and port 3240'
tcpdump: listening on eth0, link-type EN10MB (Ethernet), snapshot length 65535 bytes
^C624 packets captured
624 packets received by filter
0 packets dropped by kernel

root@Graphite:~/pcap# tcpdump -i eth0 -s 65535 -w second.pcap 'host 172.20.1.17 and port 3240'
tcpdump: listening on eth0, link-type EN10MB (Ethernet), snapshot length 65535 bytes
^C85 packets captured
85 packets received by filter
0 packets dropped by kernel

root@Graphite:~/pcap# tcpdump -i eth0 -s 65535 -w third.pcap 'host 172.20.1.17 and port 3240'
tcpdump: listening on eth0, link-type EN10MB (Ethernet), snapshot length 6
5535 bytes
^C85 packets captured
85 packets received by filter
0 packets dropped by kernel

I loaded them in wireshark. The first time I had to right click -> decode as, and set port 3240 to "USBIP" and then all the USB frames appeared. When I loaded the following files this setting remained.

[pcaps.zip](https://github.com/knxd/knxd/files/7451930/pcaps.zip)

**Comment by ThorbenJ** [comment]
With both the possible patch provided by steffen-kiess and my traces of the USB messages, is there a planned future version of knxd where this should work?
Thanks,
Thorben

**Comment by ThorbenJ** [comment]
Hi all. Cloned and compiled the da-anda "fork" (https://github.com/da-anda/knxd), which has the patch above, and I can confirm it worked on my system.

I tired to see if this root knxd had incorporated any such fix, but I wasn't sure. Git appeared to show that the patch existed in this repo, but it seems it was not connected to any branch. In the end I also tried cloning and compiling this root "fork". It also worked - until the next day when every stopped working again.

After investigation I realised that by running da-anda/knxd previously the device was already in the correct mode and thus knxd/knxd worked; but at some point there was a reset and after that knxd/knxd could no longer correctly initialise the device. Running da-anda/knxd again and everything worked. So I will stick to that fork, and hope that a fix can be merged into knxd/knxd at some point. (Please let me know)

Thank you everyone for your time and effort - I can happily continue setting openhab up on my home KNX installation.
