### ISSUE TITLE
bootstrap does not work on Debian and Ubuntu

### ISSUE THREAD

**Issue by bigblue1735** [knxd/knxd#52]
Hi, i try to compile the version and follow the instruction, but get an error message on the bootstrap command. Here is the error message:
src/backend/Makefile.am: installing `./depcomp'
configure.ac:47: error: possibly undefined macro: AC_COMPILER_OPTION
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:49: error: possibly undefined macro: AC_CHECK_PTHSEM

**Comment by vapourismo** [comment]
You might want to change the `bootstrap.sh` file.
Replace `aclocal --force` with `aclocal -I m4 --force`.

**Comment by RichiH** [comment]
Can we just run with m4 all the time? Or does that have unintended
consequences?

Richard

Sent by mobile; excuse my brevity.

**Comment by vapourismo** [comment]
> Or does that have unintended consequences?

I don't think it does. It is the distro's choice whether to include `./m4` by default.
So it might be useful have `-Im4` by default.

**Comment by J-N-K** [comment]
Fixed with merge of PR#56
