### ISSUE TITLE
Busware.de TPUART USB

### ISSUE THREAD

**Issue by temuccio** [knxd/knxd#521]
Hi all, 
I have add the TPUART USB at my raspberry Pi 3, 
if I add to `/etc/udev/rules.d/70-knxd.rules` the `idVendor` and `idProduct` the device are recognized at `/dev/ttyAMA0`:
```
ls -al /dev/knx1
lrwxrwxrwx 1 root root 7 nov  5 11:30 /dev/knx1 -> ttyAMA0
```

The knxd fail start with this error:
```knxd[6423]: F00000105: [19:C.tpuarts] Link down, terminating```

If I add to `/etc/udev/rules.d/70-knxd.rules`
```
ACTION=="add", SUBSYSTEM=="tty", KERNELS=="ttyAMA0", SYMLINK+="knx1", OWNER="knxd"
```
In accord with Raspberry Pi 3 section, the device are recognized at `/dev/ttyAMA0`:

```
ls -al /dev/knx1
lrwxrwxrwx 1 root root 7 nov  5 11:39 /dev/knx1 -> ttyAMA0
```

The knxd fail start with this error:
```knxd[6423]: F00000105: [19:C.tpuarts] Link down, terminating```

If I add to `/etc/udev/rules.d/70-knxd.rules`
```
ACTION=="add", SUBSYSTEM=="tty", KERNELS=="ttyACM0", SYMLINK+="knx1", OWNER="knxd"
```
In accord with Raspberry Pi 4 section (but I have Raspberry Pi 3), the device are recognized at `/dev/ttyACM0`:

The knxd start but ETS doen't works.
for example I try to check if knxd address is in use and I have this error:
![immagine](https://user-images.githubusercontent.com/571582/140499267-95fbb522-3cff-4939-929f-bae7414e6e86.png)

**Comment by da-anda** [comment]
the busware TPUART USB dongle works just fine for me. Been using it on a RPI2, RPI3 and RPI4 now. I am running HomeAssistant OS and didn't have to add any UDEV rule for it to show up as `/dev/ttyAMA0`. I pass it through to a Alpine based docker container in which I have knxd running and it works just fine, also ETS.

**Comment by Pavancherry12** [comment]
Can I know what is use of busware TPUART USB dongle in implementing KNXD ,can you explain me is it needed if I have Knx-IP interface device ...

**Comment by da-anda** [comment]
> Can I know what is use of busware TPUART USB dongle in implementing KNXD ,can you explain me is it needed if I have Knx-IP interface device ...

This add-on converts USB/UART interfaces into IP-interfaces. So if you already have a KNX IP-interface, you do not need this add-on or any other USB dongle/interface in order to integrate KNX into homeassistant. Your KNX IP-Interface is all you need.

**Comment by da-anda** [comment]
@Pavancherry12  whoops, sorry. For some reason I had a huge brainfart before. I thought I replied to a question on the HomeAssistant community forum regarding my `knxd add-on` and not a github issue for `kndx` (I'm a bit stressed out at the moment).
But the basic gist of my answer still applies. One big use case of `knxd` in combination with USB/UART interfaces is to convert them to IP interfaces (USB/UART interfaces are usually a bit cheaper than commercial KNX IP interfaces, or you might already have a USB interface but now need IP connectivity). There are also other things you can do with knxd, even in combination with existing IP interfaces (like tunneling, etc), but those are more advanced and likely not needed by the average smart home tinkerer.

**Comment by Pavancherry12** [comment]
Hi @da-anda,
Thank you for the detailed explanation. I need your support in implementing KNXD using a KNX-IP interface. The procedure seems to be tailored for setups with the add-on(TLU), but I have a KNX-IP interface instead. Could you please share the specific procedure to follow for this setup? Additionally, what modifications should I make in the KNXD process to implement it correctly with the KNX-IP interface?

Thank you for your assistance

**Comment by da-anda** [comment]
@Pavancherry12 sorry, but hijacking a github issue is not really the right place for support questions. Also, I am neither a knxd developer, not have detailed knowledge of all its features, so I unfortunately can't give you a clear answer to your question. But in order to use `knxd` in combination with an KNX-IP interface, you will likely have to use one of these IP related drivers, see https://github.com/knxd/knxd/blob/main/doc/inifile.rst#ip (read the sections about the `IP`, `IPT` and ´IPTN` drivers). The documentation for the configuration of knxd via ini file is in general a good read and should give you a good starting point https://github.com/knxd/knxd/blob/main/doc/inifile.rst - it at least helped me.

**Comment by Pavancherry12** [comment]
Thanks, I'll check it out.
