### ISSUE TITLE
ETS programmation faild

### ISSUE THREAD

**Issue by mika-nt28** [knxd/knxd#522]
Hi,

I want used knxd for programming device with ETS

I started knxd with this line command
knxd --daemon=/var/log/knx.log --pid-file=/var/run/knx.pid -t1023 --eibaddr=0.0.10 --client-addrs=0.0.11:3 --Name=JeedomDev -D -T -S --listen-tcp=6720 -b  ft12cemi:/dev/ttyS2

On ETS5, JeedomDev is correctly discoved and is possible to view frame on ETS BUS Monitor

0.0.13 Adress is JeedomDev connexion
`<HTML>
<BODY>
<TABLE><TR><TD>n&#176;</TD><TD>Heure</TD><TD>Service</TD><TD>Indicateurs </TD><TD>Priorit&#233;</TD><TD>Adresse de la source</TD><TD>Nom de la source</TD><TD>Adresse de la destination</TD><TD>Nom de la destination</TD><TD>Nombre de sauts</TD><TD>Type</TD><TD>DPT</TD><TD>Informations</TD><TD>Iack</TD></TR><TR><TD>1</TD><TD>10/11/2021&#160;08:39:53,348</TD><TD>D&#233;marrer</TD><TD>&nbsp;</TD><TD>&nbsp;</TD><TD>&nbsp;</TD><TD>&nbsp;</TD><TD>&nbsp;</TD><TD>&nbsp;</TD><TD>&nbsp;</TD><TD>&nbsp;</TD><TD>&nbsp;</TD><TD>L’enregistrement a &#233;t&#233; lanc&#233;, h&#244;te = DESKTOP-8TV1FF8, connexion = JeedomDev, mode = Moniteur de bus.</TD><TD>&nbsp;</TD></TR><TR><TD>2</TD><TD>10/11/2021&#160;08:39:54,575</TD><TD>&#224; partir du bus</TD><TD>S=1</TD><TD>Syst&#232;me</TD><TD>0.0.13</TD><TD>-</TD><TD>1.0.37</TD><TD>Poussoir double KNX</TD><TD>6</TD><TD>DeviceDescriptorRead (S=0)</TD><TD>&nbsp;</TD><TD>DescriptorType=0</TD><TD>&nbsp;</TD></TR><TR><TD>3</TD><TD>10/11/2021&#160;08:39:57,634</TD><TD>&#224; partir du bus</TD><TD>S=2</TD><TD>Syst&#232;me</TD><TD>0.0.13</TD><TD>-</TD><TD>1.0.37</TD><TD>Poussoir double KNX</TD><TD>6</TD><TD>DeviceDescriptorRead (S=0)</TD><TD>&nbsp;</TD><TD>DescriptorType=0</TD><TD>&nbsp;</TD></TR><TR><TD>4</TD><TD>10/11/2021&#160;08:39:58,180</TD><TD>&#224; partir du bus</TD><TD>S=3</TD><TD>Bas</TD><TD>1.0.38</TD><TD>KNX D&#233;tecteur de mouvements 180</TD><TD>11/3/1</TD><TD>Luminosit&#233;</TD><TD>6</TD><TD>GroupValueWrite</TD><TD>&nbsp;</TD><TD>0D 46 | 27</TD><TD>&nbsp;</TD></TR><TR><TD>5</TD><TD>10/11/2021&#160;08:40:00,653</TD><TD>&#224; partir du bus</TD><TD>S=4</TD><TD>Syst&#232;me</TD><TD>0.0.13</TD><TD>-</TD><TD>1.0.37</TD><TD>Poussoir double KNX</TD><TD>6</TD><TD>T_Disconnect</TD><TD>&nbsp;</TD><TD>&nbsp;</TD><TD>&nbsp;</TD></TR><TR><TD>6</TD><TD>10/11/2021&#160;08:40:01,252</TD><TD>&#224; partir du bus</TD><TD>S=5</TD><TD>Syst&#232;me</TD><TD>0.0.13</TD><TD>-</TD><TD>1.0.37</TD><TD>Poussoir double KNX</TD><TD>6</TD><TD>T_Connect</TD><TD>&nbsp;</TD><TD>&nbsp;</TD><TD>&nbsp;</TD></TR><TR><TD>7</TD><TD>10/11/2021&#160;08:40:01,314</TD><TD>&#224; partir du bus</TD><TD>S=6</TD><TD>Syst&#232;me</TD><TD>0.0.13</TD><TD>-</TD><TD>1.0.37</TD><TD>Poussoir double KNX</TD><TD>6</TD><TD>DeviceDescriptorRead (S=0)</TD><TD>&nbsp;</TD><TD>DescriptorType=0</TD><TD>&nbsp;</TD></TR><TR><TD>8</TD><TD>10/11/2021&#160;08:40:03,185</TD><TD>&#224; partir du bus</TD><TD>S=7</TD><TD>Bas</TD><TD>1.0.38</TD><TD>KNX D&#233;tecteur de mouvements 180</TD><TD>11/3/1</TD><TD>Luminosit&#233;</TD><TD>6</TD><TD>GroupValueWrite</TD><TD>&nbsp;</TD><TD>0D 46 | 27</TD><TD>&nbsp;</TD></TR><TR><TD>9</TD><TD>10/11/2021&#160;08:40:04,291</TD><TD>&#224; partir du bus</TD><TD>S=0</TD><TD>Syst&#232;me</TD><TD>0.0.13</TD><TD>-</TD><TD>1.0.37</TD><TD>Poussoir double KNX</TD><TD>6</TD><TD>DeviceDescriptorRead (S=0)</TD><TD>&nbsp;</TD><TD>DescriptorType=0</TD><TD>&nbsp;</TD></TR><TR><TD>10</TD><TD>10/11/2021&#160;08:40:07,315</TD><TD>&#224; partir du bus</TD><TD>S=1</TD><TD>Syst&#232;me</TD><TD>0.0.13</TD><TD>-</TD><TD>1.0.37</TD><TD>Poussoir double KNX</TD><TD>6</TD><TD>DeviceDescriptorRead (S=0)</TD><TD>&nbsp;</TD><TD>DescriptorType=0</TD><TD>&nbsp;</TD></TR><TR><TD>11</TD><TD>10/11/2021&#160;08:40:08,184</TD><TD>&#224; partir du bus</TD><TD>S=2</TD><TD>Bas</TD><TD>1.0.38</TD><TD>KNX D&#233;tecteur de mouvements 180</TD><TD>11/3/1</TD><TD>Luminosit&#233;</TD><TD>6</TD><TD>GroupValueWrite</TD><TD>&nbsp;</TD><TD>0D 46 | 27</TD><TD>&nbsp;</TD></TR><TR><TD>12</TD><TD>10/11/2021&#160;08:40:10,339</TD><TD>&#224; partir du bus</TD><TD>S=3</TD><TD>Syst&#232;me</TD><TD>0.0.13</TD><TD>-</TD><TD>1.0.37</TD><TD>Poussoir double KNX</TD><TD>6</TD><TD>DeviceDescriptorRead (S=0)</TD><TD>&nbsp;</TD><TD>DescriptorType=0</TD><TD>&nbsp;</TD></TR><TR><TD>13</TD><TD>10/11/2021&#160;08:40:13,184</TD><TD>&#224; partir du bus</TD><TD>S=4</TD><TD>Bas</TD><TD>1.0.38</TD><TD>KNX D&#233;tecteur de mouvements 180</TD><TD>11/3/1</TD><TD>Luminosit&#233;</TD><TD>6</TD><TD>GroupValueWrite</TD><TD>&nbsp;</TD><TD>0D 46 | 27</TD><TD>&nbsp;</TD></TR><TR><TD>14</TD><TD>10/11/2021&#160;08:40:13,353</TD><TD>&#224; partir du bus</TD><TD>S=5</TD><TD>Syst&#232;me</TD><TD>0.0.13</TD><TD>-</TD><TD>1.0.37</TD><TD>Poussoir double KNX</TD><TD>6</TD><TD>T_Disconnect</TD><TD>&nbsp;</TD><TD>&nbsp;</TD><TD>&nbsp;</TD></TR><TR><TD>15</TD><TD>10/11/2021&#160;08:40:15,876</TD><TD>&#224; partir du bus</TD><TD>S=6</TD><TD>Bas</TD><TD>1.0.2</TD><TD>-</TD><TD>2/2/3</TD><TD>Temp&#233;rature ambiante</TD><TD>6</TD><TD>GroupValueWrite</TD><TD>&nbsp;</TD><TD>07 8A | 19,3</TD><TD>&nbsp;</TD></TR><TR><TD>16</TD><TD>10/11/2021&#160;08:40:18,172</TD><TD>&#224; partir du bus</TD><TD>S=7</TD><TD>Bas</TD><TD>1.0.38</TD><TD>KNX D&#233;tecteur de mouvements 180</TD><TD>11/3/1</TD><TD>Luminosit&#233;</TD><TD>6</TD><TD>GroupValueWrite</TD><TD>&nbsp;</TD><TD>0D 46 | 27</TD><TD>&nbsp;</TD></TR><TR><TD>17</TD><TD>10/11/2021&#160;08:40:23,193</TD><TD>&#224; partir du bus</TD><TD>S=0</TD><TD>Bas</TD><TD>1.0.38</TD><TD>KNX D&#233;tecteur de mouvements 180</TD><TD>11/3/1</TD><TD>Luminosit&#233;</TD><TD>6</TD><TD>GroupValueWrite</TD><TD>&nbsp;</TD><TD>0D 46 | 27</TD><TD>&nbsp;</TD></TR><TR><TD>18</TD><TD>10/11/2021&#160;08:40:28,166</TD><TD>&#224; partir du bus</TD><TD>S=1</TD><TD>Bas</TD><TD>1.0.38</TD><TD>KNX D&#233;tecteur de mouvements 180</TD><TD>11/3/1</TD><TD>Luminosit&#233;</TD><TD>6</TD><TD>GroupValueWrite</TD><TD>&nbsp;</TD><TD>0D 46 | 27</TD><TD>&nbsp;</TD></TR><TR><TD>19</TD><TD>10/11/2021&#160;08:40:33,189</TD><TD>&#224; partir du bus</TD><TD>S=2</TD><TD>Bas</TD><TD>1.0.38</TD><TD>KNX D&#233;tecteur de mouvements 180</TD><TD>11/3/1</TD><TD>Luminosit&#233;</TD><TD>6</TD><TD>GroupValueWrite</TD><TD>&nbsp;</TD><TD>0D 46 | 27</TD><TD>&nbsp;</TD></TR><TR><TD>20</TD><TD>10/11/2021&#160;08:40:34,474</TD><TD>Arr&#234;ter</TD><TD>&nbsp;</TD><TD>&nbsp;</TD><TD>&nbsp;</TD><TD>&nbsp;</TD><TD>&nbsp;</TD><TD>&nbsp;</TD><TD>&nbsp;</TD><TD>&nbsp;</TD><TD>&nbsp;</TD><TD>L’enregistrement a &#233;t&#233; arr&#234;t&#233;.</TD><TD>&nbsp;</TD></TR></TABLE>

</BODY>
</HTML>`
![image](https://user-images.githubusercontent.com/5501935/141071045-29388828-7f18-4d7d-86c8-b660cbfc18f1.png)

What I do check or change?

Thank you for your help

**Comment by smurfix** [comment]
- please use the forum / mailing list for help
- which version are you using?
- I don't understand French, please set your system to English before submitting reports
- if this is a "two devices in programming mode" problem, that was fixed some time ago, please build current main / debian branch yourself
