### ISSUE TITLE
What version of pi will knxd run on?

### ISSUE THREAD

**Issue by Bergum** [knxd/knxd#524]
I have a raspberry pi (the first one), will knxd run on it?
I will be using it in the middle of a Hager rs232 knx and hass.io Home Assistant.

**Comment by da-anda** [comment]
I had HomeAssistant OS and a couple of add-ons (incl my own knxd docker add-on) running on the RPI2 and didn't have any issues, so I assume it should also work on a RPI1. You need to compile it for your OS ofc

**Comment by dallmair** [comment]
Pretty late to the party here, sorry 'bout that. Been using knxd on a Raspberry Pi 1 Model B+ with a TP-UART for a few years, so yes, knxd works on it flawlessly.

**Comment by dallmair** [comment]
@smurfix Please close as the question has been answered.
