### ISSUE TITLE
the link variable in knxd_args.cpp conflicts with the link() function

### ISSUE THREAD

**Issue by tru7** [knxd/knxd#527]
I was informed by OpenWRT maintainer that the link variable in src/server/knxd_args.cpp conflicts with the link() function in newer glibc versions.
They suggest to simply rename the variable to something else like link2.
Current reference: https://github.com/openwrt/packages/pull/17534/files#diff-0c01beef90d02c51e7e82da0cbc5d1d46d2027531c3efc40f1fa003f77cb42ad

**Comment by mhaehnel** [comment]
I opened a PR for a fix that worked for me. I went with knx_link since the 2 seems somewhat random for me. It is not another variant of the link function, which the 2 would otherwise indicate for me.

**Comment by mike-kfed** [comment]
I ran into this on gentoo, knxd 0.14.53 doesn't build anymore there, since glibc 2.34 is default. Can you please release a new version with that fix included? building from master works.
