### ISSUE TITLE
error while build in Debian

### ISSUE THREAD

**Issue by bigblue1735** [knxd/knxd#53]
Hi, i got an error while compile the project.

dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../knxd_0.9.0.orig.tar.{bz2,gz,lzma,xz}
dpkg-buildpackage: error: dpkg-source -b knxd gave error exit status 255

After updating the "debian/source/format" from "quilt" to "native". After this update the build begin, but failed with the following command:
configure: exit 2
dh_auto_configure: ./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --libexecdir=${prefix}/lib/knxd --disable-maintainer-mode --disable-dependency-tracking --enable-usb --enable-eibnetip --enable-eibnetiptunnel --enable-eibnetipserver --enable-groupcache --enable-tpuart --enable-ft12 returned exit code 2
make[1]: *** [override_dh_auto_configure] Error 25
make[1]: Leaving directory `/usr/local/src/knxd'
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by smurfix** [comment]
On 25.03.2015 23:50, bigblue1735 wrote:
>
> Hi, i got an error while compile the project.
>
>
You want to use the "-b" option to dpkg-buildpackage (or debuild).

-- 
-- Matthias Urlichs

**Comment by bigblue1735** [comment]
The "-b" option fix the issue with quilt, but still the same error during compilation.

**Comment by bigblue1735** [comment]
Sorry for my post. I tried it on a fresh installed debian system and it worked with the -b option. Please close this issue. I have to check what will be the problem on my current ubuntu system.

Sorry for requesting this issue.
