### ISSUE TITLE
TPUART USB interface not found under /dev/knx1

### ISSUE THREAD

**Issue by xxxLukskyxxx** [knxd/knxd#533]
Hello,

I try to setup a knxd on an debian system.
I use a TPUART USB interface from Busware.de and follow the steps in the manual.
But the device can't be found with "ls -lL /dev/knx1".

Does anybody have an idea what's wrong?

That's the TPUART Device:
looking at parent device '/devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4.2':
    KERNELS=="1-4.2"
    SUBSYSTEMS=="usb"
    DRIVERS=="usb"
    ATTRS{devnum}=="4"
    ATTRS{devpath}=="4.2"
    ATTRS{idProduct}=="000a"
    ATTRS{idVendor}=="2e8a"
    ATTRS{manufacturer}=="busware.de"
    ...

/etc/udev/rules.d/70-knxd.rules:
ACTION=="add", SUBSYSTEM=="tty", ATTRS{idVendor}=="000a", ATTRS{idProduct}=="2e8a", KERNELS=="1-4.2", SYMLINK+="knx1", OWNER="knxd"

/etc/knxd.conf:
KNXD_OPTS="-e 0.0.1 -E 0.0.2:8 -u /tmp/eib -b tpuarts:/dev/knx1"

Thanks for every help!  :)

**Comment by smurfix** [comment]
You seems to have mixed up "product" and "vendor" IDs.

**Comment by xxxLukskyxxx** [comment]
Wow... I spend more than two hours to fix the problem. Big thank you!
