### ISSUE TITLE
KNXD Link down terminating error.

### ISSUE THREAD

**Issue by berhankanbur** [knxd/knxd#535]
Hello, first of all apologies for my bad english.

I have an ABB USB/S1.2 USB device.
I installed KNXd on HomeAssistant. I made the necessary configurations, but unfortunately I cannot establish knx communication.

I'm getting the "Linkdown, terminating" warning as in the photo.

For example via ETS 5 or HomeAssistant
When I send the turn on command to 1/0/1, nothing happens when the light should be turned on.

My configuration and the error I get are attached.

![yapilandirma](https://user-images.githubusercontent.com/64873540/169402689-5abd1f88-0d30-40c7-b4bc-2b2785a1b057.png)

![Capture](https://user-images.githubusercontent.com/64873540/169402694-b4bdd159-0478-4645-94f9-37ee05325bc0.PNG)

**Comment by smartheit** [comment]
Hello,
I get a link down, terminating failure too. But this occurs after knxd has run for weeks or even months non-stop. However, it does not recover. So what I have to do is to restart knxd.
Further debug hints are very welcome.

```
knxd smartheit: E00000064: [16:router] router: setup router: failed
knxd smartheit: F00000105: [11:B.ipt] Link down, terminating
knxd smartheit: F00000105: [ 4:server] Link down, terminating
knxd smartheit: N00000128: [ 1:main] Shutting down.
```

I need to restart knxd:
```
2022-09-09 04:33:46,250 CRIT Server 'unix_http_server' running without any HTTP authentication checking
knxd smartheit: I00000131: [ 1:main] 0.14.54: /usr/bin/knxd /etc/knxd.ini
knxd smartheit: I00000129: [ 1:main] Connected: cfg:B.ipt.
knxd smartheit: I00000129: [ 1:main] Connected: cfg:server.
knxd smartheit: N00000127: [18:router.pace_] The 'pace' filter without a queue acts globally.
```

And than it works again

The knxd.ini is:

```
[A.single]
address = 15.15.255
filter = single

[B.ipt]
driver = ipt
#filters = log,A.single
filters = A.single
ip-address = 192.168.178.156

[debug-main]
error-level = 0x9

[debug-server]
name = mcast:knxd

[main]
addr = 1.0.230
client-addrs = 1.0.231:8
connections = server,B.ipt
debug = debug-main
name = knxd smartheit
pidfile = /var/run/knxd.pid

[server]
debug = debug-server
discover = true
router = router
server = ets_router
tunnel = tunnel

```

**Comment by smartheit** [comment]
I tracked it a bit further down:
knxd is connected to a Hager KNX gateway using Ethernet. There was a short network down and knxd was not able to recover.
Only restarting knxd helps.

**Comment by cyberatz** [comment]
Same issue. It's independent of uptime and seems to be reliably triggered by when the gateway (in my case, also a Hager KNX gateway) becomes unavailable (either due to reboot/power outage on GW).

**Comment by jonzyk** [comment]
Almost same here with an ABB IP Gateway, KNXD frequently terminates after a Network unreachable (once every day).
SystemD is setup to restart automatically KNXD which work quite good. I have to setup a automatic task to reload the OpenHAB KNX module.
As I have the same behavior with OpenHAB it is not able to recover from a network failure, is it something with KNX over IP ?

**Comment by smartheit** [comment]
openHAB recovers at my side. Meaning as soon as KNXD is restarted after some time OH accesses the KNX bus again.
I need now to "tinker" and write a rule which is restarting KNXD once there are no updates from a KNX weather station.
For me this is a kind of critical as I have knxd running on three sides and on two I have a KNX IP Gateway showing this phenomena.
I like knxd as it is slime and efficient C++ code. There is an alternative out there called Calimero:
https://github.com/calimero-project
However, it is written in Java :-( 
Has somebody tried it?

**Comment by smurfix** [comment]
Writing an error-blocking filter for knxd that can restart a single module (as long as it's a single link and not the UDP server) should be straightforward.

I'll look into it.

**Comment by smurfix** [comment]
… umm, looking at this again, you seem to have missed the fact that there already is a "retry" filter in knxd.

I'd suggest that you use it. 😎

**Comment by smartheit** [comment]
Hi smurfix, 
this sounds very good.
Can you please give an example how to add it to the ini?

So the retry filter should be set on the ipt driver I guess? According to the doc there is an option **retry-delay**. So I guess every 10 minutes would be a good option in case there was a LAN failure. It is not clear to me how to pass this option to the filter section.



```
[A.single]
address = 15.15.255
filter = single

[B.ipt]
driver = ipt
#filters = log,A.single
filters = A.single,**retry**
ip-address = 192.168.178.156

[debug-main]
error-level = 0x9

[debug-server]
name = mcast:knxd

[main]
addr = 1.0.230
client-addrs = 1.0.231:8
connections = server,B.ipt
debug = debug-main
name = knxd
pidfile = /var/run/knxd.pid

[server]
debug = debug-server
discover = true
router = router
server = ets_router
tunnel = tunnel
```

**Comment by smurfix** [comment]
Nb, why do you set the address for the "single" filter to the broadcast address? ideally that filter is for using the address that the remote side gives you, and since `ipt` does exactly that you should be able to just not use that option.

**Comment by smartheit** [comment]
Thanks for the hint. I removed it. The new config is:
```
[A.single]
filter = single

[A.retry]
filter = retry
retry-delay = 60.0
max-retries = 0

[B.ipt]
driver = ipt
#filters = log,A.single
filters = A.single,A.retry
ip-address = 192.168.178.156

[debug-main]
error-level = 0x9

[debug-server]
name = mcast:knxd

[main]
addr = 1.0.230
client-addrs = 1.0.231:8
connections = server,B.ipt
debug = debug-main
name = knxd smartheit
pidfile = /var/run/knxd.pid

[server]
debug = debug-server
discover = true
router = router
server = ets_router
tunnel = tunnel
```

I cannot force a network timeout as knxd is running at a remote side. Maybe jonzyk or cyberatz can test it (unplugging LAN cable)

**Comment by smurfix** [comment]
> Is it possible to bind the socket to 0.0.0.0?

You cannot do multicasting without telling the system which interface to use for sending them.

> when USB is used to connect to bus it should not stop working

It does stop working when you disconnect the LAN wire because, surprise, you can no longer talk to it.

There's currently no provision for resurrecting a failed server. If you need that, right now the best way is to run two `knxd` instances – one to handle USB and local clients, the other to handle network connections. They can talk to each other via the "ip:" driver on localhost.

Alternately, stop disconnecting network interfaces. :-P If that's not feasible, you can set your default route to a bridge interface and bind your "real" network interface to it, that way the interface KNXD uses stays up when you pull the plug.

**Comment by Race666** [comment]
> You cannot do multicasting without telling the system which interface to use for sending them.

It's possible. Set the source address to 0.0.0.0 then the routing table decides which interface (and source address) is used for sending the packet:
`#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
struct in_addr localInterface;
struct sockaddr_in groupSock;
int sd;
char databuf[32] = "TEST!";
int datalen = sizeof(databuf);
int main (int argc, char *argv[ ])
{
    sd = socket(AF_INET, SOCK_DGRAM, 0);
    if(sd < 0)
    {
      perror("Opening datagram socket error");
      exit(1);
    }
    memset((char *) &groupSock, 0, sizeof(groupSock));
    groupSock.sin_family = AF_INET;
    groupSock.sin_addr.s_addr = inet_addr("224.1.1.1");
    groupSock.sin_port = htons(6666);
    localInterface.s_addr = inet_addr("0.0.0.0");
    if(setsockopt(sd, IPPROTO_IP, IP_MULTICAST_IF, (char *)&localInterface, sizeof(localInterface)) < 0)
    {
      perror("Setting local interface error");
      exit(1);
    }
	for(;;)
	{
		if(sendto(sd, databuf, datalen, 0, (struct sockaddr*)&groupSock, sizeof(groupSock)) < 0)
		  perror("Sending datagram message error");
		else
		  printf("Sending datagram message...OK\n");
		printf("Press Any Key to Continue\n");
		getchar();
	}
    return 0;
}

`
Routing table
`Kernel-IP-Routentabelle
Ziel            Router          Genmask         Flags Metric Ref    Use Iface
default         192.168.178.1       0.0.0.0     UG    0      0        0 enp0s3
link-local      0.0.0.0         255.255.0.0     U     1000   0        0 enp0s8
192.168.178.0   0.0.0.0         255.255.255.0   U     0      0        0 enp0s3
192.168.56.0    0.0.0.0         255.255.255.0   U     100    0        0 enp0s8
`
Send Packet
`michael@deb:~# gcc sendmulticast.c -o sendmulticast
michael@deb:~# ./sendmulticast
Sending datagram message...OK
Press Any Key to Continue

`
On the wire
`tcpdump: listening on enp0s3, link-type EN10MB (Ethernet), snapshot length 262144 bytes
07:50:50.866440 IP (tos 0x0, ttl 1, id 8255, offset 0, flags [DF], proto UDP (17), length 1052)
    192.168.178.174.48964 > 224.1.1.1.6666: [bad udp cksum 0x92da -> 0xc734!] UDP, length 1024
	
`
Change routing
`route del default	
route add default gw 192.168.56.1 enp0s8`

and packet is send from the other interface
`tcpdump: listening on enp0s8, link-type EN10MB (Ethernet), snapshot length 262144 bytes
08:16:45.094755 IP (tos 0x0, ttl 1, id 38102, offset 0, flags [DF], proto UDP (17), length 44)
    192.168.56.113.45836 > 224.1.1.1.6666: [bad udp cksum 0xda45 -> 0x8ff1!] UDP, length 16
`
This would avoid the socket from being destroyed and would survive a link up->down->up.

**Comment by smurfix** [comment]
Yes, but as soon as the address vanishes and there no longer is a default route you still get an error.

**Comment by Race666** [comment]
That's true. But it's simply an "Network unreachable" error and this error goes away if the LAN connection is reestabished. I think knxd should not go down due to a "Network unreachable" error.

**Comment by jonzyk** [comment]
> I cannot force a network timeout as knxd is running at a remote side. Maybe jonzyk or cyberatz can test it (unplugging LAN cable)

I was still using the old style configuration, switched ini file now and added the filters.
Tested this one since 2 weeks and no more restart of KNXD, I have some "Communication error" in KNXD logs and it reconnects.
Thank you.
