### ISSUE TITLE
KND stops if LAN disconneted

### ISSUE THREAD

**Issue by martinmoravek** [knxd/knxd#546]
Hi,
I’m using KNX integration in HA with knxd addon to connect to KNX bus. HA server uses USB interface to connect to KNX.

Everything works fine until I remove network cable from HA server. In that moment knxd looses network connetion and shuts down and the connection to KNX bus is broken.

Any advice how to solve this issue?

I want to stay connected from HA to KNX bus even the network cable is not connected to the server.

thanks

**Comment by smartheit** [comment]
I guess it is the same as issue #535

**Comment by smurfix** [comment]
Yeah. Continued there.
