### ISSUE TITLE
compilation breakes with fmtlib/fmt >= 10.0.0

### ISSUE THREAD

**Issue by tru7** [knxd/knxd#548]
When using fmtlib/fmt >= 10.0.0 compilation of knxd fails for eibnetserver.cpp with this error:
/var/local/truniger/lede/staging_dir/target-mips_24kc_musl/usr/include/fmt/core.h:1567:7: error: static assertion failed: Cannot for         mat an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1567 |       formattable,
      |       ^~~~~~~~~~~

When reporting to https://github.com/fmtlib/fmt the maintainer replied:
The change is intentional, quoting the changelog:

    Removed deprecated implicit conversions for enums and conversions to primitive types for compatibility with std::format and to prevent potential ODR violations. Use format_as instead.

If you want to migrate to version 10 then you'll need to apply one of the fixes mentioned above (make ConnType formattable)

The suggested fixes:
So the way to fix the error is to either provide an explicit conversion to int (or whatever the underlying type of that particular enum is):

int format_as(ConnType t) { return t; }

or convert the argument to the underlying type at the call site using fmt::underlying, std::to_underlying or a cast, e.g.

fmt::printf("%d", fmt::underlying(t));

**Comment by tru7** [comment]
More comment from the author of fmtlib/fmt
>     Now the knxd project and all others are forced to put variants for different fmtlib/fmt versions in their source code, right?

> No, because both solutions (format_as and underlying) work with older versions of {fmt}. The only difference is that the newer version requires them rather than just allows.

**Comment by tru7** [comment]
I'll generate a pull request and you may check if it make sense. The author of fmtlib/fmt said the additional format_as also work with older versions of fmt so conditionals should not be needed (see citation above).

**Comment by tru7** [comment]
with changes of https://github.com/knxd/knxd/pull/549 compilation works fine using fmt >= 10.0.0
this is with the assumption that all conversions to int are OK - I was not able to test the result yet

**Comment by StefanTT** [comment]
How about merging this pull request? fmt >= 10 becomes more widespread.

**Comment by cjk** [comment]
Yes, Archlinux is already at 10.1.0 currently, i.e. KNXD no longer works on newer / related systems.
