### ISSUE TITLE
build does not work with Ubuntu 12.04 (LTS)

### ISSUE THREAD

**Issue by bigblue1735** [knxd/knxd#55]
Hi. I tried to build the package on Ubuntu 12.04 but get an error whlie compile. I tested it on Ubuntu 14.04 and the current debian and it worked very well. There is only a problem with Ubuntu 12.04. So it looks like there is a problem with a version of a depending package. I have no idea what will be the problem. If you need more information, please let me know.

I know the version of Ubuntu is old and will support only until 2017, but it would be very helpfull for me to find the problem and resolve it.

Here is the result of the "dpkg-buildpackage -b" command:
# define HAVE_TPUARTs 1
# define HAVE_EIBNETIP 1
# define HAVE_EIBNETIPTUNNEL 1

configure: exit 1
dh_auto_configure: ./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --libexecdir=${prefix}/lib/knxd --disable-maintainer-mode --disable-dependency-tracking --enable-usb --enable-eibnetip --enable-eibnetiptunnel --enable-eibnetipserver --enable-groupcache --enable-tpuart --enable-ft12 returned exit code 1
make[1]: **\* [override_dh_auto_configure] Fehler 25
make[1]: Verlasse Verzeichnis '/usr/local/src/knxd/knxd'
make: **\* [build] Fehler 2
dpkg-buildpackage: Fehler: Fehler-Exitstatus von debian/rules build war 2

**Comment by RichiH** [comment]
I don't have Ubuntu to test, but no matter what the (reasonable) fix, it
will be possible to support it in a branch.

**Comment by Morg42** [comment]
I get a similar (?) error when trying to build on Debian Squeeze 6.0.10. "dpkg-buildpackage -b" results in

[...]
#define HAVE_TPUARTs 1
#define HAVE_EIBNETIP 1
#define HAVE_EIBNETIPTUNNEL 1

configure: exit 1
dh_auto_configure: ./configure --build=i486-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --libexecdir=${prefix}/lib/knxd --disable-maintainer-mode --disable-dependency-tracking --enable-usb --enable-eibnetip --enable-eibnetiptunnel --enable-eibnetipserver --enable-groupcache --enable-tpuart --enable-ft12 returned exit code 1
make[1]: *** [override_dh_auto_configure] Error 9
make[1]: Leaving directory `/home/sh/src/knxd'
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

Here I get error 9, though I can't identify that at the moment...

**Comment by sr-verde** [comment]
Same here. Get:  make[1]: *** [override_dh_auto_configure] Fehler 25

**Comment by smurfix** [comment]
Please re-try with the current master.

**Comment by bmxp** [comment]
Hi,
just tested the compilation on Ubuntu 14.04.4 (no desktop) and the result of the last displayed lines is as follows:
---------------------------------------------------------------------------------------------
configure: exit 1
dh_auto_configure: ./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --libexecdir=${prefix}/lib/knxd --disable-maintainer-mode --disable-dependency-tracking --enable-usb --enable-eibnetip --enable-eibnetiptunnel --enable-eibnetipserver --enable-groupcache --enable-ft12 --enable-pei16s --enable-ncn5120 --enable-tpuarts --enable-dummy returned exit code 1
make[1]: *** [override_dh_auto_configure] Fehler 25
make[1]: Verzeichnis »/home/smarthome/knxd« wird verlassen
make: *** [build] Fehler 2
dpkg-buildpackage: Fehler: Fehler-Exitstatus von debian/rules build war 2
---------------------------------------------------------------------------------------------

Earlier upstream I could see the following output:
---------------------------------------------------------------------------------------------
configure:16983: checking for systemd/sd-daemon.h
configure:16983: result: yes
configure:16986: checking for sd_listen_fds in -lsystemd-daemon
configure:17020: result: yes
configure:17026: checking for sd_listen_fds in -lsystemd
configure:17060: result: no
configure:17078: checking for SYSTEMD
configure:17085: $PKG_CONFIG --exists --print-errors "libsystemd-daemon libsystemd"
Package libsystemd was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsystemd.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsystemd' found
configure:17088: $? = 1
configure:17102: $PKG_CONFIG --exists --print-errors "libsystemd-daemon libsystemd"
Package libsystemd was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsystemd.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsystemd' found
configure:17105: $? = 1
configure:17119: result: no
No package 'libsystemd' found
configure:17135: error: Package requirements (libsystemd-daemon libsystemd) were not met:

No package 'libsystemd' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SYSTEMD_CFLAGS
and SYSTEMD_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
---------------------------------------------------------------------------------------------
For me it seems as if the knxd can only be built with systemd running on the system.
Unfortunately Ubuntu won't support systemd by default installation until version 16.x
It seems as if only Debian with version 8.x does support knxd at the moment.
I would like to help but I'm not a programmer and have no idea what to do to support you...

**Comment by tru7** [comment]
You make use this commands to build your knxd
# git clone https://github.com/knxd/knxd
# cd knxd
# ./bootstraph.sh && ./configure --disable-systemd && make && make install
Adjus on your needs

**Comment by bmxp** [comment]
Thanks for the build commands. So I've broken it down to pieces after having new errors. 

After executing 'make install' the result is:
``` 
make  install-recursive
make[1]: Verzeichnis »/home/smarthome/knxd« wird betreten
Making install in .
make[2]: Verzeichnis »/home/smarthome/knxd« wird betreten
make[3]: Verzeichnis »/home/smarthome/knxd« wird betreten
make[3]: Für das Ziel »install-exec-am« ist nichts zu tun.
make[3]: Für das Ziel »install-data-am« ist nichts zu tun.
make[3]: Verzeichnis »/home/smarthome/knxd« wird verlassen
make[2]: Verzeichnis »/home/smarthome/knxd« wird verlassen
Making install in src
make[2]: Verzeichnis »/home/smarthome/knxd/src« wird betreten
Making install in common
make[3]: Verzeichnis »/home/smarthome/knxd/src/common« wird betreten
make[4]: Verzeichnis »/home/smarthome/knxd/src/common« wird betreten
make[4]: Für das Ziel »install-exec-am« ist nichts zu tun.
 /bin/mkdir -p '/usr/local/include'
 /usr/bin/install -c -m 644 eibloadresult.h '/usr/local/include'
/usr/bin/install: reguläre Datei »/usr/local/include/eibloadresult.h“ kann nicht angelegt werden: Keine Berechtigung
make[4]: *** [install-dist_includeHEADERS] Fehler 1
make[4]: Verzeichnis »/home/smarthome/knxd/src/common« wird verlassen
make[3]: *** [install-am] Fehler 2
make[3]: Verzeichnis »/home/smarthome/knxd/src/common« wird verlassen
make[2]: *** [install-recursive] Fehler 1
make[2]: Verzeichnis »/home/smarthome/knxd/src« wird verlassen
make[1]: *** [install-recursive] Fehler 1
make[1]: Verzeichnis »/home/smarthome/knxd« wird verlassen
make: *** [install] Fehler 2
```
There seems to be another thing that does not work like it should. I've tried it again using the sudo prefix and it runs through. 
Well unfortunately the make install does not install the knxd for running. I do not find anything outside the ~/knxd directory which actually runs the knxd. No start/stop scripts in /etc/default or in other locations. What needs further to be done to run the knxd?
(I am aware that I could just set up a brand new Debian Jessie which brings systemd)

**Comment by smurfix** [comment]
Hi,
> After executing 'make install' the result is: 
debian/rules will run "make install" with a prefix that installs in
./debian/tmp which is packaged into the .deb file(s) you install with dpkg.
If you run it manually, *of course* you need "sudo". That's a feature.

This is not a problem of knxd -- every other properly-written Makefile
does the exact same thing.

-- 
-- Matthias Urlichs

**Comment by tru7** [comment]
@bmxp you have to create your own start script if you build it this way
