### ISSUE TITLE
knxd: write group address main group 14/x/x 1: result: 0/0/1 0

### ISSUE THREAD

**Issue by getcom** [knxd/knxd#556]
Version: knxd 0.14.56.2
Kernel: Linux 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
OS: Debian 11.7
HW: Raspberry Pi 4 Model B Rev 1.4
Severity: High
KNXD_OPTS: "--error=5 -e 0.6.0 -E 0.6.1:8 -u /tmp/knxd -b ip: --GroupCache --send-delay=70 -T -D --Server=224.0.23.12:3671 -B log"

Steps to reproduce:
/usr/lib/knxd/groupswrite ip:127.0.0.1 14/4/0 1
/usr/lib/knxd/groupswrite ip:127.0.0.1 15/1/8 1
/usr/lib/knxd/groupswrite ip:127.0.0.1 16/8/5 1
Group monitor result from knxd address: **0/0/1 0**

Current behavior:
Unrelated which group address from main group >13 will be used, knxd sends group/value: 0/0/1 0.

Expected behavior:
Knxd should send all 32 main groups without replacing the group address or changing the value.

**Comment by dallmair** [comment]
As of version 0.14.67.1, this works mostly fine already:

![image](https://github.com/user-attachments/assets/e086c12b-f676-40a5-9270-aadd4e2daddd)

Please note that 16/8/5 is an invalid group address, though. knxtool does not reject that but treats it as 0016 (parses the first part as hex number) currently. To fix this, I've created PR #600. Tested the new behavior:

![image](https://github.com/user-attachments/assets/c5142c42-b986-4e85-bc68-5c449d9056ac)
