### ISSUE TITLE
Opening /dev/ttyAMA0 failed: Permission denied

### ISSUE THREAD

**Issue by tunm1228** [knxd/knxd#561]
<img width="919" alt="image" src="https://github.com/knxd/knxd/assets/42457760/496f38f7-0705-4398-a523-1478172c2de2">

**Comment by smurfix** [comment]
Not a knxd bug. Fix those permissions. There's an udev line for it but it's commented off because, surprise, not everybody who runs knxd on a Raspberry Pi does so by connecting it to the on-board TTY.

**Comment by tunm1228** [comment]
Please let me know this case
<img width="991" alt="image" src="https://github.com/knxd/knxd/assets/42457760/c5174117-4381-43f3-aeb0-c822c8196a24">
