### ISSUE TITLE
The 'pace' filter without a queue acts globally.

### ISSUE THREAD

**Issue by tunm1228** [knxd/knxd#562]
` knxd -t1023 -f9 -DRTS -e 1.1.128 -E 1.1.129:1 -b tpuarts:/dev/ttyAMA0`
Layer 3 [ 4:server/Server      0.000] registerLink: 4:server
Layer 3 [ 4:server/Server       0.000] Start: cfg:server
Layer 5 [ 4:server/Server       0.000] down => >up
Layer 8 [ 4:server/Server       0.001] Open
Layer 0 [ 4:server/Server       0.001] Open
Layer 0 [ 4:server/Server       0.001] Opened
Layer 8 [17:router/driver       0.001] OpenD
Layer 8 [17:router/driver       0.001] OpenedD
N00000127: [18:router.pace_] The 'pace' filter without a queue acts globally.
Layer 3 [16:router/ConnC        0.002] registerLink: 16:router_16
Layer 3 [16:router/ConnC        0.002] Start: cfg:router
Layer 5 [16:router/ConnC        0.002] down => >up
Layer 5 [16:router/ConnC        0.002] Starting
Layer 5 [16:router/ConnC        0.002] >up => up
Layer 4 [16:router/ConnC        0.002] link state changed: up
Layer 5 [16:router/ConnC        0.002] Started
Layer 4 [16:router/ConnC        0.002] link state changed: up
Layer 8 [ 4:server/Server       0.002] Opened
Layer 5 [ 4:server/Server       0.002] >up => up
Layer 4 [ 4:server/Server       0.002] link state changed: up
Layer 5 [ 4:server/Server       0.002] Started
Layer 4 [ 4:server/Server       0.002] link state changed: up
F00000105: [11:A.tpuarts] Link down, terminating
Layer 4 [16:router/ConnC        2.491] R Stopping
Layer 5 [16:router/ConnC        2.491] up => >down
Layer 5 [16:router/ConnC        2.491] L Stopping
Layer 5 [16:router/ConnC        2.492] >down => down
Layer 4 [16:router/ConnC        2.492] link state changed: down
Layer 4 [16:router/ConnC        2.492] link state changed: down
Layer 4 [ 4:server/Server       2.492] R Stopping
Layer 5 [ 4:server/Server       2.492] up => >down
Layer 5 [16:router/ConnC        2.492] L Stopping
Layer 3 [16:router/ConnC        2.492] unregisterLink: router_16
Layer 0 [ 4:server/Server       2.492] Close D
Layer 5 [ 4:server/Server       2.492] >down => down
Layer 4 [ 4:server/Server       2.492] link state changed: down
Layer 4 [ 4:server/Server       2.492] link state changed: down
Layer 8 [17:router/driver       2.492] CloseD
Layer 4 [ 4:server/Server       2.492] is down
Layer 8 [ 4:server/Server       2.492] Close E

**Comment by smurfix** [comment]
This has nothing to do with the "pace" filter, the message is just a notification. You simply cannot talk to the TPUART. You either didn't plug the KNX cable in or you still have a console or a getty running on the serial port. Not something knxd can fix.

**Comment by tunm1228** [comment]
I plugged in KNX but it's not connected yet
Can you elaborate more on this situation where getty runs on the serial port?

**Comment by smurfix** [comment]
If the bus is not powered, TPUART will not work.

How to disable the serial console and the getty process running on ttyAMA0 is extensively documented elsewhere.

**Comment by tunm1228** [comment]
root@raspberrypi:~# ls -ahl /dev/ttyKNX1
_lrwxrwxrwx 1 root root 7 Dec 12 03:17 /dev/ttyKNX1 -> ttyAMA0_
root@raspberrypi:~# ls -ahl /dev/ttyAMA0
_crw-rw---- 1 knxd dialout 204, 64 Dec 12 03:49 /dev/ttyAMA0_

**Comment by tunm1228** [comment]
> If the bus is not powered, TPUART will not work.
> 
> How to disable the serial console and the getty process running on ttyAMA0 is extensively documented elsewhere.

I've used
# Disable serial console
systemctl disable serial-getty@ttyAMA0.service > /dev/null 2>&1
systemctl disable serial-getty@ttyS0.service > /dev/null 2>&1
systemctl disable serial-getty@.service> /dev/null 2>&1

**Comment by smurfix** [comment]
Don't forget the serial console= stanza in `/boot/cmdline.txt` (or `/boot/firmware`).

**Comment by tunm1228** [comment]
sudo nano /boot/cmdline.txt

delete the following arguments

console=serial0,115200 console=tty1

**Comment by smurfix** [comment]
Well you can keep the tty1 part, that's the HDMI

**Comment by tunm1228** [comment]
you mean it: `console=tty1 root=PARTUUID=0370fef9-02 rootfstype=ext4 fsck.repair=yes rootwait`
