### ISSUE TITLE
How to change baud?

### ISSUE THREAD

**Issue by tunm1228** [knxd/knxd#563]
`Layer 0 [23:C.tpuart/TPU_ser   0.000] Opened /dev/ttyAMA0 with baud 19200`

**Comment by smurfix** [comment]
What kind of hardware do you have that can do more than 19200 baud?

In any case the TPUART sends and receives two bytes for every KNX byte, the KNX bus uses 9600 baud, so there's not much advantage of higher speed anyway.

**Comment by tunm1228** [comment]
I can't connect to knx so I want to change the baudrate to see if that's the cause?

**Comment by smurfix** [comment]
No it's not. The cause is *always* either that the KNX bus cable isn't plugged in and powered, or there's a console or a getty still on the serial port.

**Comment by tunm1228** [comment]
Can you tell me where to buy hardware to connect to knxd?

**Comment by tunm1228** [comment]
I soldered it myself but couldn't connect
<img width="605" alt="image" src="https://github.com/knxd/knxd/assets/42457760/1bb5a68d-7d98-4814-b8b9-33cb244a8bb7">
