### ISSUE TITLE
Prometheus / OpenMetrics metrics support

### ISSUE THREAD

**Issue by RichiH** [knxd/knxd#565]
@smurfix I know we had this conversation roughly a decade ago, but I can't find it any more... While I am running https://github.com/RichiH/knxd_exporter successfully, I'd still prefer a fully native way to get data into Prometheus and thus Grafana.

I'd be more than happy to help with designing the metrics format, and optionally a mapping from a list of addresses to names or .knxproject, maybe.

**Comment by hgehrts** [comment]
+1 from me. OpenTelemetry support would be awesome.

**Comment by smurfix** [comment]
Sorry, but no.

knxd is a router for KNX messages. It's strictly layer 2. It doesn't interpret or translate the contents of the messages it forwards.

Writing code that does this is fairly easy. Take xknx, a Python package that can send to your your time-series database of choice, and combine the two with ten lines of glue code.

Teaching knxd to do this would require roughly a month of work. Even learning enough Python to be able to do the above from scratch takes less than a week.
