### ISSUE TITLE
usb: --> url not supported: Success 

### ISSUE THREAD

**Issue by JoeRu** [knxd/knxd#57]
Hi all,

i did found some time to build and try to switch to knxd. But i run into several small things while trying to do so.

my test-environment
Raspi, Debian, MDT Technologies GmbH:KNX-USB Inteface - with the need to use the cEMI Patch in eibd

- Preferences in packages are not complete. I needed to add this two more: libusb-1.0-0-dev, debhelper
- dpkg-buildpackage fails when not using "-b" option.

- knxd -T -D -R --Server --listen-tcp=6730 -u --eibaddr=1.1.153 usb:1:4:1:0:0
fails with "url not supported: Success"
Same goes for:
/usr/local/bin/knxd -u -t 1023 usb:
url not supported: Success

So - usb is out of the box not enabled - or do i need another compile-option?

Regards,
Johannes

**Comment by Morg42** [comment]
regarding debhelper: see my comment to pull-request #60: debhelper ist not needed by knxd; it is needed to build it using dpkg-buildpackage (so is gcc...) I agree on libusb-1.0-0-dev.

**Comment by JoeRu** [comment]
Hi,
i did manage to get it to work with this options taken from eibd - one option is obsolete so.

./configure --enable-onlyeibd --enable-usb --enable-eibnetiptunnel --enable-eibnetipserver --enable-eibnetip
and a 
make
make install 

afterwards.
Maybe the readme should be enhanced and i have no clue why the default did not work for it.

From my side this ticket os ok.
Johannes
