### ISSUE TITLE
Lors d'un lgine scan ETS  . Chaque scan révèle que certains dispositifs disparaissent, et ce ne sont pas toujours les mêmes.

### ISSUE THREAD

**Issue by houssemmh7** [knxd/knxd#572]
Nous rencontrons actuellement un problème avec notre système KNX et nous vous serions reconnaissants de nous aider à le résoudre.
Nous avons 10 appareils connectés dans une configuration de ligne (sans coupleur). Bien que tous les appareils soient alimentés, nous rencontrons des problèmes de détection intermittents lorsque nous effectuons un balayage de la ligne. Chaque balayage révèle que certains appareils disparaissent, et ce ne sont pas toujours les mêmes.
Pour résoudre ce problème, nous avons pris les mesures suivantes :
1.	Nous avons remplacé le bloc d'alimentation, mais malheureusement, le problème persiste.
2.	Nous avons remplacé le câble de bus, mais le problème persiste.
3.	Nous avons confirmé que la longueur du câble est inférieure à 350 mètres. En outre, nous avons effectué des tests individuels sur les 10 appareils avec un câble court dans le bureau, mais nous avons malheureusement rencontré le même problème

**Comment by smurfix** [comment]
Sorry, but I don't speak French.
Also, this is not a support forum, much less a French-language one.
