### ISSUE TITLE
CAn we implement KNX Raspberry Pi HAT project with using KNX IP interface rather than KNX USB interface

### ISSUE THREAD

**Issue by Pavancherry12** [knxd/knxd#576]
Iam trying to implement KNX Raspberry Pi HAT project with using KNX IP interface rather than KNX USB interface ,Is it possible to implement this with KNX IP interface ?If yes ,can you help me with the procedure and modifications I Have to do in the KNX Raspberry Pi HAT procedure..

**Comment by smurfix** [comment]
What exactly do you want to do? I do not understand which problem you're trying to solve.

You don't need a HAT for either USB or IP, you simply plug the USB interface into the Pi, or the IP interface into your switch.

**Comment by Pavancherry12** [comment]
I'm working on implementing the KNX Raspberry Pi HAT project detailed at (https://hackaday.io/project/171850/instructions]. I've reached the stage where I need to add new specific rules for KNXD. According to the instructions, I need to edit the 80-knxd.rules file using:
#sudo nano /etc/udev/rules.d/80-knxd.rules
and add the following line:

ACTION=="add", SUBSYSTEM=="tty", ATTRS{id}=="your-attrs-id", KERNELS=="your-kernel-id", SYMLINK+="ttyKNX1", OWNER="knxd"
However, I am unsure which USB device I need to connect to the Raspberry Pi to retrieve the necessary attrs-id and kernel-id.

The instructions suggest using the following commands to obtain these IDs:
# For kernel id:
sudo udevadm info -a /dev/ttyAMA0 | grep KERNELS.*serial

# For attrs id:
sudo udevadm info -a /dev/ttyAMA0 | grep \{id\}

"Could you provide guidance on the specific USB device that should be connected to the Raspberry Pi for this purpose and confirm that the commands above are correct for retrieving the required information? Thank you for your prompt assistance."

**Comment by smurfix** [comment]
> However, I am unsure which USB device I need to connect to the Raspberry Pi to retrieve the necessary attrs-id and kernel-id.

?? what USB device? this board doesn't use USB. It connects to the Pi's UART.

This is already documented. Look for TPUART in the README and in `systemd/knxd.udev`.
