### ISSUE TITLE
Connect failed with error 25

### ISSUE THREAD

**Issue by ptorrent** [knxd/knxd#580]
Hello there !

I've this error when I try to connect knxd to my ip knx interface: 
Connect failed with error 25

That does that mean error 25?

Thanks for your help

**Comment by dallmair** [comment]
> Connect failed with error 25

Please note that the error code is in hex. It means "No More Unique Connections", i.e. the Tunneling server had unused tunnels available, but none with an unused address. In other words, each available tunnel would have used an address that is already in use by another tunnel, and that is not allowed.

More details:
* https://support.knx.org/hc/en-us/articles/4688187652114-There-are-no-more-unique-additional-addresses-available
* https://knx-user-forum.de/forum/%C3%B6ffentlicher-bereich/knx-eib-forum/knx-einsteiger/1849994-knx-gateway-meldet-there-are-no-more-unique-additional-addresses-available

**Comment by ptorrent** [comment]
Thanks !
