### ISSUE TITLE
PR suggestion: add --yes to Debian installer for unattended operation?

### ISSUE THREAD

**Issue by greiginsydney** [knxd/knxd#581]
Hi Matthias,

Would you support a PR for the Debian branch to make the installer auto-complete, without the two "Do you want to continue?" prompts?

https://github.com/knxd/knxd/blob/debian/install-debian.sh

<pre>
sudo apt-get install --no-install-recommends build-essential devscripts equivs <b>--yes</b>
</pre>

<pre>
sudo apt remove --autoremove knxd-build-deps <b>--yes</b>
</pre>

\- Greig.

**Comment by smurfix** [comment]
Sure, bring it on.

**Comment by greiginsydney** [comment]
Thanks
