### ISSUE TITLE
KNXD crashes with TPUART-USB-Light (NCN-ESP32 version)

### ISSUE THREAD

**Issue by JackyKNX** [knxd/knxd#594]
Hi,

I'm still having issues with knxd and the new TPUART-USB-Light (from busware.de).

Debian x64 and knxd updated yesterday to version 0.14.67.1

My knxd.conf: 

> KNXD_OPTS="--eibaddr=1.1.128 --client-addrs=1.1.30:8  -D -T -R -S -b tpuarts:/dev/knx1" 

After a few seconds knxd crashes and reports send timeout and link down, also not being able to bring the link up:

> Nov 20 12:15:04 orangepizero2 knxd[9631]: Layer 0 [24:A.tpuarts/log        46.824] Send(018): 80 9C 81 22 82 02 83 2E 84 03 85 D1 86 00 87 00 48 BF
> Nov 20 12:15:06 orangepizero2 knxd[9631]: Layer 8 [21:A.tpuarts/LowF       48.824] send timeout: retry
> Nov 20 12:15:06 orangepizero2 knxd[9631]: Layer 0 [24:A.tpuarts/log        48.824] Send(018): 80 9C 81 22 82 02 83 2E 84 03 85 D1 86 00 87 00 48 BF
> Nov 20 12:15:07 orangepizero2 knxd[9631]: Layer 0 [22:A.tpuarts/log        49.822] Stop
> Nov 20 12:15:07 orangepizero2 knxd[9631]: Layer 0 [24:A.tpuarts/log        49.823] Stop
> Nov 20 12:15:07 orangepizero2 knxd[9631]: Layer 0 [24:A.tpuarts/log        49.839] Errored
> Nov 20 12:15:07 orangepizero2 knxd[9631]: Layer 8 [21:A.tpuarts/LowF       49.839] state: wait > new
> Nov 20 12:15:07 orangepizero2 knxd[9631]: Layer 0 [22:A.tpuarts/log        49.839] Errored
> Nov 20 12:15:07 orangepizero2 knxd[9631]: Layer 6 [19:A.tpuarts/Conn       49.839] sendNext called, send_more set
> Nov 20 12:15:07 orangepizero2 knxd[9631]: Layer 6 [19:A.tpuarts/Conn       49.840] is OK
> Nov 20 12:15:07 orangepizero2 knxd[9631]: Layer 5 [19:A.tpuarts/Conn       49.840] up => error
> Nov 20 12:15:07 orangepizero2 knxd[9631]: Layer 4 [19:A.tpuarts/Conn       49.840] link state changed: error
> Nov 20 12:15:07 orangepizero2 knxd[9631]: Layer 6 [19:A.tpuarts/Conn       49.840] not up
> Nov 20 12:15:07 orangepizero2 knxd[9631]: Layer 6 [19:A.tpuarts/Conn       49.840] not up
> Nov 20 12:15:07 orangepizero2 knxd[9631]: F00000105: [19:A.tpuarts] Link down, terminating
> Nov 20 12:15:07 orangepizero2 knxd[9631]: Layer 4 [19:A.tpuarts/Conn       49.840] R Stopping
> Nov 20 12:15:07 orangepizero2 knxd[9631]: Layer 5 [19:A.tpuarts/Conn       49.840] error => >down
> Nov 20 12:15:07 orangepizero2 knxd[9631]: Layer 4 [19:A.tpuarts/Conn       49.840] link state changed: error
> Nov 20 12:15:07 orangepizero2 knxd[9631]: Layer 0 [22:A.tpuarts/log        49.841] Closing
> Nov 20 12:15:07 orangepizero2 knxd[9631]: Layer 2 [21:A.tpuarts/LowF       49.841] Close C
> Nov 20 12:15:07 orangepizero2 knxd[9631]: Layer 0 [24:A.tpuarts/log        49.841] Closing
> Nov 20 12:15:07 orangepizero2 knxd[9631]: Layer 2 [23:A.tpuarts/TPU_ser    49.841] Close F

I've attached full log file.
[knxd.zip](https://github.com/user-attachments/files/17829777/knxd.zip)

Anyone having same issue, any ideas how to solve?

thanks,
Jacek

**Comment by JackyKNX** [comment]
Hey, yes, I'm sure, no serial console enabled etc., I've also tested on Rasp3B with serial console disabled, same issues.  

BTW, it works like a charm (not a single failure for a few years) with old TP-UART (ATMEGA)...

**Comment by JackyKNX** [comment]
I replicated the issue on freshly installed RPI (Rasbian 64bit), same knxd version and configuration.
[knxd_rpi.zip](https://github.com/user-attachments/files/17831651/knxd_rpi.zip)

**Comment by mschulte** [comment]
Damn - i think i added a duplicated issue here: https://github.com/knxd/knxd/issues/595

pretty much looks similar to my problem.

**Comment by JackyKNX** [comment]
Hello Matthias, any chance for a fix? I can send you the light TPUART if this helps... Thanks.

**Comment by JackyKNX** [comment]
Hello Matthias, any chance for a fix? I can send you the light TPUART if this helps... Thanks.

**Comment by mschulte** [comment]
i managed to get it up and running.
see here: https://github.com/knxd/knxd/issues/595#issuecomment-2499042163

**Comment by smurfix** [comment]
Thanks for reporting back.

**Comment by JackyKNX** [comment]
I've tried the above  (#595) however it didn't help, I still receive the
[knxd_20241227.zip](https://github.com/user-attachments/files/18260121/knxd_20241227.zip)
 same errors - please see the log file.
