### ISSUE TITLE
KNXD crashes with tpuart (after receiving state 47)

### ISSUE THREAD

**Issue by mschulte** [knxd/knxd#595]
i'm using TPUART on raspberry pi and the latest source from debian-branch.

getty is disabled:
> admin@knxgw:~ $ ps axuw|grep 'getty.*AMA'
> admin      909  0.0  0.2   7448  1920 pts/0    S+   21:50   0:00 grep --color=auto getty.*AMA

i also added
```
dtoverlay=pi3-disable-bt
dtoverlay=disable-bt
enable_uart=1
```
to my `/boot/config.txt`

`/boot/cmdline.txt` is empty

I loose connection after receiving some information from the KNX bus (and getting state 47)
I don't know how to further proceed and debug that. Any ideas what could be the problem?

see logfile here:

```
admin@knxgw:~ $ /usr/bin/knxd -t1023 -e 1.1.10 -E 1.1.120:28 -D -T -R -S -b tpuarts:/dev/knx1
Layer 4 [ 1:main        0.000] initialized
Layer 4 [ 1:main        0.000] setting up
Layer 3 [ 4:server/Server      0.000] registerLink: 4:server
Layer 0 [14:A.tpuarts/log       0.001] Insert 13:LowF / 12:tpuart
Layer 0 [14:A.tpuarts/log       0.001] Setup
Layer 0 [16:A.tpuarts/log       0.001] Insert 15:TPU_ser / 13:LowF
Layer 0 [14:A.tpuarts/log       0.001] Filter single not found
Layer 0 [16:A.tpuarts/log       0.001] Setup
Layer 0 [16:A.tpuarts/log       0.001] Setup OK: yes
Layer 0 [14:A.tpuarts/log       0.001] Setup OK: yes
Layer 3 [11:A.tpuarts/Conn      0.001] registerLink: 11:A.tpuarts
Layer 4 [ 1:main                0.001] setup OK
Layer 4 [ 1:main                0.001] trigger going up
Layer 3 [11:A.tpuarts/Conn      0.001] Start: cfg:A.tpuarts
Layer 5 [11:A.tpuarts/Conn      0.001] down => >up
Layer 5 [11:A.tpuarts/Conn      0.001] Starting
Layer 0 [14:A.tpuarts/log       0.001] Start
Layer 0 [16:A.tpuarts/log       0.001] Start
Layer 0 [15:A.tpuarts/TPU_ser   0.001] Opened /dev/knx1 with baud 19200
Layer 2 [15:A.tpuarts/TPU_ser   0.002] Opened
Layer 2 [15:A.tpuarts/TPU_ser   0.002] Buffer Setup on fd 4
Layer 0 [16:A.tpuarts/log       0.002] Started
Layer 8 [13:A.tpuarts/LowF      0.002] state: new > start
Layer 0 [13:A.tpuarts/LowF      0.002] SendReset 01
Layer 0 [16:A.tpuarts/log       0.002] Send(001): 01
Layer 4 [11:A.tpuarts/Conn      0.002] link state changed: >up
Layer 3 [ 4:server/Server       0.002] Start: cfg:server
Layer 5 [ 4:server/Server       0.002] down => >up
Layer 8 [ 4:server/Server       0.002] Open
Layer 0 [ 4:server/Server       0.002] Open
Layer 0 [ 4:server/Server       0.002] Opened
Layer 8 [19:router/driver       0.002] OpenD
Layer 8 [19:router/driver       0.003] OpenedD
Layer 3 [18:router/ConnC        0.004] registerLink: 18:router_18
Layer 3 [18:router/ConnC        0.004] Start: cfg:router
Layer 5 [18:router/ConnC        0.004] down => >up
Layer 5 [18:router/ConnC        0.004] Starting
Layer 5 [18:router/ConnC        0.004] >up => up
Layer 4 [18:router/ConnC        0.004] link state changed: up
Layer 5 [18:router/ConnC        0.004] Started
Layer 4 [18:router/ConnC        0.004] link state changed: up
Layer 8 [ 4:server/Server       0.004] Opened
Layer 5 [ 4:server/Server       0.004] >up => up
Layer 4 [ 4:server/Server       0.004] link state changed: up
Layer 5 [ 4:server/Server       0.004] Started
Layer 4 [ 4:server/Server       0.004] link state changed: up
Layer 4 [ 1:main                0.004] going up triggered
Layer 4 [ 1:main                0.004] check start
Layer 4 [11:A.tpuarts/Conn      0.004] state is >up
Layer 4 [ 1:main                0.004] check end: want_up 1 some 1>1 all 0>0, going 1 up 2 down 0
Layer 0 [16:A.tpuarts/log       0.230] Recv(002): 47 47
Layer 8 [13:A.tpuarts/LowF      0.230] State: 47
Layer 8 [13:A.tpuarts/LowF      0.230] State: 47
Layer 0 [13:A.tpuarts/LowF      0.482] SendReset 01
Layer 0 [16:A.tpuarts/log       0.482] Send(001): 01
Layer 0 [16:A.tpuarts/log       0.710] Recv(013): 47 47 BC 11 15 35 00 E3 00 80 07 7B 6D
Layer 8 [13:A.tpuarts/LowF      0.710] State: 47
Layer 8 [13:A.tpuarts/LowF      0.710] State: 47
Layer 1 [13:A.tpuarts/LowF      0.710] RecvLP(011): BC 11 15 35 00 E3 00 80 07 7B 6D
Layer 0 [14:A.tpuarts/log       0.711] Recv L_Data low from 1.1.21 to 6/5/0 hops: 06 T_Data_Group A_GroupValue_Write 07 7B
Layer 8 [ 1:main                0.711] unknown addr 1.1.21
Layer 0 [16:A.tpuarts/log       0.977] Recv(008): BC 11 14 2D 00 E3 00 80
Layer 0 [13:A.tpuarts/LowF      0.982] SendReset 01
Layer 0 [16:A.tpuarts/log       0.982] Send(001): 01
Layer 0 [16:A.tpuarts/log       0.983] Recv(003): 06 FD F3
Layer 1 [13:A.tpuarts/LowF      0.983] RecvLP(011): BC 11 14 2D 00 E3 00 80 06 FD F3
Layer 0 [14:A.tpuarts/log       0.983] Recv L_Data low from 1.1.20 to 5/5/0 hops: 06 T_Data_Group A_GroupValue_Write 06 FD
Layer 8 [ 1:main                0.983] unknown addr 1.1.20
Layer 0 [16:A.tpuarts/log       1.211] Recv(002): 47 47
Layer 8 [13:A.tpuarts/LowF      1.211] State: 47
Layer 8 [13:A.tpuarts/LowF      1.211] State: 47
Layer 8 [13:A.tpuarts/LowF      1.483] state: in_reset > error
Layer 0 [16:A.tpuarts/log       2.484] Stop
Layer 0 [16:A.tpuarts/log       2.484] Errored
Layer 8 [13:A.tpuarts/LowF      2.484] state: error > new
Layer 0 [14:A.tpuarts/log       2.484] Errored
Layer 5 [11:A.tpuarts/Conn      2.484] >up => error
Layer 4 [11:A.tpuarts/Conn      2.484] link state changed: error
Layer 4 [ 1:main                2.484] check start
Layer 4 [ 1:main                2.484] check end: want_up 1 some 1>1 all 0>0, going 0 up 2 down 1
F00000105: [11:A.tpuarts] Link down, terminating
Layer 4 [ 1:main                2.484] trigger Going down
Layer 4 [18:router/ConnC        2.484] R Stopping
Layer 5 [18:router/ConnC        2.484] up => >down
Layer 5 [18:router/ConnC        2.484] L Stopping
Layer 5 [18:router/ConnC        2.484] >down => down
Layer 4 [18:router/ConnC        2.485] link state changed: down
Layer 4 [18:router/ConnC        2.485] link state changed: down
Layer 4 [11:A.tpuarts/Conn      2.485] R Stopping
Layer 5 [11:A.tpuarts/Conn      2.485] error => >down
Layer 4 [11:A.tpuarts/Conn      2.485] link state changed: error
Layer 4 [ 4:server/Server       2.485] R Stopping
Layer 5 [ 4:server/Server       2.485] up => >down
Layer 5 [18:router/ConnC        2.485] L Stopping
Layer 3 [18:router/ConnC        2.485] unregisterLink: router_18
Layer 0 [ 4:server/Server       2.485] Close D
Layer 5 [ 4:server/Server       2.485] >down => down
Layer 4 [ 4:server/Server       2.485] link state changed: down
Layer 4 [ 4:server/Server       2.485] link state changed: down
Layer 4 [ 1:main                2.485] check start
Layer 8 [19:router/driver       2.485] CloseD
Layer 4 [ 4:server/Server       2.485] is down
Layer 4 [ 1:main                2.485] check end: want_up 0 some 1>0 all 0>0, going 0 up 0 down 2
Layer 4 [ 1:main                2.486] down
Layer 4 [ 1:main                2.486] deleting
Layer 0 [14:A.tpuarts/log       2.486] Closing
Layer 2 [13:A.tpuarts/LowF      2.486] Close C
Layer 0 [16:A.tpuarts/log       2.486] Closing
Layer 2 [15:A.tpuarts/TPU_ser   2.486] Close F
Layer 8 [ 4:server/Server       2.486] Close E
Layer 4 [ 1:main                2.486] deleted.
```

**Comment by mschulte** [comment]
Hey @dallmair i'm using the latest commit from the debian branch (version 0.14.67).

My interface is a busware PIGATOR with KNX-Module: https://www.busware.de/tiki-index.php?page=POD
I think thats not available anymore.

However it worked perfectly fine with a older version of knxd (dunno which exactly, was ~3 years old) before i had to reinstall (due to malfunctioning sd-card).

**Comment by smurfix** [comment]
Huh. You might be able to find the older version and do a "git bisect" on this.

NB you might try adding an explicit `console=tty1" entry to `cmdline.txt`.

**Comment by mschulte** [comment]
0.14.38 was the version that worked for me.

found some commits that - in terms of their commit message - may be interesting in git bisect:

> commit 2430f69531d7042e317b2f0babfa3c01a3051272
> Merge: 0ca2c2e fabc8b8
> Author: Matthias Urlichs <matthias@urlichs.de>
> Date:   Wed Nov 13 08:05:55 2024 +0100
> 
>     Merge pull request #592 from dallmair/fix/serial-over-tcp
> 
>     Fixes for serial drivers: Port config keys + TP-UART via TCP comes up again

> commit fabc8b85c7b2746980b94d0e21305bcf0fd9becc
> Author: Thomas Dallmair <dev@thomas-dallmair.de>
> Date:   Wed Nov 13 00:04:20 2024 +0100
> 
>     Fix TP-UART via TCP to come up again

> commit 6915ed4468a8d7ee99e92bbd558327826298d67f
> Author: Matthias Urlichs <matthias@urlichs.de>
> Date:   Fri Oct 11 17:03:43 2024 +0200
> 
>     tpuart: Fix retrying when keepalive-ing.

> commit 5551b0e12180cdec1c7d9a74cd512714e508b3aa
> Merge: 10b76ff e97a649
> Author: Matthias Urlichs <matthias@urlichs.de>
> Date:   Fri Dec 30 14:06:54 2022 +0100
> 
>     Merge pull request #534 from debug-richard/parityfix
> 
>     Parity error on reset fix for **TPUART devices in combination with FTDI ICs**


> commit e97a6494eba00fb4e6c5ce5cc3fdbd165eaa68c2
> Author: Richard Schleich <rs@noreya.tech>
> Date:   Wed May 4 17:40:12 2022 +0200
> 
>     Fixes a reset detected as a parity error on TPUART devices in combination with FTDI ICs.
> 
>     Signed-off-by: Richard Schleich <rs@noreya.tech>

> commit 848a5cc6cc1f3f79116fbf61c825ca9cd47057cd
> Merge: 9929ed6 382c07e
> Author: Matthias Urlichs <matthias@urlichs.de>
> Date:   Sat Mar 13 18:23:09 2021 +0100
> 
>     Merge pull request #503 from haxtibal/bugfix/tpuart_segfault
> 
>     Fix potential segfault in TPUART

> commit 382c07ed26d886dcf69869b7f6bf566dded1d7c4
> Author: Tobias Deiminger <tobias.deiminger@posteo.de>
> Date:   Fri Mar 12 23:39:54 2021 +0100
> 
>     Fix potential segfault in TPUART
> 
>     TPUARTwrap::RecvLPDU dereferenced the pointer returned by
>     CM_TP1_to_L_Data() without a nullptr check. CM_TP1_to_L_Data() has
>     multiple code paths where it does return nullptr, so
>     TPUARTwrap::RecvLPDU potentially segfaults (happened for me).
> 
>     This commit immediately drops the packet if the pointer is invalid.
> 
>     Signed-off-by: Tobias Deiminger <tobias.deiminger@posteo.de>

browsing the commits i don't find anything suspicious that could cause my error - however i'm not a C programmer :)

**Comment by mschulte** [comment]
oh well guys "console=tty1" in /boot/cmdline.txt did the trick.
old version 0.14.25-5 is working fine.

**Comment by JackyKNX** [comment]
I've tried the above however it didn't helped, I receive same errors - please see the log file.
[knxd_20241227.zip](https://github.com/user-attachments/files/18260111/knxd_20241227.zip)
