### ISSUE TITLE
Fix KNXnet/IP behavior

### ISSUE THREAD

**Issue by Makki1** [knxd/knxd#6]
To conform to Standards:
- not showing 0.0.0 and 0.0.1 as Physical address (if configured)
- respond with MAC if first interface in KNXnet/IP (Multicast) search
- respond with actual hostname

**Comment by p3root** [comment]
Part 3: done with d86a66db

**Comment by Makki1** [comment]
Only for the log: we have four problems: three minor and one major

1) Property 83 (PID_DEVICE_DESCRIPTOR) = (ErrorType=Unspecified Error)
2) MAC-address (00:00:00:00:00:00)
3) 53 (PID_MAX_APDULENGTH) = "Unspecified Error"
4) Routing-counter on KNXnet/IP Tunneling-connections

**Comment by smurfix** [comment]
Is any of this still a problem?
