### ISSUE TITLE
 install-debian.sh removed the complete (old) ubuntu system

### ISSUE THREAD

**Issue by gvtienen** [knxd/knxd#614]
Because of my issues with valgrind on a raspberry pi2, I wanted to check if I have same issue #606  on an old (intel) desktop computer. So I upgraded first the ubuntu to "latest" "jammy".
Then cloned the debian branch from the git. and I ran "sh install-debian.sh" (I dont remember which commit I had, but I did this yesterday)
First it installed some more packages, then compiled and installed knxd (I noticed it was creating a user for knxd). Everything
looked successful. After that it started removing a lot of packages, and removing itself from grub. So my complete system is gone...

**Comment by smurfix** [comment]
> After that it started removing a lot of packages, and removing itself from grub. So my complete system is gone...

Huh. That step is `apt-get remove --autoremove knxd-build-deps --yes` which is supposed to only clean up whatever the previous step installed.

Fixed in e053cb8.

**Comment by gvtienen** [comment]
Thanks for the fix, but I don't think it was correct. 
the autoremove will happen anyway, there is no question asked up-front

**Comment by smurfix** [comment]
If there are no packages that warrant autoremoval, then the script won't ask. That would be kindof pointless.

**Comment by gvtienen** [comment]
I was expecting the script to ask if step 5 was needed or to be skipped ...
