### ISSUE TITLE
Multiple lower layers

### ISSUE THREAD

**Issue by smurfix** [knxd/knxd#63]
knxd really should have a better idea of which devices are where. The current version does exactly one Layer-2 connection (the two-wire KNX hardware), everything else is a "connection". There is no notion of multiple lower layers (two multicasts and three TPUART bus interfaces, anybody?). Thus there's also no cache of which physical address is located on which bus(es) and no way to restrict traffic to a single line; this inability to filter causes unnecessary bus traffic.

Refactoring this would be a perfect topic for a CS student paper.

**Comment by smurfix** [comment]
I'm working on this problem. There's some broken code in there …

**Comment by Makki1** [comment]
I really appreciate that, please go ahead!

**Comment by smurfix** [comment]
I have pushed the "multi_l2" branch.

Disclaimer: This is a work in progress and I have not really tested this in any meaningful way.
This code may get rebased when (not if …) bugs are discovered.
A lot is still missing: physaddr caching, combining backend/eibnetrouter and libserver/eibnetserver in some way, testing, adding a config file since this is getting too complex for the command line, …

**Comment by smurfix** [comment]
Sufficiently tested that it's now the new master branch.
