### ISSUE TITLE
Remove outdated back-end drivers

### ISSUE THREAD

**Issue by smurfix** [knxd/knxd#67]
I propose to remove outdated drivers from the source.

Specifically, "tpuart" and "pei16" (bcu1) use kernel drivers that are no longer supported since 2.6.31 or earlier.

**Comment by Makki1** [comment]
On 19.05.2015 06:03, Matthias Urlichs wrote:
> I propose to remove outdated drivers from the source.
> 
> Specifically, "tpuart" and "pei16" (bcu1) use kernel drivers that are no
> longer supported since 2.6.31 or earlier.
> 

Agreed.

Michael

**Comment by smurfix** [comment]
Done.
