### ISSUE TITLE
Submit knxd to Debian

### ISSUE THREAD

**Issue by RichiH** [knxd/knxd#68]
As soon as @Maulkin is done with Debian PPAs (sometime next week, surely... ;) and as long as the dependencies of knxd are not cleaned up yet, I will put up a Debian PPA with somewhat-official packages. That should make it easier to run knxd on Debian.

This issue is half a reminder for me and half a marker for others who want to ask about this.

**Comment by Makki1** [comment]
Appreciated, I just wish some backward-compatibility for Lenny (5.0) for some reasons (as long as this creates no big pain..)

**Comment by RichiH** [comment]
I am not sure if that's possible in the context of PPAs, but I can build & host packages elsewhere if that's deemed useful.

FWIW, I can sign the packages with my Debian key, so that should be better than random packages on the interwebs.

**Comment by alteholz** [comment]
Just out of curiosity, what blocks knxd to become an official Debian package?

**Comment by smurfix** [comment]
libpthsem. See #29.

**Comment by smurfix** [comment]
We no longer need pthsem, so the next step is for somebody to do the Debian thing.

I'd prefer that not to be me, frankly.

**Comment by pfisterer** [comment]
@RichiH Is there still something preventing the submission to Debian? Or is there still some work to do?

**Comment by smurfix** [comment]
Debian is currently frozen, preparing their next major release. Unfortunately my de-libpthsem-ization effort missed the deadline for new packages by about a week.

I plan to upload v0.14 to experimental soon(ish).

**Comment by jcbastosportela** [comment]
wowwww, this would be great! I'd been following the project evolution, unfortunately I've hadn't the opportunity to contribute.

BTW, I've been using 0.14 almost since it became stable and it works fine to me. I've been using it with ETS5.5.2, and downloading works fine. Didn't have any issue so far.

Great work here... Soon we will see "KNX Data Secure" implemented, right?! XD

**Comment by smurfix** [comment]
> Soon we will see "KNX Data Secure" implemented
Are you volunteering?

**Comment by jcbastosportela** [comment]
For the KNX Data Secure? I do not have practical experience on Data Secure yet. I've attended some webinars though, and I have some technical documentation lying around...

**Comment by chrwick** [comment]
Hi!

Any news on this topic? Has 0.14 been uploaded to experimental yet?
