### ISSUE TITLE
bootstrap.sh runs into errors on Debian

### ISSUE THREAD

**Issue by NSchnitzler** [knxd/knxd#70]
,/bootstrap.sh throughs the following error:
´´´libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./config.guess'
libtoolize: copying file `./config.sub'
libtoolize: copying file `./install-sh'
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
libtoolize: `AC_PROG_RANLIB' is rendered obsolete by `LT_INIT'
src/client/c/Makefile.am:5: warning: source file 'gen/getapdu.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
src/client/c/Makefile.am:5: warning: source file 'gen/loadimage.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mcpropertyread.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mprogmodeoff.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/opentconnection.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/getapdusrc.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mcauthorize.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mcpropertyscan.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mprogmodeon.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/opentgroup.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/getbusmonitorpacket.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mcconnect.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mcpropertywrite.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mprogmodestatus.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/opentindividual.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/getgroupsrc.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mcgetmaskversion.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mcreadadc.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mprogmodetoggle.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/openttpdu.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/groupcacheclear.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mcgetpeitype.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mcread.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mreadindividualaddresses.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/openvbusmonitor.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/groupcachedisable.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mcprogmodeoff.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mcrestart.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mwriteindividualaddress.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/openvbusmonitortext.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/groupcacheenable.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mcprogmodeon.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mcsetkey.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/openbusmonitor.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/reset.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/groupcacheread.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mcprogmodestatus.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mcwrite.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/openbusmonitortext.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/sendapdu.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/groupcachereadsync.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mcprogmodetoggle.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mcwriteplain.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/opengroupsocket.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/sendgroup.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/groupcacheremove.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mcpropertydesc.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mgetmaskversion.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/opentbroadcast.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/sendtpdu.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/gettpdu.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/mcindividual.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/groupcachelastupdates.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/openbusmonitorts.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/openvbusmonitorts.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled
src/client/c/Makefile.am:5: warning: source file 'gen/getbusmonitorpacketts.c' is in a subdirectory,
src/client/c/Makefile.am:5: but option 'subdir-objects' is disabled´´´

**Comment by smurfix** [comment]
should work OK with current master
