### ISSUE TITLE
Programming not working

### ISSUE THREAD

**Issue by SgtSeppel** [knxd/knxd#74]
I compiled knxd on a Banana Pi.

I want to use it as a KNX/IP programming interface over openVPN.
I have a Raspberry Pi where this is working like a charm with the old eibd.

When I use knxd however, programming is not working. I can use it to log GAs in the busmonitor of the ETS. I can use it to read and write GAs. The busmonitor (vbusmonitor1) is working too.

What I noticed is, that ETS always shows 0.0.0 as the address, even though 0.0.1 is set, here's an example of a group address read in ETS and what's seen on the console:

![image](https://cloud.githubusercontent.com/assets/10022598/8273081/65acfd9c-185e-11e5-9490-9e60d6072274.png)

![image](https://cloud.githubusercontent.com/assets/10022598/8273090/afd945b0-185e-11e5-89ab-f1e759e64b6e.png)

When I try to programm _any_ device it's not working. I can see the telegrams in the ETS busmonitor, as well as on the Pi. I do not get any answers though:

![image](https://cloud.githubusercontent.com/assets/10022598/8273103/07bed9e8-185f-11e5-9adf-eec6491b75ff.png)

![image](https://cloud.githubusercontent.com/assets/10022598/8273106/0eb6d69c-185f-11e5-9266-9516bc1ed323.png)

Knxd is started with: 

     -c -S -D -T --daemon=/var/log/knxd.log --no-tunnel-client-queuing -i ipt:192.168.1.201

Programming directly on site with the IP router works fine too.

Any ideas?

**Comment by smurfix** [comment]
Hi,
> | -c -S -D -T --daemon=/var/log/knxd.log --no-tunnel-client-queuing -i ipt:192.168.1.201
> |
>
> Programming directly on site with the IP router works fine too.
>
> Any ideas?
>
Which branch are you using? Which ETS version?

-- 
-- Matthias Urlichs

**Comment by SgtSeppel** [comment]
ETS4, currently on master

**Comment by smurfix** [comment]
OK, could you please test the current master? (You'll have to use `-D -T -S`, not `-S -D -T`)

If that doesn't work, please provide before/after traces with wireshark.

**Comment by smurfix** [comment]
No feedback? Works here …

**Comment by smurfix** [comment]
Closing due to no feedback and "works here".
Please re-open if you have more information.

**Comment by gedia** [comment]
Same issue here. Well at least the ETS 4.2.0 busmonitor view is exactly the same... Here's the story:

I've tried knxd on two different machines:
* gentoo ~amd64 running as dom0 under the xen hypervisor
* debian squeeze i386 running as guest under KVM

The same symptoms persist with both the master and the conn_sep branches.

Packets flowing in and out of the knxd host look as follows:
![capt](https://cloud.githubusercontent.com/assets/15806134/12209525/389de3c4-b65c-11e5-98e3-6a4ea2bd456c.png)

I've also uploaded the original dump captured using tcpdump at the following link, if anyone wants to have a look. Sorry for the lame hosting:

    http://s000.tinyupload.com/index.php?file_id=02525711318193883647

Lastly, knxd is started with the following options:

    -e 1.1.254 -u /tmp/eib -u /var/run/knx -i -D -T -R -S -b ipt:172.17.178.254

172.17.178.254 is the ABB IP Interface IPS/S2.1.

Lastly, but importantly, I was able to program devices on the KNX bus when using USB as the backend. So it might be ipt related.

**Comment by gedia** [comment]
I forgot to provide a legend for the IPs involved:
* 172.17.178.178 is the knxd host
* 172.17.178.249 is the windows machine ETS 4.2.0 runs on
* 172.17.178.254 is the ABB IP interface

**Comment by gedia** [comment]
Furthermore, in my case the source address reported in ETS monitor is NOT 0.0.0, as was the case with the original poster

**Comment by smurfix** [comment]
On 08.01.2016 22:57, gedia wrote:
>
> Furthermore, in my case the source address reported in ETS monitor is
> NOT 0.0.0, as was the case with the original poster
>
… which is good, as a source of zero should not occur on KNX.

If knxd sees that source address, it will replace it either with its own
address or (conn_sep branch with the appropriate option) with a
dynamically-assigned address.

NB: all-ones is also a special address – a device uses that when you
push its Programming button.

-- 
-- Matthias Urlichs

**Comment by gedia** [comment]
> … which is good, as a source of zero should not occur on KNX.

By that I only meant that it is likely the problem lies somewhere else, and not the source address.

Is there anything unusual about the packets in the dump I attached? Let me know if I can provide any further information or perform more tests on this.

**Comment by smurfix** [comment]
Apparently knxd doesn't want to forward the multicast packets to ipt:.

First, please use a different address. Your ETS uses the same source address as knxd. Not a good idea.

If that doesn't help, turn on knxd debugging (-t 1023 -f 9).
