### ISSUE TITLE
Build/install help (knxd missing files (/lib/*))

### ISSUE THREAD

**Issue by pakerfeldt** [knxd/knxd#75]
I'm trying to install knxd but fail miserably. This is the output after `dpkg-buildpackage -b` (after doing all other steps listed in Readme).
```
dh_install
        install -d debian/knxd///usr/bin
        cp -a debian/tmp//usr/bin/knxd debian/knxd///usr/bin/
        install -d debian/knxd///usr/lib
        cp -a debian/tmp//usr/lib/libeibclient.a debian/knxd///usr/lib/
        cp -a debian/tmp//usr/lib/libeibclient.la debian/knxd///usr/lib/
        cp -a debian/tmp//usr/lib/libeibclient.so debian/knxd///usr/lib/
        cp -a debian/tmp//usr/lib/libeibclient.so.0 debian/knxd///usr/lib/
        cp -a debian/tmp//usr/lib/libeibclient.so.0.0.0 debian/knxd///usr/lib/
        cp -a debian/tmp//usr/lib/systemd debian/knxd///usr/lib/
        cp -a debian/tmp//usr/lib/sysusers.d debian/knxd///usr/lib/
dh_install: knxd missing files (/lib/*), aborting
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
```
Thanks!

**Comment by smurfix** [comment]
On 30.06.2015 22:53, Patrik Åkerfeldt wrote:
>
> I'm trying to install knxd but fail miserably. This is the output
> after |dpkg-buildpackage -b| (after doing all other steps listed in
> Readme).
>
> |dh_install
>         install -d debian/knxd///usr/bin
>         cp -a debian/tmp//usr/bin/knxd debian/knxd///usr/bin/
>         install -d debian/knxd///usr/lib
>         cp -a debian/tmp//usr/lib/libeibclient.a debian/knxd///usr/lib/
>         cp -a debian/tmp//usr/lib/libeibclient.la debian/knxd///usr/lib/
>         cp -a debian/tmp//usr/lib/libeibclient.so debian/knxd///usr/lib/
>         cp -a debian/tmp//usr/lib/libeibclient.so.0 debian/knxd///usr/lib/
>         cp -a debian/tmp//usr/lib/libeibclient.so.0.0.0 debian/knxd///usr/lib/
>         cp -a debian/tmp//usr/lib/systemd debian/knxd///usr/lib/
>         cp -a debian/tmp//usr/lib/sysusers.d debian/knxd///usr/lib/
> dh_install: knxd missing files (/lib/*), aborting
> make: *** [binary] Error 2
> dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
> |
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/knxd/knxd/issues/75>.
>
Presumably, you're on Debian Wheezy and have no systemd.
You need to remove '/lib/*' from debian/knxd.init because without
systemd there are no files there.

I have updated the README.

-- 
-- Matthias Urlichs

**Comment by pakerfeldt** [comment]
Thanks!
Is this something to be concerned about (after installing the packages):
```
etting up knxd (0.10.2-2) ...
Adding group `knxd' (GID 124) ...
Done.
Warning: The home dir /var/lib/knxd you specified can't be accessed: No such file or directory
Adding system user `knxd' (UID 116) ...
Adding new user `knxd' (UID 116) with group `knxd' ...
Not creating home directory `/var/lib/knxd'.
I know of no Layer-2 interface. Giving up.
Setting up knxd-tools (0.10.2-2) ...
```

**Comment by smurfix** [comment]
On 01.07.2015 08:01, Patrik Åkerfeldt wrote:
>
> Thanks!
> Is this something to be concerned about (after installing the packages):
>
> |etting up knxd (0.10.2-2) ...
> Adding group `knxd' (GID 124) ...
> Done.
> Warning: The home dir /var/lib/knxd you specified can't be accessed: No such file or directory
> Adding system user `knxd' (UID 116) ...
> Adding new user `knxd' (UID 116) with group `knxd' ...
> Not creating home directory `/var/lib/knxd'.
> I know of no Layer-2 interface. Giving up.
> Setting up knxd-tools (0.10.2-2) ...
> |
>
> —
>

Not a problem. I will fix the warning.

-- 
-- Matthias Urlichs

**Comment by pakerfeldt** [comment]
Unless you want to keep the issue around as a reminder to fix the warning, I'm happy to close the issue.

**Comment by JoeRu** [comment]
Hi,
on ubuntu the same issue. 
i did comment all lines with ./lib

But the solution does not work:

make[1]: Verzeichnis »/home/joe/knxd« wird verlassen
   dh_install
	install -d debian/knxd///usr/bin
	cp -a debian/tmp//usr/bin/knxd debian/knxd///usr/bin/
dh_install: knxd missing files (/lib/*), aborting
make: *** [binary] Fehler 2
dpkg-buildpackage: Fehler: Fehler-Exitstatus von fakeroot debian/rules binary war 2

~/knxd$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty 

Joe

**Comment by nero87** [comment]
had same problem, remove '/lib/*' from debian/knxd.install.systemd and not '. /lib' from debian/knxd.init

**Comment by viknet365** [comment]
same problem here nero87's solution did the trick
