### ISSUE TITLE
vbusmonitor does not work in master since a while

### ISSUE THREAD

**Issue by tru7** [knxd/knxd#77]
Since about April/May busmonitor tool cannot be used anymore.

knxd is running like that:
knxd -D -T -S -d -i --pid-file=/var/run/knxd.pid ipt:192.168.1.2

Busmonitor tool returns error:
$ knxtool vbusmonitor1 ip:localhost
Open Busmonitor failed: Device or resource busy

**Comment by smurfix** [comment]
Thanks for the report. Will check.

**Comment by smurfix** [comment]
I have added a vbusmonitor1 test (two, actually) to the test scropt (`tolls/test.hs`) in the master branch and don't see a bug. The monitor program correctly displays the trace packets.

Thus, please retry with the current master.

**Comment by tru7** [comment]
Now, with current master knxd segfaults on Ubuntu 32 and 64 bit. Here is the debugger output

gdb ./knxd
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./knxd...done.
(gdb) r -D -T -S -d -i ipt:192.168.1.20
Starting program: /sw/pkgs/knxd/bin/knxd -D -T -S -d -i ipt:192.168.1.20
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106     ../sysdeps/x86_64/strlen.S: No such file or directory.
(gdb) where
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ffff788682e in __GI___strdup (s=0x0) at strdup.c:41
#2  0x0000000000403776 in parse_opt (key=<optimized out>, arg=0x0, state=<optimized out>) at knxd.cpp:326
#3  0x00007ffff7904fbd in group_parse (arg=<optimized out>, key=83, state=0x7fffffffe3e0, group=0x67bc00) at argp-parse.c:257
#4  parser_parse_opt (val=<optimized out>, opt=83, parser=0x7fffffffe370) at argp-parse.c:747
#5  parser_parse_next (arg_ebadkey=<synthetic pointer>, parser=0x7fffffffe370) at argp-parse.c:867
#6  __argp_parse (argp=<optimized out>, argc=<optimized out>, argv=<optimized out>, flags=<optimized out>, end_index=0x7fffffffe498,
    input=0x667e40 <arg>) at argp-parse.c:921
#7  0x0000000000402ed2 in main (ac=7, ag=0x7fffffffe618) at knxd.cpp:515

**Comment by smurfix** [comment]
Fixed, sorry about the stupid mistake.

**Comment by tru7** [comment]
Fine, knxd runs again. And even better, vbusmonitor is working also.
