### ISSUE TITLE
Tunneling Server

### ISSUE THREAD

**Issue by vapourismo** [knxd/knxd#84]
When starting `knxd` with `-T -S` options, incoming connection requests are left unanswered.

Here is what I get as debug output:
```
$ ./src/server/knxd -t 99 -T -S ip:      
Layer 0(0134F9F0,55CE57AD) Open
Layer 0(0134F9F0,55CE57AD) Openend
Layer 0(01370810,55CE57AD) Open
Layer 0(01370810,55CE57AD) Openend
Layer 0(01370810,55CE57AF) Recv(026): 06 10 02 05 00 1A 08 01 00 00 00 00 00 00 08 01 00 00 00 00 00 00 04 04 02 00
Layer 1(01370810,55CE57AF) Recv(020): 08 01 00 00 00 00 00 00 08 01 00 00 00 00 00 00 04 04 02 00
```

Instead I expect something like that:
```
$ eibd -t 99 -T -S ip:  
Layer 0(01B90910,55CE587A) Open
Layer 0(01B90910,55CE587A) Openend
Layer 0(01BC21E0,55CE587A) Open
Layer 0(01BC21E0,55CE587A) Openend
Layer 0(01BC21E0,55CE587C) Recv(026): 06 10 02 05 00 1A 08 01 00 00 00 00 00 00 08 01 00 00 00 00 00 00 04 04 02 00
Layer 1(01BC21E0,55CE587C) Recv(020): 08 01 00 00 00 00 00 00 08 01 00 00 00 00 00 00 04 04 02 00
Layer 1(01BC21E0,55CE587C) Send(014): 01 00 08 01 00 00 00 00 00 00 04 04 00 00
Layer 0(01BC21E0,55CE587C) Send(020): 06 10 02 06 00 14 01 00 08 01 00 00 00 00 00 00 04 04 00 00
```

**Comment by smurfix** [comment]
On 14.08.2015 23:11, Ole wrote:
Which git version are you using, which client is that request from?

-t99 doesn't make sense, it's a bitmask, repeat with -t1023 -f9 please.

> When starting |knxd| with |-T -S| options, incoming connection
> requests are left unanswered.
>
> Here is what I get as debug output:
>
> |$ ./src/server/knxd -t 99 -T -S ip:      
> Layer 0(0134F9F0,55CE57AD) Open
> Layer 0(0134F9F0,55CE57AD) Openend
> Layer 0(01370810,55CE57AD) Open
> Layer 0(01370810,55CE57AD) Openend
> Layer 0(01370810,55CE57AF) Recv(026): 06 10 02 05 00 1A 08 01 00 00 00 00 00 00 08 01 00 00 00 00 00 00 04 04 02 00
> Layer 1(01370810,55CE57AF) Recv(020): 08 01 00 00 00 00 00 00 08 01 00 00 00 00 00 00 04 04 02 00
> |
>
> Instead I expect something like that:
>
> |$ eibd -t 99 -T -S ip:  
> Layer 0(01B90910,55CE587A) Open
> Layer 0(01B90910,55CE587A) Openend
> Layer 0(01BC21E0,55CE587A) Open
> Layer 0(01BC21E0,55CE587A) Openend
> Layer 0(01BC21E0,55CE587C) Recv(026): 06 10 02 05 00 1A 08 01 00 00 00 00 00 00 08 01 00 00 00 00 00 00 04 04 02 00
> Layer 1(01BC21E0,55CE587C) Recv(020): 08 01 00 00 00 00 00 00 08 01 00 00 00 00 00 00 04 04 02 00
> Layer 1(01BC21E0,55CE587C) Send(014): 01 00 08 01 00 00 00 00 00 00 04 04 00 00
> Layer 0(01BC21E0,55CE587C) Send(020): 06 10 02 06 00 14 01 00 08 01 00 00 00 00 00 00 04 04 00 00
> |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/knxd/knxd/issues/84>.
>


-- 
-- Matthias Urlichs

**Comment by vapourismo** [comment]
I have built from `master` and I am using my own client [library](https://github.com/vapourismo/knxclient) to generate the request.

It works with all my KNX/IP gateways and eibd, which makes me wonder.

**Comment by smurfix** [comment]
Thanks, I'll have a look.

-- 
-- Matthias Urlichs

**Comment by smurfix** [comment]
Not a bug.

The problem is that you have opened two UDP sockets on port 3671. One by -S and one by ip:. One of these ports will get your packet. In this case it's the wrong one because the order knxd opens the ports in has changed.
The fix is to use -RTS and drop the "ip:". 
In fact you need to replace it with "dummy:" as the setup logic doesn't consider -R and -T to be separate interfaces, but I'll fix that shortly.

**Comment by smurfix** [comment]
Uploaded eeff01a

**Comment by vapourismo** [comment]
Thanks!
