### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [knxd/knxd#97]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/knxd/knxd/blob/d1e6f417503119ee2b593ecb6e4a18cab767bd39/src/server/knxd.cpp#L511)" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main) so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706)?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108) like they are described by Danny Kalev?

**Comment by smurfix** [comment]
Right now there is no code whatsoever in knxd that could throw an exception, so why should main() catch any?
Also, I very much doubt that libpth[sem] would handle exceptions originating in non-main threads in a sane way.

I'd suggest to discuss switching to exceptions in the course of removing libpthsem in favor of libev+pthreads, as discussed in issue #29.

Personally I'm not convinced that we need them.

**Comment by elfring** [comment]
I suggest to consider another safety aspect which can depend on your preferred software build configuration eventually.
Do you care for implementation-defined behaviour from the general structure of your function "main"?

How do you think about to add the following items there?
* Catching [the exception "std::bad_alloc"](http://en.cppreference.com/w/cpp/memory/new/bad_alloc "Allocation failure") explicitly
* [Catch-all clause](http://en.cppreference.com/w/cpp/language/try_catch "try-block")
