### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [knxd/knxd#98]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null) like the following.
- [CEMILayer2](https://github.com/knxd/knxd/blob/d1e6f417503119ee2b593ecb6e4a18cab767bd39/src/libserver/cemi.cpp#L54)
- [EIBNetIPRouter](https://github.com/knxd/knxd/blob/dd89741b11506a7b1beb8d664c1f0f374806cace/src/backend/eibnetrouter.cpp#L69)
- [GetSourceAddress](https://github.com/knxd/knxd/blob/d1e6f417503119ee2b593ecb6e4a18cab767bd39/src/libserver/eibnetip.cpp#L116)
- [Layer7_Broadcast](https://github.com/knxd/knxd/blob/d1e6f417503119ee2b593ecb6e4a18cab767bd39/src/libserver/layer7.cpp#L36)

**Comment by smurfix** [comment]
Feel free to submit patches.

**Comment by elfring** [comment]
Would it be acceptable to improve the affected implementation details by [the reuse of smart pointers](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Reusing smart pointers?")?

**Comment by smurfix** [comment]
I have no problem with that.
NB: please apply any changes to the conn_seq branch. It already requires libstdc++.
